// dehaze-uniapp/src/pages/messages/detail/index.vue
<template>
  <PageLayout level="L2" title="消息详情">
    <view class="message-detail-page">
      <view v-if="loading" class="message-detail-status">
        <text>加载中...</text>
      </view>
      <view v-else-if="!message" class="message-detail-status">
        <text>消息不存在</text>
      </view>
      <template v-else>
        <view class="message-detail-header">
          <view class="message-detail-type">
            <text>{{ message.typeLabel }}</text>
          </view>
          <text class="message-detail-title">{{ message.title }}</text>
          <text class="message-detail-time">{{ formatDateTime(message.createTime) }}</text>
        </view>
        <view class="message-detail-body">
          <rich-text
            v-if="message.content"
            :nodes="message.content"
            class="message-detail-content"
          />
          <text v-else class="message-detail-summary">
            {{ message.summary || "暂无内容" }}
          </text>
        </view>
        <view class="message-detail-footer">
          <view
            v-if="message.jumpUrl"
            class="message-detail-action"
            @click="handleJump"
          >
            <text>查看详情 →</text>
          </view>
          <view class="message-detail-delete" @click="handleDelete">
            <text>{{ deleting ? "删除中..." : "删除" }}</text>
          </view>
        </view>
      </template>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import PageLayout from "@/layout/index.vue";
import { MessageAPI } from "dehaze-sdk-js";
import type { MessageVO } from "dehaze-sdk-js";
import { getErrorMessage } from "@/utils/error";

const message = ref<MessageVO | null>(null);
const loading = ref(true);
const deleting = ref(false);

function formatDateTime(dateStr: string): string {
  if (!dateStr) return "";
  const d = new Date(dateStr);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

onMounted(() => {
  const pages = getCurrentPages();
  const currentPage = pages[pages.length - 1] as { options?: { id?: string } };
  const id = currentPage?.options?.id;

  if (!id) {
    uni.showToast({ title: "参数错误", icon: "none" });
    setTimeout(() => uni.navigateBack(), 1000);
    loading.value = false;
    return;
  }

  MessageAPI.getDetail(Number(id))
    .then((res) => {
      message.value = res;
      if (res.readStatus === 0) {
        MessageAPI.markRead(res.id).catch(() => {});
      }
    })
    .catch((error) => {
      uni.showToast({
        title: getErrorMessage(error, "加载失败"),
        icon: "none",
      });
    })
    .finally(() => {
      loading.value = false;
    });
});

const handleJump = () => {
  if (message.value?.jumpUrl) {
    uni.navigateTo({ url: message.value.jumpUrl });
  }
};

const handleDelete = async () => {
  if (!message.value || deleting.value) return;
  const res = await uni.showModal({
    title: "确认删除",
    content: "确定删除这条消息吗？",
  });
  if (!res.confirm) return;
  deleting.value = true;
  try {
    await MessageAPI.deleteByIds(String(message.value.id));
    uni.showToast({ title: "已删除", icon: "success" });
    setTimeout(() => uni.navigateBack(), 800);
  } catch (error) {
    uni.showToast({ title: getErrorMessage(error, "删除失败"), icon: "none" });
  } finally {
    deleting.value = false;
  }
};
</script>

<style lang="scss" scoped>
.message-detail-page {
  min-height: 100vh;
  padding: 24rpx;
}

.message-detail-header {
  padding: 32rpx 24rpx;
  margin-bottom: 24rpx;
  background: $color-white;
  border-radius: $radius-lg;
  box-shadow: $shadow-sm;
}

.message-detail-type {
  display: inline-block;
  padding: 4rpx 16rpx;
  margin-bottom: 16rpx;
  font-size: $font-xs;
  color: $color-primary;
  background: $color-primary-bg;
  border-radius: $radius-sm;
}

.message-detail-title {
  display: block;
  margin-bottom: 12rpx;
  font-size: $font-lg;
  font-weight: 700;
  line-height: 1.4;
  color: $color-text-primary;
}

.message-detail-time {
  font-size: $font-xs;
  color: $color-text-placeholder;
}

.message-detail-body {
  min-height: 200rpx;
  padding: 24rpx;
  background: $color-white;
  border-radius: $radius-lg;
  box-shadow: $shadow-sm;
}

.message-detail-content {
  font-size: $font-md;
  line-height: 1.8;
  color: $color-text-primary;
}

.message-detail-summary {
  font-size: $font-md;
  line-height: 1.8;
  color: $color-text-secondary;
}

.message-detail-footer {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
  margin-top: 32rpx;
}

.message-detail-action {
  padding: 24rpx;
  font-size: $font-md;
  font-weight: 600;
  color: $color-primary;
  text-align: center;
  background: $color-white;
  border-radius: $radius-lg;
  box-shadow: $shadow-sm;
}

.message-detail-delete {
  padding: 24rpx;
  font-size: $font-md;
  color: $color-danger;
  text-align: center;
  background: $color-white;
  border-radius: $radius-lg;
  box-shadow: $shadow-sm;
}

.message-detail-status {
  display: flex;
  justify-content: center;
  padding: 96rpx;
  font-size: $font-sm;
  color: $color-text-placeholder;
}
</style>

// dehaze-taro/src/pages/messages/detail/index.tsx
/**
 * 消息详情页面 (L2)
 */
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, RichText } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { MessageAPI } from "dehaze-sdk-js";
import type { MessageVO } from "dehaze-sdk-js";
import PageLayout from "@/layout";
import { getErrorMessage } from "@/utils/error";
import "./index.less";

function formatDateTime(dateStr: string): string {
  if (!dateStr) return "";
  const d = new Date(dateStr);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

const MessageDetailPage: React.FC = () => {
  const [message, setMessage] = useState<MessageVO | null>(null);
  const [loading, setLoading] = useState(true);
  const [deleting, setDeleting] = useState(false);

  useEffect(() => {
    const instance = Taro.getCurrentInstance();
    const id = instance.router?.params?.id;
    if (!id) {
      Taro.showToast({ title: "参数错误", icon: "none" });
      setTimeout(() => Taro.navigateBack(), 1000);
      return;
    }

    MessageAPI.getDetail(Number(id))
      .then((res) => {
        setMessage(res);
        if (res.readStatus === 0) {
          MessageAPI.markRead(res.id).catch(() => {});
        }
      })
      .catch((error) => {
        Taro.showToast({
          title: getErrorMessage(error, "加载失败"),
          icon: "none",
        });
      })
      .finally(() => setLoading(false));
  }, []);

  const handleJump = useCallback(() => {
    if (message?.jumpUrl) {
      Taro.navigateTo({ url: message.jumpUrl });
    }
  }, [message]);

  const handleDelete = useCallback(async () => {
    if (!message || deleting) return;
    const res = await Taro.showModal({
      title: "确认删除",
      content: "确定删除这条消息吗？",
    });
    if (!res.confirm) return;
    setDeleting(true);
    try {
      await MessageAPI.deleteByIds(String(message.id));
      Taro.showToast({ title: "已删除", icon: "success" });
      setTimeout(() => Taro.navigateBack(), 800);
    } catch (error) {
      Taro.showToast({
        title: getErrorMessage(error, "删除失败"),
        icon: "none",
      });
    } finally {
      setDeleting(false);
    }
  }, [message, deleting]);

  if (loading) {
    return (
      <PageLayout level="L2" title="消息详情">
        <View className="message-detail-loading">
          <Text>加载中...</Text>
        </View>
      </PageLayout>
    );
  }

  if (!message) {
    return (
      <PageLayout level="L2" title="消息详情">
        <View className="message-detail-empty">
          <Text>消息不存在</Text>
        </View>
      </PageLayout>
    );
  }

  return (
    <PageLayout level="L2" title="消息详情">
      <View className="message-detail-page">
        <View className="message-detail-header">
          <View className="message-detail-type">
            <Text>{message.typeLabel}</Text>
          </View>
          <Text className="message-detail-title">{message.title}</Text>
          <Text className="message-detail-time">{formatDateTime(message.createTime)}</Text>
        </View>
        <View className="message-detail-body">
          {message.content ? (
            <RichText
              nodes={message.content}
              className="message-detail-content"
            />
          ) : (
            <Text className="message-detail-summary">
              {message.summary || "暂无内容"}
            </Text>
          )}
        </View>
        <View className="message-detail-footer">
          {message.jumpUrl && (
            <View className="message-detail-action" onClick={handleJump}>
              <Text>查看详情 →</Text>
            </View>
          )}
          <View className="message-detail-delete" onClick={handleDelete}>
            <Text>{deleting ? "删除中..." : "删除"}</Text>
          </View>
        </View>
      </View>
    </PageLayout>
  );
};

export default MessageDetailPage;
