// dehaze-uniapp/src/pages/system/recommend/index.vue
<template>
  <PageLayout level="L2" title="推荐管理">
    <view class="page-body">
      <view class="stats-bar">
        <view class="stat-item">
          <text class="stat-value">{{ rules.length }}</text>
          <text class="stat-label">总规则数</text>
        </view>
        <view class="stat-item">
          <text class="stat-value">{{ enabledCount }}</text>
          <text class="stat-label">生效中</text>
        </view>
      </view>

      <view v-if="loading" class="loading-container">
        <view class="loading-spinner" />
        <text class="loading-text">加载中...</text>
      </view>

      <view v-else-if="rules.length > 0" class="list">
        <view v-for="rule in rules" :key="rule.id" class="rule-card">
          <view class="rule-top">
            <text class="rule-name">{{ rule.ruleName }}</text>
            <text
              :class="['status-tag', rule.enabled ? 's-enabled' : 's-disabled']"
            >
              {{ rule.enabled ? "生效中" : "已禁用" }}
            </text>
          </view>
          <view class="rule-meta">
            <text v-if="rule.sceneType" class="meta-tag"
              >场景: {{ rule.sceneType }}</text
            >
            <text class="meta-tag">权重: {{ rule.weight }}</text>
          </view>
          <view
            v-if="rule.algorithmIds && rule.algorithmIds.length > 0"
            class="rule-algos"
          >
            <text class="algo-label">关联算法: </text>
            <text>{{ rule.algorithmIds.join(", ") }}</text>
          </view>
          <view v-if="canEdit" class="rule-actions">
            <text class="action-btn" @click="editRule(rule)">编辑</text>
            <text class="action-btn danger" @click="handleDelete(rule)"
              >删除</text
            >
          </view>
        </view>
      </view>

      <view v-else class="empty-tip">暂无推荐规则</view>
    </view>

    <!-- 编辑弹窗 -->
    <Popup :show="showForm" mode="bottom" round @close="showForm = false">
      <view class="popup-content">
        <text class="popup-title">编辑推荐规则</text>
        <view class="form-item">
          <text class="form-label">规则名称</text>
          <input
            class="form-input"
            v-model="form.ruleName"
            placeholder="请输入规则名称"
          />
        </view>
        <view class="form-item">
          <text class="form-label">场景类型</text>
          <input
            class="form-input"
            v-model="form.sceneType"
            placeholder="如: urban, landscape"
          />
        </view>
        <view class="form-item">
          <text class="form-label">关联算法ID</text>
          <input
            class="form-input"
            v-model="form.algorithmIds"
            placeholder="逗号分隔, 如: 1,2,3"
          />
        </view>
        <view class="form-item">
          <text class="form-label">匹配权重</text>
          <input
            class="form-input"
            v-model="form.weight"
            type="number"
            placeholder="0-100"
          />
        </view>
        <view class="form-item switch-row">
          <text class="form-label">启用规则</text>
          <switch
            :checked="form.enabled"
            @change="(e: any) => (form.enabled = e.detail.value)"
          />
        </view>
        <view class="popup-footer">
          <button class="btn btn-default" @click="showForm = false">
            取消
          </button>
          <button
            class="btn btn-primary"
            :disabled="saving"
            @click="handleSave"
          >
            保存
          </button>
        </view>
      </view>
    </Popup>
  </PageLayout>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import PageLayout from "@/layout/index.vue";
import Popup from "@/components/common/Popup.vue";
import { RecommendationAPI } from "dehaze-sdk-js";
import type { RecommendationRule } from "dehaze-sdk-js";
import { useAuthStore } from "@/store/auth";

const auth = useAuthStore();
const canEdit = computed(() => auth.hasPerm("sys:recommendation:rule:edit"));

const rules = ref<RecommendationRule[]>([]);
const loading = ref(false);
const showForm = ref(false);
const editingRule = ref<RecommendationRule | null>(null);
const saving = ref(false);

const form = ref({
  ruleName: "",
  sceneType: "",
  algorithmIds: "",
  weight: "1",
  enabled: true,
});

const enabledCount = computed(
  () => rules.value.filter((r) => r.enabled).length
);

async function fetchRules() {
  loading.value = true;
  try {
    rules.value = await RecommendationAPI.getRules();
  } catch {
    uni.showToast({ title: "加载失败", icon: "error" });
  } finally {
    loading.value = false;
  }
}

function editRule(rule: RecommendationRule) {
  editingRule.value = rule;
  form.value = {
    ruleName: rule.ruleName,
    sceneType: rule.sceneType || "",
    algorithmIds: rule.algorithmIds?.join(",") || "",
    weight: String(rule.weight ?? 1),
    enabled: rule.enabled ?? true,
  };
  showForm.value = true;
}

async function handleSave() {
  if (!form.value.ruleName || !editingRule.value?.id) {
    uni.showToast({ title: "请填写规则名称", icon: "none" });
    return;
  }
  saving.value = true;
  try {
    const algoIds = form.value.algorithmIds
      ? form.value.algorithmIds
          .split(",")
          .map((s: string) => Number(s.trim()))
          .filter((n: number) => !isNaN(n))
      : [];
    await RecommendationAPI.updateRule(editingRule.value.id, {
      id: editingRule.value.id,
      ruleName: form.value.ruleName,
      sceneType: form.value.sceneType,
      algorithmIds: algoIds,
      weight: Number(form.value.weight) || 1,
      enabled: form.value.enabled,
    });
    uni.showToast({ title: "保存成功", icon: "success" });
    showForm.value = false;
    fetchRules();
  } catch {
    uni.showToast({ title: "保存失败", icon: "error" });
  } finally {
    saving.value = false;
  }
}

async function handleDelete(rule: RecommendationRule) {
  const res = await uni.showModal({
    title: "确认删除",
    content: `确定要删除规则「${rule.ruleName}」吗？`,
    confirmColor: "#ef4444",
  });
  if (!res.confirm) return;
  try {
    await RecommendationAPI.updateRule(rule.id!, {
      ...rule,
      enabled: false,
    });
    uni.showToast({ title: "已删除", icon: "success" });
    fetchRules();
  } catch {
    uni.showToast({ title: "删除失败", icon: "error" });
  }
}

fetchRules();
</script>

<style lang="scss" scoped>
.page-body {
  padding: 20rpx;
  padding-bottom: 60rpx;
}

.stats-bar {
  display: flex;
  gap: 24rpx;
  margin-bottom: $spacing-md;
}
.stat-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 20rpx;
  background: $color-white;
  border-radius: $radius-lg;
}
.stat-value {
  font-size: 40rpx;
  font-weight: 700;
  color: $color-primary;
}
.stat-label {
  font-size: $font-xs;
  color: $color-text-secondary;
}

.list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.rule-card {
  background: $color-white;
  border-radius: $radius-lg;
  padding: 24rpx;
  border-left: 6rpx solid $color-primary;
  box-shadow: $shadow-sm;
}
.rule-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.rule-name {
  font-size: $font-md;
  font-weight: 600;
  color: $color-text-primary;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.status-tag {
  font-size: $font-xs;
  font-weight: 500;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
  flex-shrink: 0;
}
.s-enabled {
  color: $color-success;
  background: $color-success-bg;
}
.s-disabled {
  color: $color-text-placeholder;
  background: $color-bg-secondary;
}

.rule-meta {
  display: flex;
  gap: 12rpx;
  margin-bottom: 8rpx;
}
.meta-tag {
  font-size: $font-xs;
  color: $color-primary;
  background: $color-primary-bg;
  padding: 4rpx 12rpx;
  border-radius: 6rpx;
}
.rule-algos {
  margin-bottom: 12rpx;
  font-size: $font-xs;
  color: $color-text-secondary;
}
.algo-label {
  font-weight: 500;
}

.rule-actions {
  display: flex;
  gap: 16rpx;
  justify-content: flex-end;
}
.action-btn {
  font-size: $font-sm;
  color: $color-primary;
  &.danger {
    color: $color-danger;
  }
}

.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 120rpx 0;
}
.loading-text {
  margin-top: 24rpx;
  font-size: $font-md;
  color: $color-text-placeholder;
}
.empty-tip {
  text-align: center;
  padding: 80rpx 0;
  color: $color-text-secondary;
}

.popup-content {
  padding: 32rpx;
}
.popup-title {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
  display: block;
  margin-bottom: 24rpx;
}
.form-item {
  padding: 16rpx 0;
  border-bottom: 1rpx solid $color-border;
  &:last-child {
    border-bottom: none;
  }
}
.form-label {
  display: block;
  margin-bottom: 12rpx;
  font-size: $font-sm;
  color: $color-text-secondary;
}
.form-input {
  width: 100%;
  box-sizing: border-box;
  padding: 14rpx 20rpx;
  font-size: $font-md;
  background: $color-bg-primary;
  border-radius: $radius-md;
}
.switch-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  .form-label {
    margin-bottom: 0;
  }
}
.popup-footer {
  display: flex;
  gap: 16rpx;
  margin-top: 24rpx;
}
.btn {
  flex: 1;
  padding: 12rpx 20rpx;
  border-radius: $radius-sm;
  font-size: $font-sm;
  line-height: 1.6;
  &::after {
    border: none;
  }
}
.btn-primary {
  color: $color-white;
  background: $color-primary;
}
.btn-default {
  color: $color-text-primary;
  background: $color-bg-secondary;
}
</style>

// dehaze-taro/src/pages/recommend/index.tsx
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Navbar, Button, Popup, Input, Switch, Tag } from "@taroify/core";
import { ArrowLeft, Plus, Edit, Delete } from "@taroify/icons";
import { RecommendationAPI } from "dehaze-sdk-js";
import type { RecommendationRule } from "dehaze-sdk-js";
import PageLayout from "@/layout";
import EmptyState from "@/components/common/EmptyState";
import StatusTag from "@/components/common/StatusTag";
import "./index.less";

const RecommendRulesPage: React.FC = () => {
  const [rules, setRules] = useState<RecommendationRule[]>([]);
  const [loading, setLoading] = useState(false);

  // 弹窗状态
  const [editMode, setEditMode] = useState<"create" | "edit" | null>(null);
  const [editingRule, setEditingRule] = useState<RecommendationRule | null>(
    null
  );
  const [rulePopupVisible, setRulePopupVisible] = useState(false);

  // 表单数据
  const [formData, setFormData] = useState<{
    ruleName?: string;
    sceneType?: string;
    algorithmIds?: number;
    weight?: number;
    enabled?: boolean;
  }>({
    enabled: true,
    weight: 1,
  });

  // 加载规则列表
  const loadRules = useCallback(async () => {
    setLoading(true);
    try {
      const allRules = await RecommendationAPI.getRules();
      setRules(allRules || []);
    } catch {
      Taro.showToast({ title: "加载规则失败", icon: "none" });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadRules();
  }, [loadRules]);

  // 打开新增弹窗
  const handleCreate = () => {
    setEditMode("create");
    setEditingRule(null);
    setFormData({
      enabled: true,
      weight: 1,
    });
    setRulePopupVisible(true);
  };

  // 打开编辑弹窗
  const handleEdit = (rule: RecommendationRule) => {
    setEditMode("edit");
    setEditingRule(rule);
    setFormData({
      ruleName: rule.ruleName,
      sceneType: rule.sceneType,
      algorithmIds: rule.algorithmIds?.[0],
      weight: rule.weight ?? 1,
      enabled: rule.enabled ?? true,
    });
    setRulePopupVisible(true);
  };

  // 保存规则
  const handleSave = async () => {
    if (!formData.ruleName) {
      Taro.showToast({ title: "请输入规则名称", icon: "none" });
      return;
    }

    try {
      const payload = {
        ruleName: formData.ruleName,
        sceneType: formData.sceneType || undefined,
        algorithmIds: formData.algorithmIds
          ? [formData.algorithmIds]
          : undefined,
        weight: formData.weight || 1,
        enabled: formData.enabled ?? true,
      };

      if (editMode === "create") {
        await RecommendationAPI.updateRule(0, payload as any);
      } else {
        await RecommendationAPI.updateRule(
          editingRule?.id ?? 0,
          payload as any
        );
      }

      setRulePopupVisible(false);
      Taro.showToast({
        title: editMode === "create" ? "添加成功" : "保存成功",
        icon: "success",
      });
      loadRules();
    } catch {
      Taro.showToast({ title: "保存失败", icon: "none" });
    }
  };

  // 删除规则
  const handleDelete = useCallback(
    async (rule: RecommendationRule) => {
      const confirmed = await Taro.showModal({
        title: "确认删除",
        content: `确定要删除规则「${rule.ruleName}」吗？`,
        confirmColor: "#ef4444",
      });
      if (!confirmed.confirm) return;

      try {
        // TODO: 实现删除规则 API
        await RecommendationAPI.updateRule(rule.id!, {
          ...rule,
          enabled: false,
        });
        Taro.showToast({ title: "已删除", icon: "success" });
        loadRules();
      } catch {
        Taro.showToast({ title: "删除失败", icon: "none" });
      }
    },
    [loadRules]
  );

  // 场景类型标签
  const SCENE_LABELS: Record<string, string> = {
    outdoor: "户外",
    indoor: "室内",
    landscape: "风景",
    portrait: "人像",
    urban: "城市",
    nature: "自然",
    other: "其他",
  };

  return (
    <PageLayout level="L2" title="推荐规则">
      <View className="recommend-page">
        {/* 顶部操作栏 */}
        <View className="recommend-header">
          <Navbar.NavLeft>
            <ArrowLeft />
          </Navbar.NavLeft>
          <Navbar.Title>推荐规则</Navbar.Title>
          <Navbar.NavRight icon={<Plus size="20" />} onClick={handleCreate} />
        </View>

        {/* 规则统计 */}
        <View className="stats-bar">
          <View className="stat-item">
            <Text className="stat-value">{rules.length}</Text>
            <Text className="stat-label">总规则数</Text>
          </View>
          <View className="stat-item">
            <Text className="stat-value">
              {rules.filter((r) => r.enabled).length}
            </Text>
            <Text className="stat-label">生效中</Text>
          </View>
        </View>

        {/* 规则列表 */}
        <ScrollView
          scrollY
          className="rule-list"
          enhanced
          showScrollbar={false}
        >
          {loading && rules.length === 0 ? (
            <View className="loading-wrapper">
              <Text className="loading-text">加载中...</Text>
            </View>
          ) : rules.length === 0 ? (
            <View className="empty-wrapper">
              <EmptyState
                type="search"
                title="暂无推荐规则"
                description="添加规则以自定义算法推荐逻辑"
              />
            </View>
          ) : (
            <>
              {rules.map((rule) => (
                <View key={rule.id} className="rule-card">
                  {/* 头部：规则名 + 状态 */}
                  <View className="rule-top">
                    <View className="rule-algo-name">
                      <Text className="algo-title">{rule.ruleName}</Text>
                    </View>
                    <StatusTag status={rule.enabled ? 1 : 0} size="small" />
                  </View>

                  {/* 条件信息 */}
                  <View className="rule-conditions">
                    {rule.sceneType && (
                      <Tag color="primary" size="small">
                        场景: {SCENE_LABELS[rule.sceneType] || rule.sceneType}
                      </Tag>
                    )}
                    {rule.weight && (
                      <Tag color="warning" size="small">
                        权重: {rule.weight}
                      </Tag>
                    )}
                  </View>

                  {/* 权重 */}
                  <View className="rule-meta">
                    <View className="meta-item">
                      <Text className="meta-label">权重:</Text>
                      <Text className="meta-value">{rule.weight ?? 1}</Text>
                    </View>
                  </View>

                  {/* 操作按钮 */}
                  <View className="rule-actions">
                    <View
                      className="action-edit"
                      onClick={() => handleEdit(rule)}
                    >
                      <Edit size="14" color="#3b82f6" />
                      <Text className="action-text">编辑</Text>
                    </View>
                    <View
                      className="action-delete"
                      onClick={() => handleDelete(rule)}
                    >
                      <Delete size="14" color="#ef4444" />
                      <Text className="action-text">删除</Text>
                    </View>
                  </View>
                </View>
              ))}
            </>
          )}
        </ScrollView>

        {/* 添加/编辑弹窗 */}
        <Popup
          open={rulePopupVisible}
          placement="bottom"
          rounded
          onClose={() => setRulePopupVisible(false)}
        >
          <View className="rule-popup">
            <View className="popup-title-bar">
              <Text className="popup-title">
                {editMode === "create" ? "添加推荐规则" : "编辑推荐规则"}
              </Text>
              <View
                className="popup-close"
                onClick={() => setRulePopupVisible(false)}
              >
                ×
              </View>
            </View>

            <ScrollView scrollY className="popup-scroll">
              {/* 规则名称 */}
              <View className="form-item">
                <Text className="form-label">规则名称 *</Text>
                <Input
                  className="form-input"
                  placeholder="请输入规则名称"
                  value={formData.ruleName || ""}
                  onInput={(e) =>
                    setFormData({ ...formData, ruleName: e.detail?.value })
                  }
                />
              </View>

              {/* 场景类型 */}
              <View className="form-item">
                <Text className="form-label">场景类型</Text>
                <Input
                  className="form-input"
                  placeholder="如: outdoor, indoor, landscape"
                  value={formData.sceneType || ""}
                  onInput={(e) =>
                    setFormData({ ...formData, sceneType: e.detail?.value })
                  }
                />
              </View>

              {/* 权重 */}
              <View className="form-item">
                <Text className="form-label">匹配权重 ({formData.weight})</Text>
                <Input
                  className="form-input"
                  type="number"
                  value={String(formData.weight || 1)}
                  onInput={(e) =>
                    setFormData({
                      ...formData,
                      weight: Number(e.detail?.value) || 1,
                    })
                  }
                />
              </View>

              {/* 启用开关 */}
              <View className="form-item switch-item">
                <Text className="form-label">启用规则</Text>
                <Switch
                  checked={formData.enabled ?? true}
                  onChange={(checked) =>
                    setFormData({
                      ...formData,
                      enabled: checked,
                    })
                  }
                />
              </View>
            </ScrollView>

            <View className="popup-actions">
              <Button
                variant="outlined"
                onClick={() => setRulePopupVisible(false)}
                className="popup-cancel-btn"
              >
                取消
              </Button>
              <Button
                variant="contained"
                onClick={handleSave}
                className="popup-confirm-btn"
              >
                保存
              </Button>
            </View>
          </View>
        </Popup>
      </View>
    </PageLayout>
  );
};

export default RecommendRulesPage;
