// dehaze-uniapp/src/pages/system/feedback/index.vue
<template>
  <PageLayout level="L2" title="反馈评价管理">
    <view class="page-body">
      <view class="tabs">
        <view :class="['tab', { active: tab === 0 }]" @click="tab = 0">
          <text>反馈列表</text>
        </view>
        <view :class="['tab', { active: tab === 1 }]" @click="tab = 1">
          <text>评价列表</text>
        </view>
      </view>

      <!-- 反馈列表 -->
      <view v-if="tab === 0">
        <view class="search-bar">
          <input
            class="search-input"
            v-model="keyword"
            placeholder="搜索反馈内容"
            confirm-type="search"
            @confirm="handleSearch"
          />
          <view class="filter-row">
            <view
              v-for="s in statusOptions"
              :key="s.value"
              :class="['filter-tag', { active: statusFilter === s.value }]"
              @click="applyStatusFilter(s.value)"
            >
              {{ s.label }}
            </view>
          </view>
          <view class="filter-row">
            <view
              v-for="t in typeOptions"
              :key="t.value"
              :class="['filter-tag', { active: typeFilter === t.value }]"
              @click="applyTypeFilter(t.value)"
            >
              {{ t.label }}
            </view>
          </view>
        </view>

        <view v-if="loading" class="loading-container">
          <view class="loading-spinner" />
          <text class="loading-text">加载中...</text>
        </view>

        <view v-else-if="feedbacks.length > 0" class="list">
          <view v-for="f in feedbacks" :key="f.id" class="card">
            <view class="card-header">
              <text class="card-title">{{ f.title }}</text>
              <view class="header-right">
                <text :class="['status-tag', 's-' + f.status]">
                  {{ statusMap[f.status] || f.status }}
                </text>
              </view>
            </view>
            <view class="card-meta">
              <text>用户: {{ f.username }} (ID:{{ f.userId }})</text>
              <text>类型: {{ typeMap[f.feedbackType] || f.feedbackType }}</text>
              <text>优先级: {{ f.priority }}</text>
            </view>
            <text class="card-content">{{ f.content }}</text>
            <view class="card-footer">
              <text class="card-time">{{ f.createTime }}</text>
              <view v-if="f.status !== 'closed'" class="card-actions">
                <text class="action-btn" @click="openReply(f.id, 'feedback')"
                  >回复</text
                >
                <text class="action-btn danger" @click="openClose(f.id)"
                  >关闭</text
                >
              </view>
            </view>
          </view>
          <view v-if="!hasMoreFb" class="end-text">— 没有更多了 —</view>
          <view v-else class="load-more" @click="loadMoreFeedback"
            >加载更多</view
          >
        </view>

        <view v-else class="empty-tip">暂无反馈数据</view>
      </view>

      <!-- 评价列表 -->
      <view v-else>
        <view v-if="ratingLoading" class="loading-container">
          <view class="loading-spinner" />
          <text class="loading-text">加载中...</text>
        </view>

        <view v-else-if="ratings.length > 0" class="list">
          <view v-for="r in ratings" :key="r.id" class="card">
            <view class="card-header">
              <text class="card-title">{{ r.algorithmName }}</text>
              <view class="stars">
                <text v-for="i in 5" :key="i" :class="{ active: i <= r.rating }"
                  >★</text
                >
              </view>
            </view>
            <text v-if="r.comment" class="card-content">{{ r.comment }}</text>
            <view class="card-meta">
              <text>用户: {{ r.username || "ID:" + r.userId }}</text>
            </view>
            <view v-if="r.adminReply" class="admin-reply">
              <text>管理员回复: {{ r.adminReply }}</text>
            </view>
            <view class="card-footer">
              <text class="card-time">{{ r.createTime }}</text>
              <view class="card-actions">
                <text class="action-btn" @click="openReply(r.id, 'rating')"
                  >回复</text
                >
                <text
                  v-if="r.isHidden !== 1"
                  class="action-btn danger"
                  @click="handleHideRating(r.id)"
                  >隐藏</text
                >
              </view>
            </view>
          </view>
          <view v-if="!hasMoreR" class="end-text">— 没有更多了 —</view>
          <view v-else class="load-more" @click="loadMoreRatings"
            >加载更多</view
          >
        </view>

        <view v-else class="empty-tip">暂无评价数据</view>
      </view>

      <!-- 回复弹窗 -->
      <Popup
        :show="replyVisible"
        mode="bottom"
        round
        @close="replyVisible = false"
      >
        <view class="popup-content">
          <text class="popup-title">回复</text>
          <textarea
            class="form-textarea"
            v-model="replyContent"
            placeholder="请输入回复内容"
          />
          <view class="popup-footer">
            <button class="btn btn-default" @click="replyVisible = false">
              取消
            </button>
            <button
              class="btn btn-primary"
              :disabled="replying"
              @click="handleReply"
            >
              提交
            </button>
          </view>
        </view>
      </Popup>

      <!-- 关闭弹窗 -->
      <Popup
        :show="closeVisible"
        mode="bottom"
        round
        @close="closeVisible = false"
      >
        <view class="popup-content">
          <text class="popup-title">关闭反馈</text>
          <textarea
            class="form-textarea"
            v-model="closeReason"
            placeholder="请填写关闭原因（必填）"
          />
          <view class="popup-footer">
            <button class="btn btn-default" @click="closeVisible = false">
              取消
            </button>
            <button
              class="btn btn-danger"
              :disabled="closing"
              @click="handleClose"
            >
              确认关闭
            </button>
          </view>
        </view>
      </Popup>
    </view>
  </PageLayout>
</template>

<script setup lang="ts">
import { ref } from "vue";
import PageLayout from "@/layout/index.vue";
import Popup from "@/components/common/Popup.vue";
import { usePagedList } from "@/composables/usePagedList";
import { FeedbackAPI } from "dehaze-sdk-js";
import type { FeedbackPageVO, RatingPageVO } from "dehaze-sdk-js";

const statusMap: Record<string, string> = {
  pending: "待处理",
  processing: "处理中",
  replied: "已回复",
  closed: "已关闭",
};

const typeMap: Record<string, string> = {
  suggestion: "建议",
  bug: "缺陷",
  experience: "体验",
  complaint: "投诉",
};

const statusOptions = [
  { value: "", label: "全部" },
  { value: "pending", label: "待处理" },
  { value: "processing", label: "处理中" },
  { value: "replied", label: "已回复" },
  { value: "closed", label: "已关闭" },
];

const typeOptions = [
  { value: "", label: "全部类型" },
  { value: "suggestion", label: "建议" },
  { value: "bug", label: "缺陷" },
  { value: "experience", label: "体验" },
  { value: "complaint", label: "投诉" },
];

const tab = ref(0);

const statusFilter = ref("");
const typeFilter = ref("");

const {
  list: feedbacks,
  keyword,
  hasMore: hasMoreFb,
  loading,
  fetchList: fetchFeedbacks,
  handleSearch,
  loadMore: loadMoreFeedback,
} = usePagedList<FeedbackPageVO>({
  fetcher: (p) => {
    const params: any = { pageNum: p.pageNum, pageSize: 15 };
    if (p.keyword) params.keywords = p.keyword;
    if (statusFilter.value) params.status = statusFilter.value;
    if (typeFilter.value) params.feedbackType = typeFilter.value;
    return FeedbackAPI.listFeedback(params).then((r) => r.list || []);
  },
});

const {
  list: ratings,
  hasMore: hasMoreR,
  loading: ratingLoading,
  fetchList: fetchRatings,
  loadMore: loadMoreRatings,
} = usePagedList<RatingPageVO>({
  fetcher: (p) =>
    FeedbackAPI.listRatings({ pageNum: p.pageNum, pageSize: 15 }).then(
      (r) => r.list || []
    ),
});

// 回复
const replyVisible = ref(false);
const replyTarget = ref<{ id: number; type: "feedback" | "rating" } | null>(
  null
);
const replyContent = ref("");
const replying = ref(false);

// 关闭
const closeVisible = ref(false);
const closeTargetId = ref(0);
const closeReason = ref("");
const closing = ref(false);

function applyStatusFilter(val: string) {
  statusFilter.value = val;
  fetchFeedbacks(true);
}

function applyTypeFilter(val: string) {
  typeFilter.value = val;
  fetchFeedbacks(true);
}

function openReply(id: number, type: "feedback" | "rating") {
  replyTarget.value = { id, type };
  replyContent.value = "";
  replyVisible.value = true;
}

async function handleReply() {
  if (!replyTarget.value || !replyContent.value.trim()) {
    uni.showToast({ title: "请输入回复内容", icon: "none" });
    return;
  }
  replying.value = true;
  try {
    if (replyTarget.value.type === "feedback") {
      await FeedbackAPI.replyFeedback(replyTarget.value.id, {
        content: replyContent.value,
      });
    } else {
      await FeedbackAPI.replyRating(replyTarget.value.id, replyContent.value);
    }
    uni.showToast({ title: "回复成功", icon: "success" });
    replyVisible.value = false;
    if (replyTarget.value.type === "feedback") fetchFeedbacks(true);
    else fetchRatings(true);
  } catch {
    uni.showToast({ title: "回复失败", icon: "error" });
  } finally {
    replying.value = false;
  }
}

function openClose(id: number) {
  closeTargetId.value = id;
  closeReason.value = "";
  closeVisible.value = true;
}

async function handleClose() {
  if (!closeReason.value.trim()) {
    uni.showToast({ title: "请输入关闭原因", icon: "none" });
    return;
  }
  closing.value = true;
  try {
    await FeedbackAPI.closeFeedback(closeTargetId.value, {
      closeReason: closeReason.value,
    });
    uni.showToast({ title: "已关闭", icon: "success" });
    closeVisible.value = false;
    fetchFeedbacks(true);
  } catch {
    uni.showToast({ title: "关闭失败", icon: "error" });
  } finally {
    closing.value = false;
  }
}

async function handleHideRating(id: number) {
  const res = await uni.showModal({
    title: "确认隐藏",
    content: "确定要隐藏这条评价吗？",
  });
  if (!res.confirm) return;
  try {
    await FeedbackAPI.hideRating(id);
    uni.showToast({ title: "已隐藏", icon: "success" });
    fetchRatings(true);
  } catch {
    uni.showToast({ title: "操作失败", icon: "error" });
  }
}

fetchFeedbacks(true);
fetchRatings(true);
</script>

<style lang="scss" scoped>
.page-body {
  padding: 20rpx;
  padding-bottom: 60rpx;
}

.tabs {
  display: flex;
  background: $color-white;
  border-radius: $radius-lg;
  margin-bottom: $spacing-md;
  overflow: hidden;
}
.tab {
  flex: 1;
  text-align: center;
  padding: 24rpx;
  font-size: $font-md;
  color: $color-text-secondary;
  &.active {
    color: $color-primary;
    font-weight: 600;
    background: $color-primary-bg;
  }
}

.search-bar {
  background: $color-white;
  border-radius: $radius-lg;
  padding: 16rpx;
  margin-bottom: $spacing-md;

  .search-input {
    width: 100%;
    box-sizing: border-box;
    padding: 14rpx 20rpx;
    font-size: 28rpx;
    background: $color-bg-secondary;
    border-radius: $radius-md;
  }
}
.filter-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12rpx;
  margin-top: 12rpx;
}
.filter-tag {
  padding: 8rpx 16rpx;
  font-size: $font-xs;
  color: $color-text-secondary;
  background: $color-bg-primary;
  border-radius: 8rpx;
  &.active {
    color: $color-white;
    background: $color-primary;
  }
}

.list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.card {
  background: $color-white;
  border-radius: $radius-lg;
  padding: 24rpx;
  box-shadow: $shadow-sm;
}
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.card-title {
  font-size: $font-md;
  font-weight: 600;
  color: $color-text-primary;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.header-right {
  flex-shrink: 0;
}
.status-tag {
  font-size: $font-xs;
  font-weight: 500;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
}
.s-pending {
  color: $color-warning;
  background: $color-warning-bg;
}
.s-processing {
  color: $color-primary;
  background: $color-primary-bg;
}
.s-replied {
  color: $color-success;
  background: $color-success-bg;
}
.s-closed {
  color: $color-text-placeholder;
  background: $color-bg-secondary;
}

.card-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8rpx 24rpx;
  margin-bottom: 12rpx;
  font-size: $font-xs;
  color: $color-text-secondary;
}
.card-content {
  font-size: $font-sm;
  color: $color-text-primary;
  display: block;
  margin-bottom: 12rpx;
  line-height: 1.6;
}
.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.card-time {
  font-size: $font-xs;
  color: $color-text-placeholder;
}
.card-actions {
  display: flex;
  gap: 16rpx;
}
.action-btn {
  font-size: $font-sm;
  color: $color-primary;
  &.danger {
    color: $color-danger;
  }
}

.admin-reply {
  margin: 12rpx 0;
  padding: 12rpx 16rpx;
  background: $color-primary-bg;
  border-radius: 8rpx;
  font-size: $font-sm;
  color: $color-primary;
}

.stars {
  font-size: $font-md;
  color: $color-text-disabled;
  .active {
    color: $color-warning;
  }
}

.end-text {
  text-align: center;
  font-size: $font-sm;
  color: $color-text-disabled;
  padding: 32rpx 0;
}
.load-more {
  text-align: center;
  font-size: $font-sm;
  color: $color-secondary;
  padding: 24rpx 0;
}
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 120rpx 0;
}
.loading-text {
  margin-top: 24rpx;
  font-size: $font-md;
  color: $color-text-placeholder;
}

.popup-content {
  padding: 32rpx;
}
.popup-title {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
  display: block;
  margin-bottom: 24rpx;
}
.form-textarea {
  width: 100%;
  box-sizing: border-box;
  min-height: 160rpx;
  padding: 16rpx 20rpx;
  font-size: 28rpx;
  border: 1rpx solid $color-border;
  border-radius: $radius-md;
}
.popup-footer {
  display: flex;
  gap: 16rpx;
  margin-top: 24rpx;
}
.btn {
  flex: 1;
  padding: 12rpx 20rpx;
  border-radius: $radius-sm;
  font-size: $font-sm;
  line-height: 1.6;
  &::after {
    border: none;
  }
}
.btn-primary {
  color: $color-white;
  background: $color-primary;
}
.btn-danger {
  color: $color-white;
  background: $color-danger;
}
.btn-default {
  color: $color-text-primary;
  background: $color-bg-secondary;
}
</style>

// dehaze-taro/src/pages/system/feedback/index.tsx
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Tag, Loading, Empty, Tabs, Popup, Input, Textarea } from "@taroify/core";
import { FeedbackAPI } from "dehaze-sdk-js";
import type { FeedbackPageVO, RatingPageVO } from "dehaze-sdk-js";
import PageLayout from "@/layout";
import { usePermission } from "@/hooks/usePermission";
import { getErrorMessage } from "@/utils/error";
import "./index.less";

const FEEDBACK_STATUS_LABELS: Record<string, string> = {
  pending: "待处理",
  processing: "处理中",
  replied: "已回复",
  closed: "已关闭",
};

const FEEDBACK_TYPE_LABELS: Record<string, string> = {
  suggestion: "建议",
  bug: "缺陷",
  experience: "体验",
  complaint: "投诉",
};

const FeedbackManagePage: React.FC = () => {
  const { hasPermission } = usePermission();
  const canManage = hasPermission("sys:feedback:*");

  const [tab, setTab] = useState(0);
  const [feedbacks, setFeedbacks] = useState<FeedbackPageVO[]>([]);
  const [ratings, setRatings] = useState<RatingPageVO[]>([]);
  const [loading, setLoading] = useState(false);
  const [totalFeedback, setTotalFeedback] = useState(0);
  const [totalRating, setTotalRating] = useState(0);
  const [pageNum, setPageNum] = useState(1);
  const [ratingPageNum, setRatingPageNum] = useState(1);
  const [keyword, setKeyword] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [typeFilter, setTypeFilter] = useState("");

  const [replyPopupVisible, setReplyPopupVisible] = useState(false);
  const [replyTarget, setReplyTarget] = useState<{
    id: number;
    type: "feedback" | "rating";
  } | null>(null);
  const [replyContent, setReplyContent] = useState("");

  const [closePopupVisible, setClosePopupVisible] = useState(false);
  const [closeTargetId, setCloseTargetId] = useState<number | null>(null);
  const [closeReason, setCloseReason] = useState("");

  const fetchFeedbacks = useCallback(
    async (page: number, kw: string, status: string, type: string) => {
      setLoading(true);
      try {
        const params: any = { pageNum: page, pageSize: 15 };
        if (kw) params.keywords = kw;
        if (status) params.status = status;
        if (type) params.feedbackType = type;
        const res = await FeedbackAPI.listFeedback(params);
        setFeedbacks(res.list);
        setTotalFeedback(res.total);
        setPageNum(page);
      } catch (err: unknown) {
        Taro.showToast({
          title: getErrorMessage(err, "加载反馈失败"),
          icon: "none",
        });
      } finally {
        setLoading(false);
      }
    },
    []
  );

  const fetchRatings = useCallback(async (page: number) => {
    try {
      const res = await FeedbackAPI.listRatings({
        pageNum: page,
        pageSize: 15,
      });
      setRatings(res.list);
      setTotalRating(res.total);
      setRatingPageNum(page);
    } catch {
      // 静默
    }
  }, []);

  useEffect(() => {
    fetchFeedbacks(1, "", "", "");
    fetchRatings(1);
  }, [fetchFeedbacks, fetchRatings]);

  const handleSearch = () => {
    fetchFeedbacks(1, keyword, statusFilter, typeFilter);
  };

  const handleLoadMoreFeedback = () => {
    if (feedbacks.length < totalFeedback) {
      fetchFeedbacks(pageNum + 1, keyword, statusFilter, typeFilter);
    }
  };

  const handleLoadMoreRating = () => {
    if (ratings.length < totalRating) {
      fetchRatings(ratingPageNum + 1);
    }
  };

  const openClose = (id: number) => {
    setCloseTargetId(id);
    setCloseReason("");
    setClosePopupVisible(true);
  };

  const handleCloseFeedback = async () => {
    if (!closeTargetId || !closeReason.trim()) {
      Taro.showToast({ title: "请输入关闭原因", icon: "none" });
      return;
    }
    try {
      await FeedbackAPI.closeFeedback(closeTargetId, {
        closeReason: closeReason.trim(),
      });
      Taro.showToast({ title: "已关闭", icon: "success" });
      setClosePopupVisible(false);
      fetchFeedbacks(pageNum, keyword, statusFilter, typeFilter);
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "操作失败"), icon: "none" });
    }
  };

  const openReply = (id: number, type: "feedback" | "rating") => {
    setReplyTarget({ id, type });
    setReplyContent("");
    setReplyPopupVisible(true);
  };

  const handleReply = async () => {
    if (!replyTarget || !replyContent.trim()) {
      Taro.showToast({ title: "请输入回复内容", icon: "none" });
      return;
    }
    try {
      if (replyTarget.type === "feedback") {
        await FeedbackAPI.replyFeedback(replyTarget.id, {
          content: replyContent,
        });
      } else {
        await FeedbackAPI.replyRating(replyTarget.id, replyContent);
      }
      Taro.showToast({ title: "回复成功", icon: "success" });
      setReplyPopupVisible(false);
      if (replyTarget.type === "feedback") {
        fetchFeedbacks(pageNum, keyword, statusFilter, typeFilter);
      } else {
        fetchRatings(ratingPageNum);
      }
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "回复失败"), icon: "none" });
    }
  };

  const handleHideRating = async (id: number) => {
    const res = await Taro.showModal({
      title: "确认隐藏",
      content: "确定要隐藏这条评价吗？",
    });
    if (!res.confirm) return;
    try {
      await FeedbackAPI.hideRating(id);
      Taro.showToast({ title: "已隐藏", icon: "success" });
      fetchRatings(ratingPageNum);
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "操作失败"), icon: "none" });
    }
  };

  return (
    <PageLayout level="L2" title="反馈评价管理">
      <View className="system-manage-page">
        <Tabs value={tab} onChange={setTab}>
          <Tabs.TabPane title="反馈列表" />
          <Tabs.TabPane title="评价列表" />
        </Tabs>

        {tab === 0 && (
          <>
            <View className="search-bar">
              <Input
                className="search-input"
                placeholder="搜索反馈内容"
                value={keyword}
                onInput={(e) => setKeyword(e.detail.value)}
                onConfirm={handleSearch}
              />
              <View className="filter-row">
                {["", "pending", "processing", "replied", "closed"].map((s) => (
                  <Tag
                    key={s}
                    color={statusFilter === s ? "primary" : "default"}
                    size="small"
                    onClick={() => {
                      setStatusFilter(s);
                      fetchFeedbacks(1, keyword, s, typeFilter);
                    }}
                  >
                    {s ? FEEDBACK_STATUS_LABELS[s] || s : "全部"}
                  </Tag>
                ))}
              </View>
              <View className="filter-row" style={{ marginTop: "12rpx" }}>
                {["", "suggestion", "bug", "experience", "complaint"].map(
                  (t) => (
                    <Tag
                      key={t}
                      color={typeFilter === t ? "primary" : "default"}
                      size="small"
                      onClick={() => {
                        setTypeFilter(t);
                        fetchFeedbacks(1, keyword, statusFilter, t);
                      }}
                    >
                      {t ? FEEDBACK_TYPE_LABELS[t] || t : "全部类型"}
                    </Tag>
                  )
                )}
              </View>
            </View>

            <ScrollView
              scrollY
              className="list-scroll"
              onScrollToLower={handleLoadMoreFeedback}
            >
              {loading && feedbacks.length === 0 ? (
                <View className="loading-wrapper">
                  <Loading>加载中...</Loading>
                </View>
              ) : feedbacks.length === 0 ? (
                <Empty>
                  <Empty.Description>暂无反馈数据</Empty.Description>
                </Empty>
              ) : (
                feedbacks.map((f) => (
                  <View key={f.id} className="list-card">
                    <View className="card-header">
                      <View className="card-title-row">
                        <Text className="card-name">{f.title}</Text>
                        <Tag
                          size="small"
                          color={
                            f.status === "closed"
                              ? "default"
                              : f.status === "replied"
                                ? "success"
                                : f.status === "processing"
                                  ? "warning"
                                  : "primary"
                          }
                        >
                          {FEEDBACK_STATUS_LABELS[f.status] || f.status}
                        </Tag>
                      </View>
                      <Tag size="small" color="default">
                        {FEEDBACK_TYPE_LABELS[f.feedbackType] || f.feedbackType}
                      </Tag>
                    </View>
                    <View className="card-meta">
                      <Text className="meta-item">
                        用户: {f.username} (ID:{f.userId})
                      </Text>
                      {f.assigneeName && (
                        <Text className="meta-item">
                          处理人: {f.assigneeName}
                        </Text>
                      )}
                      <Text className="meta-item">优先级: {f.priority}</Text>
                    </View>
                    <Text className="card-content" numberOfLines={2}>
                      {f.content}
                    </Text>
                    <View className="card-meta">
                      <Text className="meta-item">
                        {new Date(f.createTime).toLocaleString("zh-CN")}
                      </Text>
                    </View>
                    {canManage && (
                      <View className="card-actions">
                        {f.status !== "closed" && (
                          <>
                            <View
                              className="action-btn"
                              onClick={() => openReply(f.id, "feedback")}
                            >
                              回复
                            </View>
                            <View
                              className="action-btn danger"
                              onClick={() => openClose(f.id)}
                            >
                              关闭
                            </View>
                          </>
                        )}
                      </View>
                    )}
                  </View>
                ))
              )}
              {feedbacks.length > 0 && feedbacks.length < totalFeedback && (
                <View className="load-more" onClick={handleLoadMoreFeedback}>
                  <Text>加载更多</Text>
                </View>
              )}
            </ScrollView>
          </>
        )}

        {tab === 1 && (
          <ScrollView
            scrollY
            className="list-scroll"
            onScrollToLower={handleLoadMoreRating}
          >
            {ratings.length === 0 ? (
              <Empty>
                <Empty.Description>暂无评价数据</Empty.Description>
              </Empty>
            ) : (
              ratings.map((r) => (
                <View key={r.id} className="list-card">
                  <View className="card-header">
                    <View className="card-title-row">
                      <Text className="card-name">{r.algorithmName}</Text>
                      <Tag size="small" color="warning">
                        {"★".repeat(r.rating)}
                      </Tag>
                    </View>
                    {r.isHidden === 1 && (
                      <Tag size="small" color="default">
                        已隐藏
                      </Tag>
                    )}
                  </View>
                  {r.comment && (
                    <Text className="card-content">{r.comment}</Text>
                  )}
                  <View className="card-meta">
                    <Text className="meta-item">
                      用户: {r.username || `ID:${r.userId}`}
                    </Text>
                    <Text className="meta-item">
                      {new Date(r.createTime).toLocaleString("zh-CN")}
                    </Text>
                  </View>
                  {r.adminReply && (
                    <View className="admin-reply">
                      <Text className="reply-label">管理员回复: </Text>
                      <Text>{r.adminReply}</Text>
                    </View>
                  )}
                  {canManage && (
                    <View className="card-actions">
                      <View
                        className="action-btn"
                        onClick={() => openReply(r.id, "rating")}
                      >
                        回复
                      </View>
                      {r.isHidden !== 1 && (
                        <View
                          className="action-btn danger"
                          onClick={() => handleHideRating(r.id)}
                        >
                          隐藏
                        </View>
                      )}
                    </View>
                  )}
                </View>
              ))
            )}
            {ratings.length > 0 && ratings.length < totalRating && (
              <View className="load-more" onClick={handleLoadMoreRating}>
                <Text>加载更多</Text>
              </View>
            )}
          </ScrollView>
        )}

        {/* 回复弹窗 */}
        <Popup
          open={replyPopupVisible}
          placement="bottom"
          rounded
          onClose={() => setReplyPopupVisible(false)}
        >
          <View className="popup-content">
            <View className="popup-header">
              <Text className="popup-title">回复</Text>
              <Text
                className="popup-close"
                onClick={() => setReplyPopupVisible(false)}
              >
                ×
              </Text>
            </View>
            <View className="popup-body">
              <View className="form-item">
                <Text className="form-label">回复内容</Text>
                <Textarea
                  className="form-textarea"
                  placeholder="请输入回复内容"
                  value={replyContent}
                  onChange={(e) =>
                    setReplyContent(e.detail?.value || "")
                  }
                  maxlength={2000}
                />
              </View>
              <View className="popup-confirm-btn" onClick={handleReply}>
                <Text>提交回复</Text>
              </View>
            </View>
          </View>
        </Popup>

        {/* 关闭反馈弹窗 */}
        <Popup
          open={closePopupVisible}
          placement="bottom"
          rounded
          onClose={() => setClosePopupVisible(false)}
        >
          <View className="popup-content">
            <View className="popup-header">
              <Text className="popup-title">关闭反馈</Text>
              <Text
                className="popup-close"
                onClick={() => setClosePopupVisible(false)}
              >
                ×
              </Text>
            </View>
            <View className="popup-body">
              <View className="form-item">
                <Text className="form-label">关闭原因 *</Text>
                <Textarea
                  className="form-textarea"
                  placeholder="请填写关闭原因（必填）"
                  value={closeReason}
                  onChange={(e) =>
                    setCloseReason(e.detail?.value || "")
                  }
                  maxlength={500}
                />
              </View>
              <View className="popup-confirm-btn" onClick={handleCloseFeedback}>
                <Text>确认关闭</Text>
              </View>
            </View>
          </View>
        </Popup>
      </View>
    </PageLayout>
  );
};

export default FeedbackManagePage;
