// dehaze-uniapp/src/pages/system/package/index.vue
<template>
  <PageLayout level="L2" title="套餐管理">
    <view class="page-body">
      <view class="list-row list-row-head">
        <text class="cell">名称</text>
        <text class="cell">售价</text>
        <text class="cell">周期</text>
        <text class="cell">状态</text>
        <text class="cell">操作</text>
      </view>
      <view v-for="item in list" :key="item.id" class="list-row">
        <text class="cell">{{ item.name }}</text>
        <text class="cell">¥{{ item.salePrice }}</text>
        <text class="cell">{{ item.periodDays }}天</text>
        <view class="cell">
          <view
            class="tag tag-sm"
            :class="item.status === 1 ? 'tag-success' : 'tag-danger'"
          >
            {{ item.status === 1 ? "上架" : "下架" }}
          </view>
        </view>
        <view class="cell cell-actions">
          <SvgIcon name="edit-pen" @click="editItem(item)" />
          <button
            class="btn btn-sm"
            :class="item.status === 1 ? 'btn-warning' : 'btn-success'"
            @click="toggleStatus(item)"
          >
            {{ item.status === 1 ? "下架" : "上架" }}
          </button>
        </view>
      </view>
      <view v-if="list.length === 0" class="empty-tip">暂无套餐</view>
    </view>
    <FabButton @click="editItem(null)"
      ><SvgIcon name="plus" color="#fff" size="24"
    /></FabButton>
    <Popup :show="showForm" mode="center" round @close="showForm = false">
      <view class="popup-content">
        <view class="popup-title">{{ form.id ? "编辑套餐" : "新增套餐" }}</view>
        <view class="form-row">
          <text class="form-label">名称</text>
          <input
            class="form-input"
            v-model="form.name"
            placeholder="套餐名称"
          />
        </view>
        <view class="form-row">
          <text class="form-label">售价</text>
          <input
            class="form-input"
            v-model.number="form.salePrice"
            type="number"
            placeholder="售价"
          />
        </view>
        <view class="form-row">
          <text class="form-label">原价</text>
          <input
            class="form-input"
            v-model.number="form.originalPrice"
            type="number"
            placeholder="原价"
          />
        </view>
        <view class="form-row">
          <text class="form-label">等级</text>
          <input
            class="form-input"
            v-model="form.levelCode"
            placeholder="level_1/level_2/level_3"
          />
        </view>
        <view class="form-row">
          <text class="form-label">周期</text>
          <input
            class="form-input"
            v-model="form.period"
            placeholder="monthly/quarterly/yearly"
          />
        </view>
        <view class="form-row">
          <text class="form-label">天数</text>
          <input
            class="form-input"
            v-model.number="form.periodDays"
            type="number"
            placeholder="有效天数"
          />
        </view>
        <view class="form-row">
          <text class="form-label">描述</text>
          <input
            class="form-input"
            v-model="form.description"
            placeholder="描述"
          />
        </view>
        <view class="form-row">
          <text class="form-label">状态</text>
          <switch
            :checked="form.status === 1"
            @change="(e: any) => (form.status = e.detail.value ? 1 : 0)"
          />
        </view>
        <button class="btn btn-primary" :disabled="saving" @click="handleSave">
          保存
        </button>
      </view>
    </Popup>
  </PageLayout>
</template>

<script setup lang="ts">
import { ref } from "vue";
import PageLayout from "@/layout/index.vue";
import Popup from "@/components/common/Popup.vue";
import FabButton from "@/components/common/FabButton.vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import { PackageAPI } from "dehaze-sdk-js";

const list = ref<any[]>([]);
const showForm = ref(false);
const form = ref<any>({
  name: "",
  salePrice: 0,
  originalPrice: 0,
  levelCode: "level_1",
  period: "monthly",
  periodDays: 30,
  description: "",
  status: 1,
});
const saving = ref(false);

const fetchList = async () => {
  try {
    const res = await PackageAPI.getPage({ pageNum: 1, pageSize: 100 });
    list.value = res.list || [];
  } catch {}
};
const editItem = (item: any) => {
  if (item) {
    form.value = {
      id: item.id,
      name: item.name,
      salePrice: item.salePrice,
      originalPrice: item.originalPrice,
      levelCode: item.levelCode,
      period: item.period,
      periodDays: item.periodDays,
      description: item.description || "",
      status: item.status,
    };
  } else {
    form.value = {
      name: "",
      salePrice: 0,
      originalPrice: 0,
      levelCode: "level_1",
      period: "monthly",
      periodDays: 30,
      description: "",
      status: 1,
    };
  }
  showForm.value = true;
};
const handleSave = async () => {
  saving.value = true;
  try {
    const data = {
      name: form.value.name,
      salePrice: Number(form.value.salePrice),
      originalPrice: Number(form.value.originalPrice),
      levelCode: form.value.levelCode,
      period: form.value.period,
      periodDays: Number(form.value.periodDays),
      description: form.value.description,
      status: form.value.status,
    };
    if (form.value.id) await PackageAPI.update(form.value.id, data);
    else await PackageAPI.add(data);
    showForm.value = false;
    fetchList();
  } catch {
    uni.showToast({ title: "保存失败", icon: "error" });
  } finally {
    saving.value = false;
  }
};
const toggleStatus = async (item: any) => {
  const newStatus = item.status === 1 ? 0 : 1;
  try {
    await PackageAPI.updateStatus(item.id, newStatus);
    item.status = newStatus;
  } catch {
    uni.showToast({ title: "操作失败", icon: "error" });
  }
};

fetchList();
</script>

<style lang="scss" scoped>
.page-body {
  padding: 20rpx;
}
.list-row {
  display: flex;
  align-items: center;
  padding: 20rpx 16rpx;
  border-bottom: 1rpx solid $color-border;
  font-size: 26rpx;

  .cell {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .cell-actions {
    display: flex;
    gap: 12rpx;
    align-items: center;
  }
}
.list-row-head {
  background: $color-bg-secondary;
  font-weight: 600;
  color: $color-text-secondary;
}
.tag {
  padding: 4rpx 12rpx;
  border-radius: $radius-sm;
  font-size: $font-xs;
}
.tag-sm {
  padding: 2rpx 10rpx;
}
.tag-success {
  color: $color-success;
  background: $color-success-bg;
}
.tag-danger {
  color: $color-danger;
  background: $color-danger-bg;
}
.btn {
  padding: 8rpx 20rpx;
  border-radius: $radius-sm;
  font-size: $font-sm;
  line-height: 1.6;
  &::after {
    border: none;
  }
}
.btn-sm {
  padding: 4rpx 16rpx;
  font-size: $font-xs;
}
.btn-primary {
  color: $color-white;
  background: $color-primary;
}
.btn-success {
  color: $color-white;
  background: $color-success;
}
.btn-warning {
  color: $color-white;
  background: $color-warning;
}
.popup-content {
  padding: 30rpx;
  width: 90vw;
  max-height: 80vh;
  overflow-y: auto;
}
.popup-title {
  font-size: 32rpx;
  font-weight: bold;
  margin-bottom: 20rpx;
}
.form-row {
  display: flex;
  align-items: center;
  padding: 20rpx 0;
  border-bottom: 1rpx solid $color-border;

  .form-label {
    width: 120rpx;
    flex-shrink: 0;
    font-size: 28rpx;
    color: $color-text-secondary;
  }

  .form-input {
    flex: 1;
    font-size: 28rpx;
  }
}
</style>

// dehaze-taro/src/pages/system/package/index.tsx
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Tag, Loading, Empty, Popup, Input } from "@taroify/core";
import { PackageAPI } from "dehaze-sdk-js";
import type { PackagePageVO } from "dehaze-sdk-js";
import PageLayout from "@/layout";
import { usePermission } from "@/hooks/usePermission";
import { getErrorMessage } from "@/utils/error";
import "./index.less";

const PERIOD_LABELS: Record<string, string> = {
  monthly: "月卡",
  quarterly: "季卡",
  yearly: "年卡",
};

const LEVEL_LABELS: Record<string, string> = {
  level_1: "普通",
  level_2: "白银",
  level_3: "黄金",
};

const PackageManagePage: React.FC = () => {
  const { hasPermission } = usePermission();
  const canEdit = hasPermission("sys:package:edit");

  const [packages, setPackages] = useState<PackagePageVO[]>([]);
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(0);
  const [pageNum, setPageNum] = useState(1);
  const [keyword, setKeyword] = useState("");
  const [statusFilter, setStatusFilter] = useState<number | undefined>(
    undefined
  );

  const [editPopupVisible, setEditPopupVisible] = useState(false);
  const [editingPkg, setEditingPkg] = useState<PackagePageVO | null>(null);
  const [formName, setFormName] = useState("");
  const [formSalePrice, setFormSalePrice] = useState("");
  const [formOriginalPrice, setFormOriginalPrice] = useState("");
  const [formSort, setFormSort] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const fetchPackages = useCallback(
    async (page: number, kw: string, status?: number) => {
      setLoading(true);
      try {
        const params: any = { pageNum: page, pageSize: 15 };
        if (kw) params.name = kw;
        if (status !== undefined) params.status = status;
        const res = await PackageAPI.getPage(params);
        setPackages(res.list);
        setTotal(res.total);
        setPageNum(page);
      } catch (err: unknown) {
        Taro.showToast({
          title: getErrorMessage(err, "加载套餐列表失败"),
          icon: "none",
        });
      } finally {
        setLoading(false);
      }
    },
    []
  );

  useEffect(() => {
    fetchPackages(1, "", undefined);
  }, [fetchPackages]);

  const handleSearch = () => {
    fetchPackages(1, keyword, statusFilter);
  };

  const handleLoadMore = () => {
    if (packages.length < total) {
      fetchPackages(pageNum + 1, keyword, statusFilter);
    }
  };

  const handleToggleStatus = async (pkg: PackagePageVO) => {
    if (!canEdit) return;
    const newStatus = pkg.status === 1 ? 0 : 1;
    const label = newStatus === 0 ? "下架" : "上架";
    const res = await Taro.showModal({
      title: `确认${label}`,
      content: `确定要${label}套餐「${pkg.name}」吗？`,
    });
    if (!res.confirm) return;
    try {
      await PackageAPI.updateStatus(pkg.id, newStatus);
      Taro.showToast({ title: `${label}成功`, icon: "success" });
      fetchPackages(pageNum, keyword, statusFilter);
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "操作失败"), icon: "none" });
    }
  };

  const [formDesc, setFormDesc] = useState("");

  const openEdit = (pkg: PackagePageVO) => {
    setEditingPkg(pkg);
    setFormName(pkg.name);
    setFormSalePrice(String(pkg.salePrice));
    setFormOriginalPrice(String(pkg.originalPrice));
    setFormSort("");
    setFormDesc("");
    setEditPopupVisible(true);
  };

  const handleSave = async () => {
    if (!editingPkg) return;
    setSubmitting(true);
    try {
      await PackageAPI.update(editingPkg.id, {
        name: formName || editingPkg.name,
        levelCode: editingPkg.levelCode,
        period: editingPkg.period,
        periodDays: editingPkg.periodDays,
        originalPrice: Number(formOriginalPrice) || editingPkg.originalPrice,
        salePrice: Number(formSalePrice) || editingPkg.salePrice,
        description: formDesc || undefined,
        sort: Number(formSort) || 0,
      });
      Taro.showToast({ title: "保存成功", icon: "success" });
      setEditPopupVisible(false);
      fetchPackages(pageNum, keyword, statusFilter);
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "保存失败"), icon: "none" });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <PageLayout level="L2" title="套餐管理">
      <View className="system-manage-page">
        {/* 搜索栏 */}
        <View className="search-bar">
          <Input
            className="search-input"
            placeholder="搜索套餐名称"
            value={keyword}
            onInput={(e) => setKeyword(e.detail.value)}
            onConfirm={handleSearch}
          />
          <View className="filter-row">
            <Tag
              color={statusFilter === undefined ? "primary" : "default"}
              size="small"
              onClick={() => {
                setStatusFilter(undefined);
                fetchPackages(1, keyword, undefined);
              }}
            >
              全部
            </Tag>
            <Tag
              color={statusFilter === 1 ? "primary" : "default"}
              size="small"
              onClick={() => {
                setStatusFilter(1);
                fetchPackages(1, keyword, 1);
              }}
            >
              在售
            </Tag>
            <Tag
              color={statusFilter === 0 ? "primary" : "default"}
              size="small"
              onClick={() => {
                setStatusFilter(0);
                fetchPackages(1, keyword, 0);
              }}
            >
              已下架
            </Tag>
          </View>
        </View>

        {/* 套餐列表 */}
        <ScrollView
          scrollY
          className="list-scroll"
          onScrollToLower={handleLoadMore}
        >
          {loading && packages.length === 0 ? (
            <View className="loading-wrapper">
              <Loading>加载中...</Loading>
            </View>
          ) : packages.length === 0 ? (
            <Empty>
              <Empty.Description>暂无套餐数据</Empty.Description>
            </Empty>
          ) : (
            packages.map((pkg) => (
              <View key={pkg.id} className="list-card">
                <View className="card-header">
                  <View className="card-title-row">
                    <Text className="card-name">{pkg.name}</Text>
                    <Tag
                      size="small"
                      color={pkg.status === 1 ? "success" : "default"}
                    >
                      {pkg.status === 1 ? "在售" : "已下架"}
                    </Tag>
                  </View>
                  <Text className="card-id">#{pkg.id}</Text>
                </View>
                <View className="card-meta">
                  <Text className="meta-item">
                    等级:{" "}
                    {pkg.levelName ||
                      LEVEL_LABELS[pkg.levelCode] ||
                      pkg.levelCode}
                  </Text>
                  <Text className="meta-item">
                    周期: {PERIOD_LABELS[pkg.period] || pkg.period} (
                    {pkg.periodDays}天)
                  </Text>
                </View>
                <View className="card-pricing">
                  <Text className="sale-price">¥{pkg.salePrice}</Text>
                  <Text className="original-price">¥{pkg.originalPrice}</Text>
                  <Text className="daily-price">日均 ¥{pkg.dailyPrice}</Text>
                </View>
                <View className="card-meta">
                  <Text className="meta-item">销量: {pkg.salesCount}</Text>
                  <Text className="meta-item">
                    创建: {new Date(pkg.createTime).toLocaleDateString("zh-CN")}
                  </Text>
                </View>
                {canEdit && (
                  <View className="card-actions">
                    <View className="action-btn" onClick={() => openEdit(pkg)}>
                      编辑
                    </View>
                    <View
                      className={`action-btn ${pkg.status === 1 ? "danger" : "primary"}`}
                      onClick={() => handleToggleStatus(pkg)}
                    >
                      {pkg.status === 1 ? "下架" : "上架"}
                    </View>
                  </View>
                )}
              </View>
            ))
          )}
          {packages.length > 0 && packages.length < total && (
            <View className="load-more" onClick={handleLoadMore}>
              <Text>加载更多</Text>
            </View>
          )}
        </ScrollView>

        {/* 编辑弹窗 */}
        <Popup
          open={editPopupVisible}
          placement="bottom"
          rounded
          onClose={() => setEditPopupVisible(false)}
        >
          <View className="popup-content">
            <View className="popup-header">
              <Text className="popup-title">编辑套餐</Text>
              <Text
                className="popup-close"
                onClick={() => setEditPopupVisible(false)}
              >
                ×
              </Text>
            </View>
            <View className="popup-body">
              <View className="form-item">
                <Text className="form-label">套餐名称</Text>
                <Input
                  className="form-input"
                  value={formName}
                  onInput={(e) => setFormName(e.detail.value)}
                />
              </View>
              <View className="form-item">
                <Text className="form-label">售价</Text>
                <Input
                  className="form-input"
                  type="number"
                  value={formSalePrice}
                  onInput={(e) => setFormSalePrice(e.detail.value)}
                />
              </View>
              <View className="form-item">
                <Text className="form-label">原价</Text>
                <Input
                  className="form-input"
                  type="number"
                  value={formOriginalPrice}
                  onInput={(e) => setFormOriginalPrice(e.detail.value)}
                />
              </View>
              <View className="form-item">
                <Text className="form-label">描述</Text>
                <Input
                  className="form-input"
                  value={formDesc}
                  onInput={(e) => setFormDesc(e.detail.value)}
                />
              </View>
              <View className="form-item">
                <Text className="form-label">排序</Text>
                <Input
                  className="form-input"
                  type="number"
                  value={formSort}
                  onInput={(e) => setFormSort(e.detail.value)}
                />
              </View>
              <View className="popup-confirm-btn" onClick={handleSave}>
                <Text>{submitting ? "保存中..." : "保存"}</Text>
              </View>
            </View>
          </View>
        </Popup>
      </View>
    </PageLayout>
  );
};

export default PackageManagePage;
