// dehaze-front-vue/src/views/algorithm/index.vue
<script lang="ts" setup>
import EditDialog from "@/components/DataList/EditDialog/index.vue";
import { Algorithm, AlgorithmAPI, AlgorithmQuery } from "dehaze-sdk-js";

defineOptions({
  name: "AlgorithmList",
  inheritAttrs: false,
});

const queryFormRef = ref(ElForm);
const loading = ref(false);
const queryParams = reactive<AlgorithmQuery>({
  keywords: "",
});
const list = ref<Algorithm[]>([]);

// 列选项
const selectedColumns = ref([
  "name",
  "type",
  "description",
  "size",
  "importPath",
  "path",
  "status",
]);
const columns = [
  { label: "名称", value: "name" },
  { label: "类型", value: "type" },
  { label: "描述", value: "description" },
  { label: "大小", value: "size" },
  { label: "代码导入路径", value: "importPath" },
  { label: "存储位置", value: "path" },
  { label: "状态", value: "status" },
];

// 查询算法列表
function handleQuery() {
  loading.value = true;
  AlgorithmAPI.getList(queryParams)
    .then((data) => {
      list.value = data;
    })
    .finally(() => {
      loading.value = false;
    });
}

// 搜索防抖（300ms）
const debouncedQuery = useDebounceFn(handleQuery, 300);

// 关键字变化时防抖搜索
watch(
  () => queryParams.keywords,
  () => {
    debouncedQuery();
  }
);

function resetQuery() {
  queryFormRef.value.resetFields();
  handleQuery();
}

const dialogRef = ref();

function onEdit<T extends Algorithm>(type: string, row: T) {
  dialogRef.value.open(type, row);
}

function openDialog<T extends Algorithm>(type: string, row: T) {
  onEdit(type, row);
}

// 删除算法（带算法名确认文案）
function handleDelete(row: Algorithm) {
  ElMessageBox.confirm(
    `确认删除算法「${row.name}」吗？删除后不可恢复。`,
    "警告",
    {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    }
  )
    .then(() => {
      AlgorithmAPI.deleteByIds([row.id.toString()]);
      ElMessage.success("删除成功");
      handleQuery();
    })
    .catch(() => ElMessage.info("已取消删除"));
}

// 切换算法状态
function handleStatusChange(row: Algorithm, val: string | number | boolean) {
  const status = Number(val);
  AlgorithmAPI.updateStatus(row.id, status)
    .then(() => {
      row.status = status;
      ElMessage.success(status === 1 ? "已启用" : "已禁用");
    })
    .catch(() => {
      // 接口失败时回滚状态
      row.status = status === 1 ? 0 : 1;
    });
}

// 算法详情弹窗
const detailVisible = ref(false);
const detailData = ref<Algorithm>();

function handleShowDetail(row: Algorithm) {
  detailData.value = row;
  detailVisible.value = true;
}

onMounted(() => {
  handleQuery();
});
</script>

<template>
  <div class="app-container">
    <div class="search-container">
      <el-form ref="queryFormRef" :inline="true" :model="queryParams">
        <el-form-item label="关键字" prop="keywords">
          <el-input
            v-model="queryParams.keywords"
            placeholder="算法名称"
            clearable
            @keyup.enter="handleQuery"
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleQuery">
            <template #icon>
              <i-ep-search />
            </template>
            搜索
          </el-button>
          <el-button @click="resetQuery">
            <template #icon>
              <i-ep-refresh />
            </template>
            重置
          </el-button>
          <el-dropdown class="setting-button">
            <el-button>
              <template #icon>
                <i-ep-setting />
              </template>
              设置
            </el-button>
            <template #dropdown>
              <div class="setting-title">列选项</div>
              <el-divider class="p-0" />
              <el-checkbox-group
                v-model="selectedColumns"
                class="setting-checkbox"
              >
                <el-checkbox
                  v-for="column in columns"
                  :key="column.value"
                  :label="column.label"
                  :value="column.value"
                />
              </el-checkbox-group>
            </template>
          </el-dropdown>
        </el-form-item>
      </el-form>
    </div>

    <el-card class="table-container" shadow="never">
      <el-table
        v-loading="loading"
        :data="list"
        :tree-props="{
          children: 'children',
          hasChildren: 'hasChildren',
        }"
        :default-expand-all="true"
        highlight-current-row
        row-key="id"
      >
        <el-table-column
          v-if="selectedColumns.includes('name')"
          label="名称"
          prop="name"
          width="200"
        >
          <template #default="scope">
            <el-button link type="primary" @click.stop="handleShowDetail(scope.row)">
              {{ scope.row.name }}
            </el-button>
          </template>
        </el-table-column>
        <el-table-column
          v-if="selectedColumns.includes('type')"
          label="类型"
          prop="type"
          width="100"
        />
        <el-table-column
          v-if="selectedColumns.includes('description')"
          label="描述"
          min-width="500"
          prop="description"
        />
        <el-table-column
          v-if="selectedColumns.includes('size')"
          label="大小"
          prop="size"
          width="120"
        />
        <el-table-column
          v-if="selectedColumns.includes('importPath')"
          label="代码导入路径"
          min-width="180"
          prop="importPath"
        />
        <el-table-column
          v-if="selectedColumns.includes('path')"
          label="存储位置"
          prop="path"
          width="300"
        />
        <el-table-column
          v-if="selectedColumns.includes('status')"
          align="center"
          label="状态"
          min-width="90"
        >
          <template #default="scope">
            <el-switch
              :model-value="scope.row.status"
              :active-value="1"
              :inactive-value="0"
              active-text="启用"
              inactive-text="禁用"
              inline-prompt
              @change="(val) => handleStatusChange(scope.row, val)"
              @click.stop
            />
          </template>
        </el-table-column>
        <el-table-column align="center" fixed="right" label="操作" width="220">
          <template #default="scope">
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="openDialog('新增', scope.row)"
            >
              <i-ep-plus />
              新增
            </el-button>
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="openDialog('编辑', scope.row)"
            >
              <i-ep-edit />
              编辑
            </el-button>
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="handleDelete(scope.row)"
            >
              <i-ep-delete />
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <EditDialog
      ref="dialogRef"
      :isDatasetList="false"
      @on-update="handleQuery"
      @on-add="handleQuery"
    />

    <!-- 算法详情弹窗 -->
    <el-dialog
      v-model="detailVisible"
      title="算法详情"
      width="640px"
      append-to-body
      destroy-on-close
    >
      <el-descriptions
        v-if="detailData"
        :column="2"
        border
        label-class-name="detail-label"
      >
        <el-descriptions-item label="算法名称">
          {{ detailData.name }}
        </el-descriptions-item>
        <el-descriptions-item label="算法类型">
          {{ detailData.type }}
        </el-descriptions-item>
        <el-descriptions-item label="算法大小">
          {{ detailData.size }}
        </el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag v-if="detailData.status === 1" type="success">启用</el-tag>
          <el-tag v-else type="info">禁用</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="导入路径" :span="2">
          {{ detailData.importPath || "-" }}
        </el-descriptions-item>
        <el-descriptions-item label="存储位置" :span="2">
          {{ detailData.path || "-" }}
        </el-descriptions-item>
        <el-descriptions-item label="创建时间" :span="2">
          {{ detailData.createTime || "-" }}
        </el-descriptions-item>
        <el-descriptions-item label="算法描述" :span="2">
          {{ detailData.description || "-" }}
        </el-descriptions-item>
      </el-descriptions>
      <template #footer>
        <el-button @click="detailVisible = false">关闭</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style lang="scss" scoped>
.setting-button {
  margin-left: 12px;
}

.setting-title {
  margin-top: 8px;
  margin-bottom: 8px;
  font-size: 16px;
  font-weight: bold;
  text-align: center;
}

.setting-checkbox {
  display: flex;
  flex-direction: column;
  margin: 0 15px;
}

:deep(.detail-label) {
  width: 110px;
  font-weight: bold;
}
</style>

<style lang="scss">
.el-divider--horizontal {
  margin: 5px 0;
}
</style>

// src/pages/algorithm/index.tsx
import AlgorithmAPI from "@/api/algorithm";
import { Algorithm, AlgorithmQuery } from "@/api/algorithm/model";
import EditModal from "@/pages/dataset/components/EditModal";
import { DeleteOutlined, EditOutlined } from "@ant-design/icons";
import {
  Button,
  Card,
  Checkbox,
  Form,
  Input,
  Popconfirm,
  Popover,
  Table,
  TableColumnsType,
} from "antd";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

/**
 * 递归函数，用于遍历和清理 Dataset 结构
 * @param algorithms - 当前遍历的 Dataset 数组
 */
function cleanAlgorithm(algorithms: Algorithm[]): void {
  for (const element of algorithms) {
    const algorithm = element;

    if (algorithm.children && algorithm.children.length > 0) {
      // 递归遍历每个子数据集
      cleanAlgorithm(algorithm.children);
    } else if (
      algorithm.children &&
      Object.keys(algorithm.children).length === 0
    ) {
      delete algorithm.children;
    }
  }
}

export default function AlgorithmList(): React.JSX.Element {
  const [algorithmList, setAlgorithmList] = useState<Algorithm[]>();
  const [loading, setLoading] = useState(false);
  const [queryParams, setQueryParams] = useState<AlgorithmQuery>({});

  const handleDelete = useCallback(
    (id: number) => {
      return () => {
        AlgorithmAPI.deleteByIds([id.toString()]).then(() => {
          const newAlgorithmList = algorithmList?.filter(
            (algorithm) => algorithm.id !== id
          );
          setAlgorithmList(newAlgorithmList);
        });
      };
    },
    [algorithmList]
  );

  const columns: TableColumnsType<Algorithm> = useMemo(
    () => [
      {
        title: "名称",
        dataIndex: "name",
        key: "name",
        width: 160,
        align: "center",
      },
      {
        title: "类型",
        dataIndex: "type",
        key: "type",
        width: 80,
        align: "center",
      },
      {
        title: "描述",
        dataIndex: "description",
        minWidth: 250,
        key: "description",
      },
      {
        title: "大小",
        dataIndex: "size",
        key: "size",
        width: 90,
        align: "center",
      },
      {
        title: "存储位置",
        dataIndex: "path",
        key: "path",
        width: 50,
        align: "center",
      },
      {
        title: "代码导入路径",
        dataIndex: "importPath",
        key: "importPath",
        width: 50,
        align: "center",
      },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
        width: 50,
        align: "center",
        render: (status: number) => {
          return status === 1 ? "正常" : "异常";
        },
      },
      {
        title: "操作",
        key: "action",
        width: 180,
        align: "center",
        fixed: "right",
        render: (text: string, record: any) => (
          <>
            <Button
              type="text"
              size="small"
              icon={<EditOutlined />}
              onClick={() => openModal("新增", record)}
            >
              新增
            </Button>
            <Button
              type="text"
              size="small"
              icon={<EditOutlined />}
              onClick={() => openModal("编辑", record)}
            >
              编辑
            </Button>
            <Popconfirm
              title="确认要删除当前数据集吗？"
              onConfirm={handleDelete(record.id)}
              okText="确定"
              cancelText="取消"
            >
              <Button type="text" size="small" icon={<DeleteOutlined />} danger>
                删除
              </Button>
            </Popconfirm>
          </>
        ),
      },
    ],
    [handleDelete]
  );

  const tableColumns = columns.map((column) => {
    return {
      label: column.title as string,
      value: column.key as string,
    };
  });

  const [selectedColumns, setSelectedColumns] = useState([
    "name",
    "type",
    "description",
    "size",
    "importPath",
    "path",
    "status",
    "action",
  ]);
  const handleColumnChange = (checkedValues: string[]) => {
    setSelectedColumns(checkedValues);
  };
  const tableSettings = (
    <Checkbox.Group
      options={tableColumns}
      defaultValue={selectedColumns}
      onChange={handleColumnChange}
    ></Checkbox.Group>
  );

  const visibleColumns = useMemo(() => {
    return columns.filter((column) =>
      selectedColumns.includes(column.key as string)
    );
  }, [columns, selectedColumns]);

  useEffect(() => {
    const getAlgorithmInfo = () => {
      setLoading(true);
      AlgorithmAPI.getList(queryParams).then((data) => {
        cleanAlgorithm(data);
        setAlgorithmList(data);
        setLoading(false);
      });
    };
    getAlgorithmInfo();
  }, [queryParams]);

  const onFinish = (values: AlgorithmQuery) => {
    setQueryParams(values);
  };

  const onReset = () => {
    setQueryParams({});
  };

  // 获取对话框实例
  const editRef = useRef(null);

  // 打开对话框
  const openModal = (type: string, row: Algorithm) => {
    (editRef.current as any)?.open(type, row);
  };

  return (
    <div className="app-container">
      <Card className="search-container">
        <Form layout="inline" onFinish={onFinish} onReset={onReset}>
          <Form.Item name="keywords" label="关键字">
            <Input placeholder="数据集名称" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit">
              搜索
            </Button>
          </Form.Item>
          <Form.Item>
            <Button type="default" htmlType="reset">
              重置
            </Button>
          </Form.Item>
          <Form.Item>
            <Popover content={tableSettings}>
              <Button type="default">设置</Button>
            </Popover>
          </Form.Item>
        </Form>
      </Card>

      <Card style={{ overflowX: "hidden" }}>
        <Table
          columns={visibleColumns}
          expandable={{
            defaultExpandAllRows: true,
            indentSize: 10,
          }}
          rowKey={(record: Algorithm) => record.id}
          dataSource={algorithmList}
          loading={loading}
          pagination={false}
        />
      </Card>

      <EditModal ref={editRef} />
    </div>
  );
}
