// dehaze-front-vue/src/views/system/dict/index.vue
<!--字典类型-->

<template>
  <div class="app-container">
    <div class="search-container">
      <el-form ref="queryFormRef" :inline="true" :model="queryParams">
        <el-form-item label="关键字" prop="name">
          <el-input
            v-model="queryParams.keywords"
            clearable
            placeholder="字典类型名称/编码"
            @keyup.enter="handleQuery"
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleQuery()"
            ><el-icon><Search /></el-icon>搜索</el-button
          >
          <el-button @click="resetQuery()"
            ><el-icon><Refresh /></el-icon>重置</el-button
          >
        </el-form-item>
      </el-form>
    </div>

    <el-card class="table-container" shadow="never">
      <template #header>
        <div class="flex justify-between items-center">
          <div>
            <el-button
              v-hasPerm="['sys:dict:type:add']"
              type="success"
              @click="openDialog()"
              ><el-icon><Plus /></el-icon>新增</el-button
            >
            <el-button
              :disabled="ids.length === 0"
              type="danger"
              @click="handleDelete()"
              ><el-icon><Delete /></el-icon>删除</el-button
            >
          </div>
          <ImportExportToolbar
            module="dict"
            :query-params="queryParams"
            @import-complete="handleQuery"
          />
        </div>
      </template>
      <el-table
        v-loading="loading"
        :data="dictTypeList"
        border
        highlight-current-row
        @selection-change="handleSelectionChange"
      >
        <el-table-column align="center" type="selection" width="55" />
        <el-table-column label="字典类型名称" prop="name" width="200" />
        <el-table-column label="字典类型编码" prop="code" width="200" />
        <el-table-column align="center" label="状态" width="100">
          <template #default="scope">
            <el-tag v-if="scope.row.status === 1" type="success">启用</el-tag>
            <el-tag v-else type="info">禁用</el-tag>
          </template>
        </el-table-column>
        <el-table-column align="center" label="备注" prop="remark" />
        <el-table-column label="创建时间" prop="createTime" width="180" />
        <el-table-column align="center" fixed="right" label="操作" width="220">
          <template #default="scope">
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="openDictDialog(scope.row)"
              ><el-icon><Collection /></el-icon>字典数据</el-button
            >
            <el-button
              v-hasPerm="['sys:dict:type:edit']"
              link
              size="small"
              type="primary"
              @click.stop="openDialog(scope.row.id)"
              ><el-icon><Edit /></el-icon>编辑</el-button
            >
            <el-button
              v-hasPerm="['sys:dict:type:delete']"
              link
              size="small"
              type="primary"
              @click.stop="handleDelete(scope.row)"
              ><el-icon><Delete /></el-icon>删除</el-button
            >
          </template>
        </el-table-column>
      </el-table>

      <pagination
        v-if="total > 0"
        v-model:limit="queryParams.pageSize"
        v-model:page="queryParams.pageNum"
        v-model:total="total"
        @pagination="handleQuery"
      />
    </el-card>

    <el-dialog
      v-model="dialog.visible"
      :title="dialog.title"
      width="500px"
      @close="closeDialog"
    >
      <el-form
        ref="dataFormRef"
        :model="formData"
        :rules="rules"
        label-width="80px"
      >
        <el-form-item label="字典名称" prop="name">
          <el-input v-model="formData.name" placeholder="请输入字典名称" />
        </el-form-item>
        <el-form-item label="字典编码" prop="code">
          <el-input v-model="formData.code" placeholder="请输入字典编码" />
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="formData.status">
            <el-radio :label="1">正常</el-radio>
            <el-radio :label="0">停用</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="备注" prop="remark">
          <el-input
            v-model="formData.remark"
            :autosize="{ minRows: 2, maxRows: 4 }"
            placeholder="字典类型备注"
            type="textarea"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="handleSubmit">确 定</el-button>
          <el-button @click="closeDialog">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <!--字典数据弹窗-->
    <el-dialog
      v-model="dictDataDialog.visible"
      :title="dictDataDialog.title"
      width="1000px"
      @close="closeDictDialog"
    >
      <dict-item
        v-model:typeCode="selectedDictType.typeCode"
        v-model:typeName="selectedDictType.typeName"
      />
    </el-dialog>
  </div>
</template>

<script lang="ts" setup>
defineOptions({
  name: "DictType",
  inheritAttrs: false,
});

import {
  DictAPI,
  DictTypeForm,
  DictTypePageVO,
  DictTypeQuery,
} from "dehaze-sdk-js";
import {
  Collection,
  Delete,
  Edit,
  Plus,
  Refresh,
  Search,
} from "@element-plus/icons-vue";
import ImportExportToolbar from "@/components/ImportExportToolbar/index.vue";

const queryFormRef = ref(ElForm);
const dataFormRef = ref(ElForm);

const loading = ref(false);
const ids = ref<number[]>([]);
const total = ref(0);

const queryParams = reactive<DictTypeQuery>({
  pageNum: 1,
  pageSize: 10,
});

const dictTypeList = ref<DictTypePageVO[]>();

const dialog = reactive({
  title: "",
  visible: false,
});

const formData = reactive<DictTypeForm>({
  status: 1,
});

const rules = reactive({
  name: [{ required: true, message: "请输入字典类型名称", trigger: "blur" }],
  code: [{ required: true, message: "请输入字典类型编码", trigger: "blur" }],
});

/** 查询 */
function handleQuery() {
  loading.value = true;
  DictAPI.getDictTypePage(queryParams)
    .then((data) => {
      dictTypeList.value = data.list;
      total.value = data.total;
    })
    .finally(() => {
      loading.value = false;
    });
}

/**
 * 重置查询
 */
function resetQuery() {
  queryFormRef.value.resetFields();
  queryParams.pageNum = 1;
  handleQuery();
}

/** 行复选框选中  */
function handleSelectionChange(selection: any) {
  ids.value = selection.map((item: any) => item.id);
}

/**
 * 打开字典类型表单弹窗
 *
 * @param dicTypeId 字典类型ID
 */
function openDialog(dicTypeId?: number) {
  dialog.visible = true;
  if (dicTypeId) {
    dialog.title = "修改字典类型";
    DictAPI.getDictTypeForm(dicTypeId).then((data) => {
      Object.assign(formData, data);
    });
  } else {
    dialog.title = "新增字典类型";
  }
}

/** 字典类型表单提交 */
function handleSubmit() {
  dataFormRef.value.validate((isValid: boolean) => {
    if (isValid) {
      loading.value = false;
      const dictTypeId = formData.id;
      if (dictTypeId) {
        DictAPI.updateDictType(dictTypeId, formData)
          .then(() => {
            ElMessage.success("修改成功");
            closeDialog();
            handleQuery();
          })
          .finally(() => (loading.value = false));
      } else {
        DictAPI.addDictType(formData)
          .then(() => {
            ElMessage.success("新增成功");
            closeDialog();
            handleQuery();
          })
          .finally(() => (loading.value = false));
      }
    }
  });
}

/** 关闭字典类型弹窗 */
function closeDialog() {
  dialog.visible = false;
  resetForm();
}

/**  重置字典类型表单 */
function resetForm() {
  dataFormRef.value.resetFields();
  dataFormRef.value.clearValidate();

  formData.id = undefined;
  formData.status = 1;
}

/** 删除字典类型 */
function handleDelete(row?: any) {
  const dictTypeIds = (row ? [row.id] : ids.value).join(",");
  if (!dictTypeIds) {
    ElMessage.warning("请勾选删除项");
    return;
  }

  const forceDelete = ref(false);
  const confirmMsg = row
    ? `确认删除字典类型「${row.name}」吗？删除后不可恢复。`
    : "确认删除选中的字典类型吗？删除后不可恢复。";
  ElMessageBox.confirm(
    () =>
      h("div", null, [
        h("p", { style: "margin: 0 0 12px" }, confirmMsg),
        h(
          ElCheckbox,
          {
            modelValue: forceDelete.value,
            "onUpdate:modelValue": (val: boolean) => {
              forceDelete.value = val;
            },
          },
          { default: () => "同时删除关联的字典数据" }
        ),
      ]),
    "警告",
    {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    }
  ).then(() => {
    DictAPI.deleteDictTypes(dictTypeIds, forceDelete.value).then(() => {
      ElMessage.success("删除成功");
      resetQuery();
    });
  });
}

const dictDataDialog = reactive({
  title: "",
  visible: false,
});

const selectedDictType = reactive({ typeCode: "", typeName: "" }); // 当前选中的字典类型

/** 打开字典数据弹窗 */
function openDictDialog(row: DictTypePageVO) {
  dictDataDialog.visible = true;
  dictDataDialog.title = "【" + row.name + "】字典数据";

  selectedDictType.typeCode = row.code;
  selectedDictType.typeName = row.name;
}

/**  关闭字典数据弹窗 */
function closeDictDialog() {
  dictDataDialog.visible = false;
}

onMounted(() => {
  handleQuery();
});
</script>

// dehaze-front-react/src/pages/system/dict/index.tsx
import {
  DictAPI,
  type DictTypePageVO,
  type DictTypeQuery,
} from "dehaze-sdk-js";
import ImportExportToolbar from "@/components/ImportExportToolbar";
import {
  Button,
  Card,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Space,
  Table,
  Tag,
  type TableColumnsType,
} from "antd";
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UnorderedListOutlined,
} from "@ant-design/icons";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import DictItemDialog, {
  type DictItemDialogRef,
} from "./components/DictItemDialog";
import DictTypeFormDialog, {
  type DictTypeFormDialogRef,
} from "./components/DictTypeFormDialog";
import "./index.scss";

const STATUS_MAP: Record<number, { label: string; color: string }> = {
  1: { label: "启用", color: "green" },
  0: { label: "禁用", color: "default" },
};

const DictManagement: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<DictTypePageVO[]>([]);
  const [total, setTotal] = useState(0);
  const [searchForm] = Form.useForm();
  const [query, setQuery] = useState<DictTypeQuery>({
    pageNum: 1,
    pageSize: 10,
  });

  const typeDialogRef = useRef<DictTypeFormDialogRef>(null);
  const itemDialogRef = useRef<DictItemDialogRef>(null);
  const [refreshFlag, setRefreshFlag] = useState(0);
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);

  const loadData = useCallback(async (params: DictTypeQuery) => {
    setLoading(true);
    try {
      const result = await DictAPI.getDictTypePage(params);
      setData(result.list || []);
      setTotal(result.total || 0);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData(query);
  }, [query, refreshFlag]);

  const refreshList = useCallback(() => {
    setRefreshFlag((prev) => prev + 1);
    setSelectedRowKeys([]);
  }, []);

  const handleSearch = useCallback((values: { keywords?: string }) => {
    setSelectedRowKeys([]);
    setQuery((prev) => ({
      ...prev,
      pageNum: 1,
      keywords: values.keywords || undefined,
    }));
  }, []);

  const handleReset = useCallback(() => {
    searchForm.resetFields();
    setSelectedRowKeys([]);
    setQuery({ pageNum: 1, pageSize: 10 });
  }, [searchForm]);
  const handleAdd = useCallback(() => typeDialogRef.current?.open("add"), []);
  const handleEdit = useCallback(
    (record: DictTypePageVO) => typeDialogRef.current?.open("edit", record),
    []
  );
  const handleDelete = useCallback(
    (record: DictTypePageVO) => {
      DictAPI.deleteDictTypes(String(record.id))
        .then(() => {
          message.success("删除成功");
          refreshList();
        })
        .catch((e) => message.error(e?.message || "删除失败"));
    },
    [refreshList]
  );
  // 批量删除字典类型
  const handleBatchDelete = useCallback(() => {
    Modal.confirm({
      title: "批量删除",
      content: `确认删除选中的 ${selectedRowKeys.length} 个字典类型吗？删除后不可恢复。`,
      okText: "确定",
      cancelText: "取消",
      okType: "danger",
      onOk: () =>
        DictAPI.deleteDictTypes(selectedRowKeys.join(","))
          .then(() => {
            message.success(`成功删除 ${selectedRowKeys.length} 个字典类型`);
            refreshList();
          })
          .catch((e) => {
            message.error(e?.message || "删除失败");
            return Promise.reject(e);
          }),
    });
  }, [selectedRowKeys, refreshList]);
  const handleManageItems = useCallback(
    (record: DictTypePageVO) =>
      itemDialogRef.current?.open(record.code, record.name),
    []
  );

  const columns: TableColumnsType<DictTypePageVO> = useMemo(
    () => [
      { title: "类型名称", dataIndex: "name", key: "name", width: 200 },
      { title: "类型编码", dataIndex: "code", key: "code", width: 150 },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
        width: 80,
        align: "center",
        render: (s: number) => (
          <Tag color={STATUS_MAP[s]?.color}>{STATUS_MAP[s]?.label}</Tag>
        ),
      },
      {
        title: "备注",
        dataIndex: "remark",
        key: "remark",
        width: 200,
        render: (t: string) => t || "-",
      },
      {
        title: "创建时间",
        dataIndex: "createTime" as any,
        key: "createTime",
        width: 180,
        align: "center",
      },
      {
        title: "操作",
        key: "action",
        width: 220,
        align: "center",
        fixed: "right",
        render: (_: unknown, record: DictTypePageVO) => (
          <Space size="small">
            <Button
              type="link"
              size="small"
              icon={<UnorderedListOutlined />}
              onClick={() => handleManageItems(record)}
            >
              管理
            </Button>
            <Button
              type="link"
              size="small"
              icon={<EditOutlined />}
              onClick={() => handleEdit(record)}
            >
              编辑
            </Button>
            <Popconfirm
              title={`确认删除字典类型「${record.name}」吗？删除后不可恢复。`}
              onConfirm={() => handleDelete(record)}
              okText="确定"
              cancelText="取消"
              okType="danger"
            >
              <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                删除
              </Button>
            </Popconfirm>
          </Space>
        ),
      },
    ],
    [handleManageItems, handleEdit, handleDelete]
  );

  // 行选择配置
  const rowSelection = useMemo(
    () => ({
      selectedRowKeys,
      onChange: (keys: React.Key[]) => setSelectedRowKeys(keys),
    }),
    [selectedRowKeys]
  );

  return (
    <div className="dict-management-container">
      <Card className="search-card" size="small">
        <Form form={searchForm} layout="inline" onFinish={handleSearch}>
          <Form.Item name="keywords" label="关键字">
            <Input
              placeholder="类型名称/编码"
              allowClear
              style={{ width: 200 }}
            />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                htmlType="submit"
                icon={<SearchOutlined />}
              >
                搜索
              </Button>
              <Button
                htmlType="reset"
                icon={<ReloadOutlined />}
                onClick={handleReset}
              >
                重置
              </Button>
              <Button
                type="primary"
                icon={<PlusOutlined />}
                onClick={handleAdd}
              >
                新增
              </Button>
              <Button
                danger
                icon={<DeleteOutlined />}
                disabled={selectedRowKeys.length === 0}
                onClick={handleBatchDelete}
              >
                删除
              </Button>
              <ImportExportToolbar
                module="dict"
                queryParams={query}
                onImportComplete={refreshList}
              />
            </Space>
          </Form.Item>
        </Form>
      </Card>
      <Card className="table-card" size="small">
        <Table
          columns={columns}
          dataSource={data}
          rowKey={(r) => r.id}
          loading={loading}
          scroll={{ x: 1000 }}
          rowSelection={rowSelection}
          pagination={{
            current: query.pageNum,
            pageSize: query.pageSize,
            total,
            showSizeChanger: true,
            showQuickJumper: true,
            pageSizeOptions: ["10", "20", "50", "100"],
            showTotal: (t) => `共 ${t} 条`,
            onChange: (p, ps) =>
              setQuery((prev) => ({ ...prev, pageNum: p, pageSize: ps })),
          }}
        />
      </Card>
      <DictTypeFormDialog ref={typeDialogRef} onSuccess={refreshList} />
      <DictItemDialog ref={itemDialogRef} />
    </div>
  );
};

export default DictManagement;
