// dehaze-uniapp/src/pages/personal/feedback/index.vue
<template>
  <PageLayout level="L2" title="反馈评价" class="page">
    <view class="main-content">
      <!-- Tab 切换 -->
      <view class="tabs">
        <view
          :class="['tab', { active: activeTab === 'feedback' }]"
          @click="activeTab = 'feedback'"
        >
          <text>我的反馈</text>
        </view>
        <view
          :class="['tab', { active: activeTab === 'rating' }]"
          @click="activeTab = 'rating'"
        >
          <text>我的评价</text>
        </view>
      </view>

      <!-- 反馈列表 -->
      <view v-if="activeTab === 'feedback'">
        <view v-if="loading" class="loading-container">
          <up-loading-icon mode="circle" size="40" color="#ec4899" />
          <text class="loading-text">加载中...</text>
        </view>

        <view v-else-if="feedbacks.length > 0" class="list">
          <view v-for="fb in feedbacks" :key="fb.id" class="card">
            <view class="card-header">
              <text class="card-title">{{ fb.title }}</text>
              <text :class="['fb-status', statusClass(fb.status)]">{{
                statusText(fb.status)
              }}</text>
            </view>
            <text class="card-content">{{ fb.content }}</text>
            <text class="card-time">{{
              formatRelativeTime(fb.createTime)
            }}</text>
          </view>
          <view v-if="!hasMoreFb" class="end-text">— 没有更多了 —</view>
          <view v-else class="load-more" @click="loadMoreFeedback"
            >加载更多</view
          >
        </view>

        <view v-else class="empty-state">
          <up-empty mode="list" text="暂无反馈" />
        </view>

        <view class="submit-btn" @click="showForm = true">
          <SvgIcon name="plus" size="20" color="#fff" />
          <text>提交反馈</text>
        </view>
      </view>

      <!-- 评价列表 -->
      <view v-else>
        <view v-if="loading" class="loading-container">
          <up-loading-icon mode="circle" size="40" color="#ec4899" />
          <text class="loading-text">加载中...</text>
        </view>

        <view v-else-if="ratings.length > 0" class="list">
          <view v-for="r in ratings" :key="r.id" class="card">
            <view class="card-header">
              <text class="card-title">{{ r.algorithmName }}</text>
              <view class="stars">
                <text v-for="i in 5" :key="i" :class="{ active: i <= r.rating }"
                  >★</text
                >
              </view>
            </view>
            <text v-if="r.comment" class="card-content">{{ r.comment }}</text>
            <view v-if="r.adminReply" class="admin-reply">
              <text>管理员回复: {{ r.adminReply }}</text>
            </view>
            <text class="card-time">{{
              formatRelativeTime(r.createTime)
            }}</text>
          </view>
          <view v-if="!hasMoreR" class="end-text">— 没有更多了 —</view>
          <view v-else class="load-more" @click="loadMoreRatings"
            >加载更多</view
          >
        </view>

        <view v-else class="empty-state">
          <up-empty mode="list" text="暂无评价" />
        </view>
      </view>

      <!-- 提交反馈弹窗 -->
      <u-popup
        :show="showForm"
        mode="bottom"
        round="24"
        @close="showForm = false"
      >
        <view class="form-container">
          <text class="form-title">提交反馈</text>
          <view class="type-selector">
            <view
              v-for="t in feedbackTypes"
              :key="t.value"
              :class="['type-option', { active: form.feedbackType === t.value }]"
              @click="form.feedbackType = t.value"
            >
              {{ t.label }}
            </view>
          </view>
          <u-input
            v-model="form.title"
            placeholder="标题"
            border="surround"
            class="form-item"
          />
          <u-input
            v-model="form.content"
            placeholder="内容"
            type="textarea"
            border="surround"
            class="form-item"
            :rows="4"
          />
          <u-input
            v-model="form.contact"
            placeholder="联系方式（选填）"
            border="surround"
            class="form-item"
          />
          <view class="form-footer">
            <u-button text="取消" @click="showForm = false" />
            <u-button
              text="提交"
              type="primary"
              @click="submitFeedback"
              :loading="submitting"
            />
          </view>
        </view>
      </u-popup>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, onMounted, watch } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import PageLayout from "@/layout/index.vue";
import { FeedbackAPI } from "dehaze-sdk-js";
import type { FeedbackPageVO, FeedbackStatus, MyRatingVO, FeedbackType } from "dehaze-sdk-js";
import { formatRelativeTime } from "@/utils/format";

const activeTab = ref("feedback");
const loading = ref(false);
const showForm = ref(false);
const submitting = ref(false);

// 反馈
const feedbacks = ref<FeedbackPageVO[]>([]);
const fbPage = ref(1);
const hasMoreFb = ref(true);

// 评价
const ratings = ref<MyRatingVO[]>([]);
const rPage = ref(1);
const hasMoreR = ref(true);

const feedbackTypes: { value: FeedbackType; label: string }[] = [
  { value: "suggestion", label: "建议" },
  { value: "bug", label: "缺陷" },
  { value: "experience", label: "体验" },
  { value: "complaint", label: "投诉" },
];

// 表单
const form = ref({
  feedbackType: "suggestion" as FeedbackType,
  title: "",
  content: "",
  contact: "",
});

function statusText(status: FeedbackStatus): string {
  const map: Record<string, string> = {
    pending: "待处理",
    processing: "处理中",
    replied: "已回复",
    closed: "已关闭",
  };
  return map[status] || status;
}

function statusClass(status: FeedbackStatus): string {
  const map: Record<string, string> = {
    pending: "s-pending",
    processing: "s-processing",
    replied: "s-replied",
    closed: "s-closed",
  };
  return map[status] || "";
}

async function loadFeedbacks(page = 1) {
  if (loading.value) return;
  loading.value = true;
  try {
    const result = await FeedbackAPI.listMyFeedback({
      pageNum: page,
      pageSize: 20,
    });
    if (page === 1) feedbacks.value = result.list;
    else feedbacks.value = [...feedbacks.value, ...result.list];
    hasMoreFb.value = feedbacks.value.length < result.total;
    fbPage.value = page;
  } catch {
    uni.showToast({ title: "加载失败", icon: "none" });
  } finally {
    loading.value = false;
  }
}

async function loadRatings(page = 1) {
  if (loading.value) return;
  loading.value = true;
  try {
    const result = await FeedbackAPI.listMyRatings({
      pageNum: page,
      pageSize: 20,
    });
    if (page === 1) ratings.value = result.list;
    else ratings.value = [...ratings.value, ...result.list];
    hasMoreR.value = ratings.value.length < result.total;
    rPage.value = page;
  } catch {
    uni.showToast({ title: "加载失败", icon: "none" });
  } finally {
    loading.value = false;
  }
}

function loadMoreFeedback() {
  if (hasMoreFb.value) loadFeedbacks(fbPage.value + 1);
}

function loadMoreRatings() {
  if (hasMoreR.value) loadRatings(rPage.value + 1);
}

async function submitFeedback() {
  if (!form.value.title || !form.value.content) {
    uni.showToast({ title: "请填写标题和内容", icon: "none" });
    return;
  }
  submitting.value = true;
  try {
    await FeedbackAPI.createFeedback({
      feedbackType: form.value.feedbackType,
      title: form.value.title,
      content: form.value.content,
      contact: form.value.contact || undefined,
    });
    uni.showToast({ title: "提交成功", icon: "success" });
    showForm.value = false;
    form.value = { feedbackType: "suggestion", title: "", content: "", contact: "" };
    loadFeedbacks(1);
  } catch {
    uni.showToast({ title: "提交失败", icon: "none" });
  } finally {
    submitting.value = false;
  }
}

watch(activeTab, (tab) => {
  if (tab === "feedback") loadFeedbacks(1);
  else loadRatings(1);
});

onMounted(() => loadFeedbacks(1));
</script>

<style lang="scss" scoped>
.page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}
.main-content {
  padding: $spacing-md;
  padding-bottom: calc(120rpx + constant(safe-area-inset-bottom));
}

.tabs {
  display: flex;
  background: #fff;
  border-radius: $radius-lg;
  margin-bottom: $spacing-md;
  overflow: hidden;
}
.tab {
  flex: 1;
  text-align: center;
  padding: 24rpx;
  font-size: $font-md;
  color: $color-text-secondary;
  &.active {
    color: $color-primary;
    font-weight: 600;
    background: $color-primary-bg;
  }
}

.list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.card {
  background: #fff;
  border-radius: $radius-lg;
  padding: 24rpx;
  box-shadow: $shadow-sm;
}
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.card-title {
  font-size: $font-md;
  font-weight: 600;
  color: $color-text-primary;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.card-content {
  font-size: $font-sm;
  color: $color-text-secondary;
  display: block;
  margin-bottom: 12rpx;
  line-height: 1.6;
}
.card-time {
  font-size: $font-xs;
  color: $color-text-placeholder;
}

.fb-status {
  font-size: $font-xs;
  font-weight: 500;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
  flex-shrink: 0;
}
.s-pending {
  color: #f59e0b;
  background: #fef3c7;
}
.s-processing {
  color: #3b82f6;
  background: #dbeafe;
}
.s-replied {
  color: #10b981;
  background: #ecfdf5;
}
.s-closed {
  color: #9ca3af;
  background: #f3f4f6;
}

.stars {
  font-size: $font-md;
  color: #d1d5db;
}
.stars .active {
  color: #f59e0b;
}

.end-text {
  text-align: center;
  font-size: $font-sm;
  color: $color-text-disabled;
  padding: 32rpx 0;
}
.load-more {
  text-align: center;
  font-size: $font-sm;
  color: $color-secondary;
  padding: 24rpx 0;
}
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 120rpx 0;
}
.loading-text {
  margin-top: 24rpx;
  font-size: $font-md;
  color: $color-text-placeholder;
}
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 80rpx 0;
}

.submit-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8rpx;
  background: $color-primary;
  color: #fff;
  font-size: $font-md;
  padding: 24rpx;
  border-radius: $radius-lg;
  margin-top: 32rpx;
  &:active {
    opacity: 0.8;
  }
}

.form-container {
  padding: 32rpx;
}
.form-title {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
  display: block;
  margin-bottom: 24rpx;
}
.type-selector {
  display: flex;
  gap: 16rpx;
  margin-bottom: 24rpx;
}
.type-option {
  padding: 12rpx 24rpx;
  font-size: $font-sm;
  color: $color-text-secondary;
  background: $color-bg-primary;
  border-radius: $radius-md;
  &.active {
    color: #fff;
    background: $color-primary;
  }
}
.form-item {
  margin-bottom: 16rpx;
}
.form-footer {
  display: flex;
  gap: 16rpx;
  margin-top: 24rpx;
}

.admin-reply {
  margin-top: 12rpx;
  padding: 12rpx 16rpx;
  background: #eff6ff;
  border-radius: 8rpx;
  font-size: $font-sm;
  color: #3b82f6;
}
</style>

// dehaze-taro/src/pages/personal/feedback/index.tsx
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Button, Tag, Popup, Textarea, Input, Tabs } from "@taroify/core";
import { Plus } from "@taroify/icons";
import { FeedbackAPI } from "dehaze-sdk-js";
import type {
  FeedbackPageVO,
  FeedbackDetailVO,
  MyRatingVO,
  FeedbackType,
  FeedbackStatus,
} from "dehaze-sdk-js";
import PageLayout from "@/layout";
import EmptyState from "@/components/common/EmptyState";
import "./index.less";

const STATUS_CONFIG: Record<FeedbackStatus, { label: string; color: string }> = {
  pending: { label: "待处理", color: "#f59e0b" },
  processing: { label: "处理中", color: "#3b82f6" },
  replied: { label: "已回复", color: "#10b981" },
  closed: { label: "已关闭", color: "#6b7280" },
};

const TYPE_CONFIG: Record<FeedbackType, { label: string }> = {
  suggestion: { label: "建议" },
  bug: { label: "缺陷" },
  experience: { label: "体验" },
  complaint: { label: "投诉" },
};

const FEEDBACK_TYPES: { value: FeedbackType; label: string }[] = [
  { value: "suggestion", label: "建议" },
  { value: "bug", label: "缺陷" },
  { value: "experience", label: "体验" },
  { value: "complaint", label: "投诉" },
];

const FeedbackPage: React.FC = () => {
  const [tab, setTab] = useState(0);

  // 反馈
  const [feedbackList, setFeedbackList] = useState<FeedbackPageVO[]>([]);
  const [loading, setLoading] = useState(false);
  const [submitVisible, setSubmitVisible] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [formType, setFormType] = useState<FeedbackType>("suggestion");
  const [formTitle, setFormTitle] = useState("");
  const [formContent, setFormContent] = useState("");
  const [formContact, setFormContact] = useState("");

  // 反馈详情
  const [detailVisible, setDetailVisible] = useState(false);
  const [feedbackDetail, setFeedbackDetail] =
    useState<FeedbackDetailVO | null>(null);
  const [supplementVisible, setSupplementVisible] = useState(false);
  const [supplementContent, setSupplementContent] = useState("");
  const [supplementing, setSupplementing] = useState(false);

  // 评价
  const [ratings, setRatings] = useState<MyRatingVO[]>([]);
  const [ratingLoading, setRatingLoading] = useState(false);

  const loadFeedback = useCallback(async () => {
    setLoading(true);
    try {
      const res = await FeedbackAPI.listMyFeedback({
        pageNum: 1,
        pageSize: 20,
      });
      setFeedbackList((res.list as FeedbackPageVO[]) || []);
    } catch {
      Taro.showToast({ title: "加载失败", icon: "none" });
    } finally {
      setLoading(false);
    }
  }, []);

  const loadRatings = useCallback(async () => {
    setRatingLoading(true);
    try {
      const res = await FeedbackAPI.listMyRatings({
        pageNum: 1,
        pageSize: 20,
      });
      setRatings((res.list as MyRatingVO[]) || []);
    } catch {
      Taro.showToast({ title: "加载评价失败", icon: "none" });
    } finally {
      setRatingLoading(false);
    }
  }, []);

  useEffect(() => {
    loadFeedback();
    loadRatings();
  }, [loadFeedback, loadRatings]);

  const handleSubmit = async () => {
    if (!formTitle.trim()) {
      Taro.showToast({ title: "请输入标题", icon: "none" });
      return;
    }
    if (!formContent.trim()) {
      Taro.showToast({ title: "请输入反馈内容", icon: "none" });
      return;
    }
    setSubmitting(true);
    try {
      await FeedbackAPI.createFeedback({
        feedbackType: formType,
        title: formTitle.trim(),
        content: formContent.trim(),
        contact: formContact.trim() || undefined,
      });
      setSubmitVisible(false);
      setFormTitle("");
      setFormContent("");
      setFormContact("");
      Taro.showToast({ title: "提交成功", icon: "success" });
      loadFeedback();
    } catch {
      Taro.showToast({ title: "提交失败", icon: "none" });
    } finally {
      setSubmitting(false);
    }
  };

  const handleViewDetail = async (id: number) => {
    try {
      const detail = await FeedbackAPI.getFeedbackDetail(id);
      setFeedbackDetail(detail);
      setDetailVisible(true);
    } catch {
      Taro.showToast({ title: "获取详情失败", icon: "none" });
    }
  };

  const handleSupplement = async () => {
    if (!supplementContent.trim() || !feedbackDetail) return;
    setSupplementing(true);
    try {
      await FeedbackAPI.supplementFeedback(feedbackDetail.id, {
        content: supplementContent.trim(),
      });
      Taro.showToast({ title: "补充成功", icon: "success" });
      setSupplementVisible(false);
      setSupplementContent("");
      const detail = await FeedbackAPI.getFeedbackDetail(feedbackDetail.id);
      setFeedbackDetail(detail);
    } catch {
      Taro.showToast({ title: "补充失败", icon: "none" });
    } finally {
      setSupplementing(false);
    }
  };

  return (
    <PageLayout level="L2" title="反馈评价">
      <View className="personal-feedback-page">
        <Tabs value={tab} onChange={setTab}>
          <Tabs.TabPane title="我的反馈" />
          <Tabs.TabPane title="我的评价" />
        </Tabs>

        {tab === 0 && (
          <>
            <View className="feedback-toolbar">
              <View
                className="submit-btn"
                onClick={() => setSubmitVisible(true)}
              >
                <Plus size="16" color="#fff" />
                <Text className="submit-text">提交反馈</Text>
              </View>
            </View>

            <ScrollView
              scrollY
              className="feedback-list"
              enhanced
              showScrollbar={false}
            >
              {loading && feedbackList.length === 0 ? (
                <View className="loading-wrapper">
                  <Text>加载中...</Text>
                </View>
              ) : feedbackList.length === 0 ? (
                <View className="empty-wrapper">
                  <EmptyState
                    type="search"
                    title="暂无反馈"
                    description="您的反馈对我们很重要"
                  />
                </View>
              ) : (
                feedbackList.map((item) => {
                  const typeCfg =
                    TYPE_CONFIG[item.feedbackType as FeedbackType] ||
                    TYPE_CONFIG.suggestion;
                  const status = item.status as FeedbackStatus;
                  const statusCfg =
                    STATUS_CONFIG[status] || STATUS_CONFIG.pending;
                  return (
                    <View
                      key={item.id}
                      className="feedback-card"
                      onClick={() => handleViewDetail(item.id)}
                    >
                      <View className="feedback-top">
                        <View className="feedback-title-row">
                          <Text className="feedback-title">{item.title}</Text>
                          <Tag color={statusCfg.color as any} size="small">
                            {statusCfg.label}
                          </Tag>
                        </View>
                      </View>
                      <Text className="feedback-content" numberOfLines={2}>
                        {item.content}
                      </Text>
                      <View className="feedback-bottom">
                        <Tag size="small" color="default">
                          {typeCfg.label}
                        </Tag>
                        <Text className="feedback-time">
                          {new Date(item.createTime).toLocaleString()}
                        </Text>
                      </View>
                    </View>
                  );
                })
              )}
            </ScrollView>
          </>
        )}

        {tab === 1 && (
          <ScrollView
            scrollY
            className="feedback-list"
            enhanced
            showScrollbar={false}
          >
            {ratingLoading && ratings.length === 0 ? (
              <View className="loading-wrapper">
                <Text>加载中...</Text>
              </View>
            ) : ratings.length === 0 ? (
              <View className="empty-wrapper">
                <EmptyState
                  type="search"
                  title="暂无评价"
                  description="去雾处理后可以评价效果哦"
                />
              </View>
            ) : (
              ratings.map((r) => (
                <View key={r.id} className="feedback-card">
                  <View className="feedback-top">
                    <View className="feedback-title-row">
                      <Text className="feedback-title">
                        {r.algorithmName}
                      </Text>
                      <Tag color="warning" size="small">
                        {"★".repeat(r.rating)}
                      </Tag>
                    </View>
                  </View>
                  {r.comment && (
                    <Text className="feedback-content">{r.comment}</Text>
                  )}
                  {r.adminReply && (
                    <View className="admin-reply">
                      <Text className="reply-label">管理员回复: </Text>
                      <Text>{r.adminReply}</Text>
                    </View>
                  )}
                  <View className="feedback-bottom">
                    <Text className="feedback-time">
                      {new Date(r.createTime).toLocaleString()}
                    </Text>
                  </View>
                </View>
              ))
            )}
          </ScrollView>
        )}

        {/* 提交弹窗 */}
        <Popup
          open={submitVisible}
          placement="bottom"
          rounded
          onClose={() => setSubmitVisible(false)}
        >
          <View className="submit-popup">
            <View className="popup-header">
              <Text className="popup-title">提交反馈</Text>
              <View
                className="popup-close"
                onClick={() => setSubmitVisible(false)}
              >
                ×
              </View>
            </View>
            <View className="type-selector">
              {FEEDBACK_TYPES.map((t) => (
                <View
                  key={t.value}
                  className={`type-option ${formType === t.value ? "active" : ""}`}
                  onClick={() => setFormType(t.value)}
                >
                  <Text className="option-label">{t.label}</Text>
                </View>
              ))}
            </View>
            <Input
              className="form-input-field"
              placeholder="标题（必填）"
              value={formTitle}
              onInput={(e) => setFormTitle(e.detail?.value || "")}
              maxlength={100}
            />
            <Textarea
              className="content-textarea"
              placeholder="请描述您遇到的问题或建议..."
              value={formContent}
              onChange={(e) => setFormContent(e.detail?.value || "")}
              maxlength={2000}
            />
            <Input
              className="form-input-field"
              placeholder="联系方式（选填，如邮箱/手机号）"
              value={formContact}
              onInput={(e) => setFormContact(e.detail?.value || "")}
              maxlength={100}
            />
            <Button
              variant="contained"
              block
              loading={submitting}
              onClick={handleSubmit}
              className="submit-action-btn"
            >
              <Text className="submit-btn-text">提交反馈</Text>
            </Button>
          </View>
        </Popup>

        {/* 反馈详情弹窗 */}
        <Popup
          open={detailVisible}
          placement="bottom"
          rounded
          onClose={() => {
            setDetailVisible(false);
            setFeedbackDetail(null);
          }}
        >
          <View className="submit-popup">
            {feedbackDetail && (
              <>
                <View className="popup-header">
                  <Text className="popup-title">反馈详情</Text>
                  <View
                    className="popup-close"
                    onClick={() => {
                      setDetailVisible(false);
                      setFeedbackDetail(null);
                    }}
                  >
                    ×
                  </View>
                </View>
                <View className="detail-section">
                  <View className="detail-row">
                    <Text className="detail-label">类型</Text>
                    <Tag size="small" color="default">
                      {TYPE_CONFIG[
                        feedbackDetail.feedbackType as FeedbackType
                      ]?.label || feedbackDetail.feedbackType}
                    </Tag>
                  </View>
                  <View className="detail-row">
                    <Text className="detail-label">状态</Text>
                    <Tag
                      size="small"
                      color={
                        STATUS_CONFIG[
                          feedbackDetail.status as FeedbackStatus
                        ]?.color as any
                      }
                    >
                      {STATUS_CONFIG[feedbackDetail.status as FeedbackStatus]
                        ?.label || feedbackDetail.status}
                    </Tag>
                  </View>
                  <View className="detail-row">
                    <Text className="detail-label">标题</Text>
                    <Text className="detail-value">
                      {feedbackDetail.title}
                    </Text>
                  </View>
                  <View className="detail-row">
                    <Text className="detail-label">内容</Text>
                    <Text className="detail-value">
                      {feedbackDetail.content}
                    </Text>
                  </View>
                  {feedbackDetail.contact && (
                    <View className="detail-row">
                      <Text className="detail-label">联系方式</Text>
                      <Text className="detail-value">
                        {feedbackDetail.contact}
                      </Text>
                    </View>
                  )}
                  <View className="detail-row">
                    <Text className="detail-label">时间</Text>
                    <Text className="detail-value">
                      {new Date(
                        feedbackDetail.createTime
                      ).toLocaleString()}
                    </Text>
                  </View>
                </View>

                {feedbackDetail.replies &&
                  feedbackDetail.replies.length > 0 && (
                    <View className="replies-section">
                      <Text className="section-title">回复记录</Text>
                      {feedbackDetail.replies.map((reply) => (
                        <View key={reply.id} className="reply-item">
                          <View className="reply-header">
                            <Text className="reply-author">
                              {reply.replierName}
                            </Text>
                            <Text className="reply-time">
                              {new Date(
                                reply.createTime
                              ).toLocaleString()}
                            </Text>
                          </View>
                          <Text className="reply-content">
                            {reply.content}
                          </Text>
                        </View>
                      ))}
                    </View>
                  )}

                {feedbackDetail.status !== "closed" && (
                  <View className="detail-actions">
                    <Button
                      variant="outlined"
                      onClick={() => setSupplementVisible(true)}
                    >
                      补充说明
                    </Button>
                  </View>
                )}
              </>
            )}
          </View>
        </Popup>

        {/* 补充说明弹窗 */}
        <Popup
          open={supplementVisible}
          placement="bottom"
          rounded
          onClose={() => setSupplementVisible(false)}
        >
          <View className="submit-popup">
            <View className="popup-header">
              <Text className="popup-title">补充说明</Text>
              <View
                className="popup-close"
                onClick={() => setSupplementVisible(false)}
              >
                ×
              </View>
            </View>
            <Textarea
              className="content-textarea"
              placeholder="请输入补充内容..."
              value={supplementContent}
              onChange={(e) =>
                setSupplementContent(e.detail?.value || "")
              }
              maxlength={2000}
            />
            <Button
              variant="contained"
              block
              loading={supplementing}
              onClick={handleSupplement}
              className="submit-action-btn"
            >
              提交补充
            </Button>
          </View>
        </Popup>
      </View>
    </PageLayout>
  );
};

export default FeedbackPage;
