// dehaze-uniapp/src/pages/magnifier/index.vue
<template>
  <ImmersiveLayout title="放大镜对比">
    <view v-if="hasImages" class="main-content">
      <view
        class="magnifier-wrapper"
        @touchstart="handleTouchStart"
        @touchmove="handleTouchMove"
        @touchend="handleTouchEnd"
      >
        <image :src="resultUrl" class="base-image" mode="widthFix" lazy-load />

        <!-- 原图放大镜（双窗口模式左） -->
        <view
          v-if="showOriginLens"
          class="lens lens-origin"
          :style="lensStyle(originUrl, 'left')"
        >
          <view class="lens-image" :style="lensImageStyle(originUrl)" />
        </view>

        <!-- 处理后放大镜（双窗口模式右） -->
        <view
          v-if="showResultLens"
          class="lens lens-result"
          :style="lensStyle(resultUrl, 'right')"
        >
          <view class="lens-image" :style="lensImageStyle(resultUrl)" />
        </view>

        <!-- 放大倍数标签 -->
        <view class="zoom-badge">{{ zoom }}x</view>
      </view>

      <!-- 提示 -->
      <view class="magnifier-hint">
        <text>拖动移动放大镜 · 双指捏合调整倍数 · 点击切换模式</text>
      </view>

      <!-- 控制面板 -->
      <view class="control-panel">
        <!-- 显示模式 -->
        <view class="control-group">
          <text class="control-label">显示模式</text>
          <view class="control-options">
            <view
              v-for="opt in displayModes"
              :key="opt.value"
              class="control-option"
              :class="{ active: displayMode === opt.value }"
              @click="displayMode = opt.value"
            >
              <text>{{ opt.label }}</text>
            </view>
          </view>
        </view>

        <!-- 放大倍数 -->
        <view class="control-group">
          <text class="control-label">放大倍数</text>
          <view class="control-options">
            <view
              v-for="z in zoomOptions"
              :key="z"
              class="control-option"
              :class="{ active: zoom === z }"
              @click="zoom = z"
            >
              <text>{{ z }}x</text>
            </view>
          </view>
        </view>

        <!-- 放大镜大小 -->
        <view class="control-group">
          <text class="control-label">放大镜大小</text>
          <view class="control-options">
            <view
              v-for="sz in sizeOptions"
              :key="sz.value"
              class="control-option"
              :class="{ active: lensSize === sz.value }"
              @click="lensSize = sz.value"
            >
              <text>{{ sz.label }}</text>
            </view>
          </view>
        </view>

        <!-- 边框样式 -->
        <view class="control-group">
          <text class="control-label">边框样式</text>
          <view class="control-options">
            <view
              v-for="bs in borderStyles"
              :key="bs.value"
              class="control-option"
              :class="{ active: borderStyle === bs.value }"
              @click="borderStyle = bs.value"
            >
              <text>{{ bs.label }}</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <CompareEmptyState v-else text="暂无对比数据" btn-color="#f59e0b" />

    <template #toolbar>
      <view class="toolbar-grid">
        <view
          v-for="m in modes"
          :key="m.key"
          class="toolbar-item"
          :class="{ active: m.key === 'magnifier' }"
          @click="switchPage(m.path)"
        >
          <SvgIcon :name="m.icon" size="20" color="#f59e0b" />
          <text>{{ m.label }}</text>
        </view>
      </view>
      <view class="toolbar-actions">
        <view class="action-item" @click="handleSave">
          <SvgIcon name="download" size="18" color="rgba(255,255,255,0.7)" />
          <text>保存</text>
        </view>
        <view class="action-item" @click="handleReprocess">
          <SvgIcon name="refresh" size="18" color="rgba(255,255,255,0.7)" />
          <text>重新处理</text>
        </view>
        <view class="action-item" @click="handleChangeAlgorithm">
          <SvgIcon name="swap" size="18" color="rgba(255,255,255,0.7)" />
          <text>换算法</text>
        </view>
        <view class="action-item" @click="handleFavorite">
          <SvgIcon
            :name="favorited ? 'star-fill' : 'star'"
            size="18"
            :color="favorited ? '#f59e0b' : 'rgba(255,255,255,0.7)'"
          />
          <text :style="{ color: favorited ? '#f59e0b' : '' }">{{
            favorited ? "已收藏" : "收藏"
          }}</text>
        </view>
      </view>
    </template>
  </ImmersiveLayout>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import ImmersiveLayout from "@/layout/ImmersiveLayout.vue";
import CompareEmptyState from "@/components/common/CompareEmptyState.vue";
import { useProcessingStore } from "@/store/processing";
import { FavoriteAPI } from "dehaze-sdk-js";

const store = useProcessingStore();
const favorited = ref(false);
const favoriteLoading = ref(false);

const zoomOptions = [2, 3, 5] as const;
const sizeOptions = [
  { value: 100, label: "小" },
  { value: 150, label: "中" },
  { value: 200, label: "大" },
] as const;
const displayModes = [
  { value: "origin" as const, label: "原图" },
  { value: "result" as const, label: "处理后" },
  { value: "compare" as const, label: "对比" },
];
const borderStyles = [
  { value: "circle" as const, label: "圆形" },
  { value: "square" as const, label: "方形" },
  { value: "rounded" as const, label: "圆角" },
];

type DisplayMode = "origin" | "result" | "compare";
type BorderStyle = "circle" | "square" | "rounded";
type ZoomValue = 2 | 3 | 5;

const zoom = ref<ZoomValue>(2);
const lensSize = ref<number>(150);
const displayMode = ref<DisplayMode>("compare");
const borderStyle = ref<BorderStyle>("circle");
const posX = ref(150);
const posY = ref(200);
const active = ref(false);
const wrapperRect = ref<{
  left: number;
  top: number;
  width: number;
  height: number;
} | null>(null);

// 双指捏合
let lastPinchDist = 0;

const originUrl = computed(() => store.originUrl);
const resultUrl = computed(() => store.result?.resultUrl || "");
const hasImages = computed(() => !!(originUrl.value && resultUrl.value));
const resultId = computed(() => store.result?.logId);

const showOriginLens = computed(
  () => displayMode.value === "origin" || displayMode.value === "compare"
);
const showResultLens = computed(
  () => displayMode.value === "result" || displayMode.value === "compare"
);

const borderRadius = computed(() => {
  if (borderStyle.value === "circle") return "50%";
  if (borderStyle.value === "rounded") return "16rpx";
  return "0";
});

const modes = [
  {
    key: "side-by-side",
    label: "并排",
    path: "/pages/side-by-side/index",
    icon: "grid",
  },
  {
    key: "overlay",
    label: "重叠",
    path: "/pages/overlay/index",
    icon: "photo",
  },
  {
    key: "magnifier",
    label: "放大镜",
    path: "/pages/magnifier/index",
    icon: "search",
  },
  {
    key: "filter",
    label: "滤镜",
    path: "/pages/filter/index",
    icon: "setting",
  },
  {
    key: "metrics",
    label: "指标",
    path: "/pages/metrics/index",
    icon: "integral",
  },
];

function lensStyle(_imgUrl: string, side: "left" | "right" = "left") {
  const half = lensSize.value / 2;
  let left = posX.value - half;
  if (displayMode.value === "compare") {
    left = side === "left" ? posX.value - lensSize.value - 8 : posX.value + 8;
  }
  return {
    width: `${lensSize.value}px`,
    height: `${lensSize.value}px`,
    left: `${left}px`,
    top: `${posY.value - half}px`,
    borderRadius: borderRadius.value,
    borderColor: side === "left" ? "#3b82f6" : "#34d399",
  };
}

function lensImageStyle(imgUrl: string) {
  const rect = wrapperRect.value;
  const base: Record<string, string> = {
    width: "100%",
    height: "100%",
    backgroundImage: `url(${imgUrl})`,
    backgroundRepeat: "no-repeat",
    borderRadius: borderRadius.value,
  };
  if (!rect) {
    return { ...base, backgroundSize: "cover", backgroundPosition: "center" };
  }
  const relX = posX.value - rect.left;
  const relY = posY.value - rect.top;
  const bgW = rect.width * zoom.value;
  const bgH = rect.height * zoom.value;
  const bgX = -(relX * zoom.value - lensSize.value / 2);
  const bgY = -(relY * zoom.value - lensSize.value / 2);
  return {
    ...base,
    backgroundSize: `${bgW}px ${bgH}px`,
    backgroundPosition: `${bgX}px ${bgY}px`,
  };
}

function updateRect(e: any) {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect?.();
  if (rect) {
    wrapperRect.value = {
      left: rect.left,
      top: rect.top,
      width: rect.width,
      height: rect.height,
    };
  }
}

function handleTouchStart(e: any) {
  updateRect(e);
  active.value = true;
  const touches = e.touches || [];
  if (touches.length === 2) {
    const dx = touches[0].clientX - touches[1].clientX;
    const dy = touches[0].clientY - touches[1].clientY;
    lastPinchDist = Math.sqrt(dx * dx + dy * dy);
  }
}

function handleTouchMove(e: any) {
  const touches = e.touches || [];
  if (touches.length === 2) {
    const dx = touches[0].clientX - touches[1].clientX;
    const dy = touches[0].clientY - touches[1].clientY;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (lastPinchDist > 0 && Math.abs(dist - lastPinchDist) > 20) {
      const curIdx = zoomOptions.indexOf(zoom.value);
      if (dist > lastPinchDist && curIdx < zoomOptions.length - 1) {
        zoom.value = zoomOptions[curIdx + 1] as ZoomValue;
      } else if (dist < lastPinchDist && curIdx > 0) {
        zoom.value = zoomOptions[curIdx - 1] as ZoomValue;
      }
      lastPinchDist = dist;
    }
    return;
  }
  active.value = true;
  updateRect(e);
  const touch = touches[0] || e.changedTouches?.[0];
  if (!touch) return;
  posX.value = touch.clientX;
  posY.value = touch.clientY;
}

function handleTouchEnd() {
  lastPinchDist = 0;
}

function switchPage(url: string) {
  uni.redirectTo({ url });
}

function handleSave() {
  if (!resultUrl.value) {
    uni.showToast({ title: "无结果图片可保存", icon: "none" });
    return;
  }
  uni.downloadFile({
    url: resultUrl.value,
    success(res) {
      if (res.statusCode === 200) {
        uni.saveImageToPhotosAlbum({
          filePath: res.tempFilePath,
          success: () =>
            uni.showToast({ title: "已保存到相册", icon: "success" }),
          fail: () => uni.showToast({ title: "保存失败", icon: "none" }),
        });
      }
    },
  });
}

function handleReprocess() {
  uni.redirectTo({ url: "/pages/processing/index" });
}

function handleChangeAlgorithm() {
  uni.redirectTo({ url: "/pages/algorithm-select/index" });
}

async function handleFavorite() {
  if (!resultId.value) {
    uni.showToast({ title: "暂不支持收藏", icon: "none" });
    return;
  }
  if (favoriteLoading.value) return;
  favoriteLoading.value = true;
  try {
    if (favorited.value) {
      await FavoriteAPI.deleteByIds([resultId.value]);
      favorited.value = false;
      uni.showToast({ title: "已取消收藏", icon: "success" });
    } else {
      await FavoriteAPI.add({ targetType: "result", targetId: resultId.value });
      favorited.value = true;
      uni.showToast({ title: "已收藏", icon: "success" });
    }
  } catch {
    uni.showToast({ title: "操作失败", icon: "none" });
  } finally {
    favoriteLoading.value = false;
  }
}

onMounted(() => {
  if (!hasImages.value)
    uni.showToast({ title: "请先完成去雾处理", icon: "none" });
  if (resultId.value) {
    FavoriteAPI.getStatus("result", resultId.value)
      .then((res) => {
        favorited.value = res.favorited;
      })
      .catch(() => {});
  }
});
</script>

<style lang="scss" scoped>
.main-content {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.magnifier-wrapper {
  position: relative;
  flex: 1;
  overflow: hidden;
  background: #000;
}

.base-image {
  width: 100%;
  display: block;
}

.lens {
  position: fixed;
  border: 4rpx solid;
  box-shadow:
    0 4rpx 24rpx rgba(0, 0, 0, 0.5),
    0 0 0 9999rpx rgba(0, 0, 0, 0.3);
  overflow: hidden;
  pointer-events: none;
  z-index: 999;

  &.lens-origin {
    border-color: #3b82f6;
  }
  &.lens-result {
    border-color: #34d399;
  }
}

.lens-image {
  width: 100%;
  height: 100%;
}

.zoom-badge {
  position: absolute;
  top: 16rpx;
  left: 16rpx;
  padding: 4rpx 16rpx;
  border-radius: 32rpx;
  background: rgba(0, 0, 0, 0.6);
  color: #fff;
  font-size: 22rpx;
  font-weight: 600;
}

.magnifier-hint {
  padding: 16rpx 32rpx;
  font-size: 24rpx;
  color: rgba(255, 255, 255, 0.3);
  text-align: center;
  background: rgba(255, 255, 255, 0.03);
}

.control-panel {
  max-height: 480rpx;
  padding: 24rpx 32rpx;
  overflow-y: auto;
  background: rgba(255, 255, 255, 0.03);
}

.control-group {
  margin-bottom: 24rpx;

  &:last-child {
    margin-bottom: 0;
  }
}

.control-label {
  display: block;
  margin-bottom: 16rpx;
  font-size: 26rpx;
  color: rgba(255, 255, 255, 0.5);
}

.control-options {
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx;

  .control-option {
    padding: 12rpx 32rpx;
    font-size: 26rpx;
    color: rgba(255, 255, 255, 0.5);
    background: rgba(255, 255, 255, 0.08);
    border: 2rpx solid rgba(255, 255, 255, 0.1);
    border-radius: 32rpx;

    &.active {
      color: #f59e0b;
      background: rgba(245, 158, 11, 0.15);
      border-color: #f59e0b;
    }
  }
}

.toolbar-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 4rpx;
  padding: 16rpx 16rpx 8rpx;
}

.toolbar-actions {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 4rpx;
  padding: 0 16rpx 16rpx;
}

.toolbar-item,
.action-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8rpx;
  padding: 20rpx 8rpx;
  font-size: 22rpx;
  color: rgba(255, 255, 255, 0.5);

  &:active {
    background: rgba(245, 158, 11, 0.15);
    border-radius: 12rpx;
  }

  &.active {
    color: #f59e0b;
    background: rgba(245, 158, 11, 0.12);
    border-radius: 12rpx;
  }
}
</style>

// dehaze-taro/src/pages/magnifier/index.tsx
import React, { useState, useEffect, useRef, useCallback } from "react";
import { View, Text, Image } from "@tarojs/components";
import type { BaseEventOrig } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Button } from "@taroify/core";
import { ModelAPI } from "dehaze-sdk-js";
import ImmersiveLayout from "@/layout/immersive";
import CompareToolbar from "@/components/compare/CompareToolbar";
import { loadCompareContext } from "@/components/compare/types";
import EmptyState from "@/components/common/EmptyState";
import "./index.less";

// 放大倍数选项
const ZOOM_OPTIONS = [2, 3, 5] as const;
type ZoomValue = (typeof ZOOM_OPTIONS)[number];
// 放大镜尺寸选项
const SIZE_OPTIONS = [
  { value: 100, label: "小" },
  { value: 150, label: "中" },
  { value: 200, label: "大" },
] as const;
// 显示模式
type DisplayMode = "origin" | "result" | "compare";

// Taro 的 BaseEventOrig 类型定义不完整（缺 touches），扩展为触摸事件类型
type TaroTouchEvent = BaseEventOrig & {
  touches: Array<{ clientX: number; clientY: number }>;
};

// PredEvalTaskStatus: 1 = PENDING, 2 = COMPLETED, 3 = FAILED
type TaskStatus = 1 | 2 | 3;

const MagnifierPage: React.FC = () => {
  const [ctx] = useState(loadCompareContext);
  const [zoom, setZoom] = useState<ZoomValue>(2);
  const [lensSize, setLensSize] = useState<number>(150);
  const [displayMode, setDisplayMode] = useState<DisplayMode>("compare");
  const [lensPos, setLensPos] = useState({ x: 0, y: 0 });
  const [containerSize, setContainerSize] = useState({ width: 0, height: 0 });
  const [reportLoading, setReportLoading] = useState(false);
  const [reportDownloading, setReportDownloading] = useState(false);

  // 缓存容器边界信息（跨端兼容：小程序不支持 getBoundingClientRect）
  const containerRectRef = useRef<{
    left: number;
    top: number;
    width: number;
    height: number;
  } | null>(null);

  const { originImage, result } = ctx;
  const hasResult = originImage && result?.resultUrl;

  // 获取容器尺寸（使用 Taro 节点查询 API，兼容小程序）
  useEffect(() => {
    if (!hasResult) return;
    const timer = setTimeout(() => {
      const query = Taro.createSelectorQuery();
      query.select(".image-container").boundingClientRect();
      query.exec((res) => {
        if (res && res[0]) {
          const rect = res[0];
          containerRectRef.current = rect;
          setContainerSize({ width: rect.width, height: rect.height });
          setLensPos({ x: rect.width / 2, y: rect.height / 2 });
        }
      });
    }, 300);
    return () => clearTimeout(timer);
  }, [hasResult]);

  // 触摸移动放大镜
  const handleTouchMove = useCallback((e: BaseEventOrig) => {
    const { touches } = e as TaroTouchEvent;
    const touch = touches[0];
    const rect = containerRectRef.current;
    if (!rect) return;
    const x = touch.clientX - rect.left;
    const y = touch.clientY - rect.top;
    setLensPos({
      x: Math.max(0, Math.min(rect.width, x)),
      y: Math.max(0, Math.min(rect.height, y)),
    });
  }, []);

  // 双指捏合调整倍数
  const lastPinchDistance = useRef(0);
  const handleTouchStart = useCallback((e: BaseEventOrig) => {
    const { touches } = e as TaroTouchEvent;
    if (touches.length === 2) {
      const dx = touches[0].clientX - touches[1].clientX;
      const dy = touches[0].clientY - touches[1].clientY;
      lastPinchDistance.current = Math.sqrt(dx * dx + dy * dy);
    }
  }, []);

  const handlePinchMove = useCallback((e: BaseEventOrig) => {
    const { touches } = e as TaroTouchEvent;
    if (touches.length !== 2 || lastPinchDistance.current === 0) return;
    const dx = touches[0].clientX - touches[1].clientX;
    const dy = touches[0].clientY - touches[1].clientY;
    const distance = Math.sqrt(dx * dx + dy * dy);
    const delta = distance - lastPinchDistance.current;

    if (Math.abs(delta) > 10) {
      setZoom((prev) => {
        const currentIndex = ZOOM_OPTIONS.indexOf(prev);
        if (delta > 0) {
          const nextIndex = Math.min(currentIndex + 1, ZOOM_OPTIONS.length - 1);
          return ZOOM_OPTIONS[nextIndex];
        } else {
          const nextIndex = Math.max(currentIndex - 1, 0);
          return ZOOM_OPTIONS[nextIndex];
        }
      });
      lastPinchDistance.current = distance;
    }
  }, []);

  const handleTouchEnd = useCallback(() => {
    lastPinchDistance.current = 0;
  }, []);

  // 生成并下载报告
  const handleExportReport = async () => {
    if (!result?.resultUrl) {
      Taro.showToast({ title: "缺少必要参数，无法生成报告", icon: "none" });
      return;
    }
    setReportLoading(true);
    try {
      const res = await ModelAPI.generateReport({ logId: 0, format: "pdf" });
      const taskId = res.taskId;
      if (!taskId) throw new Error("未返回任务ID");
      while (true) {
        const statusRes = await ModelAPI.getReportStatus(taskId);
        const status = statusRes.status as TaskStatus;
        if (status === 2) {
          if (statusRes.downloadUrl) {
            setReportLoading(false);
            setReportDownloading(true);
            try {
              const filePath = await Taro.downloadFile({ url: statusRes.downloadUrl });
              if (filePath.tempFilePath) {
                await Taro.openDocument({ filePath: filePath.tempFilePath, showMenu: true });
              }
            } catch { Taro.showToast({ title: "打开报告失败", icon: "none" }); }
            finally { setReportDownloading(false); }
          } else { throw new Error("报告生成但无下载链接"); }
          break;
        }
        if (status === 3) throw new Error(statusRes.errorMessage || "报告生成失败");
        await new Promise((r) => setTimeout(r, 2000));
      }
    } catch (err: unknown) {
      Taro.showToast({ title: err instanceof Error ? err.message : "报告生成失败", icon: "none" });
    } finally { setReportLoading(false); }
  };

  // 点击切换显示模式（原图 → 处理后 → 对比 → 原图）
  const handleTap = useCallback(() => {
    setDisplayMode((prev) => {
      if (prev === "origin") return "result";
      if (prev === "result") return "compare";
      return "origin";
    });
  }, []);

  // 计算放大镜内背景图位置
  const getLensBackgroundPosition = () => {
    if (!containerSize.width || !containerSize.height) return "0 0";
    const bgX = -(lensPos.x * zoom - lensSize / 2);
    const bgY = -(lensPos.y * zoom - lensSize / 2);
    return `${bgX}px ${bgY}px`;
  };

  const lensStyle = (imageUrl: string): React.CSSProperties => ({
    width: `${lensSize}px`,
    height: `${lensSize}px`,
    left: `${lensPos.x - lensSize / 2}px`,
    top: `${lensPos.y - lensSize / 2}px`,
    backgroundImage: `url(${imageUrl})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: `${containerSize.width * zoom}px ${containerSize.height * zoom}px`,
    backgroundPosition: getLensBackgroundPosition(),
    borderRadius: "50%",
    border: "4rpx solid #fff",
    boxShadow: "0 4rpx 16rpx rgb(0 0 0 / 30%)",
  });

  return (
    <ImmersiveLayout
      title="放大镜对比"
      toolbar={
        <CompareToolbar currentMode="magnifier" resultUrl={result?.resultUrl} resultId={result?.logId} />
      }
    >
      {/* 对比区域 */}
      {!hasResult ? (
        <EmptyState type="compare" />
      ) : (
        <>
          {/* 图片容器 + 放大镜 */}
          <View
            className="image-container"
            onTouchStart={handleTouchStart}
            onTouchMove={(e) => {
              handleTouchMove(e);
              handlePinchMove(e);
            }}
            onTouchEnd={handleTouchEnd}
            onClick={handleTap}
          >
            <Image
              src={result!.resultUrl || ""}
              className="base-image"
              mode="widthFix"
              lazyLoad
            />

            {/* 原图放大镜 */}
            {(displayMode === "origin" || displayMode === "compare") && (
              <View
                className={`magnifier-lens ${displayMode === "compare" ? "lens-origin" : ""}`}
                style={lensStyle(originImage!.url)}
              />
            )}

            {/* 处理后放大镜 */}
            {(displayMode === "result" || displayMode === "compare") && (
              <View
                className={`magnifier-lens ${displayMode === "compare" ? "lens-result" : ""}`}
                style={{
                  ...lensStyle(result!.resultUrl || ""),
                  ...(displayMode === "compare"
                    ? { left: `${lensPos.x + lensSize / 2}px` }
                    : {}),
                }}
              />
            )}
          </View>

          {/* 提示 */}
          <View className="magnifier-hint">
            <Text>拖动移动放大镜 · 双指捏合调整倍数 · 点击切换模式</Text>
          </View>

          {/* 控制面板 */}
          <View className="control-panel">
            {/* 显示模式 */}
            <View className="control-group">
              <Text className="control-label">显示模式</Text>
              <View className="control-options">
                {(
                  [
                    { value: "origin", label: "原图" },
                    { value: "result", label: "处理后" },
                    { value: "compare", label: "对比" },
                  ] as const
                ).map((opt) => (
                  <View
                    key={opt.value}
                    className={`control-option ${displayMode === opt.value ? "active" : ""}`}
                    onClick={() => setDisplayMode(opt.value)}
                  >
                    <Text>{opt.label}</Text>
                  </View>
                ))}
              </View>
            </View>

            {/* 放大倍数 */}
            <View className="control-group">
              <Text className="control-label">放大倍数</Text>
              <View className="control-options">
                {ZOOM_OPTIONS.map((z) => (
                  <View
                    key={z}
                    className={`control-option ${zoom === z ? "active" : ""}`}
                    onClick={() => setZoom(z)}
                  >
                    <Text>{z}x</Text>
                  </View>
                ))}
              </View>
            </View>

            {/* 放大镜尺寸 */}
            <View className="control-group">
              <Text className="control-label">放大镜大小</Text>
              <View className="control-options">
                {SIZE_OPTIONS.map((opt) => (
                  <View
                    key={opt.value}
                    className={`control-option ${lensSize === opt.value ? "active" : ""}`}
                    onClick={() => setLensSize(opt.value)}
                  >
                    <Text>{opt.label}</Text>
                  </View>
                ))}
              </View>
            </View>
          </View>

          {/* 导出报告 */}
          <View className="export-report-section">
            <Button
              block
              color="primary"
              loading={reportLoading || reportDownloading}
              onClick={handleExportReport}
            >
              {reportDownloading ? "正在打开报告..." : "导出报告"}
            </Button>
          </View>
        </>
      )}
    </ImmersiveLayout>
  );
};

export default MagnifierPage;
