// src/components/AlgorithmToolBar/AlgorithmHeader/index.vue
<script setup lang="ts">
defineOptions({
  name: "AlgorithmHeader",
});

defineProps({
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
});
</script>

<template>
  <h2 class="text-center m2">{{ title }}</h2>
  <el-text class="m2">
    {{ description }}
  </el-text>
</template>

<style lang="scss" scoped></style>

// src/components/AlgorithmToolBar/AlgorithmHeader.tsx
import React from "react";

interface AlgorithmHeaderProps {
  title: string;
  description: string;
}

const AlgorithmHeader: React.FC<AlgorithmHeaderProps> = ({
  title,
  description,
}) => {
  return (
    <>
      <h2 style={{ textAlign: "center", margin: "8px" }}>{title}</h2>
      <div style={{ margin: "8px" }}>{description}</div>
    </>
  );
};

export default AlgorithmHeader;
