// src/components/AlgorithmToolBar/index.tsx
import AlgorithmHeader from "@/components/AlgorithmToolBar/AlgorithmHeader";
import ImageUploadButton from "@/components/AlgorithmToolBar/ImageUploadButton";
import SubmitButton from "@/components/AlgorithmToolBar/SubmitButton";

import { MagnifierInfo } from "@/components/AlgorithmToolBar/types";
import { Card } from "antd";
import React from "react";
import "./index.scss";

interface AlgorithmToolBarProps {
  title?: string;
  description?: string;
  disableMore: boolean;
  magnifier: MagnifierInfo;
  onUpload: (file: File) => void;
  onTakePhoto: () => void;
  onReset: () => void;
  onGenerate: () => void;
  onMagnifierChange: () => void;
  onBrightnessChange: (value: number) => void;
  onContrastChange: (value: number) => void;
  children: React.ReactNode;
}

const AlgorithmToolBar: React.FC<AlgorithmToolBarProps> = ({
  title = "图像去雾",
  description = "通过对遭受雾气影响的图像进行相应处理，恢复图像原本的纹理结构和细节信息，进而提升图像的能见度",
  disableMore,
  magnifier,
  onUpload,
  onTakePhoto,
  onReset,
  onGenerate,
  onMagnifierChange,
  onBrightnessChange,
  onContrastChange,
  children,
}) => {
  return (
    <div className="mr-3">
      <Card className="sidebar-card">
        <AlgorithmHeader title={title} description={description} />
        <ImageUploadButton
          onUpload={onUpload}
          onTakePhoto={onTakePhoto}
          onReset={onReset}
        />
        {children}
        <SubmitButton
          disableMore={disableMore}
          magnifier={magnifier}
          onGenerate={onGenerate}
          onMagnifierChange={onMagnifierChange}
          onBrightnessChange={onBrightnessChange}
          onContrastChange={onContrastChange}
        />
      </Card>
    </div>
  );
};

export default AlgorithmToolBar;

// src/components/AlgorithmToolBar/index.vue
<script lang="ts" setup>
import { MagnifierInfo } from "./types";
import AlgorithmHeader from "@/components/AlgorithmToolBar/AlgorithmHeader/index.vue";
import ImageUploadButton from "@/components/AlgorithmToolBar/ImageUploadButton/index.vue";
import SubmitButton from "@/components/AlgorithmToolBar/SubmitButton/index.vue";

defineOptions({
  name: "AlgorithmToolBar",
});

const props = defineProps({
  title: {
    type: String,
    default: "图像去雾",
  },
  description: {
    type: String,
    default:
      "通过对遭受雾气影响的图像进行相应处理，恢复图像原本的纹理结构和细节信息，进而提升图像的能见度",
  },
  disableMore: {
    type: Boolean,
    default: false,
  },
  magnifier: {
    type: Object as () => MagnifierInfo,
    default: () => ({
      imgUrls: [],
      radius: 100,
      originScale: 1,
      point: { x: 0, y: 0 },
    }),
  },
});

const emit = defineEmits([
  "onUpload",
  "onTakePhoto",
  "onReset",
  "onGenerate",
  "onMagnifierChange",
  "onBrightnessChange",
  "onContrastChange",
]);
</script>

<template>
  <div class="mr-3">
    <el-card class="sidebar-card">
      <AlgorithmHeader :description="description" :title="title" />
      <ImageUploadButton
        @on-upload="(file: File) => emit('onUpload', file)"
        @on-take-photo="() => emit('onTakePhoto')"
        @on-reset="() => emit('onReset')"
      />
      <slot></slot>
      <SubmitButton
        :disable-more="disableMore"
        :magnifier="magnifier"
        @on-generate="() => emit('onGenerate')"
        @on-magnifier-change="
          (flag: boolean) => emit('onMagnifierChange', flag)
        "
        @on-brightness-change="
          (value: number) => emit('onBrightnessChange', value)
        "
        @on-contrast-change="(value: number) => emit('onContrastChange', value)"
      />
    </el-card>
  </div>
</template>

<style lang="scss" scoped>
.sidebar-card {
  width: 30vw;
  height: 100%;
  padding: 0 15px;
  overflow-y: auto;
}
</style>
