// dehaze-uniapp/src/pages/personal/orders/index.vue
<template>
  <PageLayout level="L2" title="我的订单" class="page">
    <view class="main-content">
      <view v-if="loading" class="loading-container">
        <view class="loading-spinner" />
        <text class="loading-text">加载中...</text>
      </view>

      <view v-else-if="orders.length > 0" class="order-list">
        <view
          v-for="order in orders"
          :key="order.orderNo"
          class="order-card"
          @click="handleDetail(order)"
        >
          <view class="order-header">
            <text class="order-no">{{ order.orderNo }}</text>
            <text :class="['order-status', statusClass(order.status)]">{{
              statusText(order.status)
            }}</text>
          </view>
          <view class="order-body">
            <text class="order-package">{{ order.packageName }}</text>
            <text class="order-amount">¥{{ order.payableAmount }}</text>
          </view>
          <view class="order-footer">
            <text class="order-time">{{
              formatRelativeTime(order.createTime)
            }}</text>
          </view>
        </view>
        <view v-if="!hasMore" class="end-text">— 没有更多了 —</view>
        <view v-else class="load-more" @click="loadMore">加载更多</view>
      </view>

      <view v-else class="empty-state">
        <view class="empty-tip">暂无订单</view>
        <text class="empty-hint">购买套餐后订单会显示在这里</text>
      </view>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import PageLayout from "@/layout/index.vue";
import { OrderAPI } from "dehaze-sdk-js";
import type { MyOrderVO, OrderStatus } from "dehaze-sdk-js";
import { formatRelativeTime } from "@/utils/format";

const loading = ref(false);
const orders = ref<MyOrderVO[]>([]);
const currentPage = ref(1);
const hasMore = ref(true);

async function loadData(page = 1) {
  if (loading.value) return;
  loading.value = true;
  try {
    const result = await OrderAPI.listMy({ pageNum: page, pageSize: 20 });
    if (page === 1) {
      orders.value = result.list;
    } else {
      orders.value = [...orders.value, ...result.list];
    }
    hasMore.value = orders.value.length < result.total;
    currentPage.value = page;
  } catch {
    uni.showToast({ title: "加载失败", icon: "none" });
  } finally {
    loading.value = false;
  }
}

function loadMore() {
  if (hasMore.value) loadData(currentPage.value + 1);
}

function handleDetail(order: MyOrderVO) {
  uni.showToast({ title: `订单 ${order.orderNo} 详情`, icon: "none" });
}

function statusText(status: OrderStatus): string {
  const map: Record<string, string> = {
    pending: "待支付",
    paid: "已支付",
    completed: "已完成",
    cancelled: "已取消",
    refunding: "退款中",
    refunded: "已退款",
  };
  return map[status] || status;
}

function statusClass(status: OrderStatus): string {
  const map: Record<string, string> = {
    pending: "status-pending",
    paid: "status-paid",
    completed: "status-done",
    cancelled: "status-cancel",
    refunding: "status-warn",
    refunded: "status-done",
  };
  return map[status] || "";
}

onMounted(() => loadData());
</script>

<style lang="scss" scoped>
@import "@/styles/mixins.scss";

.page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}
.main-content {
  padding: $spacing-md;
  @include safe-area-bottom(80rpx);
}

.order-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.order-card {
  background: $color-white;
  border-radius: 20rpx;
  padding: 24rpx;
  box-shadow: $shadow-sm;
  &:active {
    background: $color-bg-primary;
  }
}
.order-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.order-no {
  font-size: $font-sm;
  color: $color-text-secondary;
  font-family: monospace;
}
.order-status {
  font-size: $font-xs;
  font-weight: 500;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
}
.status-pending {
  color: $color-warning;
  background: #fef3c7;
}
.status-paid {
  color: $color-primary;
  background: #dbeafe;
}
.status-done {
  color: $color-success;
  background: #ecfdf5;
}
.status-cancel {
  color: $color-text-placeholder;
  background: $color-bg-secondary;
}
.status-warn {
  color: $color-danger;
  background: #fef2f2;
}

.order-body {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12rpx;
}
.order-package {
  font-size: $font-md;
  font-weight: 600;
  color: $color-text-primary;
}
.order-amount {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-warning;
}
.order-footer {
}
.order-time {
  font-size: $font-xs;
  color: $color-text-placeholder;
}

.end-text {
  text-align: center;
  font-size: $font-sm;
  color: $color-text-disabled;
  padding: 32rpx 0;
}
.load-more {
  text-align: center;
  font-size: $font-sm;
  color: $color-secondary;
  padding: 24rpx 0;
}
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 120rpx 0;
}
.loading-text {
  margin-top: 24rpx;
  font-size: $font-md;
  color: $color-text-placeholder;
}
.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 80rpx 0;
}
.empty-tip {
  font-size: $font-md;
}
.empty-hint {
  font-size: $font-sm;
  color: $color-text-placeholder;
  margin-top: 16rpx;
}
</style>

// dehaze-react-native/src/pages/personal/orders/index.tsx
/**
 * 我的订单 (L2)
 *
 * OrderAPI.listMy 订单列表 + 状态标签
 */
import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  FlatList,
  StyleSheet,
  RefreshControl,
  Alert,
} from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { OrderAPI } from 'dehaze-sdk-js';
import type { MyOrderVO } from 'dehaze-sdk-js';
import Ionicons from 'react-native-vector-icons/Ionicons';

import { theme } from '@/theme';
import { AppHeader } from '@/layout';

const PAGE_SIZE = 20;

const ORDER_STATUS_MAP: Record<string, { label: string; color: string }> = {
  PENDING_PAYMENT: { label: '待支付', color: theme.colors.status.warning },
  PAID: { label: '已支付', color: theme.colors.primary },
  PROCESSING: { label: '处理中', color: '#8b5cf6' },
  COMPLETED: { label: '已完成', color: theme.colors.status.success },
  CANCELLED: { label: '已取消', color: theme.colors.text.tertiary },
  REFUNDING: { label: '退款中', color: theme.colors.status.warning },
  REFUNDED: { label: '已退款', color: theme.colors.text.tertiary },
};

const PersonalOrdersScreen: React.FC = () => {
  const navigation = useNavigation();
  const [orders, setOrders] = useState<MyOrderVO[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [hasMore, setHasMore] = useState(true);
  const [page, setPage] = useState(1);

  const loadOrders = useCallback(async (pageNum = 1, isRefresh = false) => {
    try {
      if (isRefresh) setRefreshing(true);
      else if (pageNum === 1) setLoading(true);

      const result = await OrderAPI.listMy({ pageNum, pageSize: PAGE_SIZE });
      const list = result.list || [];
      if (pageNum === 1) {
        setOrders(list);
      } else {
        setOrders(prev => [...prev, ...list]);
      }
      setHasMore(list.length >= PAGE_SIZE);
      setPage(pageNum);
    } catch {
      Alert.alert('加载失败', '获取订单列表失败，请重试');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      loadOrders(1);
    }, [loadOrders]),
  );

  const handleRefresh = useCallback(() => loadOrders(1, true), [loadOrders]);
  const handleLoadMore = useCallback(() => {
    if (hasMore && !refreshing) loadOrders(page + 1);
  }, [hasMore, refreshing, page, loadOrders]);

  const renderItem = useCallback(({ item }: { item: MyOrderVO }) => {
    const statusInfo = ORDER_STATUS_MAP[item.status] || { label: item.status, color: theme.colors.text.tertiary };

    return (
      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.orderNo} numberOfLines={1}>{item.orderNo}</Text>
          <View style={[styles.statusBadge, { backgroundColor: statusInfo.color + '20' }]}>
            <Text style={[styles.statusText, { color: statusInfo.color }]}>{statusInfo.label}</Text>
          </View>
        </View>
        <Text style={styles.packageName}>{item.packageName}</Text>
        <View style={styles.cardFooter}>
          <Text style={styles.amount}>¥{(item.payableAmount ?? 0).toFixed(2)}</Text>
          <Text style={styles.time}>
            {item.createTime ? new Date(item.createTime).toLocaleDateString('zh-CN') : ''}
          </Text>
        </View>
      </View>
    );
  }, []);

  const renderEmpty = () =>
    !loading ? (
      <View style={styles.empty}>
        <Ionicons name="cart-outline" size={48} color={theme.colors.text.tertiary} />
        <Text style={styles.emptyText}>暂无订单</Text>
      </View>
    ) : null;

  return (
    <View style={styles.container}>
      <AppHeader title="我的订单" showBack onBackPress={() => navigation.goBack()} />
      <FlatList
        data={orders}
        renderItem={renderItem}
        keyExtractor={item => item.orderNo}
        contentContainerStyle={styles.list}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={handleRefresh} colors={[theme.colors.primary]} tintColor={theme.colors.primary} />
        }
        onEndReached={handleLoadMore}
        onEndReachedThreshold={0.5}
        ListEmptyComponent={renderEmpty}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background.secondary },
  list: { padding: theme.spacing.md, flexGrow: 1 },
  card: {
    backgroundColor: theme.colors.background.primary,
    borderRadius: theme.layout.borderRadius.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    ...theme.layout.shadows.sm,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  orderNo: {
    fontSize: theme.typography.sizes.small,
    color: theme.colors.text.tertiary,
    flex: 1,
    marginRight: theme.spacing.sm,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.layout.borderRadius.sm,
  },
  statusText: {
    fontSize: theme.typography.sizes.tiny,
    fontWeight: theme.typography.weights.semibold,
  },
  packageName: {
    fontSize: theme.typography.sizes.bodySmall,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.text.primary,
    marginBottom: 8,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amount: {
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.status.error,
  },
  time: {
    fontSize: theme.typography.sizes.tiny,
    color: theme.colors.text.tertiary,
  },
  empty: { alignItems: 'center', paddingVertical: theme.spacing.xxxl },
  emptyText: { fontSize: theme.typography.sizes.bodySmall, color: theme.colors.text.tertiary, marginTop: theme.spacing.sm },
});

export default PersonalOrdersScreen;
