// dehaze-front-vue/src/views/system/user/index.vue
<!-- 用户管理 -->
<template>
  <div class="app-container">
    <el-row :gutter="20">
      <!-- 部门树 -->
      <el-col :lg="4" :xs="24" class="mb-[12px]">
        <dept-tree v-model="queryParams.deptId" @node-click="handleQuery" />
      </el-col>

      <!-- 用户列表 -->
      <el-col :lg="20" :xs="24">
        <div class="search-container">
          <el-form ref="queryFormRef" :inline="true" :model="queryParams">
            <el-form-item label="关键字" prop="keywords">
              <el-input
                v-model="queryParams.keywords"
                clearable
                placeholder="用户名/昵称/手机号"
                style="width: 200px"
                @keyup.enter="handleQuery"
                @input="debouncedQuery"
              />
            </el-form-item>

            <el-form-item label="状态" prop="status">
              <el-select
                v-model="queryParams.status"
                class="!w-[100px]"
                clearable
                placeholder="全部"
              >
                <el-option label="启用" value="1" />
                <el-option label="禁用" value="0" />
              </el-select>
            </el-form-item>

            <el-form-item label="创建时间">
              <el-date-picker
                v-model="dateTimeRange"
                class="!w-[240px]"
                end-placeholder="截止时间"
                range-separator="~"
                start-placeholder="开始时间"
                type="daterange"
                value-format="YYYY-MM-DD"
              />
            </el-form-item>

            <el-form-item>
              <el-button type="primary" @click="handleQuery"
                ><el-icon><Search /></el-icon>搜索</el-button
              >
              <el-button @click="resetQuery">
                <el-icon><Refresh /></el-icon>
                重置</el-button
              >
            </el-form-item>
          </el-form>
        </div>

        <el-card class="table-container" shadow="never">
          <template #header>
            <div class="flex justify-between">
              <div>
                <el-button
                  v-hasPerm="['sys:user:add']"
                  type="success"
                  @click="openDialog('user-form')"
                  ><el-icon><Plus /></el-icon>新增</el-button
                >
                <el-button
                  v-hasPerm="['sys:user:delete']"
                  :disabled="removeIds.length === 0"
                  type="danger"
                  @click="handleDelete()"
                  ><el-icon><Delete /></el-icon>删除</el-button
                >
              </div>
              <div>
                <el-dropdown split-button>
                  导入
                  <template #dropdown>
                    <el-dropdown-menu>
                      <el-dropdown-item @click="downloadTemplate">
                        <el-icon>
                          <Download />
                        </el-icon>
                        下载模板
                      </el-dropdown-item>
                      <el-dropdown-item @click="openDialog('user-import')">
                        <el-icon>
                          <Top />
                        </el-icon>
                        导入数据
                      </el-dropdown-item>
                    </el-dropdown-menu>
                  </template>
                </el-dropdown>
                <el-button
                  class="ml-3"
                  :loading="exportLoading"
                  @click="handleExport"
                >
                  <template #icon>
                    <el-icon>
                      <Download />
                    </el-icon>
                  </template>
                  导出
                </el-button>
              </div>
            </div>
          </template>

          <el-table
            v-loading="loading"
            :data="pageData"
            @selection-change="handleSelectionChange"
          >
            <el-table-column align="center" type="selection" width="50" />
            <el-table-column
              key="id"
              align="center"
              label="编号"
              prop="id"
              width="100"
            />
            <el-table-column
              key="username"
              align="center"
              label="用户名"
              prop="username"
            />
            <el-table-column
              align="center"
              label="用户昵称"
              prop="nickname"
              width="120"
            />

            <el-table-column
              align="center"
              label="性别"
              prop="genderLabel"
              width="100"
            />

            <el-table-column
              align="center"
              label="部门"
              prop="deptName"
              width="120"
            />
            <el-table-column
              align="center"
              label="手机号码"
              prop="mobile"
              width="120"
            />

            <el-table-column align="center" label="状态" prop="status">
              <template #default="scope">
                <el-switch
                  v-model="scope.row.status"
                  :active-value="1"
                  :inactive-value="0"
                  @change="handleStatusChange(scope.row)"
                />
              </template>
            </el-table-column>
            <el-table-column
              align="center"
              label="创建时间"
              prop="createTime"
              width="180"
            />
            <el-table-column fixed="right" label="操作" width="220">
              <template #default="scope">
                <el-button
                  v-hasPerm="['sys:user:password:reset']"
                  link
                  size="small"
                  type="primary"
                  @click="resetPassword(scope.row)"
                  ><el-icon><RefreshLeft /></el-icon>重置密码</el-button
                >
                <el-button
                  v-hasPerm="['sys:user:edit']"
                  link
                  size="small"
                  type="primary"
                  @click="openDialog('user-form', scope.row.id)"
                  ><el-icon><Edit /></el-icon>编辑</el-button
                >
                <el-button
                  v-hasPerm="['sys:user:delete']"
                  link
                  size="small"
                  type="primary"
                  @click="handleDelete(scope.row)"
                  ><el-icon><Delete /></el-icon>删除</el-button
                >
              </template>
            </el-table-column>
          </el-table>

          <pagination
            v-if="total > 0"
            v-model:limit="queryParams.pageSize"
            v-model:page="queryParams.pageNum"
            v-model:total="total"
            @pagination="handleQuery"
          />
        </el-card>
      </el-col>
    </el-row>

    <!-- 弹窗 -->
    <el-dialog
      v-model="dialog.visible"
      :title="dialog.title"
      :width="dialog.width"
      append-to-body
      @close="closeDialog"
    >
      <!-- 用户新增/编辑表单 -->
      <el-form
        v-if="dialog.type === 'user-form'"
        ref="userFormRef"
        :model="formData"
        :rules="rules"
        label-width="80px"
      >
        <el-form-item label="用户名" prop="username">
          <el-input
            v-model="formData.username"
            :readonly="!!formData.id"
            placeholder="请输入用户名"
          />
        </el-form-item>

        <el-form-item label="用户昵称" prop="nickname">
          <el-input v-model="formData.nickname" placeholder="请输入用户昵称" />
        </el-form-item>

        <el-form-item label="所属部门" prop="deptId">
          <el-tree-select
            v-model="formData.deptId"
            :data="deptList"
            :render-after-expand="false"
            check-strictly
            filterable
            placeholder="请选择所属部门"
          />
        </el-form-item>

        <el-form-item label="性别" prop="gender">
          <dictionary v-model="formData.gender" type-code="gender" />
        </el-form-item>

        <el-form-item label="角色" prop="roleIds">
          <el-select v-model="formData.roleIds" multiple placeholder="请选择">
            <el-option
              v-for="item in roleList"
              :key="item.value"
              :label="item.label"
              :value="item.value"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="手机号码" prop="mobile">
          <el-input
            v-model="formData.mobile"
            maxlength="11"
            placeholder="请输入手机号码"
          />
        </el-form-item>

        <el-form-item label="邮箱" prop="email">
          <el-input
            v-model="formData.email"
            maxlength="50"
            placeholder="请输入邮箱"
          />
        </el-form-item>

        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="formData.status">
            <el-radio :label="1">正常</el-radio>
            <el-radio :label="0">禁用</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>

      <!-- 用户导入表单 -->
      <el-form
        v-else-if="dialog.type === 'user-import'"
        :model="importData"
        label-width="100px"
      >
        <el-form-item label="部门">
          <el-tree-select
            v-model="importData.deptId"
            :data="deptList"
            check-strictly
            filterable
            placeholder="请选择部门"
          />
        </el-form-item>

        <el-form-item label="Excel文件">
          <el-upload
            ref="uploadRef"
            :auto-upload="false"
            :file-list="importData.fileList"
            :limit="1"
            :on-change="handleFileChange"
            :on-exceed="handleFileExceed"
            accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
            action=""
            drag
          >
            <el-icon class="el-icon--upload">
              <UploadFilled />
            </el-icon>
            <div class="el-upload__text">
              将文件拖到此处，或
              <em>点击上传</em>
            </div>
            <template #tip>
              <div>xls/xlsx files</div>
            </template>
          </el-upload>
        </el-form-item>
      </el-form>
      <!-- 弹窗底部操作按钮 -->
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="handleSubmit">确 定</el-button>
          <el-button @click="closeDialog">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script lang="ts" setup>
defineOptions({
  name: "User",
  inheritAttrs: false,
});

import {
  DeptAPI,
  OptionType,
  RoleAPI,
  UserAPI,
  UserForm,
  UserPageVO,
  UserQuery,
} from "dehaze-sdk-js";

import {
  Delete,
  Download,
  Edit,
  Plus,
  Refresh,
  RefreshLeft,
  Search,
  Top,
  UploadFilled,
} from "@element-plus/icons-vue";

import type { UploadInstance } from "element-plus";
import { genFileId } from "element-plus";

const queryFormRef = ref(ElForm); // 查询表单
const userFormRef = ref(ElForm); // 用户表单
const uploadRef = ref<UploadInstance>(); // 上传组件

const loading = ref(false); //  加载状态
const exportLoading = ref(false); // 导出加载状态
const removeIds = ref([]); // 删除用户ID集合 用于批量删除
const queryParams = reactive<UserQuery>({
  pageNum: 1,
  pageSize: 10,
});
const dateTimeRange = ref("");
const total = ref(0); // 数据总数
const pageData = ref<UserPageVO[]>(); // 用户分页数据
const deptList = ref<OptionType[]>(); // 部门下拉数据源
const roleList = ref<OptionType[]>(); // 角色下拉数据源

watch(dateTimeRange, (newVal) => {
  if (newVal) {
    queryParams.startTime = newVal[0];
    queryParams.endTime = newVal[1];
  } else {
    queryParams.startTime = undefined;
    queryParams.endTime = undefined;
  }
});

// 弹窗对象
const dialog = reactive({
  visible: false,
  type: "user-form",
  width: 800,
  title: "",
});

// 用户表单数据
const formData = reactive<UserForm>({
  status: 1,
});

// 用户导入数据
const importData = reactive({
  deptId: undefined,
  file: undefined,
  fileList: [],
});

// 校验规则
const rules = reactive({
  username: [{ required: true, message: "用户名不能为空", trigger: "blur" }],
  nickname: [{ required: true, message: "用户昵称不能为空", trigger: "blur" }],
  deptId: [{ required: true, message: "所属部门不能为空", trigger: "blur" }],
  gender: [{ required: true, message: "性别不能为空", trigger: "change" }],
  roleIds: [{ required: true, message: "用户角色不能为空", trigger: "blur" }],
  email: [
    {
      pattern: /\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}/,
      message: "请输入正确的邮箱地址",
      trigger: "blur",
    },
  ],
  mobile: [
    {
      pattern: /^1[3|4|5|6|7|8|9][0-9]\d{8}$/,
      message: "请输入正确的手机号码",
      trigger: "blur",
    },
  ],
});

/** 查询 */
function handleQuery() {
  loading.value = true;
  UserAPI.getPage(queryParams)
    .then((data) => {
      pageData.value = data.list;
      total.value = data.total;
    })
    .finally(() => {
      loading.value = false;
    });
}

/** 防抖查询（300ms） */
const debouncedQuery = useDebounceFn(handleQuery, 300);

/** 修改用户状态 */
function handleStatusChange(row: any) {
  UserAPI.updateStatus(row.id, row.status)
    .then(() => {
      ElMessage.success("状态修改成功");
    })
    .catch(() => {
      row.status = row.status === 1 ? 0 : 1;
    });
}

/** 重置查询 */
function resetQuery() {
  queryFormRef.value.resetFields();
  dateTimeRange.value = "";
  queryParams.pageNum = 1;
  queryParams.deptId = undefined;
  queryParams.startTime = undefined;
  queryParams.endTime = undefined;
  handleQuery();
}

/** 行选中 */
function handleSelectionChange(selection: any) {
  removeIds.value = selection.map((item: any) => item.id);
}

/** 重置密码 */
function resetPassword(row: { [key: string]: any }) {
  ElMessageBox.prompt(
    "请输入用户「" + row.username + "」的新密码",
    "重置密码",
    {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
    }
  )
    .then(({ value }) => {
      if (!value) {
        ElMessage.warning("请输入新密码");
        return false;
      }
      UserAPI.updatePassword(row.id, value).then(() => {
        ElMessage.success("密码重置成功，新密码是：" + value);
      });
    })
    .catch(() => {});
}

/** 加载角色下拉数据源 */
async function loadRoleOptions() {
  roleList.value = await RoleAPI.getOptions();
}

/** 加载部门下拉数据源 */
async function loadDeptOptions() {
  deptList.value = await DeptAPI.getOptions();
}

/**
 * 打开弹窗
 *
 * @param type 弹窗类型  用户表单：user-form | 用户导入：user-import
 * @param id 用户ID
 */
async function openDialog(type: string, id?: number) {
  dialog.visible = true;
  dialog.type = type;

  if (dialog.type === "user-form") {
    // 用户表单弹窗
    await loadDeptOptions();
    await loadRoleOptions();
    if (id) {
      dialog.title = "修改用户";
      const data = await UserAPI.getFormData(id);
      Object.assign(formData, { ...data });
    } else {
      dialog.title = "新增用户";
    }
  } else if (dialog.type === "user-import") {
    // 用户导入弹窗
    dialog.title = "导入用户";
    dialog.width = 600;
    await loadDeptOptions();
  }
}

/**
 * 关闭弹窗
 *
 * @param type 弹窗类型  用户表单：user-form | 用户导入：user-import
 */
function closeDialog() {
  dialog.visible = false;
  if (dialog.type === "user-form") {
    userFormRef.value.resetFields();
    userFormRef.value.clearValidate();

    formData.id = undefined;
    formData.status = 1;
  } else if (dialog.type === "user-import") {
    importData.file = undefined;
    importData.fileList = [];
  }
}

/** 表单提交 */
const handleSubmit = useThrottleFn(() => {
  if (dialog.type === "user-form") {
    userFormRef.value.validate((valid: any) => {
      if (valid) {
        const userId = formData.id;
        loading.value = true;
        if (userId) {
          UserAPI.update(userId, formData)
            .then(() => {
              ElMessage.success("修改用户成功");
              closeDialog();
              resetQuery();
            })
            .finally(() => (loading.value = false));
        } else {
          UserAPI.add(formData)
            .then(() => {
              ElMessage.success("新增用户成功");
              closeDialog();
              resetQuery();
            })
            .finally(() => (loading.value = false));
        }
      }
    });
  } else if (dialog.type === "user-import") {
    if (!importData?.deptId) {
      ElMessage.warning("请选择部门");
      return false;
    }
    if (!importData?.file) {
      ElMessage.warning("上传Excel文件不能为空");
      return false;
    }
    UserAPI.import(importData?.deptId, importData?.file).then(() => {
      ElMessage.success("导入用户成功");
      closeDialog();
      resetQuery();
    });
  }
}, 3000);

/** 删除用户 */
function handleDelete(row?: any) {
  let userIds: string;
  let confirmText: string;

  if (row) {
    userIds = String(row.id);
    confirmText = `确认删除用户「${row.username}」吗？删除后不可恢复。`;
  } else {
    if (removeIds.value.length === 0) {
      ElMessage.warning("请勾选删除项");
      return;
    }
    userIds = removeIds.value.join(",");
    confirmText = `确认删除选中的 ${removeIds.value.length} 个用户吗？删除后不可恢复。`;
  }

  ElMessageBox.confirm(confirmText, "警告", {
    confirmButtonText: "确定",
    cancelButtonText: "取消",
    type: "warning",
  })
    .then(function () {
      UserAPI.deleteByIds(userIds).then(() => {
        ElMessage.success("删除成功");
        resetQuery();
      });
    })
    .catch(() => {});
}

/** 下载导入模板 */
function downloadTemplate() {
  UserAPI.downloadTemplate().then((response: any) => {
    const fileData = response.data;
    const fileName = decodeURI(
      response.headers["content-disposition"].split(";")[1].split("=")[1]
    );
    const fileType =
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8";

    const blob = new Blob([fileData], { type: fileType });
    const downloadUrl = window.URL.createObjectURL(blob);

    const downloadLink = document.createElement("a");
    downloadLink.href = downloadUrl;
    downloadLink.download = fileName;

    document.body.appendChild(downloadLink);
    downloadLink.click();

    document.body.removeChild(downloadLink);
    window.URL.revokeObjectURL(downloadUrl);
  });
}

/** Excel文件 Change */
function handleFileChange(file: any) {
  importData.file = file.raw;
}

/** Excel文件 Exceed  */
function handleFileExceed(files: any) {
  uploadRef.value!.clearFiles();
  const file = files[0];
  file.uid = genFileId();
  uploadRef.value!.handleStart(file);
  importData.file = file;
}

/** 导出用户 */
function handleExport() {
  exportLoading.value = true;
  UserAPI.export(queryParams)
    .then((response: any) => {
      const fileData = response.data;
      const fileName = decodeURI(
        response.headers["content-disposition"].split(";")[1].split("=")[1]
      );
      const fileType =
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8";

      const blob = new Blob([fileData], { type: fileType });
      const downloadUrl = window.URL.createObjectURL(blob);

      const downloadLink = document.createElement("a");
      downloadLink.href = downloadUrl;
      downloadLink.download = fileName;

      document.body.appendChild(downloadLink);
      downloadLink.click();

      document.body.removeChild(downloadLink);
      window.URL.revokeObjectURL(downloadUrl);
    })
    .finally(() => {
      exportLoading.value = false;
    });
}

onMounted(async () => {
  // 默认选中部门树第一个根节点
  const deptOptions = await DeptAPI.getOptions();
  if (deptOptions && deptOptions.length > 0) {
    queryParams.deptId = Number(deptOptions[0].value);
  }
  handleQuery();
});
</script>

// dehaze-front-react/src/pages/system/user/index.tsx
import {
  DeptAPI,
  UserAPI,
  type DeptVO,
  type UserPageVO,
  type UserQuery,
} from "dehaze-sdk-js";
import { useDebounceFn } from "ahooks";
import {
  Button,
  Card,
  DatePicker,
  Dropdown,
  Empty,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Select,
  Space,
  Spin,
  Switch,
  Table,
  Tree,
  TreeSelect,
  Upload,
  type MenuProps,
  type TableColumnsType,
  type UploadFile,
} from "antd";
import {
  DeleteOutlined,
  DownOutlined,
  DownloadOutlined,
  EditOutlined,
  ExportOutlined,
  ImportOutlined,
  KeyOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UploadOutlined,
} from "@ant-design/icons";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import PasswordResetDialog, {
  type PasswordResetDialogRef,
} from "./components/PasswordResetDialog";
import UserFormDialog, {
  type UserFormDialogRef,
} from "./components/UserFormDialog";
import "./index.scss";

const { RangePicker } = DatePicker;

/** 递归转换部门数据为 Tree 组件需要的格式 */
function buildDeptTree(depts: DeptVO[]): any[] {
  return depts.map((dept) => ({
    title: dept.name,
    key: dept.id,
    children: dept.children?.length ? buildDeptTree(dept.children) : undefined,
  }));
}

/** 递归转换部门数据为 TreeSelect 组件需要的格式 */
function buildDeptTreeSelectData(depts: DeptVO[]): any[] {
  return depts.map((dept) => ({
    title: dept.name,
    value: dept.id,
    children: dept.children?.length
      ? buildDeptTreeSelectData(dept.children)
      : undefined,
  }));
}

/** 下载二进制数据为文件 */
function downloadBlob(data: ArrayBuffer, filename: string) {
  const blob = new Blob([data]);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const UserManagement: React.FC = () => {
  // ==================== 状态 ====================
  const [loading, setLoading] = useState(false);
  const [deptLoading, setDeptLoading] = useState(false);

  // 部门树
  const [deptList, setDeptList] = useState<DeptVO[]>([]);
  const [selectedDeptId, setSelectedDeptId] = useState<number | undefined>(
    undefined
  );

  // 查询参数
  const [queryParams, setQueryParams] = useState<UserQuery>({
    pageNum: 1,
    pageSize: 10,
  });

  // 表格数据
  const [userList, setUserList] = useState<UserPageVO[]>([]);
  const [total, setTotal] = useState(0);

  // 搜索表单
  const [searchForm] = Form.useForm();

  // 弹窗 ref
  const formDialogRef = useRef<UserFormDialogRef>(null);
  const passwordDialogRef = useRef<PasswordResetDialogRef>(null);

  // 选中行
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);

  // 刷新标记
  const [refreshFlag, setRefreshFlag] = useState(0);

  // 状态切换中的用户ID（用于Switch loading）
  const [statusUpdatingId, setStatusUpdatingId] = useState<number | undefined>(
    undefined
  );

  // 导出loading
  const [exportLoading, setExportLoading] = useState(false);

  // 导入弹窗
  const [importDialogVisible, setImportDialogVisible] = useState(false);
  const [importLoading, setImportLoading] = useState(false);
  const [importDeptId, setImportDeptId] = useState<number | undefined>(
    undefined
  );
  const [importFileList, setImportFileList] = useState<UploadFile[]>([]);

  // ==================== 数据加载 ====================

  /** 加载部门树 */
  const loadDeptTree = useCallback(async () => {
    setDeptLoading(true);
    try {
      const data = await DeptAPI.getList();
      setDeptList(data || []);
      // 默认选中第一个根部门
      if (data && data.length > 0) {
        const rootId = data[0].id;
        setSelectedDeptId(rootId);
        setQueryParams((prev) => ({
          ...prev,
          pageNum: 1,
          deptId: rootId,
        }));
      }
    } finally {
      setDeptLoading(false);
    }
  }, []);

  /** 加载用户列表 */
  const loadUserList = useCallback(async (params: UserQuery) => {
    setLoading(true);
    try {
      const result = await UserAPI.getPage(params);
      setUserList(result.list || []);
      setTotal(result.total || 0);
    } finally {
      setLoading(false);
    }
  }, []);

  // ==================== 副作用 ====================

  useEffect(() => {
    loadDeptTree();
  }, [loadDeptTree]);

  useEffect(() => {
    loadUserList(queryParams);
  }, [queryParams, refreshFlag]);

  // ==================== 通用刷新 ====================

  const refreshList = useCallback(() => {
    setRefreshFlag((prev) => prev + 1);
    setSelectedRowKeys([]);
  }, []);

  // ==================== 事件处理 ====================

  /** 点击部门树节点 */
  const handleDeptSelect = useCallback((selectedKeys: React.Key[]) => {
    const deptId =
      selectedKeys.length > 0 ? (selectedKeys[0] as number) : undefined;
    setSelectedDeptId(deptId);
    setSelectedRowKeys([]);
    setQueryParams((prev) => ({
      ...prev,
      pageNum: 1,
      deptId,
    }));
  }, []);

  /** 搜索 */
  const handleSearch = useCallback(
    (values: {
      keywords?: string;
      status?: number;
      dateRange?: [any, any];
    }) => {
      const startTime =
        values.dateRange?.[0]?.format?.("YYYY-MM-DD HH:mm:ss") ?? undefined;
      const endTime =
        values.dateRange?.[1]?.format?.("YYYY-MM-DD HH:mm:ss") ?? undefined;
      setSelectedRowKeys([]);
      setQueryParams((prev) => ({
        ...prev,
        pageNum: 1,
        keywords: values.keywords || undefined,
        status: values.status !== undefined ? values.status : undefined,
        startTime,
        endTime,
      }));
    },
    []
  );

  /** 搜索防抖：关键字输入时延时触发搜索 */
  const { run: debouncedSearch } = useDebounceFn(
    () => {
      const values = searchForm.getFieldsValue();
      handleSearch(values);
    },
    { wait: 300 }
  );

  /** 重置搜索 */
  const handleReset = useCallback(() => {
    searchForm.resetFields();
    setSelectedRowKeys([]);
    setQueryParams((prev) => ({
      pageNum: 1,
      pageSize: prev.pageSize,
      deptId: selectedDeptId,
    }));
  }, [searchForm, selectedDeptId]);

  /** 分页变化 */
  const handlePageChange = useCallback((page: number, pageSize: number) => {
    setSelectedRowKeys([]);
    setQueryParams((prev) => ({
      ...prev,
      pageNum: page,
      pageSize,
    }));
  }, []);

  /** 新增 */
  const handleAdd = useCallback(() => {
    formDialogRef.current?.open("add");
  }, []);

  /** 编辑 */
  const handleEdit = useCallback((record: UserPageVO) => {
    formDialogRef.current?.open("edit", { id: record.id });
  }, []);

  /** 单个删除 */
  const handleDelete = useCallback(
    (record: UserPageVO) => {
      UserAPI.deleteByIds(String(record.id))
        .then(() => {
          message.success(`用户「${record.username}」删除成功`);
          refreshList();
        })
        .catch((error) => {
          message.error(error?.message || "删除失败");
        });
    },
    [refreshList]
  );

  /** 批量删除 */
  const handleBatchDelete = useCallback(() => {
    Modal.confirm({
      title: "批量删除",
      content: `确认删除选中的 ${selectedRowKeys.length} 个用户吗？删除后不可恢复。`,
      okText: "确定",
      cancelText: "取消",
      okType: "danger",
      onOk: () => {
        return UserAPI.deleteByIds(selectedRowKeys.join(","))
          .then(() => {
            message.success(`成功删除 ${selectedRowKeys.length} 个用户`);
            refreshList();
          })
          .catch((error) => {
            message.error(error?.message || "删除失败");
            return Promise.reject(error);
          });
      },
    });
  }, [selectedRowKeys, refreshList]);

  /** 重置密码 */
  const handleResetPassword = useCallback((record: UserPageVO) => {
    passwordDialogRef.current?.open(record.id!, record.username!);
  }, []);

  /** 切换用户状态 */
  const handleStatusChange = useCallback(
    (record: UserPageVO, checked: boolean) => {
      const newStatus = checked ? 1 : 0;
      setStatusUpdatingId(record.id);
      UserAPI.updateStatus(record.id!, newStatus)
        .then(() => {
          message.success(
            `用户「${record.username}」已${checked ? "启用" : "禁用"}`
          );
          refreshList();
        })
        .catch((error) => {
          message.error(error?.message || "状态切换失败");
        })
        .finally(() => setStatusUpdatingId(undefined));
    },
    [refreshList]
  );

  /** 下载导入模板 */
  const handleDownloadTemplate = useCallback(async () => {
    try {
      const data = await UserAPI.downloadTemplate();
      downloadBlob(data, "用户导入模板.xlsx");
      message.success("模板下载成功");
    } catch (error: any) {
      message.error(error?.message || "模板下载失败");
    }
  }, []);

  /** 导出用户列表 */
  const handleExport = useCallback(async () => {
    setExportLoading(true);
    try {
      const data = await UserAPI.export(queryParams);
      downloadBlob(data, "用户列表.xlsx");
      message.success("导出成功");
    } catch (error: any) {
      message.error(error?.message || "导出失败");
    } finally {
      setExportLoading(false);
    }
  }, [queryParams]);

  /** 打开导入弹窗 */
  const handleOpenImport = useCallback(() => {
    setImportDeptId(selectedDeptId);
    setImportFileList([]);
    setImportDialogVisible(true);
  }, [selectedDeptId]);

  /** 提交导入 */
  const handleImportSubmit = useCallback(async () => {
    if (importDeptId === undefined) {
      message.warning("请选择所属部门");
      return;
    }
    const file = importFileList[0]?.originFileObj as File | undefined;
    if (!file) {
      message.warning("请选择Excel文件");
      return;
    }
    setImportLoading(true);
    try {
      await UserAPI.import(importDeptId, file);
      message.success("导入成功");
      setImportDialogVisible(false);
      refreshList();
    } catch (error: any) {
      message.error(error?.message || "导入失败");
    } finally {
      setImportLoading(false);
    }
  }, [importDeptId, importFileList, refreshList]);

  /** 导入下拉菜单点击 */
  const importMenuItems: MenuProps["items"] = useMemo(
    () => [
      { key: "template", label: "下载模板", icon: <DownloadOutlined /> },
      { key: "import", label: "导入数据", icon: <ImportOutlined /> },
    ],
    []
  );

  const handleImportMenuClick = useCallback(
    ({ key }: { key: string }) => {
      if (key === "template") {
        handleDownloadTemplate();
      } else if (key === "import") {
        handleOpenImport();
      }
    },
    [handleDownloadTemplate, handleOpenImport]
  );

  // ==================== 表格列定义 ====================

  const columns: TableColumnsType<UserPageVO> = useMemo(
    () => [
      {
        title: "编号",
        dataIndex: "id",
        key: "id",
        width: 100,
        align: "center",
      },
      {
        title: "用户名",
        dataIndex: "username",
        key: "username",
        width: 120,
        align: "center",
      },
      {
        title: "昵称",
        dataIndex: "nickname",
        key: "nickname",
        width: 120,
        align: "center",
      },
      {
        title: "性别",
        dataIndex: "genderLabel",
        key: "genderLabel",
        width: 80,
        align: "center",
      },
      {
        title: "部门",
        dataIndex: "deptName",
        key: "deptName",
        width: 120,
        align: "center",
      },
      {
        title: "手机号",
        dataIndex: "mobile",
        key: "mobile",
        width: 120,
        align: "center",
        render: (text: string) => text || "-",
      },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
        width: 80,
        align: "center",
        render: (status: number, record: UserPageVO) => (
          <Switch
            checked={status === 1}
            loading={statusUpdatingId === record.id}
            onChange={(checked) => handleStatusChange(record, checked)}
          />
        ),
      },
      {
        title: "创建时间",
        dataIndex: "createTime",
        key: "createTime",
        width: 180,
        align: "center",
      },
      {
        title: "操作",
        key: "action",
        width: 240,
        align: "center",
        fixed: "right",
        render: (_: unknown, record: UserPageVO) => (
          <Space size="small">
            <Button
              type="link"
              size="small"
              icon={<KeyOutlined />}
              onClick={() => handleResetPassword(record)}
            >
              重置密码
            </Button>
            <Button
              type="link"
              size="small"
              icon={<EditOutlined />}
              onClick={() => handleEdit(record)}
            >
              编辑
            </Button>
            <Popconfirm
              title={`确认删除用户「${record.username}」吗？删除后不可恢复。`}
              onConfirm={() => handleDelete(record)}
              okText="确定"
              cancelText="取消"
              okType="danger"
            >
              <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                删除
              </Button>
            </Popconfirm>
          </Space>
        ),
      },
    ],
    [
      handleEdit,
      handleDelete,
      handleResetPassword,
      handleStatusChange,
      statusUpdatingId,
    ]
  );

  /** 行选择配置 */
  const rowSelection = useMemo(
    () => ({
      selectedRowKeys,
      onChange: (keys: React.Key[]) => setSelectedRowKeys(keys),
    }),
    [selectedRowKeys]
  );

  // ==================== 渲染 ====================

  return (
    <div className="user-management-container">
      {/* 左侧部门树 */}
      <Card className="dept-tree-card" size="small" title="部门列表">
        {deptLoading ? (
          <div className="dept-tree-loading">
            <Spin />
          </div>
        ) : deptList.length === 0 ? (
          <Empty description="暂无部门数据" />
        ) : (
          <Tree
            treeData={buildDeptTree(deptList)}
            selectedKeys={selectedDeptId ? [selectedDeptId] : []}
            onSelect={handleDeptSelect}
            defaultExpandAll
            blockNode
          />
        )}
      </Card>

      {/* 右侧用户列表区域 */}
      <div className="user-list-area">
        {/* 搜索区域 */}
        <Card className="search-card" size="small">
          <Form
            form={searchForm}
            layout="inline"
            onFinish={handleSearch}
            onValuesChange={(changed) => {
              // 关键字输入时触发防抖搜索
              if ("keywords" in changed) {
                debouncedSearch();
              }
            }}
          >
            <Form.Item name="keywords" label="关键字">
              <Input
                placeholder="用户名/昵称/手机号"
                allowClear
                style={{ width: 220 }}
              />
            </Form.Item>
            <Form.Item name="status" label="状态">
              <Select
                placeholder="全部"
                allowClear
                style={{ width: 120 }}
                options={[
                  { value: 1, label: "启用" },
                  { value: 0, label: "禁用" },
                ]}
              />
            </Form.Item>
            <Form.Item name="dateRange" label="创建时间">
              <RangePicker
                showTime
                placeholder={["开始时间", "截止时间"]}
                style={{ width: 360 }}
              />
            </Form.Item>
            <Form.Item>
              <Space>
                <Button
                  type="primary"
                  htmlType="submit"
                  icon={<SearchOutlined />}
                >
                  搜索
                </Button>
                <Button
                  htmlType="reset"
                  icon={<ReloadOutlined />}
                  onClick={handleReset}
                >
                  重置
                </Button>
                <Button
                  type="primary"
                  icon={<PlusOutlined />}
                  onClick={handleAdd}
                >
                  新增
                </Button>
                <Button
                  danger
                  icon={<DeleteOutlined />}
                  disabled={selectedRowKeys.length === 0}
                  onClick={handleBatchDelete}
                >
                  删除
                </Button>
                {/* 导入下拉菜单 */}
                <Dropdown
                  menu={{
                    items: importMenuItems,
                    onClick: handleImportMenuClick,
                  }}
                >
                  <Button icon={<ImportOutlined />}>
                    导入 <DownOutlined />
                  </Button>
                </Dropdown>
                {/* 导出 */}
                <Button
                  icon={<ExportOutlined />}
                  loading={exportLoading}
                  onClick={handleExport}
                >
                  导出
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>

        {/* 表格区域 */}
        <Card className="table-card" size="small">
          <Table
            rowSelection={rowSelection}
            columns={columns}
            dataSource={userList}
            rowKey={(record) => record.id ?? Math.random()}
            loading={loading}
            scroll={{ x: 1280 }}
            pagination={{
              current: queryParams.pageNum,
              pageSize: queryParams.pageSize,
              total,
              showSizeChanger: true,
              showQuickJumper: true,
              pageSizeOptions: ["10", "20", "50", "100"],
              showTotal: (t) => `共 ${t} 条`,
              onChange: handlePageChange,
            }}
          />
        </Card>
      </div>

      {/* 新增/编辑弹窗 */}
      <UserFormDialog ref={formDialogRef} onSuccess={refreshList} />

      {/* 密码重置弹窗 */}
      <PasswordResetDialog ref={passwordDialogRef} onSuccess={refreshList} />

      {/* 导入弹窗 */}
      <Modal
        title="导入用户"
        open={importDialogVisible}
        confirmLoading={importLoading}
        onOk={handleImportSubmit}
        onCancel={() => setImportDialogVisible(false)}
        okText="确定"
        cancelText="取消"
        destroyOnHidden
      >
        <Form layout="vertical">
          <Form.Item label="所属部门" required>
            <TreeSelect
              treeData={buildDeptTreeSelectData(deptList)}
              value={importDeptId}
              onChange={(value: number) => setImportDeptId(value)}
              placeholder="请选择部门"
              allowClear
              treeDefaultExpandAll
            />
          </Form.Item>
          <Form.Item label="Excel文件" required>
            <Upload
              accept=".xls,.xlsx"
              maxCount={1}
              fileList={importFileList}
              beforeUpload={(file) => {
                setImportFileList([
                  {
                    uid: file.uid,
                    name: file.name,
                    status: "done",
                    originFileObj: file,
                  } as UploadFile,
                ]);
                return false;
              }}
              onRemove={() => setImportFileList([])}
            >
              <Button icon={<UploadOutlined />}>选择文件</Button>
            </Upload>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default UserManagement;
