// dehaze-uniapp/src/layout/Sidebar.vue
<template>
  <!-- 遮罩层 -->
  <view
    v-if="visible"
    class="sidebar-overlay"
    :class="{ active: visible }"
    @click="closeSidebar"
  />

  <!-- 侧边栏面板 -->
  <view class="sidebar-panel" :class="{ active: visible }">
    <!-- 头部 -->
    <view class="sidebar-header">
      <view class="header-content">
        <view class="logo-wrapper">
          <u-icon name="cloud-fill" color="#fff" size="24" />
        </view>
        <view class="header-text">
          <text class="app-name">图像去雾系统</text>
          <text class="app-desc">功能菜单</text>
        </view>
      </view>
      <view class="close-btn" @click="closeSidebar">
        <u-icon name="close" size="20" color="#fff" />
      </view>
    </view>

    <!-- 菜单内容 -->
    <scroll-view class="sidebar-content" scroll-y>
      <!-- 首页 -->
      <view
        class="menu-item"
        :class="{ active: isActive(homeItem.route) }"
        @click="navigateTo(homeItem.route)"
      >
        <u-icon
          :name="
            isActive(homeItem.route)
              ? homeItem.activeIcon || homeItem.icon
              : homeItem.icon
          "
          size="20"
          :color="isActive(homeItem.route) ? '#3b82f6' : '#6b7280'"
        />
        <text class="menu-title">{{ homeItem.title }}</text>
      </view>

      <view class="menu-divider" />

      <!-- 分组菜单 -->
      <view
        v-for="section in menuSections"
        :key="section.title"
        class="menu-section"
      >
        <view class="section-header">
          <u-icon
            v-if="section.icon"
            :name="section.icon"
            size="14"
            color="#9ca3af"
          />
          <text class="section-title">{{ section.title }}</text>
        </view>
        <view
          v-for="item in section.items"
          :key="item.route"
          class="menu-item"
          :class="{ active: isActive(item.route) }"
          @click="navigateTo(item.route)"
        >
          <u-icon
            :name="
              isActive(item.route) ? item.activeIcon || item.icon : item.icon
            "
            size="20"
            :color="isActive(item.route) ? '#3b82f6' : '#6b7280'"
          />
          <text class="menu-title">{{ item.title }}</text>
          <view v-if="item.badge" class="menu-badge">{{ item.badge }}</view>
          <view v-if="item.isNew" class="menu-new">NEW</view>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<script lang="ts" setup>
import { homeItem, menuSections, isTabBarPage } from "@/config/menu";

interface Props {
  /** 侧边栏是否可见 */
  visible: boolean;
  /** 当前路由 */
  currentRoute?: string;
}

interface Emits {
  (e: "close"): void;
  (e: "navigate", route: string): void;
}

const props = withDefaults(defineProps<Props>(), {
  currentRoute: "/pages/home/index",
});

const emit = defineEmits<Emits>();

/** 判断是否为当前激活路由 */
const isActive = (route: string) => props.currentRoute === route;

/** 关闭侧边栏 */
const closeSidebar = () => {
  emit("close");
};

/** 导航到指定路由 */
const navigateTo = (route: string) => {
  emit("navigate", route);
  closeSidebar();

  // 判断是否为 tabBar 页面
  if (isTabBarPage(route)) {
    uni.switchTab({ url: route });
  } else {
    uni.navigateTo({
      url: route,
      fail: () => {
        uni.showToast({ title: "页面开发中", icon: "none" });
      },
    });
  }
};
</script>

<style lang="scss" scoped>
.sidebar-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: 998;
  opacity: 0;
  visibility: hidden;
  transition: all 0.3s ease;

  &.active {
    opacity: 1;
    visibility: visible;
  }
}

.sidebar-panel {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  width: 560rpx;
  max-width: 85vw;
  background: #ffffff;
  z-index: 999;
  transform: translateX(100%);
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: -8rpx 0 32rpx rgba(0, 0, 0, 0.1);
  display: flex;
  flex-direction: column;

  &.active {
    transform: translateX(0);
  }
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 48rpx 32rpx 32rpx;
  background: linear-gradient(135deg, #3b82f6 0%, #6366f1 100%);
  // 适配状态栏
  padding-top: calc(48rpx + constant(safe-area-inset-top));
  padding-top: calc(48rpx + env(safe-area-inset-top));
}

.header-content {
  display: flex;
  align-items: center;
  gap: 20rpx;
}

.logo-wrapper {
  width: 80rpx;
  height: 80rpx;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 20rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.header-text {
  display: flex;
  flex-direction: column;
  gap: 4rpx;
}

.app-name {
  font-size: 36rpx;
  font-weight: 700;
  color: #ffffff;
}

.app-desc {
  font-size: 24rpx;
  color: rgba(255, 255, 255, 0.8);
}

.close-btn {
  width: 64rpx;
  height: 64rpx;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;

  &:active {
    background: rgba(255, 255, 255, 0.3);
  }
}

.sidebar-content {
  flex: 1;
  padding: 24rpx 0;
  // 适配底部安全区
  padding-bottom: calc(24rpx + constant(safe-area-inset-bottom));
  padding-bottom: calc(24rpx + env(safe-area-inset-bottom));
}

.menu-divider {
  height: 2rpx;
  background: #e5e7eb;
  margin: 16rpx 24rpx;
}

.menu-section {
  margin-bottom: 16rpx;
}

.section-header {
  display: flex;
  align-items: center;
  gap: 12rpx;
  padding: 16rpx 32rpx;
}

.section-title {
  font-size: 24rpx;
  font-weight: 600;
  color: #9ca3af;
  text-transform: uppercase;
  letter-spacing: 1rpx;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 24rpx;
  padding: 24rpx 32rpx;
  margin: 4rpx 16rpx;
  border-radius: 20rpx;
  transition: all 0.2s;

  &:active {
    background: #f3f4f6;
  }

  &.active {
    background: rgba(59, 130, 246, 0.1);

    .menu-title {
      color: #3b82f6;
      font-weight: 600;
    }
  }
}

.menu-title {
  flex: 1;
  font-size: 30rpx;
  color: #374151;
}

.menu-badge {
  padding: 4rpx 16rpx;
  background: #3b82f6;
  border-radius: 20rpx;
  font-size: 22rpx;
  color: #ffffff;
  font-weight: 600;
}

.menu-new {
  padding: 4rpx 12rpx;
  background: linear-gradient(135deg, #f59e0b 0%, #ef4444 100%);
  border-radius: 8rpx;
  font-size: 18rpx;
  color: #ffffff;
  font-weight: 700;
}
</style>

// dehaze-taro/src/layout/sidebar/index.tsx
/**
 * 侧边菜单组件
 */
import React from 'react';
import { View, Text, ScrollView } from '@tarojs/components';
import Taro from '@tarojs/taro';
import { Popup } from '@taroify/core';
import { Cross, EyeOutlined } from '@taroify/icons';
import { homeItem, menuSections, isTabBarPage, type MenuItem } from '@/config/menu';
import './index.less';

interface AppSidebarProps {
  /** 侧边栏是否可见 */
  visible: boolean;
  /** 当前路由 */
  currentRoute?: string;
  /** 关闭回调 */
  onClose: () => void;
  /** 导航回调 */
  onNavigate?: (route: string) => void;
}

const AppSidebar: React.FC<AppSidebarProps> = ({
  visible,
  currentRoute = '/pages/home/index',
  onClose,
  onNavigate,
}) => {
  /** 判断是否为当前激活路由 */
  const isActive = (route: string) => currentRoute === route;

  /** 导航到指定路由 */
  const navigateTo = (route: string) => {
    onNavigate?.(route);
    onClose();

    // 判断是否为 tabBar 页面
    if (isTabBarPage(route)) {
      Taro.switchTab({ url: route });
    } else {
      Taro.navigateTo({
        url: route,
        fail: () => {
          Taro.showToast({ title: '页面开发中', icon: 'none' });
        },
      });
    }
  };

  /** 渲染菜单项 */
  const renderMenuItem = (item: MenuItem) => (
    <View
      key={item.route}
      className={`menu-item ${isActive(item.route) ? 'active' : ''}`}
      onClick={() => navigateTo(item.route)}
    >
      <Text className='menu-title'>{item.title}</Text>
      {item.badge && <View className='menu-badge'>{item.badge}</View>}
      {item.isNew && <View className='menu-new'>NEW</View>}
    </View>
  );

  return (
    <Popup
      open={visible}
      placement='right'
      style={{ width: '70vw', maxWidth: '280px' }}
      onClose={onClose}
    >
      <View className='sidebar-container'>
        {/* 头部 */}
        <View className='sidebar-header'>
          <View className='header-content'>
            <View className='logo-wrapper'>
              <EyeOutlined size='18' color='#ffffff' />
            </View>
            <View className='header-text'>
              <Text className='app-name'>图像去雾系统</Text>
              <Text className='app-desc'>功能菜单</Text>
            </View>
          </View>
          <View className='close-btn' onClick={onClose}>
            <Cross size='16' color='#fff' />
          </View>
        </View>

        {/* 菜单内容 */}
        <ScrollView className='sidebar-content' scrollY>
          {/* 首页 */}
          {renderMenuItem(homeItem)}

          <View className='menu-divider' />

          {/* 分组菜单 */}
          {menuSections.map((section) => (
            <View key={section.title} className='menu-section'>
              <View className='section-header'>
                <Text className='section-title'>{section.title}</Text>
              </View>
              {section.items.map(renderMenuItem)}
            </View>
          ))}
        </ScrollView>
      </View>
    </Popup>
  );
};

export default AppSidebar;
