// dehaze-front-vue/src/components/ImportExportToolbar/ImportDialog.vue
<script lang="ts" setup>
import { ImportModule, ImportResult } from "dehaze-sdk-js";
import { UploadFilled, Download } from "@element-plus/icons-vue";
import type { UploadFile, UploadInstance, UploadRawFile } from "element-plus";
import { genFileId } from "element-plus";
import { useImportExport } from "@/composables/useImportExport";
import ImportResultPanel from "./ImportResultPanel.vue";

defineOptions({
  name: "ImportDialog",
});

const props = defineProps<{
  modelValue: boolean;
  module: ImportModule;
  extraImportParams?: Record<string, unknown>;
}>();

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
  (e: "import-complete"): void;
  (e: "async-task-created", taskId: string): void;
}>();

const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});

const moduleRef = computed(() => props.module);
const queryParamsRef = ref<Record<string, any>>({});
const extraImportParamsRef = computed(() => props.extraImportParams);

const { importLoading, downloadTemplate, importData } = useImportExport({
  module: moduleRef,
  queryParams: queryParamsRef,
  extraImportParams: extraImportParamsRef,
});

const uploadRef = ref<UploadInstance>();
const selectedFile = ref<File>();
const importMode = ref<"all" | "partial">("all");
const syncResult = ref<ImportResult | null>(null);
const asyncTaskId = ref<string | null>(null);

const MAX_FILE_SIZE = 20 * 1024 * 1024;
const ACCEPT_EXTENSIONS = [".xlsx", ".xls", ".csv"];

const dialogTitle = computed(() => `导入${moduleLabel(props.module)}`);

function moduleLabel(m: ImportModule): string {
  const map: Record<ImportModule, string> = {
    user: "用户",
    role: "角色",
    dept: "部门",
    menu: "菜单",
    dict: "字典",
    algorithm: "算法",
  };
  return map[m] ?? m;
}

function resetState() {
  selectedFile.value = undefined;
  importMode.value = "all";
  syncResult.value = null;
  asyncTaskId.value = null;
  uploadRef.value?.clearFiles();
}

function handleClose() {
  resetState();
  visible.value = false;
}

function validateFile(file: File): string | null {
  const ext = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
  if (!ACCEPT_EXTENSIONS.includes(ext)) {
    return "仅支持 .xlsx、.xls、.csv 格式文件";
  }
  if (file.size > MAX_FILE_SIZE) {
    return "文件大小不能超过 20MB";
  }
  return null;
}

function handleFileChange(uploadFile: UploadFile) {
  if (!uploadFile.raw) return;
  const error = validateFile(uploadFile.raw);
  if (error) {
    ElMessage.warning(error);
    uploadRef.value?.clearFiles();
    return;
  }
  selectedFile.value = uploadFile.raw;
  syncResult.value = null;
  asyncTaskId.value = null;
}

function handleFileExceed(files: File[]) {
  if (files.length === 0) return;
  uploadRef.value?.clearFiles();
  const file = files[0] as UploadRawFile;
  file.uid = genFileId();
  uploadRef.value?.handleStart(file);
  const error = validateFile(file);
  if (error) {
    ElMessage.warning(error);
    return;
  }
  selectedFile.value = file;
}

async function handleDownloadTemplate(format: "excel" | "csv") {
  await downloadTemplate(format);
}

async function handleSubmit() {
  if (!selectedFile.value) {
    ElMessage.warning("请先选择文件");
    return;
  }
  try {
    const result = await importData(selectedFile.value, importMode.value);
    if (result.isAsync) {
      asyncTaskId.value = result.taskId;
      ElMessage.success("数据量较大，已创建导入任务，可在任务列表查看进度");
      emit("async-task-created", result.taskId);
      emit("import-complete");
      handleClose();
    } else {
      syncResult.value = result.result;
      ElMessage.success("导入完成");
      emit("import-complete");
    }
  } catch (e: any) {
    ElMessage.error(e.message || "导入失败");
  }
}

const canSubmit = computed(() => !!selectedFile.value && !importLoading.value);
</script>

<template>
  <el-dialog
    v-model="visible"
    :title="dialogTitle"
    width="640px"
    :close-on-click-modal="false"
    append-to-body
    @close="handleClose"
  >
    <div v-if="!syncResult && !asyncTaskId" class="import-form">
      <el-form label-width="100px">
        <el-form-item label="导入模式">
          <el-radio-group v-model="importMode">
            <el-radio value="all">全量导入</el-radio>
            <el-radio value="partial">部分导入</el-radio>
          </el-radio-group>
          <div class="mode-tip">
            {{
              importMode === "all"
                ? "全量导入：覆盖更新已存在的记录，新增不存在的记录"
                : "部分导入：仅新增不存在的记录，已存在的记录跳过"
            }}
          </div>
        </el-form-item>

        <el-form-item label="下载模板">
          <el-button
            plain
            size="small"
            @click="handleDownloadTemplate('excel')"
          >
            <el-icon><Download /></el-icon>
            Excel 模板
          </el-button>
          <el-button
            plain
            size="small"
            class="ml-2"
            @click="handleDownloadTemplate('csv')"
          >
            <el-icon><Download /></el-icon>
            CSV 模板
          </el-button>
        </el-form-item>

        <el-form-item label="数据文件">
          <el-upload
            ref="uploadRef"
            :auto-upload="false"
            :limit="1"
            :on-change="handleFileChange"
            :on-exceed="handleFileExceed"
            :show-file-list="true"
            accept=".xlsx,.xls,.csv"
            action="#"
            drag
            class="upload-area"
          >
            <el-icon class="el-icon--upload"><UploadFilled /></el-icon>
            <div class="el-upload__text">
              将文件拖到此处，或<em>点击上传</em>
            </div>
            <template #tip>
              <div class="upload-tip">
                支持 .xlsx、.xls、.csv 格式，文件大小 ≤ 20MB
              </div>
            </template>
          </el-upload>
        </el-form-item>
      </el-form>
    </div>

    <ImportResultPanel v-else-if="syncResult" :result="syncResult" />

    <el-result
      v-else-if="asyncTaskId"
      icon="info"
      title="已创建导入任务"
      sub-title="数据量较大，已转为异步任务，可在任务列表查看进度"
    />

    <template #footer>
      <el-button @click="handleClose">
        {{ syncResult || asyncTaskId ? "关闭" : "取消" }}
      </el-button>
      <el-button
        v-if="!syncResult && !asyncTaskId"
        type="primary"
        :loading="importLoading"
        :disabled="!canSubmit"
        @click="handleSubmit"
      >
        确定导入
      </el-button>
    </template>
  </el-dialog>
</template>

<style lang="scss" scoped>
.import-form {
  .mode-tip {
    margin-top: 4px;
    font-size: 12px;
    color: var(--el-text-color-secondary);
  }
}

.upload-area {
  width: 100%;
}

.upload-tip {
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>

// dehaze-front-react/src/components/ImportExportToolbar/ImportDialog.tsx
import { downloadBlob, useImportExport } from "@/hooks/useImportExport";
import {
  DownloadOutlined,
  InboxOutlined,
  UploadOutlined,
} from "@ant-design/icons";
import {
  Alert,
  Button,
  Modal,
  Radio,
  Space,
  Statistic,
  Table,
  Typography,
  Upload,
  type UploadFile,
  type UploadProps,
  message,
} from "antd";
import React, { useMemo, useState } from "react";
import type { ImportError, ImportModule, ImportResult } from "dehaze-sdk-js";
import { MODULE_LABEL_MAP } from "./types";

const { Dragger } = Upload;
const { Text } = Typography;

const MAX_FILE_SIZE = 20 * 1024 * 1024;
const ACCEPT_EXTENSIONS = [".xlsx", ".xls", ".csv"];

interface ImportDialogProps {
  open: boolean;
  module: ImportModule;
  extraImportParams?: Record<string, unknown>;
  onClose: () => void;
  onImportComplete: () => void;
}

const ImportDialog: React.FC<ImportDialogProps> = ({
  open,
  module,
  extraImportParams,
  onClose,
  onImportComplete,
}) => {
  const { importLoading, downloadTemplate, importData } = useImportExport({
    module: module,
    queryParams: {},
    extraImportParams,
  });

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [importMode, setImportMode] = useState<"all" | "partial">("all");
  const [syncResult, setSyncResult] = useState<ImportResult | null>(null);
  const [asyncTaskId, setAsyncTaskId] = useState<string | null>(null);
  const [errorReportLoading, setErrorReportLoading] = useState(false);

  const dialogTitle = `导入${MODULE_LABEL_MAP[module] ?? module}`;

  const resetState = () => {
    setSelectedFile(null);
    setImportMode("all");
    setSyncResult(null);
    setAsyncTaskId(null);
  };

  const handleClose = () => {
    resetState();
    onClose();
  };

  const validateFile = (file: File): string | null => {
    const ext = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
    if (!ACCEPT_EXTENSIONS.includes(ext)) {
      return "仅支持 .xlsx、.xls、.csv 格式文件";
    }
    if (file.size > MAX_FILE_SIZE) {
      return "文件大小不能超过 20MB";
    }
    return null;
  };

  const draggerProps: UploadProps = {
    accept: ".xlsx,.xls,.csv",
    multiple: false,
    maxCount: 1,
    fileList: selectedFile
      ? [
          {
            uid: selectedFile.name,
            name: selectedFile.name,
            status: "done",
          } as UploadFile,
        ]
      : [],
    beforeUpload: (file) => {
      const error = validateFile(file);
      if (error) {
        message.warning(error);
        setSelectedFile(null);
        return Upload.LIST_IGNORE;
      }
      setSelectedFile(file);
      setSyncResult(null);
      setAsyncTaskId(null);
      return false;
    },
    onRemove: () => {
      setSelectedFile(null);
    },
  };

  const handleDownloadTemplate = (format: "excel" | "csv") => {
    downloadTemplate(format);
  };

  const handleSubmit = async () => {
    if (!selectedFile) {
      message.warning("请先选择文件");
      return;
    }
    try {
      const result = await importData(selectedFile, importMode);
      if (result.isAsync) {
        setAsyncTaskId(result.taskId);
        message.success("数据量较大，已创建导入任务，可在任务列表查看进度");
        onImportComplete();
      } else {
        setSyncResult(result.result);
        message.success("导入完成");
        onImportComplete();
      }
    } catch (error: unknown) {
      message.error((error as Error)?.message || "导入失败");
    }
  };

  const handleDownloadErrorReport = async () => {
    if (!syncResult?.errorReportUrl) {
      message.warning("无错误报告可下载");
      return;
    }
    setErrorReportLoading(true);
    try {
      const res = await fetch(syncResult.errorReportUrl);
      if (!res.ok) throw new Error("下载失败");
      const blob = await res.blob();
      downloadBlob(blob, "import_error_report.xlsx");
    } catch (error: unknown) {
      message.error((error as Error)?.message || "错误报告下载失败");
    } finally {
      setErrorReportLoading(false);
    }
  };

  const errorColumns = useMemo(
    () => [
      {
        title: "行号",
        dataIndex: "row",
        key: "row",
        width: 80,
        align: "center" as const,
      },
      { title: "字段", dataIndex: "field", key: "field", width: 140 },
      {
        title: "错误信息",
        dataIndex: "message",
        key: "message",
        ellipsis: true,
      },
    ],
    []
  );

  const hasErrors = !!syncResult && syncResult.failureCount > 0;

  return (
    <Modal
      title={dialogTitle}
      open={open}
      onCancel={handleClose}
      width={640}
      destroyOnHidden
      footer={
        <Space>
          <Button onClick={handleClose}>
            {syncResult || asyncTaskId ? "关闭" : "取消"}
          </Button>
          {!syncResult && !asyncTaskId && (
            <Button
              type="primary"
              icon={<UploadOutlined />}
              loading={importLoading}
              disabled={!selectedFile}
              onClick={handleSubmit}
            >
              确定导入
            </Button>
          )}
        </Space>
      }
    >
      {!syncResult && !asyncTaskId && (
        <Space direction="vertical" size="middle" style={{ width: "100%" }}>
          <div>
            <Text strong>导入模式</Text>
            <Radio.Group
              value={importMode}
              onChange={(e) => setImportMode(e.target.value)}
              style={{ marginLeft: 12 }}
            >
              <Radio value="all">全量导入</Radio>
              <Radio value="partial">部分导入</Radio>
            </Radio.Group>
            <div style={{ marginTop: 4 }}>
              <Text type="secondary" style={{ fontSize: 12 }}>
                {importMode === "all"
                  ? "全量导入：覆盖更新已存在的记录，新增不存在的记录"
                  : "部分导入：仅新增不存在的记录，已存在的记录跳过"}
              </Text>
            </div>
          </div>

          <div>
            <Text strong>下载模板</Text>
            <Space style={{ marginLeft: 12 }}>
              <Button
                size="small"
                icon={<DownloadOutlined />}
                onClick={() => handleDownloadTemplate("excel")}
              >
                Excel 模板
              </Button>
              <Button
                size="small"
                icon={<DownloadOutlined />}
                onClick={() => handleDownloadTemplate("csv")}
              >
                CSV 模板
              </Button>
            </Space>
          </div>

          <Dragger {...draggerProps} style={{ padding: 16 }}>
            <p className="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p className="ant-upload-text">将文件拖到此处，或点击上传</p>
            <p className="ant-upload-hint">
              支持 .xlsx、.xls、.csv 格式，文件大小 ≤ 20MB
            </p>
          </Dragger>
        </Space>
      )}

      {syncResult && (
        <Space direction="vertical" size="middle" style={{ width: "100%" }}>
          <Alert
            type={hasErrors ? "warning" : "success"}
            message={
              hasErrors
                ? `导入完成，${syncResult.failureCount} 条数据失败`
                : "导入完成"
            }
            showIcon
          />
          <Space
            size="large"
            style={{ justifyContent: "space-around", width: "100%" }}
          >
            <Statistic title="总行数" value={syncResult.totalRows} />
            <Statistic
              title="成功"
              value={syncResult.successCount}
              valueStyle={{ color: "#3f8600" }}
            />
            <Statistic
              title="失败"
              value={syncResult.failureCount}
              valueStyle={{ color: "#cf1322" }}
            />
            <Statistic
              title="跳过"
              value={syncResult.skippedCount}
              valueStyle={{ color: "#d48806" }}
            />
          </Space>
          {syncResult.errorReportUrl && (
            <div style={{ textAlign: "center" }}>
              <Button
                type="primary"
                ghost
                icon={<DownloadOutlined />}
                loading={errorReportLoading}
                onClick={handleDownloadErrorReport}
              >
                下载错误报告
              </Button>
            </div>
          )}
          {syncResult.errors && syncResult.errors.length > 0 && (
            <Table<ImportError>
              columns={errorColumns}
              dataSource={syncResult.errors}
              rowKey={(record, index) => `${record.row}-${index}`}
              size="small"
              pagination={{ pageSize: 5 }}
              scroll={{ y: 240 }}
            />
          )}
        </Space>
      )}

      {asyncTaskId && (
        <Alert
          type="info"
          message="已创建导入任务"
          description="数据量较大，已转为异步任务，可在任务列表查看进度"
          showIcon
        />
      )}
    </Modal>
  );
};

export default ImportDialog;
