// dehaze-front-vue/src/components/ImportExportToolbar/TaskListDrawer.vue
<script lang="ts" setup>
import { ExportModule, TaskVO } from "dehaze-sdk-js";
import { useTaskStore } from "@/store";

defineOptions({
  name: "TaskListDrawer",
});

const props = defineProps<{
  modelValue: boolean;
  module?: ExportModule;
}>();

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
}>();

const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});

const taskStore = useTaskStore();

const statusFilter = ref("");
const categoryFilter = ref<"import" | "export" | "">("");

const POLLING_STATUSES = ["PENDING", "PROCESSING"];

const statusLabel: Record<string, string> = {
  PENDING: "待执行",
  PROCESSING: "执行中",
  COMPLETED: "已完成",
  FAILED: "失败",
  CANCELLED: "已取消",
};

const statusTagType: Record<
  string,
  "info" | "primary" | "success" | "danger" | "warning"
> = {
  PENDING: "info",
  PROCESSING: "primary",
  COMPLETED: "success",
  FAILED: "danger",
  CANCELLED: "warning",
};

const taskTypeLabel: Record<string, string> = {
  dataset_export: "数据集导出",
  user_export: "用户导出",
  role_export: "角色导出",
  dept_export: "部门导出",
  menu_export: "菜单导出",
  dict_export: "字典导出",
  algorithm_export: "算法导出",
  user_import: "用户导入",
  role_import: "角色导入",
  dept_import: "部门导入",
  menu_import: "菜单导入",
  dict_import: "字典导入",
  algorithm_import: "算法导入",
};

const queryParams = reactive({
  pageNum: 1,
  pageSize: 10,
});

const downloadLoadingId = ref<string | null>(null);
const cancelLoadingId = ref<string | null>(null);

function buildTaskTypeFilter(): string | undefined {
  if (props.module) {
    return [`${props.module}_export`, `${props.module}_import`].join(",");
  }
  return undefined;
}

async function loadTaskList() {
  const query: any = {
    ...queryParams,
    status: statusFilter.value || undefined,
    taskCategory: categoryFilter.value || undefined,
    taskType: buildTaskTypeFilter(),
  };
  try {
    await taskStore.getTaskList(query);
  } catch (e: any) {
    ElMessage.error(e.message || "加载任务列表失败");
    return;
  }
  const hasActiveTasks = taskStore.taskList.some((t) =>
    POLLING_STATUSES.includes(t.status)
  );
  if (hasActiveTasks) {
    taskStore.startPolling();
  } else {
    taskStore.stopPolling();
  }
}

function handleFilterChange() {
  queryParams.pageNum = 1;
  loadTaskList();
}

function canCancel(status: string): boolean {
  return POLLING_STATUSES.includes(status);
}

function progressStatus(
  status: string
): "" | "success" | "exception" | "warning" {
  if (status === "COMPLETED") return "success";
  if (status === "FAILED") return "exception";
  if (status === "CANCELLED") return "warning";
  return "";
}

function formatTime(t?: string): string {
  if (!t) return "-";
  return new Date(t).toLocaleString("zh-CN");
}

async function handleCancel(task: TaskVO) {
  try {
    await ElMessageBox.confirm("确认取消该任务吗？", "提示", {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    });
  } catch {
    return;
  }
  cancelLoadingId.value = task.taskId;
  try {
    await taskStore.cancelTask(task.taskId);
    ElMessage.success("任务已取消");
    await loadTaskList();
  } catch (e: any) {
    ElMessage.error(e.message || "取消任务失败");
  } finally {
    cancelLoadingId.value = null;
  }
}

async function handleDownload(task: TaskVO) {
  downloadLoadingId.value = task.taskId;
  try {
    await taskStore.downloadResult(task.taskId);
    ElMessage.success("开始下载");
  } catch (e: any) {
    ElMessage.error(e.message || "下载失败");
  } finally {
    downloadLoadingId.value = null;
  }
}

function handleVisibilityChange() {
  if (document.hidden) {
    taskStore.stopPolling();
  } else {
    const hasActiveTasks = taskStore.taskList.some((t) =>
      POLLING_STATUSES.includes(t.status)
    );
    if (hasActiveTasks) {
      taskStore.startPolling();
    }
  }
}

watch(visible, (val) => {
  if (val) {
    loadTaskList();
    document.addEventListener("visibilitychange", handleVisibilityChange);
  } else {
    taskStore.stopPolling();
    document.removeEventListener("visibilitychange", handleVisibilityChange);
  }
});

onUnmounted(() => {
  taskStore.stopPolling();
  document.removeEventListener("visibilitychange", handleVisibilityChange);
});
</script>

<template>
  <el-drawer
    v-model="visible"
    :title="
      module
        ? `${taskTypeLabel[module + '_export']?.replace('导出', '')}任务列表`
        : '任务列表'
    "
    size="900px"
    append-to-body
  >
    <div class="drawer-content">
      <div class="filter-bar">
        <el-radio-group v-model="categoryFilter" @change="handleFilterChange">
          <el-radio-button value="">全部</el-radio-button>
          <el-radio-button value="import">导入</el-radio-button>
          <el-radio-button value="export">导出</el-radio-button>
        </el-radio-group>
        <el-select
          v-model="statusFilter"
          placeholder="任务状态"
          clearable
          class="status-select"
          @change="handleFilterChange"
        >
          <el-option label="待执行" value="PENDING" />
          <el-option label="执行中" value="PROCESSING" />
          <el-option label="已完成" value="COMPLETED" />
          <el-option label="失败" value="FAILED" />
          <el-option label="已取消" value="CANCELLED" />
        </el-select>
        <el-button @click="loadTaskList">刷新</el-button>
      </div>

      <el-table
        v-loading="taskStore.loading"
        :data="taskStore.taskList"
        border
        empty-text="暂无任务"
      >
        <el-table-column
          label="任务ID"
          prop="taskId"
          width="260"
          show-overflow-tooltip
        />
        <el-table-column label="类型" width="120" align="center">
          <template #default="{ row }">
            {{ taskTypeLabel[row.taskType] ?? row.taskType }}
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100" align="center">
          <template #default="{ row }">
            <el-tag :type="statusTagType[row.status] || 'info'">
              {{ statusLabel[row.status] ?? row.status }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="进度" min-width="200">
          <template #default="{ row }">
            <el-progress
              :percentage="row.progress"
              :status="progressStatus(row.status)"
              :stroke-width="14"
              :text-inside="true"
            />
          </template>
        </el-table-column>
        <el-table-column label="创建时间" width="170" align="center">
          <template #default="{ row }">
            {{ formatTime(row.createdAt) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="170" align="center" fixed="right">
          <template #default="{ row }">
            <el-button
              v-if="canCancel(row.status)"
              type="warning"
              link
              :loading="cancelLoadingId === row.taskId"
              @click="handleCancel(row as TaskVO)"
            >
              取消
            </el-button>
            <el-button
              v-if="row.status === 'COMPLETED'"
              type="success"
              link
              :loading="downloadLoadingId === row.taskId"
              @click="handleDownload(row as TaskVO)"
            >
              下载
            </el-button>
            <span v-if="!canCancel(row.status) && row.status !== 'COMPLETED'"
              >-</span
            >
          </template>
        </el-table-column>
      </el-table>

      <Pagination
        v-model:page="queryParams.pageNum"
        v-model:limit="queryParams.pageSize"
        :total="taskStore.total"
        @pagination="loadTaskList"
      />
    </div>
  </el-drawer>
</template>

<style lang="scss" scoped>
.drawer-content {
  display: flex;
  flex-direction: column;
  gap: 16px;
  height: 100%;
}

.filter-bar {
  display: flex;
  gap: 12px;
  align-items: center;
}

.status-select {
  width: 140px;
}
</style>

// dehaze-front-react/src/components/ImportExportToolbar/TaskListDrawer.tsx
import {
  cancelTask,
  clearPollingTimer,
  fetchTaskList,
  fetchTaskStatus,
  POLLING_STATUSES,
  setPollingTimer,
} from "@/store/modules/taskSlice";
import { DisPatchType, RootState } from "@/store";
import {
  CloseCircleOutlined,
  DownloadOutlined,
  EyeOutlined,
  ReloadOutlined,
} from "@ant-design/icons";
import {
  Button,
  Drawer,
  Modal,
  Pagination,
  Progress,
  Radio,
  Select,
  Space,
  Table,
  Tag,
  message,
  type TableColumnsType,
} from "antd";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useDispatch, useSelector } from "react-redux";
import type { TaskCategory, TaskStatus, TaskVO } from "dehaze-sdk-js";
import {
  STATUS_COLOR_MAP,
  STATUS_LABEL_MAP,
  TASK_TYPE_LABEL_MAP,
} from "./types";

const POLLING_INTERVAL = 3000;

interface TaskListDrawerProps {
  open: boolean;
  module?: string;
  onClose: () => void;
}

const STATUS_OPTIONS = [
  { label: "全部", value: "" },
  { label: "待执行", value: "PENDING" },
  { label: "执行中", value: "PROCESSING" },
  { label: "已完成", value: "COMPLETED" },
  { label: "失败", value: "FAILED" },
  { label: "已取消", value: "CANCELLED" },
];

const formatDateTime = (value?: string): string => {
  if (!value) return "-";
  const date = new Date(value);
  if (isNaN(date.getTime())) return String(value);
  return date.toLocaleString("zh-CN");
};

const isImportTask = (taskType?: string): boolean => {
  if (!taskType) return false;
  return taskType.endsWith("_import");
};

const TaskListDrawer: React.FC<TaskListDrawerProps> = ({
  open,
  module,
  onClose,
}) => {
  const dispatch = useDispatch<DisPatchType>();
  const { taskList, total, loading } = useSelector(
    (state: RootState) => state.task
  );

  const [pageNum, setPageNum] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [categoryFilter, setCategoryFilter] = useState<string>("");
  const [refreshFlag, setRefreshFlag] = useState(0);
  const [downloadLoadingId, setDownloadLoadingId] = useState<string | null>(
    null
  );
  const [cancelLoadingId, setCancelLoadingId] = useState<string | null>(null);

  const taskListRef = useRef<TaskVO[]>([]);
  useEffect(() => {
    taskListRef.current = taskList;
  }, [taskList]);

  const buildTaskTypeFilter = (): string | undefined => {
    if (module) {
      return [`${module}_export`, `${module}_import`].join(",");
    }
    return undefined;
  };

  const loadTaskList = useCallback(async () => {
    try {
      await dispatch(
        fetchTaskList({
          pageNum,
          pageSize,
          status: (statusFilter || undefined) as TaskStatus | undefined,
          taskCategory: (categoryFilter || undefined) as
            TaskCategory | undefined,
          taskType: buildTaskTypeFilter(),
        })
      );
    } catch (error: unknown) {
      message.error((error as Error)?.message || "任务列表加载失败");
    }
  }, [dispatch, pageNum, pageSize, statusFilter, categoryFilter, module]);

  useEffect(() => {
    if (open) {
      loadTaskList();
    }
  }, [open, pageNum, pageSize, refreshFlag, loadTaskList]);

  const refreshList = useCallback(() => {
    setRefreshFlag((prev) => prev + 1);
  }, []);

  const pollingTimerRef = useRef<number | null>(null);
  const pollingTimer = useSelector(
    (state: RootState) => state.task.pollingTimer
  );
  useEffect(() => {
    pollingTimerRef.current = pollingTimer;
  }, [pollingTimer]);

  const stopPolling = useCallback(() => {
    if (pollingTimerRef.current) {
      window.clearInterval(pollingTimerRef.current);
      dispatch(clearPollingTimer());
    }
  }, [dispatch]);

  const pollTaskStatuses = useCallback(() => {
    const pollingTasks = taskListRef.current.filter((task) =>
      POLLING_STATUSES.includes(task.status as TaskStatus)
    );
    if (pollingTasks.length === 0) {
      stopPolling();
      return;
    }
    pollingTasks.forEach((task) => {
      dispatch(fetchTaskStatus(task.taskId));
    });
  }, [dispatch, stopPolling]);

  const startPolling = useCallback(() => {
    if (pollingTimerRef.current) return;
    const hasPollingTask = taskListRef.current.some((task) =>
      POLLING_STATUSES.includes(task.status as TaskStatus)
    );
    if (!hasPollingTask) return;
    const timer = window.setInterval(() => {
      pollTaskStatuses();
    }, POLLING_INTERVAL);
    dispatch(setPollingTimer(timer));
  }, [dispatch, pollTaskStatuses]);

  useEffect(() => {
    if (!open) return;
    const hasPollingTask = taskList.some((task) =>
      POLLING_STATUSES.includes(task.status as TaskStatus)
    );
    if (hasPollingTask) {
      startPolling();
    } else {
      stopPolling();
    }
  }, [taskList, open, startPolling, stopPolling]);

  useEffect(() => {
    if (!open) return;
    const handleVisibilityChange = () => {
      if (document.hidden) {
        stopPolling();
      } else {
        startPolling();
      }
    };
    document.addEventListener("visibilitychange", handleVisibilityChange);
    return () => {
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, [open, startPolling, stopPolling]);

  useEffect(() => {
    if (!open && pollingTimerRef.current) {
      stopPolling();
    }
  }, [open, stopPolling]);

  useEffect(() => {
    return () => {
      if (pollingTimerRef.current) {
        window.clearInterval(pollingTimerRef.current);
      }
    };
  }, []);

  const handleFilterChange = () => {
    setPageNum(1);
    setRefreshFlag((prev) => prev + 1);
  };

  const handleCancelTask = useCallback(
    (record: TaskVO) => {
      Modal.confirm({
        title: "取消任务",
        content: "确认取消该任务吗？取消后不可恢复。",
        okText: "确定",
        cancelText: "取消",
        okType: "danger",
        onOk: () => {
          setCancelLoadingId(record.taskId);
          return dispatch(cancelTask(record.taskId))
            .unwrap()
            .then(() => {
              message.success("任务已取消");
              setCancelLoadingId(null);
              refreshList();
            })
            .catch((error: unknown) => {
              setCancelLoadingId(null);
              message.error((error as Error)?.message || "取消任务失败");
              return Promise.reject(error);
            });
        },
      });
    },
    [dispatch, refreshList]
  );

  const handleDownload = useCallback((record: TaskVO) => {
    if (record.status !== "COMPLETED") {
      message.warning("任务尚未完成，无法下载");
      return;
    }
    if (!record.downloadUrl) {
      message.warning("下载链接不存在或已过期");
      return;
    }
    if (record.expiresAt) {
      const expiresAt = new Date(record.expiresAt).getTime();
      if (Date.now() > expiresAt) {
        message.warning("任务结果已过期，无法下载");
        return;
      }
    }
    setDownloadLoadingId(record.taskId);
    try {
      const link = document.createElement("a");
      link.href = record.downloadUrl;
      link.target = "_blank";
      link.rel = "noopener noreferrer";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      message.success("开始下载");
    } finally {
      setDownloadLoadingId(null);
    }
  }, []);

  const columns: TableColumnsType<TaskVO> = useMemo(
    () => [
      {
        title: "任务ID",
        dataIndex: "taskId",
        key: "taskId",
        width: 220,
        ellipsis: true,
      },
      {
        title: "类型",
        dataIndex: "taskType",
        key: "taskType",
        width: 120,
        align: "center",
        render: (taskType: string) =>
          TASK_TYPE_LABEL_MAP[taskType] || taskType || "-",
      },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
        width: 100,
        align: "center",
        render: (status: string) => (
          <Tag color={STATUS_COLOR_MAP[status] || "default"}>
            {STATUS_LABEL_MAP[status] || status}
          </Tag>
        ),
      },
      {
        title: "进度",
        dataIndex: "progress",
        key: "progress",
        width: 200,
        align: "center",
        render: (progress: number, record: TaskVO) => {
          const status = record.status;
          let progressStatus: "active" | "success" | "exception" | "normal" =
            "active";
          if (status === "COMPLETED") {
            progressStatus = "success";
          } else if (status === "FAILED") {
            progressStatus = "exception";
          } else if (status === "CANCELLED") {
            progressStatus = "normal";
          }
          return (
            <Progress
              percent={progress || 0}
              size="small"
              status={progressStatus}
            />
          );
        },
      },
      {
        title: "创建时间",
        dataIndex: "createdAt",
        key: "createdAt",
        width: 180,
        align: "center",
        render: (text: string) => formatDateTime(text),
      },
      {
        title: "操作",
        key: "action",
        width: 200,
        align: "center",
        fixed: "right",
        render: (_: unknown, record: TaskVO) => (
          <Space size="small">
            {(record.status === "PENDING" ||
              record.status === "PROCESSING") && (
              <Button
                type="link"
                size="small"
                danger
                icon={<CloseCircleOutlined />}
                loading={cancelLoadingId === record.taskId}
                onClick={() => handleCancelTask(record)}
              >
                取消
              </Button>
            )}
            {record.status === "COMPLETED" && isImportTask(record.taskType) && (
              <Button
                type="link"
                size="small"
                icon={<EyeOutlined />}
                loading={downloadLoadingId === record.taskId}
                onClick={() => handleDownload(record)}
              >
                查看结果
              </Button>
            )}
            {record.status === "COMPLETED" &&
              !isImportTask(record.taskType) && (
                <Button
                  type="link"
                  size="small"
                  icon={<DownloadOutlined />}
                  loading={downloadLoadingId === record.taskId}
                  onClick={() => handleDownload(record)}
                >
                  下载
                </Button>
              )}
          </Space>
        ),
      },
    ],
    [cancelLoadingId, downloadLoadingId, handleCancelTask, handleDownload]
  );

  const drawerTitle = module
    ? `${TASK_TYPE_LABEL_MAP[`${module}_export`]?.replace("导出", "") || ""}任务列表`
    : "任务列表";

  return (
    <Drawer
      title={drawerTitle}
      open={open}
      onClose={onClose}
      width={960}
      destroyOnHidden
    >
      <Space direction="vertical" size="middle" style={{ width: "100%" }}>
        <Space wrap>
          <Radio.Group
            buttonStyle="solid"
            value={categoryFilter}
            onChange={(e) => {
              setCategoryFilter(e.target.value);
              handleFilterChange();
            }}
          >
            <Radio.Button value="">全部</Radio.Button>
            <Radio.Button value="import">导入</Radio.Button>
            <Radio.Button value="export">导出</Radio.Button>
          </Radio.Group>
          <Select
            value={statusFilter}
            style={{ width: 140 }}
            onChange={(value) => {
              setStatusFilter(value);
              handleFilterChange();
            }}
            options={STATUS_OPTIONS}
            placeholder="任务状态"
          />
          <Button icon={<ReloadOutlined />} onClick={refreshList}>
            刷新
          </Button>
        </Space>

        <Table
          columns={columns}
          dataSource={taskList}
          rowKey={(record) => record.taskId}
          loading={loading}
          scroll={{ x: 1100 }}
          pagination={false}
        />

        <Pagination
          current={pageNum}
          pageSize={pageSize}
          total={total}
          showSizeChanger
          showQuickJumper
          pageSizeOptions={["10", "20", "50", "100"]}
          showTotal={(t) => `共 ${t} 条`}
          onChange={(page, size) => {
            setPageNum(page);
            setPageSize(size);
          }}
        />
      </Space>
    </Drawer>
  );
};

export default TaskListDrawer;
