// dehaze-front-vue/src/views/login/index.vue
<template>
  <div class="login-container">
    <!-- 顶部 -->
    <div
      class="absolute-lt flex-x-end p-3 w-full"
      style="top: var(--titlebar-h, 0)"
    >
      <el-switch
        v-model="isDark"
        :active-icon="Moon"
        :inactive-icon="Sunny"
        inline-prompt
        @change="toggleTheme"
      />
      <lang-select class="ml-2 cursor-pointer" />
    </div>
    <!-- 登录表单 -->
    <el-card class="!border-none !bg-transparent !rounded-4% w-100 <sm:w-85">
      <div class="text-center relative">
        <h2>{{ defaultSettings.title }}</h2>
        <el-tag class="ml-2 absolute-rt">{{ defaultSettings.version }}</el-tag>
      </div>

      <el-form
        ref="loginFormRef"
        :model="loginData"
        :rules="loginRules"
        class="login-form"
      >
        <!-- 用户名 -->
        <el-form-item prop="username">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="user" />
            <el-input
              ref="username"
              v-model="loginData.username"
              :placeholder="$t('login.username')"
              class="h-[48px]"
              name="username"
              size="large"
            />
          </div>
        </el-form-item>

        <!-- 密码 -->
        <el-tooltip
          :content="$t('login.capsLock')"
          :visible="isCapslock"
          placement="right"
        >
          <el-form-item prop="password">
            <div class="flex-y-center w-full">
              <svg-icon class="mx-2" icon-class="lock" />
              <el-input
                v-model="loginData.password"
                :placeholder="$t('login.password')"
                class="h-[48px] pr-2"
                name="password"
                show-password
                size="large"
                type="password"
                @keyup="checkCapslock"
                @keyup.enter="handleLogin"
              />
            </div>
          </el-form-item>
        </el-tooltip>

        <!-- 验证码 -->
        <el-form-item prop="captchaCode">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="captcha" />
            <el-input
              v-model="loginData.captchaCode"
              :placeholder="$t('login.captchaCode')"
              auto-complete="off"
              class="flex-1"
              size="large"
              @keyup.enter="handleLogin"
            />

            <el-image
              :src="captchaBase64"
              class="rounded-tr-md rounded-br-md cursor-pointer h-[48px]"
              @click="getCaptcha"
            />
          </div>
        </el-form-item>

        <!-- 记住我 -->
        <div class="flex-x-between w-full mb-4">
          <el-checkbox v-model="loginData.rememberMe">
            记住我（7天内免登录）
          </el-checkbox>
        </div>

        <!-- 登录按钮 -->
        <el-button
          :loading="loading"
          class="w-full"
          size="large"
          type="primary"
          @click.prevent="handleLogin"
          >{{ $t("login.login") }}
        </el-button>

        <div class="text-center mt-4">
          <router-link to="/register">没有账号？立即注册</router-link>
        </div>
      </el-form>
    </el-card>

    <!-- ICP备案 -->
    <div v-show="icpVisible" class="absolute bottom-1 text-[10px] text-center">
      <p>
        Copyright © 2022 - 2024 Peixin Wu All Rights Reserved. 武沛鑫 版权所有
      </p>
      <p>渝ICP备2024111923号-2</p>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ThemeEnum } from "@/enums/ThemeEnum";
import router from "@/router";
import defaultSettings from "@/settings";
import { useSettingsStore, useUserStore } from "@/store";
import { Moon, Sunny } from "@element-plus/icons-vue";

import { AuthAPI, LoginData } from "dehaze-sdk-js";
import { LocationQuery, LocationQueryValue, useRoute } from "vue-router";

const userStore = useUserStore();
const settingsStore = useSettingsStore();

const { t } = useI18n();

const isDark = ref(settingsStore.theme === ThemeEnum.DARK);
const icpVisible = ref(true);
const loading = ref(false);
const isCapslock = ref(false);
const captchaBase64 = ref();
const loginFormRef = ref(ElForm);
const { height } = useWindowSize();

const loginData = ref<LoginData>({
  username: "",
  password: "",
  rememberMe: true,
});

const loginRules = computed(() => {
  return {
    username: [
      {
        required: true,
        trigger: "blur",
        message: t("login.message.username.required"),
      },
    ],
    password: [
      {
        required: true,
        trigger: "blur",
        message: t("login.message.password.required"),
      },
      {
        min: 6,
        message: t("login.message.password.min"),
        trigger: "blur",
      },
    ],
    captchaCode: [
      {
        required: true,
        trigger: "blur",
        message: t("login.message.captchaCode.required"),
      },
    ],
  };
});

function getCaptcha() {
  AuthAPI.getCaptcha().then((data) => {
    loginData.value.captchaKey = data.captchaKey;
    captchaBase64.value = data.captchaBase64;
  });
}

const route = useRoute();

function handleLogin() {
  loginFormRef.value.validate((valid: boolean) => {
    if (valid) {
      loading.value = true;
      userStore
        .login(loginData.value)
        .then(() => {
          const query: LocationQuery = route.query;
          const redirect = (query.redirect as LocationQueryValue) ?? "/";
          const otherQueryParams = Object.keys(query).reduce(
            (acc: any, cur: string) => {
              if (cur !== "redirect") {
                acc[cur] = query[cur];
              }
              return acc;
            },
            {}
          );

          router.push({ path: redirect, query: otherQueryParams });
        })
        .catch(() => {
          getCaptcha();
        })
        .finally(() => {
          loading.value = false;
        });
    }
  });
}

const toggleTheme = () => {
  const newTheme =
    settingsStore.theme === ThemeEnum.DARK ? ThemeEnum.LIGHT : ThemeEnum.DARK;
  settingsStore.changeTheme(newTheme);
};

watchEffect(() => {
  if (height.value < 600) {
    icpVisible.value = false;
  } else {
    icpVisible.value = true;
  }
});

function checkCapslock(event: KeyboardEvent) {
  if (event instanceof KeyboardEvent) {
    isCapslock.value = event.getModifierState("CapsLock");
  }
}

onMounted(() => {
  getCaptcha();
  nextTick(() => {
    loginFormRef.value?.fields?.[0]?.ref?.focus?.();
  });
});
</script>

<style lang="scss" scoped>
html.dark .login-container {
  background: url("@/assets/images/login-bg-dark.jpg") no-repeat center right;
}

.login-container {
  padding-top: var(--titlebar-h, 0);
  overflow-y: auto;
  background: url("@/assets/images/login-bg.jpg") no-repeat center right;

  @apply wh-full flex-center;

  .login-form {
    padding: 30px 10px;
  }
}

.el-form-item {
  background: var(--el-input-bg-color);
  border: 1px solid var(--el-border-color);
  border-radius: 5px;
}

:deep(.el-input) {
  .el-input__wrapper {
    padding: 0;
    background-color: transparent;
    box-shadow: none;

    &.is-focus,
    &:hover {
      box-shadow: none !important;
    }

    input:-webkit-autofill {
      /* 通过延时渲染背景色变相去除背景颜色 */
      transition: background-color 1000s ease-in-out 0s;
    }
  }
}
</style>

// dehaze-front-react/src/pages/login/index.tsx
import { AuthAPI, LoginData } from "dehaze-sdk-js";
import { ThemeEnum } from "@/enums/ThemeEnum";
import defaultSettings from "@/settings";
import { DisPatchType } from "@/store";
import { login } from "@/store/modules/userSlice";
import {
  EyeInvisibleOutlined,
  EyeTwoTone,
  LockOutlined,
  MoonOutlined,
  SafetyOutlined,
  SunOutlined,
  UserOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Checkbox,
  Form,
  Input,
  Switch,
  Tag,
  Tooltip,
} from "antd";
import React, { useCallback, useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { useLocation, useNavigate } from "react-router-dom";
import "./index.scss";

export default function Login() {
  const [form] = Form.useForm();
  const [captchaBase64, setCaptchaBase64] = useState("");
  const [captchaKey, setCaptchaKey] = useState("");
  const [loading, setLoading] = useState(false);
  const [isCapslock, setIsCapslock] = useState(false);
  const [isDark, setIsDark] = useState(false);
  const [rememberMe, setRememberMe] = useState(true);
  const location = useLocation();
  const navigate = useNavigate();

  const dispatch: DisPatchType = useDispatch();

  const getCaptcha = useCallback(() => {
    AuthAPI.getCaptcha().then((data) => {
      setCaptchaBase64(data.captchaBase64);
      setCaptchaKey(data.captchaKey);
    });
  }, []);

  useEffect(() => {
    getCaptcha();
  }, []);

  const handleLogin = (values: {
    username: string;
    password: string;
    captchaCode: string;
  }) => {
    setLoading(true);
    const loginData: LoginData = { ...values, captchaKey, rememberMe };
    dispatch(login(loginData))
      .then(() => {
        const query = new URLSearchParams(location.search);
        const redirect = query.get("redirect") || "/";
        const otherQueryParams: Record<string, string> = {};
        query.forEach((value, key) => {
          if (key !== "redirect") {
            otherQueryParams[key] = value;
          }
        });
        navigate({
          pathname: redirect,
          search: new URLSearchParams(otherQueryParams).toString(),
        });
      })
      .catch(() => {
        form.setFieldsValue({ password: "", captchaCode: "" });
        getCaptcha();
      })
      .finally(() => {
        setLoading(false);
      });
  };

  const toggleTheme = () => {
    const newTheme = isDark ? ThemeEnum.LIGHT : ThemeEnum.DARK;
    setIsDark(!isDark);
    dispatch({ type: "settings/changeTheme", payload: newTheme });
  };

  return (
    <div className="login-container">
      <div
        className="absolute-lt flex-x-end p-3 w-full"
        style={{ top: "var(--titlebar-h, 0px)" }}
      >
        <Switch
          checkedChildren={<MoonOutlined />}
          unCheckedChildren={<SunOutlined />}
          checked={isDark}
          onChange={toggleTheme}
        />
      </div>
      <Card className="!border-none !bg-transparent !rounded-4% w-100 <sm:w-85">
        <div className="text-center relative">
          <h2>{defaultSettings.title}</h2>
          <Tag className="ml-2 absolute-rt">{defaultSettings.version}</Tag>
        </div>

        <Form
          form={form}
          className="login-form"
          initialValues={{ username: "", password: "" }}
          onFinish={handleLogin}
        >
          <Form.Item
            name="username"
            rules={[{ required: true, message: "请输入用户名" }]}
          >
            <Input
              prefix={<UserOutlined />}
              placeholder="用户名"
              size="large"
              autoFocus
            />
          </Form.Item>
          <Tooltip title="大写锁定已开启" open={isCapslock}>
            <Form.Item
              name="password"
              rules={[{ required: true, message: "请输入密码" }]}
            >
              <Input.Password
                prefix={<LockOutlined />}
                placeholder="密码"
                size="large"
                iconRender={(visible) =>
                  visible ? <EyeTwoTone /> : <EyeInvisibleOutlined />
                }
                onKeyUp={(e) => setIsCapslock(e.getModifierState("CapsLock"))}
              />
            </Form.Item>
          </Tooltip>
          <Form.Item
            name="captchaCode"
            rules={[{ required: true, message: "请输入验证码" }]}
          >
            <Input
              prefix={<SafetyOutlined />}
              placeholder="验证码"
              size="large"
              suffix={
                captchaBase64 ? (
                  <img
                    src={captchaBase64}
                    onClick={() => getCaptcha()}
                    alt="加载失败"
                    style={{ height: 34, cursor: "pointer" }}
                  />
                ) : (
                  <Button
                    type="link"
                    size="small"
                    onClick={getCaptcha}
                    style={{ height: 34, padding: 0 }}
                  >
                    加载验证码
                  </Button>
                )
              }
            />
          </Form.Item>
          <Form.Item>
            <Checkbox
              checked={rememberMe}
              onChange={(e) => setRememberMe(e.target.checked)}
            >
              记住我（7天内免登录）
            </Checkbox>
          </Form.Item>
          <Form.Item>
            <Button
              className="w-full"
              size="large"
              type="primary"
              htmlType="submit"
              loading={loading}
            >
              登录
            </Button>
          </Form.Item>
        </Form>
        <div className="text-center mt-4">
          <a href="/register">没有账号？立即注册</a>
        </div>
      </Card>
      <div className="absolute bottom-1 text-[10px] text-center">
        <p>
          Copyright © 2022 - 2024 Peixin Wu All Rights Reserved. 武沛鑫 版权所有
        </p>
        <p>渝ICP备2024111923号-2</p>
      </div>
    </div>
  );
}
