// dehaze-front-vue/src/views/recommendation/rules/index.vue
<template>
  <div class="app-container">
    <el-card shadow="never">
      <template #header>
        <div class="flex justify-between items-center">
          <span class="title">推荐规则管理</span>
          <el-button type="primary" @click="openDialog()">
            <el-icon><Plus /></el-icon>新增规则
          </el-button>
        </div>
      </template>

      <el-table
        v-loading="loading"
        :data="tableData as RecommendationRule[]"
        border
        stripe
      >
        <el-table-column label="规则名称" prop="ruleName" min-width="160" />
        <el-table-column
          label="场景类型"
          prop="sceneType"
          width="120"
          align="center"
        >
          <template #default="scope">
            <el-tag>{{
              getSceneTypeLabel((scope.row as RecommendationRule).sceneType)
            }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="关联算法" min-width="240">
          <template #default="scope">
            <el-tag
              v-for="(alg, idx) in getAlgoNames(
                (scope.row as RecommendationRule).algorithmIds
              )"
              :key="idx"
              size="small"
              style="margin: 2px"
            >
              {{ alg }}
            </el-tag>
            <span v-if="!(scope.row as RecommendationRule).algorithmIds?.length"
              >-</span
            >
          </template>
        </el-table-column>
        <el-table-column label="权重" prop="weight" width="100" align="center">
          <template #default="scope">
            <el-input-number
              v-model="(scope.row as RecommendationRule).weight"
              :min="0"
              :max="100"
              :step="5"
              size="small"
              style="width: 70px"
              @change="handleWeightChange(scope.row as RecommendationRule)"
            />
          </template>
        </el-table-column>
        <el-table-column label="启用状态" width="100" align="center">
          <template #default="scope">
            <el-switch
              v-model="(scope.row as RecommendationRule).enabled"
              @change="handleEnabledChange(scope.row as RecommendationRule)"
            />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180" align="center" fixed="right">
          <template #default="scope">
            <el-button
              link
              type="primary"
              size="small"
              @click="openDialog(scope.row as RecommendationRule)"
            >
              <el-icon><Edit /></el-icon>编辑
            </el-button>
            <el-button
              link
              type="danger"
              size="small"
              @click="handleDelete(scope.row as RecommendationRule)"
            >
              <el-icon><Delete /></el-icon>删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- Edit/Add Dialog -->
    <el-dialog
      v-model="dialog.visible"
      :title="dialog.isEdit ? '编辑推荐规则' : '新增推荐规则'"
      width="600px"
      append-to-body
      destroy-on-close
      @close="closeDialog"
    >
      <el-form
        ref="formRef"
        :model="formData"
        :rules="rules"
        label-width="100px"
      >
        <el-form-item label="规则名称" prop="ruleName">
          <el-input v-model="formData.ruleName" placeholder="请输入规则名称" />
        </el-form-item>

        <el-form-item label="场景类型" prop="sceneType">
          <el-select
            v-model="formData.sceneType"
            placeholder="请选择场景类型"
            style="width: 100%"
          >
            <el-option label="城市" value="urban" />
            <el-option label="风景" value="landscape" />
            <el-option label="建筑" value="building" />
            <el-option label="夜景" value="night" />
            <el-option label="逆光" value="backlight" />
            <el-option label="室内" value="indoor" />
          </el-select>
        </el-form-item>

        <el-form-item label="关联算法" prop="algorithmIds">
          <el-select
            v-model="formData.algorithmIds"
            multiple
            filterable
            placeholder="请选择关联算法"
            style="width: 100%"
          >
            <el-option
              v-for="item in algorithmOptions"
              :key="item.value"
              :label="item.label"
              :value="item.value"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="权重" prop="weight">
          <el-slider
            v-model="formData.weight"
            :min="0"
            :max="100"
            :step="5"
            show-tooltip
          />
          <div style="margin-top: 4px; color: #909399; text-align: center">
            当前权重：{{ formData.weight }}
          </div>
        </el-form-item>

        <el-form-item label="启用状态">
          <el-switch v-model="formData.enabled" />
        </el-form-item>
      </el-form>

      <template #footer>
        <el-button @click="closeDialog">取 消</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSubmit"
          >确 定</el-button
        >
      </template>
    </el-dialog>
  </div>
</template>

<script lang="ts" setup>
import { ref, reactive, onMounted } from "vue";
import {
  RecommendationAPI,
  RecommendationRule,
  AlgorithmAPI,
  OptionType,
} from "dehaze-sdk-js";
import { Plus, Edit, Delete } from "@element-plus/icons-vue";

defineOptions({ name: "RecommendationRules" });

const loading = ref(false);
const submitting = ref(false);
const tableData = ref<RecommendationRule[]>([]);
const algorithmOptions = ref<OptionType[]>([]);
// Local map for algorithm id -> name resolution
const algoNameMap = ref<Record<number, string>>({});

const dialog = reactive({
  visible: false,
  isEdit: false,
});

const formRef = ref<any>(null);
const formData = reactive<RecommendationRule>({
  ruleName: "",
  sceneType: "urban",
  algorithmIds: [],
  weight: 50,
  enabled: true,
});

const rules = {
  ruleName: [{ required: true, message: "请输入规则名称", trigger: "blur" }],
  sceneType: [{ required: true, message: "请选择场景类型", trigger: "change" }],
  algorithmIds: [
    { required: true, message: "请至少选择一个关联算法", trigger: "change" },
  ],
};

function getSceneTypeLabel(sceneType: string): string {
  const map: Record<string, string> = {
    urban: "城市",
    landscape: "风景",
    building: "建筑",
    night: "夜景",
    backlight: "逆光",
    indoor: "室内",
  };
  return map[sceneType] || sceneType;
}

function getAlgoNames(ids?: number[]): string[] {
  if (!ids?.length) return [];
  return ids.map((id) => algoNameMap.value[id] || String(id));
}

async function loadData() {
  loading.value = true;
  try {
    tableData.value = await RecommendationAPI.getRules();
    // Fetch algorithm options to resolve algorithm names
    const algoList = await AlgorithmAPI.getOption();
    algorithmOptions.value = algoList;
    algoNameMap.value = {};
    algoList.forEach((a) => {
      algoNameMap.value[Number(a.value)] = a.label;
    });
  } catch {
    ElMessage.error("加载推荐规则失败");
  } finally {
    loading.value = false;
  }
}

function openDialog(rule?: RecommendationRule) {
  if (rule) {
    dialog.isEdit = true;
    Object.assign(formData, rule);
  } else {
    dialog.isEdit = false;
    ElMessage.warning("新增功能暂不可用，请使用编辑修改现有规则");
    return;
  }
  dialog.visible = true;
}

function closeDialog() {
  dialog.visible = false;
  dialog.isEdit = false;
  formRef.value?.resetFields();
}

async function handleSubmit() {
  if (!formRef.value) return;
  formRef.value.validate(async (valid: boolean) => {
    if (!valid) return;
    submitting.value = true;
    try {
      const id = await RecommendationAPI.updateRule(formData.id!, formData);
      if (id) {
        ElMessage.success("更新成功");
        closeDialog();
        loadData();
      }
    } catch {
      ElMessage.error("操作失败");
    } finally {
      submitting.value = false;
    }
  });
}

async function handleWeightChange(rule: RecommendationRule) {
  try {
    await RecommendationAPI.updateRule(rule.id!, { ...rule });
    ElMessage.success("权重已更新");
  } catch {
    ElMessage.error("权重更新失败");
    loadData();
  }
}

async function handleEnabledChange(rule: RecommendationRule) {
  try {
    await RecommendationAPI.updateRule(rule.id!, { ...rule });
  } catch {
    ElMessage.error("状态更新失败");
    loadData();
  }
}

async function handleDelete(rule: RecommendationRule) {
  ElMessageBox.confirm(`确认删除规则"${rule.ruleName}"吗？`, "提示", {
    confirmButtonText: "确定",
    cancelButtonText: "取消",
    type: "warning",
  })
    .then(async () => {
      // Note: No deleteRule API defined in SDK, using update with disabled approach
      await RecommendationAPI.updateRule(rule.id!, { ...rule, enabled: false });
      ElMessage.success("已禁用该规则");
      loadData();
    })
    .catch(() => {});
}

onMounted(() => {
  loadData();
});
</script>

<style scoped>
.title {
  font-size: 18px;
  font-weight: 600;
}
</style>

// dehaze-front-react/src/pages/recommendation/rules/index.tsx
import {
  AlgorithmAPI,
  RecommendationAPI,
  type OptionType,
  type RecommendationRule,
} from "dehaze-sdk-js";
import {
  PlusOutlined,
  SaveOutlined,
  ReloadOutlined,
  EditOutlined,
  DeleteOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Form,
  Input,
  InputNumber,
  message,
  Modal,
  Popconfirm,
  Select,
  Space,
  Switch,
  Table,
  Tag,
  Tooltip,
  type TableColumnsType,
} from "antd";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import "./index.module.scss";

export default function RecommendationRules() {
  const [loading, setLoading] = useState(false);
  const [rules, setRules] = useState<RecommendationRule[]>([]);
  const [algorithmOptions, setAlgorithmOptions] = useState<OptionType[]>([]);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingRule, setEditingRule] = useState<RecommendationRule | null>(
    null
  );
  const [form] = Form.useForm();

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [ruleData, algoData] = await Promise.all([
        RecommendationAPI.getRules(),
        AlgorithmAPI.getOption(),
      ]);
      setRules(ruleData || []);
      setAlgorithmOptions(algoData || []);
    } catch (err: unknown) {
      const messageErr = err as { message?: string };
      message.error(messageErr.message || "加载推荐规则失败");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleOpenModal = (record?: RecommendationRule) => {
    setEditingRule(record || null);
    if (record) {
      form.setFieldsValue(record);
    } else {
      form.resetFields();
      form.setFieldsValue({
        ruleName: "",
        sceneType: "",
        algorithmIds: [],
        weight: 50,
        enabled: true,
      });
    }
    setModalVisible(true);
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      if (editingRule?.id) {
        await RecommendationAPI.updateRule(editingRule.id, values);
        message.success("规则更新成功");
      } else {
        Modal.info({
          title: "提示",
          content:
            "规则创建功能待后端接口开放后启用，当前仅支持编辑和开关状态。",
          okText: "确定",
        });
      }
      setModalVisible(false);
      loadData();
    } catch (err: unknown) {
      const formErr = err as { errorFields?: Array<{ name: unknown }> };
      if (formErr.errorFields) return;
      const messageErr = err as { message?: string };
      message.error(messageErr.message || "保存失败");
    }
  };

  const handleDelete = useCallback((id: number) => {
    Modal.info({
      title: "提示",
      content: "规则删除功能待后端接口开放后启用。",
      okText: "确定",
    });
  }, []);

  const handleToggleEnabled = async (id: number, currentEnabled: boolean) => {
    try {
      const rule = rules.find((r) => r.id === id);
      if (!rule) return;
      await RecommendationAPI.updateRule(id, {
        ...rule,
        enabled: !currentEnabled,
      });
      message.success(currentEnabled ? "规则已禁用" : "规则已启用");
      loadData();
    } catch (err: unknown) {
      const messageErr = err as { message?: string };
      message.error(messageErr.message || "操作失败");
    }
  };

  const columns: TableColumnsType<RecommendationRule> = useMemo(
    () => [
      {
        title: "规则名称",
        dataIndex: "ruleName",
        key: "ruleName",
        width: 150,
      },
      {
        title: "场景类型",
        dataIndex: "sceneType",
        key: "sceneType",
        width: 120,
        render: (text: string) => <Tag color="blue">{text}</Tag>,
      },
      {
        title: "推荐算法",
        dataIndex: "algorithmIds",
        key: "algorithmIds",
        width: 200,
        render: (ids: number[]) => (
          <Space wrap>
            {(ids || []).map((id) => {
              const algo = algorithmOptions.find((a) => a.value === id);
              return algo ? <Tag key={id}>{algo.label}</Tag> : null;
            })}
          </Space>
        ),
      },
      {
        title: "权重",
        dataIndex: "weight",
        key: "weight",
        width: 100,
        align: "center",
        render: (weight: number, record: RecommendationRule) => (
          <InputNumber
            value={weight}
            onChange={(val) => {
              if (record.id && val !== undefined) {
                setRules((prev) =>
                  prev.map((r) =>
                    r.id === record.id ? { ...r, weight: val! } : r
                  )
                );
              }
            }}
            style={{ width: 80 }}
            min={0}
            max={100}
            step={5}
            onBlur={() => {}}
          />
        ),
      },
      {
        title: "状态",
        dataIndex: "enabled",
        key: "enabled",
        width: 80,
        align: "center",
        render: (enabled: boolean, record: RecommendationRule) => (
          <Switch
            checked={enabled}
            onChange={() =>
              record.id && handleToggleEnabled(record.id, enabled)
            }
            checkedChildren={<CheckCircleOutlined />}
            unCheckedChildren={<CloseCircleOutlined />}
          />
        ),
      },
      {
        title: "操作",
        key: "action",
        width: 160,
        align: "center",
        fixed: "right",
        render: (_: unknown, record: RecommendationRule) => (
          <Space size="small">
            <Tooltip title="编辑">
              <Button
                type="link"
                size="small"
                icon={<EditOutlined />}
                onClick={() => handleOpenModal(record)}
              />
            </Tooltip>
            <Popconfirm
              title="确认删除该规则？"
              onConfirm={() => record.id && handleDelete(record.id)}
              okText="确定"
              cancelText="取消"
            >
              <Button
                type="link"
                size="small"
                danger
                icon={<DeleteOutlined />}
              />
            </Popconfirm>
          </Space>
        ),
      },
    ],
    [algorithmOptions, handleDelete]
  );

  return (
    <div className="rec-rules-page">
      <Card>
        <div className="toolbar">
          <Space>
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => handleOpenModal()}
            >
              新增规则
            </Button>
            <Button icon={<ReloadOutlined />} onClick={loadData}>
              刷新
            </Button>
          </Space>
        </div>

        <Table
          columns={columns}
          dataSource={rules}
          rowKey={(record) => record.id?.toString() || Math.random().toString()}
          loading={loading}
          scroll={{ x: 900 }}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      <Modal
        title={editingRule ? "编辑推荐规则" : "新增推荐规则"}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
        width={600}
        forceRender
      >
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          <Form.Item
            name="ruleName"
            label="规则名称"
            rules={[{ required: true, message: "请输入规则名称" }]}
          >
            <Input placeholder="例如：城市白天去雾" />
          </Form.Item>

          <Form.Item
            name="sceneType"
            label="场景类型"
            rules={[{ required: true, message: "请选择场景类型" }]}
          >
            <Select
              placeholder="选择场景类型"
              options={[
                { label: "城市", value: "urban" },
                { label: "风景", value: "landscape" },
                { label: "建筑", value: "building" },
                { label: "夜景", value: "night" },
                { label: "逆光", value: "backlight" },
                { label: "室内", value: "indoor" },
              ]}
            />
          </Form.Item>

          <Form.Item
            name="algorithmIds"
            label="推荐算法"
            rules={[{ required: true, message: "请至少选择一个算法" }]}
          >
            <Select
              mode="multiple"
              placeholder="选择推荐算法"
              options={algorithmOptions}
              allowClear
            />
          </Form.Item>

          <Form.Item
            name="weight"
            label="权重 (0-100)"
            rules={[
              { required: true, message: "请输入权重" },
              { type: "number", min: 0, max: 100, message: "权重范围为 0-100" },
            ]}
          >
            <InputNumber
              style={{ width: "100%" }}
              min={0}
              max={100}
              step={5}
              suffix="%"
            />
          </Form.Item>

          <Form.Item name="enabled" label="启用" valuePropName="checked">
            <Switch />
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit" icon={<SaveOutlined />}>
                保存
              </Button>
              <Button onClick={() => setModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
