// src/components/OverlapImageShow/index.tsx
import { Point } from "@/components/AlgorithmToolBar/types";
import DraggableLine from "@/components/DraggableLine";
import React, { CSSProperties, useEffect, useRef, useState } from "react";

interface OverlapImageShowProps {
  image1: string;
  image2: string;
  showMask?: boolean;
  contrast?: number;
  brightness?: number;
  height?: number;
  onOriginScaleChange: (value: number) => void;
  onMouseover: (point: Point) => void;
}

const OverlapImageShow: React.FC<OverlapImageShowProps> = ({
  image1,
  image2,
  showMask = false,
  contrast = 0,
  brightness = 0,
  height = 700,
  onOriginScaleChange,
  onMouseover,
}) => {
  const image1Ref = useRef<HTMLImageElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [imageSize, setImageSize] = useState<{ width: number; height: number }>(
    { width: 0, height: 0 }
  );
  const maskRef = useRef<HTMLDivElement>(null);
  const [maskStyle, setMaskStyle] = useState<CSSProperties>({
    width: "100px",
    height: "100px",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    position: "absolute",
    display: "none",
  });
  const [sliderPosition, setSliderPosition] = useState(0);
  const sliderValue =
    (1 - sliderPosition / (image1Ref.current?.width || 1)) * 100;

  useEffect(() => {
    if (image1Ref.current) {
      const naturalHeight = image1Ref.current.naturalHeight;
      const naturalWidth = image1Ref.current.naturalWidth;
      const originScale = naturalHeight / (image1Ref.current.height || 1);

      onOriginScaleChange?.(originScale);
    }
  }, [image1Ref, height, onOriginScaleChange]);

  const mousemove: React.MouseEventHandler<HTMLDivElement> = (event) => {
    const getMaskStyleTopAndLeft = () => {
      let top = event.clientY - (maskRef.current?.offsetHeight || 0) / 2;
      let left = event.clientX - (maskRef.current?.offsetWidth || 0) / 2;

      if (top + (maskRef.current?.offsetHeight || 0) > height) {
        top = height - (maskRef.current?.offsetHeight || 0);
      }
      if (
        left + (maskRef.current?.offsetWidth || 0) >
        (image1Ref.current?.width || 0)
      ) {
        left =
          (image1Ref.current?.width || 0) - (maskRef.current?.offsetWidth || 0);
      }
      if (top < 0) {
        top = 0;
      }
      if (left < 0) {
        left = 0;
      }
      return { maskTop: top, maskLeft: left };
    };

    onMouseover?.({ x: event.clientX, y: event.clientY });

    const { maskTop, maskLeft } = getMaskStyleTopAndLeft();

    setMaskStyle({ ...maskStyle, top: `${maskTop}px`, left: `${maskLeft}px` });
  };

  const mouseover = () => {
    setMaskStyle({ ...maskStyle, display: "block" });
  };

  const mouseleave = () => {
    setMaskStyle({ ...maskStyle, display: "none" });
  };

  return (
    <div
      onMouseLeave={mouseleave}
      onMouseMove={mousemove}
      onMouseOver={mouseover}
      ref={containerRef}
      style={{
        position: "relative",
        width: image1Ref.current?.width || "unset",
        height: image1Ref.current?.height || height,
        overflow: "hidden",
      }}
    >
      <img
        src={image1}
        ref={image1Ref}
        alt="image1"
        style={{
          position: "absolute",
          clipPath: `inset(0 ${sliderValue}% 0 0)`,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          // filter: `brightness(${brightness}%) contrast(${contrast}%)`,
        }}
      />
      <img
        src={image2}
        alt="image2"
        style={{
          position: "absolute",
          clipPath: `inset(0 0 0 ${100 - sliderValue}%)`,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          // filter: `brightness(${brightness}%) contrast(${contrast}%)`,
        }}
      />
      {showMask && (
        <div ref={maskRef} style={maskStyle} className="mouse-mask"></div>
      )}
      <DraggableLine
        leftLabel="原图"
        rightLabel="对比图"
        onUpdateOffset={(value: number) => setSliderPosition(value)}
      />
    </div>
  );
};

export default OverlapImageShow;

// src/components/OverlapImageShow/index.vue
<script lang="ts" setup>
import DraggableLine from "@/components/DraggableLine/index.vue";
import { transform } from "@/components/AlgorithmToolBar/utils";
import { CSSProperties } from "vue";

defineOptions({
  name: "OverlapImageShow",
});

const props = defineProps({
  image1: {
    type: String,
    required: true,
  },
  image2: {
    type: String,
    required: true,
  },
  showMask: {
    type: Boolean,
    default: false,
  },
  contrast: {
    type: Number,
    default: 0,
  },
  brightness: {
    type: Number,
    default: 0,
  },
  height: {
    type: Number,
    default: 500,
  },
});

const emit = defineEmits(["onOriginScaleChange", "onMouseover"]);

const { image1, image2, showMask, contrast, brightness } = toRefs(props);

const maskRef = ref<HTMLDivElement>();
const maskStyle = ref<CSSProperties>({
  width: "100px",
  height: "100px",
  backgroundColor: "rgba(0, 0, 0, 0.5)",
  position: "absolute",
  display: "none",
});

const image1Ref = ref<HTMLImageElement>();
const {
  elementX,
  elementY,
  elementWidth: imgWidth,
  elementHeight: imgHeight,
  isOutside,
} = useMouseInElement(image1Ref);

const originScale = computed(() => {
  if (image1Ref.value) return imgHeight.value / image1Ref.value.height;
  return 1;
});

const sliderPosition = ref(0);
const sliderValue = computed(() => {
  return (1 - sliderPosition.value / imgWidth.value) * 100;
});

function updateImageStyle() {
  const images = document.querySelectorAll(".image-container img");
  images.forEach((img: Element) => {
    (img as HTMLImageElement).style.filter = `
    contrast(${transform(contrast.value)}%)
    brightness(${transform(brightness.value)}%)`;
  });
}

function mousemove(event: MouseEvent) {
  if (isOutside.value) return;

  function getMaskStyleTopAndLeft() {
    let top = elementY.value - maskRef.value!.offsetHeight / 2;
    let left = elementX.value - maskRef.value!.offsetWidth / 2;

    if (top + maskRef.value!.offsetHeight > imgHeight.value) {
      top = imgHeight.value - maskRef.value!.offsetHeight;
    }
    if (left + maskRef.value!.offsetWidth > imgWidth.value) {
      left = imgWidth.value - maskRef.value!.offsetWidth;
    }
    if (top < 0) {
      top = 0;
    }
    if (left < 0) {
      left = 0;
    }
    return { maskTop: top, maskLeft: left };
  }

  let { maskTop, maskLeft } = getMaskStyleTopAndLeft();
  maskStyle.value.top = maskTop + "px";
  maskStyle.value.left = maskLeft + "px";
}

function mouseover() {
  maskStyle.value.display = "block";
}

function mouseleave() {
  maskStyle.value.display = "none";
}

onMounted(() => {
  watch([contrast, brightness], () => updateImageStyle());
  watch([originScale], () => emit("onOriginScaleChange", originScale.value));

  watch([isOutside, elementX, elementY], () => {
    if (!isOutside.value)
      emit("onMouseover", { x: elementX.value, y: elementY.value });
  });
});
</script>

<template>
  <div
    :style="{
      width: image1Ref ? image1Ref.width + 'px' : 'auto',
      height: height + 'px',
    }"
    class="image-container"
    @mouseleave="mouseleave"
    @mousemove="mousemove"
    @mouseover="mouseover"
  >
    <img
      ref="image1Ref"
      :src="image1"
      :style="{ clipPath: `inset(0 ${sliderValue}% 0 0)` }"
      alt=""
    />
    <img
      :src="image2"
      :style="{ clipPath: `inset(0 0 0 ${100 - sliderValue}%)` }"
      alt=""
    />
    <div
      v-show="showMask"
      ref="maskRef"
      :style="maskStyle"
      class="mouse-mask"
    ></div>
    <DraggableLine
      left-label="原图"
      right-label="对比图"
      @update:offset="(value) => (sliderPosition = value)"
    />
  </div>
</template>

<style lang="scss" scoped>
.image-container {
  position: relative;
  overflow: hidden;
}

.image-container img {
  position: absolute;
  height: 100%;
  object-fit: cover;
}

.mouse-mask {
  position: fixed;
  cursor: crosshair;
  background-color: rgb(0 0 0 / 50%);
}
</style>
