// src/components/AlgorithmToolBar/index.tsx
import { RootState } from "@/store";
import {
  setBrightness,
  setContrast,
  setMagnifierShape,
  setMagnifierSize,
  setMagnifierZoomLevel,
  setSaturate,
  toggleDividerShow,
  toggleMagnifierShow,
} from "@/store/modules/imageShowSlice";
import {
  selectDisableGenerate,
  selectDividerEnabled,
  selectMagnifierZoomLevel,
} from "@/store/selector/imageShowSelector";
import { DownOutlined } from "@ant-design/icons";
import {
  Button,
  Card,
  Dropdown,
  Form,
  Menu,
  Radio,
  Slider,
  Typography,
} from "antd";
import React, { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import styles from "./index.module.scss";

interface AlgorithmToolBarProps {
  title?: string;
  description?: string;
  disableMore: boolean;
  onUpload: (file: File) => void;
  onTakePhoto: () => void;
  onEval: () => void;
  onReset: () => void;
  onGenerate: () => void;
  onSelectFromDataset: () => void;
  children: React.ReactNode;
}

const AlgorithmToolBar: React.FC<AlgorithmToolBarProps> = ({
  title = "图像去雾",
  description = "通过对遭受雾气影响的图像进行相应处理，恢复图像原本的纹理结构和细节信息，进而提升图像的能见度",
  disableMore,
  onUpload,
  onTakePhoto,
  onEval,
  onReset,
  onGenerate,
  onSelectFromDataset,
  children,
}) => {
  const dispatch = useDispatch();
  const brightness = useSelector(
    (state: RootState) => state.imageShow.brightness
  );
  const contrast = useSelector((state: RootState) => state.imageShow.contrast);
  const saturate = useSelector((state: RootState) => state.imageShow.saturate);

  const magnifierEnabled = useSelector(
    (state: RootState) => state.imageShow.magnifier.enabled
  );
  const magnifierShape = useSelector(
    (state: RootState) => state.imageShow.magnifier.shape
  );
  const magnifierZoomLevel = useSelector(selectMagnifierZoomLevel);
  const magnifierWidth = useSelector(
    (state: RootState) => state.imageShow.magnifier.width
  );
  const magnifierHeight = useSelector(
    (state: RootState) => state.imageShow.magnifier.height
  );
  const dividerEnabled = useSelector(selectDividerEnabled);
  const disableGenerate = useSelector(selectDisableGenerate);
  const loading = useSelector((state: RootState) => state.imageShow.loading);

  // 本地状态管理滤镜开关
  const [filterStates, setFilterStates] = useState({
    brightnessEnabled: true,
    contrastEnabled: true,
    saturateEnabled: true,
  });

  const windowWidth = useRef(window.innerWidth);

  useEffect(() => {
    const handleResize = () => (windowWidth.current = window.innerWidth);
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleMagnifierToggle = () => {
    dispatch(toggleMagnifierShow());
  };

  const handleDividerToggle = () => {
    dispatch(toggleDividerShow());
  };

  const handleFilterToggle = (type: "brightness" | "contrast" | "saturate") => {
    setFilterStates((prev) => ({
      ...prev,
      [`${type}Enabled`]: !prev[`${type}Enabled`],
    }));
  };

  const handleMagnifierChange = (
    type: "shape" | "zoomLevel" | "width" | "height",
    value: any
  ) => {
    switch (type) {
      case "shape":
        dispatch(setMagnifierShape(value));
        break;
      case "zoomLevel":
        dispatch(setMagnifierZoomLevel(value));
        break;
      case "width":
        dispatch(setMagnifierSize({ width: value, height: magnifierHeight }));
        break;
      case "height":
        dispatch(setMagnifierSize({ width: magnifierWidth, height: value }));
        break;
      default:
        break;
    }
  };

  const handleFilterChange = (
    type: "brightness" | "contrast" | "saturate",
    value: number
  ) => {
    switch (type) {
      case "brightness":
        dispatch(setBrightness(value));
        break;
      case "contrast":
        dispatch(setContrast(value));
        break;
      case "saturate":
        dispatch(setSaturate(value));
        break;
      default:
        break;
    }
  };

  const renderMoreMenu = () => (
    <Menu>
      <Menu.Item onClick={handleMagnifierToggle}>
        {magnifierEnabled ? "关闭" : "开启"}放大镜
      </Menu.Item>
      <Menu.Item onClick={handleDividerToggle}>
        {dividerEnabled ? "关闭" : "开启"}拖拽线
      </Menu.Item>
      <Menu.Item onClick={() => handleFilterToggle("brightness")}>
        {filterStates.brightnessEnabled ? "关闭" : "开启"}亮度调整
      </Menu.Item>
      <Menu.Item onClick={() => handleFilterToggle("contrast")}>
        {filterStates.contrastEnabled ? "关闭" : "开启"}对比度调整
      </Menu.Item>
      <Menu.Item onClick={() => handleFilterToggle("saturate")}>
        {filterStates.saturateEnabled ? "关闭" : "开启"}饱和度调整
      </Menu.Item>
      <Menu.Item onClick={onSelectFromDataset}>从现有数据集中选择</Menu.Item>
      <Menu.Item onClick={onEval}>评估结果</Menu.Item>
    </Menu>
  );

  return (
    <div className={styles.sidebarContainer}>
      <Card className={styles.sidebarCard}>
        <Typography.Title level={3} className={styles.title}>
          {title}
        </Typography.Title>
        <Typography.Text className={styles.description}>
          {description}
        </Typography.Text>

        <div className={styles.buttonGroup}>
          <Dropdown overlay={renderMoreMenu} trigger={["click"]}>
            <Button>
              更多功能 <DownOutlined />
            </Button>
          </Dropdown>
          <Button onClick={onReset}>清除结果</Button>
        </div>

        {children}

        <div className={styles.generateButtonGroup}>
          <Button
            type="primary"
            disabled={disableGenerate}
            loading={loading}
            onClick={onGenerate}
          >
            {loading ? "正在生成" : "立即生成"}
          </Button>
          <Button onClick={onEval}>评估结果</Button>
        </div>

        <Form className={styles.form}>
          {magnifierEnabled && !disableMore && (
            <div className={styles.magnifierOptions}>
              <Form.Item label="放大镜形状">
                <Radio.Group
                  value={magnifierShape}
                  onChange={(e) =>
                    handleMagnifierChange("shape", e.target.value)
                  }
                >
                  <Radio value="square">正方形</Radio>
                  <Radio value="circle">圆形</Radio>
                </Radio.Group>
              </Form.Item>
              <Form.Item label="放大倍数">
                <Slider
                  min={2}
                  max={20}
                  value={magnifierZoomLevel}
                  onChange={(v) => handleMagnifierChange("zoomLevel", v)}
                />
              </Form.Item>
              <Form.Item label="放大镜宽度">
                <Slider
                  min={100}
                  max={1000}
                  value={magnifierWidth}
                  onChange={(v) => handleMagnifierChange("width", v)}
                />
              </Form.Item>
              <Form.Item label="放大镜高度">
                <Slider
                  min={100}
                  max={1000}
                  value={magnifierHeight}
                  onChange={(v) => handleMagnifierChange("height", v)}
                />
              </Form.Item>
            </div>
          )}

          {filterStates.brightnessEnabled && !disableMore && (
            <Form.Item label="亮度">
              <Slider
                min={-100}
                max={100}
                value={brightness}
                onChange={(v) => handleFilterChange("brightness", v)}
              />
            </Form.Item>
          )}

          {filterStates.contrastEnabled && !disableMore && (
            <Form.Item label="对比度">
              <Slider
                min={-100}
                max={100}
                value={contrast}
                onChange={(v) => handleFilterChange("contrast", v)}
              />
            </Form.Item>
          )}

          {filterStates.saturateEnabled && !disableMore && (
            <Form.Item label="饱和度">
              <Slider
                min={-100}
                max={100}
                value={saturate}
                onChange={(v) => handleFilterChange("saturate", v)}
              />
            </Form.Item>
          )}
        </Form>
      </Card>
    </div>
  );
};

export default AlgorithmToolBar;

// dehaze-front-vue/src/components/AlgorithmToolBar/index.vue
<script lang="ts" setup>
import Magnifier from "@/components/Magnifier/newIndex.vue";
import { useImageShowStore } from "@/store/modules/imageShow";
import { Arrayable, useWindowSize } from "@vueuse/core";
import { UploadFile, UploadUserFile } from "element-plus";

defineOptions({
  name: "AlgorithmToolBar",
});

const props = defineProps({
  title: {
    type: String,
    default: "图像去雾",
  },
  description: {
    type: String,
    default:
      "通过对遭受雾气影响的图像进行相应处理，恢复图像原本的纹理结构和细节信息，进而提升图像的能见度",
  },
  disableMore: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits([
  "onUpload",
  "onTakePhoto",
  "onReset",
  "onEval",
  "onGenerate",
  "onSelectFromDataset",
]);

const imageShowStore = useImageShowStore();

const { width } = useWindowSize();

const labelPosition = ref<"top" | "left" | "right">("left");
watch(
  () => width.value,
  (newValue) => {
    if (newValue >= 992) {
      labelPosition.value = "left";
    } else {
      labelPosition.value = "top";
    }
  }
);

const state = reactive({
  magnifier: {
    enabled: imageShowStore.magnifierInfo.enabled,
    shape: imageShowStore.magnifierInfo.shape,
    width: imageShowStore.magnifierInfo.width,
    height: imageShowStore.magnifierInfo.height,
    zoomLevel: imageShowStore.magnifierInfo.zoomLevel,
  },
  brightness: {
    enabled: true,
    value: 0,
  },
  contrast: {
    enabled: true,
    value: 0,
  },
  saturate: {
    enabled: true,
    value: 0,
  },
  divider: true,
});

const cardRef = ref<HTMLDivElement>();

const buttonText = computed(() => {
  if (imageShowStore.loading) return "正在生成";
  return "立即生成";
});

onMounted(() => {
  const { width: barWidth } = useElementBounding(cardRef.value);
  watch(
    () => barWidth,
    () => {
      if (barWidth.value > 0) {
        let value = (barWidth.value - 30 - 40 - 20) / 2;
        state.magnifier.width = value;
        state.magnifier.height = value;
        handleMagnifierChange(value, "width");
        handleMagnifierChange(value, "height");
      }
    },
    { deep: true }
  );
});

function transform(x: number) {
  return 0.5 * x + 100;
}

function handleMagnifierChange(
  value: any,
  type: "shape" | "zoomLevel" | "width" | "height" | "enable"
) {
  switch (type) {
    case "enable":
      state.magnifier.enabled = !state.magnifier.enabled;
      imageShowStore.setMagnifierShow(state.magnifier.enabled);
      break;
    case "shape":
      imageShowStore.setMagnifierShape(value);
      break;
    case "zoomLevel":
      imageShowStore.setMagnifierZoomLevel(value);
      break;
    case "height":
      imageShowStore.setMagnifierSize(state.magnifier.width, value);
      break;
    case "width":
      imageShowStore.setMagnifierSize(value, state.magnifier.height);
      break;
    default:
      break;
  }
}

function handleImageFilterChange(
  value: number,
  type: "brightness" | "contrast" | "saturate"
) {
  value = transform(value);
  switch (type) {
    case "brightness":
      imageShowStore.setBrightness(value);
      break;
    case "contrast":
      imageShowStore.setContrast(value);
      break;
    case "saturate":
      imageShowStore.setSaturate(value);
      break;
    default:
      break;
  }
}

function handleDividerChange() {
  state.divider = !state.divider;
  imageShowStore.toggleDividerShow();
}

function handleUploadChange(uploadFile: UploadFile) {
  emit("onUpload", uploadFile.raw);
}

function handleUploadExceed(files: File[], uploadFiles: UploadUserFile[]) {
  if (files.length === 0) {
    return;
  }
  emit("onUpload", files[0]);
}

function handleEval() {
  emit("onEval");
}

watch(
  () => imageShowStore.magnifierInfo.zoomLevel,
  (newValue) => (state.magnifier.zoomLevel = newValue)
);
</script>

<template>
  <div class="mr-3">
    <el-card ref="cardRef" class="sidebar-card">
      <h2 class="text-center m2">{{ title }}</h2>
      <el-text class="m2">
        {{ description }}
      </el-text>

      <div class="flex justify-evenly m-4">
        <el-dropdown split-button type="primary">
          <el-upload
            :auto-upload="false"
            :limit="1"
            :on-change="handleUploadChange"
            :on-exceed="handleUploadExceed"
            :show-file-list="false"
            accept="image/gif, image/jpeg, image/jpg, image/png, image/svg"
            action="#"
          >
            本地上传
          </el-upload>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item @click="emit('onTakePhoto')">
                拍照上传
              </el-dropdown-item>
              <el-dropdown-item @click="emit('onSelectFromDataset')">
                从现有数据集中选择
              </el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
        <el-button id="algorithm-reset-button" @click="emit('onReset')"
          >清除结果
        </el-button>
      </div>
      <slot></slot>
      <div class="flex justify-evenly m-4">
        <el-button
          id="algorithm-generate-button"
          :disabled="imageShowStore.disableGenerate"
          :loading="imageShowStore.loading"
          type="primary"
          @click="emit('onGenerate')"
        >
          {{ buttonText }}
        </el-button>
        <el-dropdown :disabled="disableMore">
          <el-button :disabled="disableMore">更多功能</el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item
                @click="() => handleMagnifierChange(0, 'enable')"
              >
                {{ state.magnifier.enabled ? "关闭" : "开启" }}放大镜
              </el-dropdown-item>
              <el-dropdown-item @click="handleDividerChange">
                {{ state.divider ? "关闭" : "开启" }}拖拽线
              </el-dropdown-item>
              <el-dropdown-item
                @click="state.brightness.enabled = !state.brightness.enabled"
              >
                {{ state.brightness.enabled ? "关闭" : "开启" }}亮度调整
              </el-dropdown-item>
              <el-dropdown-item
                @click="state.contrast.enabled = !state.contrast.enabled"
              >
                {{ state.contrast.enabled ? "关闭" : "开启" }}对比度调整
              </el-dropdown-item>
              <el-dropdown-item
                @click="state.saturate.enabled = !state.saturate.enabled"
              >
                {{ state.saturate.enabled ? "关闭" : "开启" }}饱和度调整
              </el-dropdown-item>
              <el-dropdown-item @click="handleEval"> 评估结果</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </div>

      <template v-if="state.magnifier.enabled && !disableMore">
        <div class="flex justify-between flex-wrap items-center mb-3">
          <Magnifier
            v-for="url in imageShowStore.imageInfo.images.urls"
            :key="url.id"
            :label="url.label"
            :src="url.url"
          />
        </div>
      </template>

      <el-form :label-position="labelPosition" label-width="7.2vw">
        <template v-if="state.magnifier.enabled && !disableMore">
          <el-form-item class="more-operations" label="放大镜形状">
            <el-radio-group
              v-model="state.magnifier.shape"
              @change="
                (value: string | number | boolean | undefined) =>
                  handleMagnifierChange(value, 'shape')
              "
            >
              <el-radio label="square" value="square">正方形</el-radio>
              <el-radio label="circle" value="circle">圆形</el-radio>
            </el-radio-group>
          </el-form-item>

          <el-form-item class="more-operations" label="放大倍数">
            <el-slider
              v-model="state.magnifier.zoomLevel"
              :max="20"
              :min="2"
              @change="
                (value: Arrayable<number>) =>
                  handleMagnifierChange(value, 'zoomLevel')
              "
            />
          </el-form-item>

          <el-form-item class="more-operations" label="放大镜宽度">
            <el-slider
              v-model="state.magnifier.width"
              :max="1000"
              :min="100"
              @change="
                (value: Arrayable<number>) =>
                  handleMagnifierChange(value, 'width')
              "
            />
          </el-form-item>
          <el-form-item class="more-operations" label="放大镜高度">
            <el-slider
              v-model="state.magnifier.height"
              :max="1000"
              :min="100"
              @change="
                (value: Arrayable<number>) =>
                  handleMagnifierChange(value, 'height')
              "
            />
          </el-form-item>
        </template>

        <template v-if="state.brightness.enabled && !disableMore">
          <el-form-item class="more-operations" label="亮度">
            <el-slider
              v-model="state.brightness.value"
              :max="100"
              :min="-100"
              @change="
                (value: Arrayable<number>) =>
                  handleImageFilterChange(Number(value), 'brightness')
              "
            />
          </el-form-item>
        </template>

        <template v-if="state.contrast.enabled && !disableMore">
          <el-form-item class="more-operations" label="对比度">
            <el-slider
              v-model="state.contrast.value"
              :max="100"
              :min="-100"
              @change="
                (value: Arrayable<number>) =>
                  handleImageFilterChange(Number(value), 'contrast')
              "
            />
          </el-form-item>
        </template>

        <template v-if="state.saturate.enabled && !disableMore">
          <el-form-item class="more-operations" label="饱和度">
            <el-slider
              v-model="state.saturate.value"
              :max="100"
              :min="-100"
              @change="
                (value: Arrayable<number>) =>
                  handleImageFilterChange(Number(value), 'saturate')
              "
            />
          </el-form-item>
        </template>
      </el-form>
    </el-card>
  </div>
</template>

<style lang="scss" scoped>
.sidebar-card {
  width: 35vw;
  height: 100%;
  padding: 0 15px;
  overflow-y: auto;
  text-align: center;
}

@media screen and (width <= 992px) {
  .sidebar-card {
    width: 96vw;
  }
}

@media screen and (width <= 767px) {
  .sidebar-card {
    width: 94vw;
  }
}
</style>

<style lang="scss">
.more-operations {
  margin-bottom: 5px;
}
</style>
