// dehaze-uniapp/src/pages/profile/index.vue
<template>
  <PageLayout level="L1" title="我的" class="page">
    <view class="main-content">
      <!-- 用户卡 -->
      <view class="user-card">
        <view class="user-info">
          <image
            v-if="auth.userInfo?.avatar"
            :src="auth.userInfo.avatar"
            class="avatar-img"
          />
          <view v-else class="avatar-placeholder">
            <text class="avatar-text">{{ initial }}</text>
          </view>
          <view class="user-text">
            <view class="user-name-row">
              <text class="nickname">{{ auth.nickname || auth.username }}</text>
              <view v-if="auth.roles.length > 0" class="role-tags">
                <text v-for="role in auth.roles" :key="role" class="role-tag">{{
                  formatRole(role)
                }}</text>
              </view>
            </view>
            <text class="username">@{{ auth.username }}</text>
          </view>
        </view>
      </view>

      <!-- VIP 横幅 -->
      <view class="vip-banner" @click="handleMember">
        <view class="vip-info">
          <text class="vip-title" v-if="isVip">
            {{ memberProfile.levelName }} · 成长值
            {{ memberProfile.growthValue }}
          </text>
          <text class="vip-title" v-else>开通 VIP 畅享更多次数</text>
          <text class="vip-subtitle" v-if="isVip">
            本月已用 {{ memberProfile.monthlyUsed }} 次
          </text>
          <text class="vip-subtitle" v-else>解锁全部高级功能</text>
        </view>
        <view class="vip-action">
          <text>{{ isVip ? "查看权益" : "去开通" }}</text>
          <SvgIcon name="arrow-right" size="14" color="#fff" />
        </view>
      </view>

      <!-- 数据统计 -->
      <view class="stats-row">
        <view class="stat-item" @click="handleQuota">
          <text class="stat-value">{{ quota.remaining }}</text>
          <text class="stat-label">剩余额度</text>
        </view>
        <view class="stat-item" @click="handleTaskHistory">
          <text class="stat-value">{{ quota.used }}</text>
          <text class="stat-label">本月处理</text>
        </view>
        <view class="stat-item" @click="handleFavorite">
          <text class="stat-value">{{ favCount }}</text>
          <text class="stat-label">我的收藏</text>
        </view>
      </view>

      <!-- 分组入口：个人数据 -->
      <view class="menu-group">
        <text class="group-title">个人数据</text>
        <view class="menu-card">
          <MenuItem
            icon="folder"
            icon-color="#10b981"
            label="我的文件"
            @click="goPersonal('files')"
          />
          <MenuItem
            icon="database"
            icon-color="#6366f1"
            label="我的数据集"
            @click="goPage('/pages/dataset/index')"
          />
          <MenuItem
            icon="clock"
            icon-color="#6366f1"
            label="处理历史"
            @click="goPage('/pages/task-history/index')"
          />
          <MenuItem
            icon="star"
            icon-color="#f59e0b"
            label="我的收藏"
            @click="goPersonal('favorites')"
          />
        </view>
      </view>

      <!-- 分组入口：商业服务 -->
      <view class="menu-group">
        <text class="group-title">商业服务</text>
        <view class="menu-card">
          <MenuItem
            icon="man-delete"
            icon-color="#3b82f6"
            label="我的会员"
            @click="goPersonal('member')"
          />
          <MenuItem
            icon="rmb-circle"
            icon-color="#f59e0b"
            label="我的套餐"
            @click="goPersonal('package')"
          />
          <MenuItem
            icon="order"
            icon-color="#10b981"
            label="我的订单"
            @click="goPersonal('orders')"
          />
          <MenuItem
            icon="calendar"
            icon-color="#8b5cf6"
            label="我的额度"
            @click="goPersonal('quota')"
          />
          <MenuItem
            icon="edit-pen"
            icon-color="#ec4899"
            label="反馈评价"
            @click="goPersonal('feedback')"
          />
        </view>
      </view>

      <!-- 分组入口：其他 -->
      <view class="menu-group">
        <text class="group-title">其他</text>
        <view class="menu-card">
          <MenuItem
            icon="setting"
            icon-color="#6b7280"
            label="系统设置"
            @click="goPersonal('settings')"
          />
          <MenuItem
            icon="question-circle"
            icon-color="#3b82f6"
            label="帮助中心"
            @click="goPersonal('help')"
          />
          <MenuItem
            icon="info-circle"
            icon-color="#9ca3af"
            label="关于我们"
            @click="goPersonal('about')"
          />
          <MenuItem
            icon="bell"
            icon-color="#f59e0b"
            label="消息设置"
            @click="goPage('/pages/notify/index')"
          />
        </view>
      </view>

      <!-- 管理入口（权限过滤） -->
      <view v-if="hasAnyAdminPerm" class="menu-group">
        <text class="group-title">管理入口</text>
        <view class="menu-card">
          <template v-if="hasPermGroup('algorithm') || hasPermGroup('dataset')">
            <text class="sub-group-title">算法与数据</text>
            <MenuItem
              v-if="auth.hasPerm('sys:algorithm:*')"
              icon="cpu"
              icon-color="#3b82f6"
              label="算法管理"
              @click="goPage('/pages/system/algorithm/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dataset:*')"
              icon="database"
              icon-color="#6366f1"
              label="数据集管理"
              @click="goPage('/pages/system/dataset/index')"
            />
          </template>

          <template v-if="hasPermGroup('sys')">
            <text class="sub-group-title">系统管理</text>
            <MenuItem
              v-if="auth.hasPerm('sys:user:*')"
              icon="account"
              icon-color="#10b981"
              label="用户管理"
              @click="goPage('/pages/system/user/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:role:*')"
              icon="grid"
              icon-color="#f59e0b"
              label="角色管理"
              @click="goPage('/pages/system/role/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:menu:*')"
              icon="list-dot"
              icon-color="#8b5cf6"
              label="菜单管理"
              @click="goPage('/pages/system/menu/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dept:*')"
              icon="home"
              icon-color="#ec4899"
              label="部门管理"
              @click="goPage('/pages/system/dept/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dict:*')"
              icon="bookmark"
              icon-color="#14b8a6"
              label="字典管理"
              @click="goPage('/pages/system/dict/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:task:*')"
              icon="play-circle"
              icon-color="#f97316"
              label="任务管理"
              @click="goPage('/pages/system/task/index')"
            />
          </template>

          <template v-if="hasPermGroup('biz')">
            <text class="sub-group-title">运营管理</text>
            <MenuItem
              v-if="auth.hasPerm('sys:member:*')"
              icon="man-delete"
              icon-color="#3b82f6"
              label="会员管理"
              @click="goPage('/pages/system/member/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:package:*')"
              icon="rmb-circle"
              icon-color="#f59e0b"
              label="套餐管理"
              @click="goPage('/pages/system/package/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:order:*')"
              icon="order"
              icon-color="#10b981"
              label="订单管理"
              @click="goPage('/pages/system/order/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:feedback:*')"
              icon="edit-pen"
              icon-color="#ec4899"
              label="反馈评价管理"
              @click="goPage('/pages/system/feedback/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:recommendation:*')"
              icon="thumb-up"
              icon-color="#8b5cf6"
              label="推荐管理"
              @click="goPage('/pages/system/recommend/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:notify:*')"
              icon="bell"
              icon-color="#f97316"
              label="消息管理"
              @click="goPage('/pages/system/message/index')"
            />
          </template>
        </view>
      </view>

      <!-- 退出登录 -->
      <view class="logout-area">
        <view class="logout-btn" @click="handleLogout">
          <SvgIcon name="close-circle" size="22" color="#ef4444" />
          <text class="logout-text">退出登录</text>
        </view>
      </view>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import PageLayout from "@/layout/index.vue";
import MenuItem from "./components/MenuItem.vue";
import { useAuthStore } from "@/store/auth";
import { LOGIN_PATH } from "@/routers/guard";
import { MemberAPI, ModelAPI, FavoriteAPI } from "dehaze-sdk-js";

const auth = useAuthStore();

const initial = computed(() =>
  (auth.nickname || auth.username || "U").charAt(0).toUpperCase()
);

// VIP/会员信息
const memberProfile = ref({
  levelCode: "level_0",
  levelName: "",
  growthValue: 0,
  monthlyUsed: 0,
});

const isVip = computed(
  () =>
    memberProfile.value.levelCode !== "level_0" &&
    memberProfile.value.levelCode !== "level_1"
);

// 配额
const quota = ref({ remaining: 0, used: 0, total: 0 });

// 收藏数
const favCount = ref(0);

onMounted(async () => {
  try {
    const profile = await MemberAPI.getProfile();
    memberProfile.value = profile;
  } catch {
    // 非会员或无接口
  }

  try {
    const q = await ModelAPI.getQuota();
    quota.value = q;
  } catch {
    // 无数据
  }

  try {
    const c = await FavoriteAPI.getCount();
    const total = c.reduce((sum, item) => sum + item.count, 0);
    favCount.value = total;
  } catch {
    // 无数据
  }
});

function formatRole(role: string): string {
  return role.replace("ROLE_", "");
}

function goPage(url: string) {
  uni.navigateTo({ url });
}

function goPersonal(page: string) {
  uni.navigateTo({ url: `/pages/personal/${page}/index` });
}

function handleMember() {
  uni.navigateTo({ url: "/pages/personal/member/index" });
}

function handleQuota() {
  uni.navigateTo({ url: "/pages/personal/quota/index" });
}

function handleTaskHistory() {
  uni.navigateTo({ url: "/pages/task-history/index" });
}

function handleFavorite() {
  uni.navigateTo({ url: "/pages/personal/favorites/index" });
}

// 管理权限分组判断
const hasAnyAdminPerm = computed(() => {
  const adminPerms = [
    "sys:algorithm:*",
    "sys:dataset:*",
    "sys:user:*",
    "sys:role:*",
    "sys:menu:*",
    "sys:dept:*",
    "sys:dict:*",
    "sys:task:*",
    "sys:member:*",
    "sys:package:*",
    "sys:order:*",
    "sys:feedback:*",
    "sys:recommendation:*",
    "sys:notify:*",
  ];
  return adminPerms.some((p) => auth.hasPerm(p));
});

function hasPermGroup(group: string) {
  switch (group) {
    case "algorithm":
      return auth.hasPerm("sys:algorithm:*") || auth.hasPerm("sys:dataset:*");
    case "sys":
      return [
        "sys:user:*",
        "sys:role:*",
        "sys:menu:*",
        "sys:dept:*",
        "sys:dict:*",
        "sys:task:*",
      ].some((p) => auth.hasPerm(p));
    case "biz":
      return [
        "sys:member:*",
        "sys:package:*",
        "sys:order:*",
        "sys:feedback:*",
        "sys:recommendation:*",
        "sys:notify:*",
      ].some((p) => auth.hasPerm(p));
    default:
      return false;
  }
}

async function handleLogout() {
  uni.showModal({
    title: "确认退出",
    content: "退出登录后需要重新登录",
    confirmColor: "#ef4444",
    success: async (res) => {
      if (res.confirm) {
        try {
          await auth.logout();
          uni.showToast({ title: "已退出", icon: "success" });
          setTimeout(() => uni.reLaunch({ url: LOGIN_PATH }), 800);
        } catch {
          uni.reLaunch({ url: LOGIN_PATH });
        }
      }
    },
  });
}
</script>

<style lang="scss" scoped>
.page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}
.main-content {
  padding: $spacing-md;
  padding-bottom: calc(100rpx + constant(safe-area-inset-bottom));
  padding-bottom: calc(100rpx + env(safe-area-inset-bottom));
}

// 用户卡
.user-card {
  background: #fff;
  border-radius: $radius-xl;
  padding: $spacing-lg;
  margin-bottom: $spacing-md;
  box-shadow: $shadow-sm;
}
.user-info {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.avatar-img {
  width: 112rpx;
  height: 112rpx;
  border-radius: 50%;
  flex-shrink: 0;
}
.avatar-placeholder {
  width: 112rpx;
  height: 112rpx;
  border-radius: 50%;
  background: $color-bg-secondary;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.avatar-text {
  font-size: $font-xl;
  font-weight: 700;
  color: $color-text-secondary;
}
.user-text {
  flex: 1;
  min-width: 0;
}
.user-name-row {
  display: flex;
  align-items: center;
  gap: 12rpx;
  flex-wrap: wrap;
}
.nickname {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
}
.username {
  display: block;
  font-size: $font-sm;
  color: $color-text-placeholder;
  margin-top: 4rpx;
}
.role-tags {
  display: flex;
  gap: 8rpx;
  flex-wrap: wrap;
}
.role-tag {
  font-size: 20rpx;
  color: $color-secondary;
  background: #e0e7ff;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
  font-weight: 500;
}

// VIP 横幅
.vip-banner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: $gradient-primary;
  border-radius: $radius-lg;
  padding: 28rpx;
  margin-bottom: $spacing-md;
}
.vip-info {
  flex: 1;
}
.vip-title {
  font-size: $font-md;
  font-weight: 600;
  color: #fff;
  display: block;
}
.vip-subtitle {
  font-size: $font-xs;
  color: rgba(255, 255, 255, 0.8);
  margin-top: 4rpx;
  display: block;
}
.vip-action {
  display: flex;
  align-items: center;
  gap: 4rpx;
  background: rgba(255, 255, 255, 0.2);
  padding: 12rpx 24rpx;
  border-radius: 12rpx;
  font-size: $font-sm;
  color: #fff;
  flex-shrink: 0;
}

// 统计
.stats-row {
  display: flex;
  background: #fff;
  border-radius: $radius-xl;
  margin-bottom: $spacing-md;
  box-shadow: $shadow-sm;
}
.stat-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 28rpx 16rpx;
  &:active {
    background: #f9fafb;
  }
  & + & {
    border-left: 1rpx solid $color-border-light;
  }
}
.stat-value {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
}
.stat-label {
  font-size: $font-xs;
  color: $color-text-placeholder;
  margin-top: 4rpx;
}

// 菜单分组
.menu-group {
  margin-bottom: $spacing-md;
}
.group-title {
  display: block;
  font-size: $font-xs;
  font-weight: 500;
  color: $color-text-placeholder;
  text-transform: uppercase;
  padding: 0 4rpx 12rpx;
}
.menu-card {
  background: #fff;
  border-radius: $radius-xl;
  overflow: hidden;
  box-shadow: $shadow-sm;
}
.sub-group-title {
  display: block;
  font-size: $font-xs;
  color: $color-text-placeholder;
  padding: 20rpx 28rpx 8rpx;
}

// 退出
.logout-area {
  margin-top: 48rpx;
  padding: $spacing-md 0;
  display: flex;
  justify-content: center;
}
.logout-btn {
  display: flex;
  align-items: center;
  gap: 12rpx;
  padding: 20rpx 48rpx;
  background: #fff;
  border-radius: 16rpx;
  box-shadow: $shadow-sm;
  &:active {
    background: #f9fafb;
  }
}
.logout-text {
  font-size: $font-md;
  color: $color-danger;
}
</style>

// dehaze-react-native/src/pages/profile/index.tsx
/**
 * 个人中心（我的 Tab）
 *
 * 布局：用户卡 + VIP 横幅 + 数据统计 + 四组入口 + 管理入口（权限过滤）+ 退出登录
 * 用户信息来自 useAuthStore，会员/额度/收藏统计数据异步加载
 */
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Alert,
  RefreshControl,
  Image,
} from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import LinearGradient from 'react-native-linear-gradient';
import Ionicons from 'react-native-vector-icons/Ionicons';
import type { IoniconName } from '@/components/Icon';
import { MemberAPI, ModelAPI, FavoriteAPI, TaskAPI } from 'dehaze-sdk-js';
import type { MemberProfileVO } from 'dehaze-sdk-js';

import type { ProfileStackParamList } from '@/routes/types';
import { useAuthStore } from '@/store';
import { theme } from '@/theme';

type Props = NativeStackScreenProps<ProfileStackParamList, 'Profile'>;

// ==================== 类型 ====================

interface StatItem {
  label: string;
  value: string;
  route: keyof ProfileStackParamList;
}

interface EntryItem {
  icon: IoniconName;
  title: string;
  route: keyof ProfileStackParamList;
  permission?: string;
}

interface EntryGroup {
  title: string;
  entries: EntryItem[];
}

// ==================== 入口配置 ====================

const PERSONAL_DATA_ENTRIES: EntryItem[] = [
  { icon: 'document-text-outline', title: '我的文件', route: 'PersonalFiles' },
  { icon: 'server-outline', title: '我的数据集', route: 'Dataset' },
  { icon: 'time-outline', title: '处理历史', route: 'Task' },
  { icon: 'heart-outline', title: '我的收藏', route: 'PersonalFavorites' },
];

const BUSINESS_ENTRIES: EntryItem[] = [
  { icon: 'diamond-outline', title: '我的会员', route: 'PersonalMember' },
  { icon: 'cube-outline', title: '我的套餐', route: 'PersonalPackage' },
  { icon: 'cart-outline', title: '我的订单', route: 'PersonalOrders' },
  { icon: 'wallet-outline', title: '我的额度', route: 'PersonalQuota' },
  { icon: 'chatbox-outline', title: '反馈评价', route: 'PersonalFeedback' },
];

const OTHER_ENTRIES: EntryItem[] = [
  { icon: 'settings-outline', title: '系统设置', route: 'PersonalSettings' },
  { icon: 'help-circle-outline', title: '帮助中心', route: 'PersonalHelp' },
  { icon: 'information-circle-outline', title: '关于我们', route: 'PersonalAbout' },
  { icon: 'notifications-outline', title: '消息设置', route: 'Notify' },
];

// 管理入口分组（权限过滤，与 dev-admin 对齐）
const ADMIN_GROUPS: EntryGroup[] = [
  {
    title: '工作台',
    entries: [
      { icon: 'speedometer-outline', title: '工作台', route: 'SystemDashboard' },
    ],
  },
  {
    title: '算法与数据',
    entries: [
      { icon: 'git-network-outline', title: '算法管理', route: 'SystemAlgorithm', permission: 'sys:algorithm:*' },
      { icon: 'server-outline', title: '数据集管理', route: 'SystemDataset', permission: 'sys:dataset:*' },
    ],
  },
  {
    title: '系统管理',
    entries: [
      { icon: 'people-outline', title: '用户管理', route: 'SystemUser', permission: 'sys:user:*' },
      { icon: 'shield-checkmark-outline', title: '角色管理', route: 'SystemRole', permission: 'sys:role:*' },
      { icon: 'list-outline', title: '菜单管理', route: 'SystemMenu', permission: 'sys:menu:*' },
      { icon: 'business-outline', title: '部门管理', route: 'SystemDept', permission: 'sys:dept:*' },
      { icon: 'book-outline', title: '字典管理', route: 'SystemDict', permission: 'sys:dict:*' },
      { icon: 'timer-outline', title: '任务管理', route: 'SystemTask', permission: 'sys:task:*' },
    ],
  },
  {
    title: '运营管理',
    entries: [
      { icon: 'diamond-outline', title: '会员管理', route: 'SystemMember', permission: 'sys:member:*' },
      { icon: 'cube-outline', title: '套餐管理', route: 'SystemPackage', permission: 'sys:package:*' },
      { icon: 'cart-outline', title: '订单管理', route: 'SystemOrder', permission: 'sys:order:*' },
      { icon: 'chatbox-outline', title: '反馈评价管理', route: 'SystemFeedback', permission: 'sys:feedback:*' },
      { icon: 'trending-up-outline', title: '推荐管理', route: 'SystemRecommend', permission: 'sys:recommendation:*' },
      { icon: 'notifications-outline', title: '消息管理', route: 'SystemMessage', permission: 'sys:notify:*' },
    ],
  },
];

// ==================== 组件 ====================

const ProfileScreen: React.FC<Props> = ({ navigation }) => {
  const userInfo = useAuthStore(s => s.userInfo);
  const logout = useAuthStore(s => s.logout);
  const refreshUserInfo = useAuthStore(s => s.refreshUserInfo);
  const hasPerm = useAuthStore(s => s.hasPerm);

  const [member, setMember] = useState<MemberProfileVO | null>(null);
  const [quotaRemaining, setQuotaRemaining] = useState<number | null>(null);
  const [favoriteCount, setFavoriteCount] = useState<number | null>(null);
  const [taskCount, setTaskCount] = useState<number | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  // 加载会员信息
  const loadMember = useCallback(async () => {
    try {
      const profile = await MemberAPI.getProfile();
      setMember(profile);
    } catch {
      setMember(null);
    }
  }, []);

  // 加载统计数据
  const loadStats = useCallback(async () => {
    try {
      const quota = await ModelAPI.getQuota();
      setQuotaRemaining(quota.remaining ?? null);
    } catch {
      setQuotaRemaining(null);
    }
    try {
      const fav = await FavoriteAPI.getCount();
      if (fav && fav.length > 0) {
        const total = fav.reduce((sum, item) => sum + (item.count || 0), 0);
        setFavoriteCount(total);
      }
    } catch {
      setFavoriteCount(null);
    }
    try {
      const tasks = await TaskAPI.getPage({ pageNum: 1, pageSize: 1 });
      setTaskCount(tasks.total ?? null);
    } catch {
      setTaskCount(null);
    }
  }, []);

  useEffect(() => {
    loadMember();
    loadStats();
  }, [loadMember, loadStats]);

  const handleRefresh = useCallback(async () => {
    setRefreshing(true);
    await Promise.allSettled([refreshUserInfo(), loadMember(), loadStats()]);
    setRefreshing(false);
  }, [refreshUserInfo, loadMember, loadStats]);

  // 退出登录
  const handleLogout = useCallback(() => {
    Alert.alert('确认退出', '确定要退出登录吗？', [
      { text: '取消', style: 'cancel' },
      { text: '确定', style: 'destructive', onPress: () => logout() },
    ]);
  }, [logout]);

  // 过滤管理入口
  const visibleAdminGroups = useMemo(
    () =>
      ADMIN_GROUPS.map(g => ({
        ...g,
        entries: g.entries.filter(e => (e.permission ? hasPerm(e.permission) : true)),
      })).filter(g => g.entries.length > 0),
    [hasPerm],
  );

  // 数据统计
  const stats: StatItem[] = useMemo(
    () => [
      { label: '剩余额度', value: quotaRemaining !== null ? `${quotaRemaining} 次` : '-', route: 'PersonalQuota' },
      { label: '处理次数', value: taskCount !== null ? `${taskCount}` : '-', route: 'Task' },
      { label: '我的收藏', value: favoriteCount !== null ? `${favoriteCount}` : '-', route: 'PersonalFavorites' },
    ],
    [quotaRemaining, taskCount, favoriteCount],
  );

  // VIP 判断
  const isVip = !!member && member.levelCode !== 'level_0' && member.levelCode !== 'level_1';
  const avatarLetter = (userInfo?.nickname || userInfo?.username || 'U').charAt(0).toUpperCase();
  const nickname = userInfo?.nickname || '未登录';
  const roles = userInfo?.roles ?? [];

  const navigateTo = useCallback(
    (route: keyof ProfileStackParamList) => {
      (navigation.navigate as (screen: string) => void)(route as string);
    },
    [navigation],
  );

  // ==================== 渲染 ====================

  const renderEntryRow = (entry: EntryItem) => (
    <TouchableOpacity
      key={String(entry.route)}
      style={styles.entryRow}
      onPress={() => navigateTo(entry.route)}
      activeOpacity={0.6}
    >
      <View style={styles.entryIconWrap}>
        <Ionicons name={entry.icon} size={20} color={theme.colors.text.secondary} />
      </View>
      <Text style={styles.entryTitle}>{entry.title}</Text>
      <Ionicons name="chevron-forward" size={16} color={theme.colors.text.tertiary} />
    </TouchableOpacity>
  );

  const renderGroup = (group: EntryGroup) => (
    <View key={group.title} style={styles.groupSection}>
      <Text style={styles.groupTitle}>{group.title}</Text>
      <View style={styles.groupCard}>
        {group.entries.map((entry, idx) => (
          <React.Fragment key={String(entry.route)}>
            {idx > 0 && <View style={styles.entryDivider} />}
            {renderEntryRow(entry)}
          </React.Fragment>
        ))}
      </View>
    </View>
  );

  return (
    <View style={styles.container}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={handleRefresh}
            colors={[theme.colors.primary]}
            tintColor={theme.colors.primary}
          />
        }
      >
        {/* 用户卡 */}
        <LinearGradient
          colors={[theme.colors.primary, '#6366f1']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={styles.userCard}
        >
          <View style={styles.userCardInner}>
            <View style={styles.avatarWrap}>
              {userInfo?.avatar ? (
                <Image source={{ uri: userInfo.avatar }} style={styles.avatarImg} />
              ) : (
                <Text style={styles.avatarLetter}>{avatarLetter}</Text>
              )}
            </View>
            <View style={styles.userInfo}>
              <Text style={styles.nickname} numberOfLines={1}>{nickname}</Text>
              <View style={styles.roleRow}>
                {roles.length > 0 ? (
                  roles.slice(0, 2).map(role => (
                    <View key={role} style={styles.roleTag}>
                      <Text style={styles.roleTagText}>
                        {role.replace(/^ROLE_/, '')}
                      </Text>
                    </View>
                  ))
                ) : (
                  <Text style={styles.noRoleText}>普通用户</Text>
                )}
              </View>
            </View>
          </View>
        </LinearGradient>

        {/* VIP 横幅 */}
        <TouchableOpacity
          style={styles.vipBanner}
          onPress={() => navigateTo('PersonalMember')}
          activeOpacity={0.8}
        >
          <View style={styles.vipLeft}>
            <Ionicons name="diamond" size={22} color="#f59e0b" />
            <View style={styles.vipTextWrap}>
              <Text style={styles.vipTitle}>
                {isVip ? `${member?.levelName || '会员'}专属权益` : '开通 VIP 畅享更多次数'}
              </Text>
              <Text style={styles.vipDesc}>
                {isVip
                  ? `成长值 ${member?.growthValue || 0}，点击查看详情`
                  : '解锁全部高级功能'}
              </Text>
            </View>
          </View>
          <View style={styles.vipAction}>
            <Text style={styles.vipActionText}>{isVip ? '详情' : '去开通'}</Text>
            <Ionicons name="chevron-forward" size={14} color={theme.colors.primary} />
          </View>
        </TouchableOpacity>

        {/* 数据统计 */}
        <View style={styles.statsCard}>
          {stats.map((stat, idx) => (
            <TouchableOpacity
              key={stat.label}
              style={[styles.statItem, idx < stats.length - 1 && styles.statDivider]}
              onPress={() => navigateTo(stat.route)}
              activeOpacity={0.6}
            >
              <Text style={styles.statValue}>{stat.value}</Text>
              <Text style={styles.statLabel}>{stat.label}</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* 个人数据分组 */}
        <View style={styles.groupSection}>
          <Text style={styles.groupTitle}>个人数据</Text>
          <View style={styles.groupCard}>
            {PERSONAL_DATA_ENTRIES.map((entry, idx) => (
              <React.Fragment key={String(entry.route)}>
                {idx > 0 && <View style={styles.entryDivider} />}
                {renderEntryRow(entry)}
              </React.Fragment>
            ))}
          </View>
        </View>

        {/* 商业服务分组 */}
        <View style={styles.groupSection}>
          <Text style={styles.groupTitle}>商业服务</Text>
          <View style={styles.groupCard}>
            {BUSINESS_ENTRIES.map((entry, idx) => (
              <React.Fragment key={String(entry.route)}>
                {idx > 0 && <View style={styles.entryDivider} />}
                {renderEntryRow(entry)}
              </React.Fragment>
            ))}
          </View>
        </View>

        {/* 其他分组 */}
        <View style={styles.groupSection}>
          <Text style={styles.groupTitle}>其他</Text>
          <View style={styles.groupCard}>
            {OTHER_ENTRIES.map((entry, idx) => (
              <React.Fragment key={String(entry.route)}>
                {idx > 0 && <View style={styles.entryDivider} />}
                {renderEntryRow(entry)}
              </React.Fragment>
            ))}
          </View>
        </View>

        {/* 管理入口分组（权限过滤） */}
        {visibleAdminGroups.map(renderGroup)}

        {/* 退出登录 */}
        <TouchableOpacity
          style={styles.logoutBtn}
          onPress={handleLogout}
          activeOpacity={0.7}
        >
          <Ionicons name="log-out-outline" size={20} color={theme.colors.status.error} />
          <Text style={styles.logoutText}>退出登录</Text>
        </TouchableOpacity>

        {/* 页脚 */}
        <Text style={styles.footer}>图像去雾系统 v1.0</Text>
      </ScrollView>
    </View>
  );
};

// ==================== 样式 ====================

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.secondary,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: theme.spacing.xxxl,
  },
  // 用户卡
  userCard: {
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    borderRadius: theme.layout.borderRadius.xxl,
    ...theme.layout.shadows.lg,
  },
  userCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
  },
  avatarWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  avatarLetter: {
    fontSize: 28,
    fontWeight: theme.typography.weights.bold,
    color: '#fff',
  },
  userInfo: {
    flex: 1,
  },
  nickname: {
    fontSize: theme.typography.sizes.large,
    fontWeight: theme.typography.weights.bold,
    color: '#fff',
  },
  roleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  roleTag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.layout.borderRadius.full,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  roleTagText: {
    fontSize: theme.typography.sizes.tiny,
    fontWeight: theme.typography.weights.semibold,
    color: '#fff',
  },
  noRoleText: {
    fontSize: theme.typography.sizes.tiny,
    color: 'rgba(255,255,255,0.7)',
  },
  // VIP 横幅
  vipBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    borderRadius: theme.layout.borderRadius.lg,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  vipLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    flex: 1,
  },
  vipTextWrap: {
    flex: 1,
  },
  vipTitle: {
    fontSize: theme.typography.sizes.bodySmall,
    fontWeight: theme.typography.weights.semibold,
    color: '#92400e',
  },
  vipDesc: {
    fontSize: theme.typography.sizes.small,
    color: '#a16207',
    marginTop: 2,
  },
  vipAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  vipActionText: {
    fontSize: theme.typography.sizes.bodySmall,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.primary,
  },
  // 数据统计
  statsCard: {
    flexDirection: 'row',
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    backgroundColor: theme.colors.background.primary,
    borderRadius: theme.layout.borderRadius.lg,
    ...theme.layout.shadows.sm,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
  },
  statDivider: {
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: theme.colors.border.light,
  },
  statValue: {
    fontSize: theme.typography.sizes.h5,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.text.primary,
  },
  statLabel: {
    fontSize: theme.typography.sizes.small,
    color: theme.colors.text.tertiary,
    marginTop: 4,
  },
  // 分组
  groupSection: {
    marginTop: theme.spacing.lg,
    paddingHorizontal: theme.spacing.md,
  },
  groupTitle: {
    fontSize: theme.typography.sizes.small,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: theme.spacing.sm,
    paddingHorizontal: 4,
  },
  groupCard: {
    backgroundColor: theme.colors.background.primary,
    borderRadius: theme.layout.borderRadius.lg,
    ...theme.layout.shadows.sm,
  },
  // 入口行
  entryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  entryIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: theme.colors.background.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  entryTitle: {
    flex: 1,
    fontSize: theme.typography.sizes.bodySmall,
    fontWeight: theme.typography.weights.medium,
    color: theme.colors.text.primary,
  },
  entryDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.border.light,
    marginHorizontal: theme.spacing.md,
  },
  // 退出登录
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.xs,
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.xl,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.layout.borderRadius.md,
    backgroundColor: theme.colors.background.primary,
    ...theme.layout.shadows.sm,
  },
  logoutText: {
    fontSize: theme.typography.sizes.medium,
    fontWeight: theme.typography.weights.semibold,
    color: theme.colors.status.error,
  },
  // 页脚
  footer: {
    textAlign: 'center',
    fontSize: theme.typography.sizes.small,
    color: theme.colors.text.tertiary,
    marginTop: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
  },
});

export default ProfileScreen;
