// dehaze-taro/src/layout/tabbar/index.tsx
/**
 * 底部导航栏组件
 */
import React, { useState, useEffect } from 'react';
import { View, Text } from '@tarojs/components';
import Taro from '@tarojs/taro';
import { HomeOutlined, PhotoOutlined, BulbOutlined, SettingOutlined, AppsOutlined } from '@taroify/icons';
import { tabBarItems, isTabBarPage, getTabBarIndex, type MenuItem } from '@/config/menu';
import './index.less';

interface AppTabbarProps {
  /** 当前选中索引 */
  current?: number;
  /** 当前路由（用于自动计算索引） */
  currentRoute?: string;
  /** 激活颜色 */
  activeColor?: string;
  /** 未激活颜色 */
  inactiveColor?: string;
}

const AppTabbar: React.FC<AppTabbarProps> = ({
  current = 0,
  currentRoute = '/pages/home/index',
  activeColor = '#3b82f6',
  inactiveColor = '#9ca3af',
}) => {
  const [currentIndex, setCurrentIndex] = useState(current);

  // 监听 currentRoute 变化，自动更新索引
  useEffect(() => {
    if (currentRoute) {
      const index = getTabBarIndex(currentRoute);
      setCurrentIndex(index);
    }
  }, [currentRoute]);

  // 监听 current 属性变化
  useEffect(() => {
    setCurrentIndex(current);
  }, [current]);

  /** 切换 Tab */
  const switchTab = (item: MenuItem, index: number) => {
    if (currentIndex === index) return;

    setCurrentIndex(index);

    // tabBar 页面使用 switchTab，其他页面使用 navigateTo
    if (isTabBarPage(item.route)) {
      Taro.switchTab({ url: item.route });
    } else {
      Taro.navigateTo({
        url: item.route,
        fail: () => {
          Taro.showToast({ title: '页面开发中', icon: 'none' });
        },
      });
    }
  };

  /** 获取图标组件 */
  const getIconComponent = (icon: string, isActive: boolean) => {
    const color = isActive ? activeColor : inactiveColor;
    const size = '20';
    
    const iconMap: Record<string, React.ReactNode> = {
      'home-o': <HomeOutlined size={size} color={color} />,
      'wap-home': <HomeOutlined size={size} color={color} />,
      photograph: <PhotoOutlined size={size} color={color} />,
      'bulb-o': <BulbOutlined size={size} color={color} />,
      'setting-o': <SettingOutlined size={size} color={color} />,
      setting: <SettingOutlined size={size} color={color} />,
      'apps-o': <AppsOutlined size={size} color={color} />,
    };
    return iconMap[icon] || <AppsOutlined size={size} color={color} />;
  };

  return (
    <View className='app-tabbar'>
      {tabBarItems.map((item, index) => (
        <View
          key={item.route}
          className={`tabbar-item ${currentIndex === index ? 'active' : ''}`}
          onClick={() => switchTab(item, index)}
        >
          <View className='tabbar-icon'>
            {getIconComponent(item.icon, currentIndex === index)}
          </View>
          <Text
            className='tabbar-label'
            style={{ color: currentIndex === index ? activeColor : inactiveColor }}
          >
            {item.title}
          </Text>
        </View>
      ))}
    </View>
  );
};

export default AppTabbar;

// dehaze-uniapp/src/layout/Tabbar.vue
<template>
  <view class="app-tabbar">
    <view
      v-for="(item, index) in tabBarItems"
      :key="item.route"
      class="tabbar-item"
      :class="{ active: currentIndex === index }"
      @click="switchTab(item, index)"
    >
      <u-icon
        :name="
          currentIndex === index ? item.activeIcon || item.icon : item.icon
        "
        :size="22"
        :color="currentIndex === index ? activeColor : inactiveColor"
      />
      <text
        class="tabbar-label"
        :style="{ color: currentIndex === index ? activeColor : inactiveColor }"
      >
        {{ item.title }}
      </text>
    </view>
  </view>
</template>

<script lang="ts" setup>
import { ref, watch, onMounted } from "vue";
import {
  tabBarItems,
  isTabBarPage,
  getTabBarIndex,
  type MenuItem,
} from "@/config/menu";

interface Props {
  /** 当前选中索引 */
  current?: number;
  /** 当前路由（用于自动计算索引） */
  currentRoute?: string;
  /** 激活颜色 */
  activeColor?: string;
  /** 未激活颜色 */
  inactiveColor?: string;
}

const props = withDefaults(defineProps<Props>(), {
  current: 0,
  currentRoute: "/pages/home/index",
  activeColor: "#3b82f6",
  inactiveColor: "#9ca3af",
});

const currentIndex = ref(props.current);

// 监听 current 属性变化
watch(
  () => props.current,
  (val) => {
    currentIndex.value = val;
  }
);

// 监听 currentRoute 变化，自动更新索引
watch(
  () => props.currentRoute,
  (route) => {
    if (route) {
      const index = getTabBarIndex(route);
      currentIndex.value = index;
    }
  },
  { immediate: true }
);

/** 切换 Tab */
const switchTab = (item: MenuItem, index: number) => {
  if (currentIndex.value === index) return;

  currentIndex.value = index;

  // tabBar 页面使用 switchTab，其他页面使用 navigateTo
  if (isTabBarPage(item.route)) {
    uni.switchTab({ url: item.route });
  } else {
    uni.navigateTo({
      url: item.route,
      fail: () => {
        uni.showToast({ title: "页面开发中", icon: "none" });
      },
    });
  }
};

// 初始化时根据当前页面更新索引
onMounted(() => {
  const pages = getCurrentPages();
  if (pages.length > 0) {
    const currentPage = pages[pages.length - 1];
    const route = "/" + currentPage?.route;
    const index = getTabBarIndex(route);
    if (index !== -1) {
      currentIndex.value = index;
    }
  }
});
</script>

<style lang="scss" scoped>
.app-tabbar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 100;
  display: flex;
  align-items: center;
  justify-content: space-around;
  height: 100rpx;
  background: #ffffff;
  box-shadow: 0 -4rpx 16rpx rgba(0, 0, 0, 0.06);
  border-top: 1rpx solid #f3f4f6;
  // 适配底部安全区
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: calc(env(safe-area-inset-bottom) + 50px);
}

.tabbar-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6rpx;
  padding: 12rpx 0;
  transition: all 0.2s;

  &:active {
    transform: scale(0.95);
  }

  &.active {
    .tabbar-label {
      font-weight: 600;
    }
  }
}

.tabbar-label {
  font-size: 22rpx;
  transition: color 0.2s;
}
</style>
