// dehaze-front-react/src/pages/image-input/index.tsx
import {
  ArrowLeftOutlined,
  DeleteOutlined,
  InboxOutlined,
  ReloadOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Empty,
  Image as AntImage,
  message,
  Progress,
  Space,
  Tabs,
  Tag,
  Typography,
  Upload,
} from "antd";
import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

import Camera from "@/components/Camera";
import ExampleImageSelect from "@/components/ExampleImageSelect";
import exampleImages from "@/pages/presentation/dehaze/exampleImages";
import { changeUrl } from "@/utils";
import { FileAPI } from "dehaze-sdk-js";

const { Dragger } = Upload;
const { Title } = Typography;

// 历史记录存储 key
const HISTORY_KEY = "dehaze:image-history";
// 最大文件大小 100MB
const MAX_FILE_SIZE = 100 * 1024 * 1024;
// 历史记录最大保存数量
const MAX_HISTORY_COUNT = 20;

// 图片来源类型
type ImageSource = "upload" | "camera" | "sample" | "history";

// 历史记录结构
interface HistoryRecord {
  id: string;
  imageUrl: string;
  source: Exclude<ImageSource, "history">;
  time: number;
}

// 样例分类
const SAMPLE_CATEGORIES = [
  "全部",
  "城市建筑",
  "自然风景",
  "人像",
  "夜景",
] as const;
type SampleCategory = (typeof SAMPLE_CATEGORIES)[number];

// 样例分类列表（不含"全部"）
const SAMPLE_CATEGORY_LIST: SampleCategory[] = [
  "城市建筑",
  "自然风景",
  "人像",
  "夜景",
];

// 为样例图片分配分类
const categorizedSamples = exampleImages.map((item, index) => ({
  ...item,
  category: SAMPLE_CATEGORY_LIST[index % SAMPLE_CATEGORY_LIST.length],
}));

// 来源标签映射
const SOURCE_LABELS: Record<Exclude<ImageSource, "history">, string> = {
  upload: "上传",
  camera: "拍照",
  sample: "样例",
};

// 读取历史记录
function getHistory(): HistoryRecord[] {
  const data = localStorage.getItem(HISTORY_KEY);
  if (!data) return [];
  try {
    return JSON.parse(data) as HistoryRecord[];
  } catch {
    return [];
  }
}

// 保存历史记录
function saveToHistory(
  imageUrl: string,
  source: Exclude<ImageSource, "history">
) {
  const records = getHistory();
  const newRecord: HistoryRecord = {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    imageUrl,
    source,
    time: Date.now(),
  };
  const updated = [newRecord, ...records].slice(0, MAX_HISTORY_COUNT);
  localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
}

// 按时间分组历史记录
function groupHistoryByTime(records: HistoryRecord[]) {
  const now = new Date();
  const todayStart = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate()
  ).getTime();
  const yesterdayStart = todayStart - 24 * 60 * 60 * 1000;
  const sevenDaysAgoStart = todayStart - 7 * 24 * 60 * 60 * 1000;

  const groups: { title: string; records: HistoryRecord[] }[] = [
    { title: "今天", records: [] },
    { title: "昨天", records: [] },
    { title: "最近7天", records: [] },
    { title: "更早", records: [] },
  ];

  for (const record of records) {
    if (record.time >= todayStart) {
      groups[0].records.push(record);
    } else if (record.time >= yesterdayStart) {
      groups[1].records.push(record);
    } else if (record.time >= sevenDaysAgoStart) {
      groups[2].records.push(record);
    } else {
      groups[3].records.push(record);
    }
  }

  return groups.filter((g) => g.records.length > 0);
}

// 格式化时间显示
function formatTime(time: number): string {
  const date = new Date(time);
  const now = new Date();
  const diff = now.getTime() - time;
  if (diff < 60 * 1000) return "刚刚";
  if (diff < 60 * 60 * 1000) return `${Math.floor(diff / (60 * 1000))}分钟前`;
  if (diff < 24 * 60 * 60 * 1000)
    return `${Math.floor(diff / (60 * 60 * 1000))}小时前`;
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const h = String(date.getHours()).padStart(2, "0");
  const min = String(date.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${d} ${h}:${min}`;
}

// ============ 上传面板 ============
interface UploadPanelProps {
  onImageSelected: (url: string, source: ImageSource) => void;
}

const UploadPanel: React.FC<UploadPanelProps> = ({ onImageSelected }) => {
  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [previewUrl, setPreviewUrl] = useState<string>("");

  // 上传文件，通过 onUploadProgress 回调显示进度
  const handleUpload = (file: File) => {
    setUploading(true);
    setProgress(0);
    FileAPI.upload(file, undefined, (progressEvent) => {
      const percent = progressEvent.total
        ? Math.round((progressEvent.loaded * 100) / progressEvent.total)
        : 0;
      setProgress(percent);
    })
      .then((res) => {
        message.success("上传成功");
        onImageSelected(changeUrl(res.url), "upload");
      })
      .catch((err) => {
        message.error("上传失败: " + (err?.message || "未知错误"));
      })
      .finally(() => {
        setUploading(false);
      });
  };

  // 上传前校验：格式与大小
  const handleBeforeUpload = (file: File) => {
    // 格式校验
    const validTypes = ["image/jpeg", "image/png", "image/webp"];
    if (!validTypes.includes(file.type)) {
      message.error("不支持该图片格式，请选择 JPG/PNG/WEBP 格式");
      return Upload.LIST_IGNORE;
    }
    // 大小校验
    if (file.size > MAX_FILE_SIZE) {
      message.error("图片大小超过 100MB，请选择较小的图片");
      return Upload.LIST_IGNORE;
    }
    // 生成本地预览
    const reader = new FileReader();
    reader.onload = (e) => setPreviewUrl(e.target?.result as string);
    reader.readAsDataURL(file);
    // 开始上传
    handleUpload(file);
    return false;
  };

  return (
    <div style={{ padding: "24px 0" }}>
      <Dragger
        accept=".jpg,.jpeg,.png,.webp"
        beforeUpload={handleBeforeUpload}
        showUploadList={false}
        multiple={false}
        disabled={uploading}
      >
        <p className="ant-upload-drag-icon">
          <InboxOutlined />
        </p>
        <p className="ant-upload-text">点击或拖拽文件到此区域上传</p>
        <p className="ant-upload-hint">
          支持 JPG、PNG、WEBP 格式，单文件不超过 100MB
        </p>
      </Dragger>

      {previewUrl && (
        <div style={{ marginTop: 16, textAlign: "center" }}>
          <AntImage
            src={previewUrl}
            alt="预览"
            style={{ maxHeight: 240, objectFit: "contain" }}
          />
        </div>
      )}

      {uploading && (
        <div style={{ marginTop: 16 }}>
          <Progress percent={progress} status="active" />
        </div>
      )}
    </div>
  );
};

// ============ 拍照面板 ============
interface CameraPanelProps {
  onImageSelected: (url: string, source: ImageSource) => void;
}

const CameraPanel: React.FC<CameraPanelProps> = ({ onImageSelected }) => {
  // 拍照保存后上传
  const handleSave = (file: File) => {
    const hide = message.loading("正在上传...", 0);
    FileAPI.upload(file)
      .then((res) => {
        hide();
        message.success("拍照上传成功");
        onImageSelected(changeUrl(res.url), "camera");
      })
      .catch((err) => {
        hide();
        message.error("上传失败: " + (err?.message || "未知错误"));
      });
  };

  return (
    <div style={{ padding: "24px 0", maxWidth: 800, margin: "0 auto" }}>
      <Camera
        onSave={handleSave}
        onCancel={() => message.info("已取消拍照")}
      />
    </div>
  );
};

// ============ 样例画廊面板 ============
interface SamplePanelProps {
  onImageSelected: (url: string, source: ImageSource) => void;
}

const SamplePanel: React.FC<SamplePanelProps> = ({ onImageSelected }) => {
  const [category, setCategory] = useState<SampleCategory>("全部");

  // 按分类过滤样例图片
  const filteredUrls = useMemo(() => {
    if (category === "全部") {
      return categorizedSamples.map((s) => s.haze);
    }
    return categorizedSamples
      .filter((s) => s.category === category)
      .map((s) => s.haze);
  }, [category]);

  return (
    <div style={{ padding: "24px 0" }}>
      <Space style={{ marginBottom: 16 }}>
        {SAMPLE_CATEGORIES.map((cat) => (
          <Button
            key={cat}
            type={category === cat ? "primary" : "default"}
            onClick={() => setCategory(cat)}
          >
            {cat}
          </Button>
        ))}
      </Space>
      <ExampleImageSelect
        urls={filteredUrls}
        onExampleSelect={(url) => onImageSelected(url, "sample")}
      />
    </div>
  );
};

// ============ 历史记录面板 ============
interface HistoryPanelProps {
  onImageSelected: (url: string, source: ImageSource) => void;
}

const HistoryPanel: React.FC<HistoryPanelProps> = ({ onImageSelected }) => {
  const [records, setRecords] = useState<HistoryRecord[]>([]);

  // 加载 localStorage 中的历史记录
  useEffect(() => {
    setRecords(getHistory());
  }, []);

  // 删除单条历史记录
  const handleDelete = (id: string) => {
    const updated = records.filter((r) => r.id !== id);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
    setRecords(updated);
    message.success("已删除该记录");
  };

  // 按时间分组
  const groups = useMemo(() => groupHistoryByTime(records), [records]);

  if (records.length === 0) {
    return (
      <div style={{ padding: "48px 0" }}>
        <Empty description="暂无历史记录" />
      </div>
    );
  }

  return (
    <div style={{ padding: "24px 0" }}>
      {groups.map((group) => (
        <div key={group.title} style={{ marginBottom: 24 }}>
          <Title level={5} style={{ marginBottom: 12 }}>
            {group.title}
          </Title>
          <Space direction="vertical" style={{ width: "100%" }} size={12}>
            {group.records.map((record) => (
              <div
                key={record.id}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 16,
                  padding: 12,
                  border: "1px solid #f0f0f0",
                  borderRadius: 8,
                }}
              >
                <AntImage
                  src={record.imageUrl}
                  alt="历史图片"
                  width={80}
                  height={80}
                  style={{ objectFit: "cover", borderRadius: 4 }}
                />
                <div style={{ flex: 1 }}>
                  <Tag color="blue">{SOURCE_LABELS[record.source]}</Tag>
                  <span style={{ color: "#999", marginLeft: 8 }}>
                    {formatTime(record.time)}
                  </span>
                </div>
                <Space>
                  <Button
                    type="primary"
                    size="small"
                    icon={<ReloadOutlined />}
                    onClick={() => onImageSelected(record.imageUrl, "history")}
                  >
                    重新处理
                  </Button>
                  <Button
                    danger
                    size="small"
                    icon={<DeleteOutlined />}
                    onClick={() => handleDelete(record.id)}
                  >
                    删除
                  </Button>
                </Space>
              </div>
            ))}
          </Space>
        </div>
      ))}
    </div>
  );
};

// ============ 图像输入页面 ============
const ImageInputPage: React.FC = () => {
  const navigate = useNavigate();

  // 图片选择处理：保存历史记录并跳转到去雾页
  const handleImageSelected = (imageUrl: string, source: ImageSource) => {
    // 历史记录来源不重复保存
    if (source !== "history") {
      saveToHistory(imageUrl, source);
    }
    navigate(`/presentation/dehaze?imageUrl=${encodeURIComponent(imageUrl)}`);
  };

  return (
    <div
      style={{
        padding: 24,
        height: "calc(100vh - var(--navbar-height))",
        overflowY: "auto",
      }}
    >
      <Card>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            marginBottom: 16,
            gap: 8,
          }}
        >
          <Button
            type="text"
            icon={<ArrowLeftOutlined />}
            onClick={() => navigate(-1)}
          />
          <Title level={4} style={{ margin: 0 }}>
            图像输入
          </Title>
        </div>
        <Tabs
          defaultActiveKey="upload"
          items={[
            {
              key: "upload",
              label: "上传",
              children: (
                <UploadPanel onImageSelected={handleImageSelected} />
              ),
            },
            {
              key: "camera",
              label: "拍照",
              children: (
                <CameraPanel onImageSelected={handleImageSelected} />
              ),
            },
            {
              key: "sample",
              label: "样例",
              children: (
                <SamplePanel onImageSelected={handleImageSelected} />
              ),
            },
            {
              key: "history",
              label: "历史",
              children: (
                <HistoryPanel onImageSelected={handleImageSelected} />
              ),
            },
          ]}
        />
      </Card>
    </div>
  );
};

export default ImageInputPage;

// dehaze-front-vue/src/views/image-input/index.vue
<script lang="ts" setup>
import Camera from "@/components/Camera/index.vue";
import ExampleImageSelect from "@/components/ExampleImageSelect/index.vue";
import { useImageShowStore } from "@/store/modules/imageShow";
import { changeUrl } from "@/utils";
import examples from "@/views/presentation/dehaze/exampleImages";
import { FileAPI } from "dehaze-sdk-js";
import type { UploadRawFile, UploadRequestOptions } from "element-plus";

defineOptions({
  name: "ImageInput",
});

const router = useRouter();
const imageShowStore = useImageShowStore();

// 历史记录存储 key
const HISTORY_KEY = "dehaze:image-history";
// 支持的文件格式
const ACCEPT_FORMATS = ".jpg,.jpeg,.png,.webp";
// 最大文件大小：100MB
const MAX_FILE_SIZE = 100 * 1024 * 1024;

// 当前激活的 Tab
const activeTab = ref<"upload" | "camera" | "sample" | "history">("upload");

// ========== 上传面板状态 ==========
const uploading = ref(false);
const uploadProgress = ref(0);
const previewUrl = ref("");

// ========== 样例面板状态 ==========
const sampleCategory = ref("all");

// 样例图片分类
const sampleCategories = [
  { label: "全部", value: "all" },
  { label: "城市建筑", value: "city" },
  { label: "自然风景", value: "nature" },
  { label: "人像", value: "portrait" },
  { label: "夜景", value: "night" },
];

// 样例图片列表（复用现有样例图片，标记分类）
const allSampleImages = examples.map((item) => ({
  url: item.haze,
  category: "nature" as const,
}));

// 按分类过滤后的样例图片 URL
const filteredSampleUrls = computed(() => {
  if (sampleCategory.value === "all") {
    return allSampleImages.map((item) => item.url);
  }
  return allSampleImages
    .filter((item) => item.category === sampleCategory.value)
    .map((item) => item.url);
});

// ========== 历史记录状态 ==========
interface HistoryRecord {
  id: string;
  url: string;
  thumbnail: string;
  time: number;
  source: "upload" | "camera" | "sample";
}

const sourceLabels: Record<HistoryRecord["source"], string> = {
  upload: "上传",
  camera: "拍照",
  sample: "样例",
};

const historyRecords = ref<HistoryRecord[]>([]);

// 从 localStorage 加载历史记录
function loadHistory() {
  const data = localStorage.getItem(HISTORY_KEY);
  if (data) {
    try {
      historyRecords.value = JSON.parse(data);
    } catch {
      historyRecords.value = [];
    }
  }
}

// 保存历史记录到 localStorage
function saveHistory(records: HistoryRecord[]) {
  localStorage.setItem(HISTORY_KEY, JSON.stringify(records));
}

// 添加历史记录
function addHistoryRecord(url: string, source: "upload" | "camera" | "sample") {
  const record: HistoryRecord = {
    id: Date.now().toString() + Math.random().toString(36).slice(2),
    url,
    thumbnail: url,
    time: Date.now(),
    source,
  };
  historyRecords.value.unshift(record);
  // 最多保留 20 条
  if (historyRecords.value.length > 20) {
    historyRecords.value = historyRecords.value.slice(0, 20);
  }
  saveHistory(historyRecords.value);
}

// 删除历史记录
function deleteHistoryRecord(id: string) {
  historyRecords.value = historyRecords.value.filter((r) => r.id !== id);
  saveHistory(historyRecords.value);
}

// 按时间分组展示历史记录
const groupedHistory = computed(() => {
  const now = new Date();
  const todayStart = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate()
  ).getTime();
  const yesterdayStart = todayStart - 24 * 60 * 60 * 1000;
  const sevenDaysAgoStart = todayStart - 7 * 24 * 60 * 60 * 1000;

  const groups = {
    today: [] as HistoryRecord[],
    yesterday: [] as HistoryRecord[],
    recent7: [] as HistoryRecord[],
    earlier: [] as HistoryRecord[],
  };

  historyRecords.value.forEach((record) => {
    if (record.time >= todayStart) {
      groups.today.push(record);
    } else if (record.time >= yesterdayStart) {
      groups.yesterday.push(record);
    } else if (record.time >= sevenDaysAgoStart) {
      groups.recent7.push(record);
    } else {
      groups.earlier.push(record);
    }
  });

  return [
    { label: "今天", records: groups.today },
    { label: "昨天", records: groups.yesterday },
    { label: "最近7天", records: groups.recent7 },
    { label: "更早", records: groups.earlier },
  ].filter((g) => g.records.length > 0);
});

// 格式化时间
function formatTime(timestamp: number) {
  const date = new Date(timestamp);
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const h = String(date.getHours()).padStart(2, "0");
  const min = String(date.getMinutes()).padStart(2, "0");
  return `${y}-${m}-${d} ${h}:${min}`;
}

// ========== 图片选择统一处理 ==========
function handleImageSelected(
  url: string,
  source: "upload" | "camera" | "sample"
) {
  addHistoryRecord(url, source);
  // 跳转到去雾展示页，通过 query 参数传递图片 URL
  router.push({
    path: "/presentation/dehaze",
    query: { imageUrl: url },
  });
}

// ========== 上传面板 ==========
// 文件上传前校验：格式与大小
function handleBeforeUpload(file: UploadRawFile): boolean {
  const ext = file.name.substring(file.name.lastIndexOf(".")).toLowerCase();
  const allowedExts = [".jpg", ".jpeg", ".png", ".webp"];
  if (!allowedExts.includes(ext)) {
    ElMessage.error("不支持该图片格式，请选择 JPG/PNG/WEBP 格式");
    return false;
  }
  if (file.size > MAX_FILE_SIZE) {
    ElMessage.error("图片大小超过 100MB，请选择较小的图片");
    return false;
  }
  return true;
}

// 自定义上传请求，支持进度回调
async function handleUploadRequest(options: UploadRequestOptions) {
  uploading.value = true;
  uploadProgress.value = 0;
  previewUrl.value = URL.createObjectURL(options.file);

  try {
    const res = await FileAPI.upload(
      options.file,
      imageShowStore.modelId,
      (e) => {
        if (e.total) {
          uploadProgress.value = Math.round((e.loaded / e.total) * 100);
        }
      }
    );
    uploadProgress.value = 100;
    ElMessage.success("上传成功");
    const url = changeUrl(res.url);
    handleImageSelected(url, "upload");
  } catch (err: any) {
    ElMessage.error("上传失败：" + (err?.message || err));
  } finally {
    uploading.value = false;
    setTimeout(() => {
      previewUrl.value = "";
      uploadProgress.value = 0;
    }, 1000);
  }
}

// ========== 拍照面板 ==========
function handleCameraSave(file: File) {
  uploading.value = true;
  FileAPI.upload(file, imageShowStore.modelId)
    .then((res) => {
      const url = changeUrl(res.url);
      handleImageSelected(url, "camera");
    })
    .catch((err) => {
      ElMessage.error("上传失败：" + err);
    })
    .finally(() => {
      uploading.value = false;
    });
}

// 拍照取消时切回上传 Tab
function handleCameraCancel() {
  activeTab.value = "upload";
}

// ========== 样例面板 ==========
function handleSampleSelect(url: string) {
  handleImageSelected(url, "sample");
}

// ========== 历史面板 ==========
function handleHistoryReprocess(record: HistoryRecord) {
  router.push({
    path: "/presentation/dehaze",
    query: { imageUrl: record.url },
  });
}

function handleHistoryDelete(record: HistoryRecord) {
  ElMessageBox.confirm("确认删除该历史记录吗？删除后不可恢复。", "提示", {
    confirmButtonText: "确定",
    cancelButtonText: "取消",
    type: "warning",
  })
    .then(() => {
      deleteHistoryRecord(record.id);
      ElMessage.success("删除成功");
    })
    .catch(() => {});
}

onActivated(() => {
  loadHistory();
});
</script>

<template>
  <div class="image-input-container">
    <!-- 页面标题 -->
    <div class="page-header">
      <h2>图像输入</h2>
      <p>选择图片进行去雾处理</p>
    </div>

    <!-- Tab 切换输入方式 -->
    <el-tabs v-model="activeTab" class="input-tabs">
      <!-- 上传面板 -->
      <el-tab-pane label="上传" name="upload">
        <div class="panel upload-panel">
          <el-upload
            drag
            :accept="ACCEPT_FORMATS"
            :show-file-list="false"
            :auto-upload="true"
            :before-upload="handleBeforeUpload"
            :http-request="handleUploadRequest"
            :disabled="uploading"
          >
            <el-icon class="el-icon--upload">
              <i-ep-upload-filled />
            </el-icon>
            <div class="el-upload__text">
              拖拽图片到此处，或<em>点击上传</em>
            </div>
            <template #tip>
              <div class="el-upload__tip">
                支持 JPG / PNG / WEBP 格式，文件大小不超过 100MB
              </div>
            </template>
          </el-upload>

          <!-- 上传进度 -->
          <div v-if="uploading || uploadProgress > 0" class="upload-progress">
            <el-progress
              :percentage="uploadProgress"
              :status="uploadProgress === 100 ? 'success' : ''"
            />
          </div>

          <!-- 图片预览 -->
          <div v-if="previewUrl" class="preview-wrap">
            <img :src="previewUrl" alt="预览" class="preview-img" />
          </div>
        </div>
      </el-tab-pane>

      <!-- 拍照面板 -->
      <el-tab-pane label="拍照" name="camera">
        <div v-loading="uploading" class="panel camera-panel">
          <Camera
            v-if="activeTab === 'camera'"
            @on-save="handleCameraSave"
            @on-cancel="handleCameraCancel"
          />
        </div>
      </el-tab-pane>

      <!-- 样例面板 -->
      <el-tab-pane label="样例" name="sample">
        <div class="panel sample-panel">
          <!-- 分类过滤 -->
          <div class="category-filter">
            <el-radio-group v-model="sampleCategory">
              <el-radio-button
                v-for="cat in sampleCategories"
                :key="cat.value"
                :value="cat.value"
              >
                {{ cat.label }}
              </el-radio-button>
            </el-radio-group>
          </div>

          <!-- 样例图片 -->
          <ExampleImageSelect
            v-if="filteredSampleUrls.length > 0"
            :urls="filteredSampleUrls"
            @on-example-select="handleSampleSelect"
          />
          <el-empty v-else description="该分类暂无样例图片" />
        </div>
      </el-tab-pane>

      <!-- 历史面板 -->
      <el-tab-pane label="历史" name="history">
        <div class="panel history-panel">
          <template v-if="groupedHistory.length > 0">
            <div
              v-for="group in groupedHistory"
              :key="group.label"
              class="history-group"
            >
              <div class="group-title">{{ group.label }}</div>
              <div class="history-list">
                <div
                  v-for="record in group.records"
                  :key="record.id"
                  class="history-card"
                >
                  <img
                    :src="record.thumbnail"
                    alt="历史图片"
                    class="history-thumbnail"
                  />
                  <div class="history-info">
                    <div class="history-time">
                      {{ formatTime(record.time) }}
                    </div>
                    <div class="history-source">
                      来源：{{ sourceLabels[record.source] }}
                    </div>
                  </div>
                  <div class="history-actions">
                    <el-button
                      size="small"
                      type="primary"
                      @click="handleHistoryReprocess(record)"
                    >
                      重新处理
                    </el-button>
                    <el-button
                      size="small"
                      type="danger"
                      plain
                      @click="handleHistoryDelete(record)"
                    >
                      删除
                    </el-button>
                  </div>
                </div>
              </div>
            </div>
          </template>
          <el-empty v-else description="暂无历史记录" />
        </div>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<style lang="scss" scoped>
.image-input-container {
  height: calc(100vh - #{$navbar-height} - #{$tags-view-height});
  padding: 20px;
  overflow-y: auto;
}

.page-header {
  margin-bottom: 20px;
  text-align: center;

  h2 {
    margin: 0 0 8px;
    font-size: 24px;
    font-weight: 700;
  }

  p {
    margin: 0;
    font-size: 14px;
    color: var(--el-text-color-secondary);
  }
}

.input-tabs {
  max-width: 1200px;
  margin: 0 auto;
}

.panel {
  min-height: 400px;
  padding: 20px;
}

/* 上传面板 */
.upload-panel {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: flex-start;

  :deep(.el-upload-dragger) {
    width: 500px;
    max-width: 100%;
    padding: 40px 20px;
  }

  .upload-progress {
    width: 500px;
    max-width: 100%;
    margin-top: 20px;
  }

  .preview-wrap {
    margin-top: 20px;
    text-align: center;

    .preview-img {
      max-width: 100%;
      max-height: 400px;
      border-radius: 8px;
      box-shadow: var(--el-box-shadow-light);
    }
  }
}

/* 拍照面板 */
.camera-panel {
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 样例面板 */
.sample-panel {
  .category-filter {
    margin-bottom: 20px;
    text-align: center;
  }
}

/* 历史面板 */
.history-panel {
  .history-group {
    margin-bottom: 24px;
  }

  .group-title {
    padding-left: 8px;
    margin-bottom: 12px;
    font-size: 16px;
    font-weight: 600;
    border-left: 4px solid var(--el-color-primary);
  }

  .history-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(360px, 1fr));
    gap: 16px;
  }

  .history-card {
    display: flex;
    gap: 12px;
    align-items: center;
    padding: 12px;
    background-color: var(--el-bg-color-page);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 8px;
    transition: all 0.2s ease;

    &:hover {
      border-color: var(--el-color-primary);
      box-shadow: var(--el-box-shadow-light);
    }
  }

  .history-thumbnail {
    flex-shrink: 0;
    width: 80px;
    height: 80px;
    object-fit: cover;
    border-radius: 6px;
  }

  .history-info {
    flex: 1;
    min-width: 0;

    .history-time {
      margin-bottom: 4px;
      font-size: 14px;
      font-weight: 500;
    }

    .history-source {
      font-size: 12px;
      color: var(--el-text-color-secondary);
    }
  }

  .history-actions {
    display: flex;
    flex-shrink: 0;
    flex-direction: column;
    gap: 8px;
  }
}

@media screen and (width <= 768px) {
  .upload-panel {
    :deep(.el-upload-dragger) {
      width: 100%;
    }

    .upload-progress {
      width: 100%;
    }
  }

  .history-panel {
    .history-list {
      grid-template-columns: 1fr;
    }

    .history-card {
      flex-direction: column;
      align-items: stretch;
      text-align: center;

      .history-thumbnail {
        width: 100%;
        height: 120px;
      }

      .history-actions {
        flex-direction: row;
        justify-content: center;
      }
    }
  }
}
</style>
