// dehaze-taro/src/pages/personal/files/index.tsx
import React, { useState, useEffect, useCallback } from "react";
import { View, Text, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { FileAPI } from "dehaze-sdk-js";
import type { FileInfo } from "dehaze-sdk-js";
import PageLayout from "@/layout";
import "./index.less";

const FilesPage: React.FC = () => {
  const [files, setFiles] = useState<FileInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [pageNum, setPageNum] = useState(1);
  const [hasMore, setHasMore] = useState(true);

  const loadData = useCallback(
    async (page = 1) => {
      if (loading) return;
      setLoading(true);
      try {
        const result = await FileAPI.getPage({ pageNum: page, pageSize: 20 });
        const list = result.list || [];
        if (page === 1) {
          setFiles(list);
        } else {
          setFiles((prev) => [...prev, ...list]);
        }
        setHasMore(list.length < (result.total || 0));
        setPageNum(page);
      } catch {
        Taro.showToast({ title: "加载失败", icon: "none" });
      } finally {
        setLoading(false);
      }
    },
    [loading]
  );

  useEffect(() => {
    loadData(1);
  }, []);

  const handleClick = (file: FileInfo) => {
    if (file.url) {
      Taro.setClipboardData({
        data: file.url,
        success: () => Taro.showToast({ title: "URL 已复制", icon: "success" }),
      });
    }
  };

  const getIcon = (type?: string): string => {
    if (!type) return "📄";
    const t = type.toLowerCase();
    if (t.includes("image")) return "🖼️";
    if (t.includes("video")) return "🎬";
    if (t.includes("audio")) return "🎵";
    if (t.includes("pdf") || t.includes("doc")) return "📝";
    return "📄";
  };

  const formatFileSize = (size?: string): string => {
    return size || "-";
  };

  const formatTime = (time?: string): string => {
    if (!time) return "";
    try {
      const d = new Date(time);
      const now = new Date();
      const diff = now.getTime() - d.getTime();
      if (diff < 60000) return "刚刚";
      if (diff < 3600000) return `${Math.floor(diff / 60000)} 分钟前`;
      if (diff < 86400000) return `${Math.floor(diff / 3600000)} 小时前`;
      if (diff < 604800000) return `${Math.floor(diff / 86400000)} 天前`;
      return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    } catch {
      return time;
    }
  };

  return (
    <PageLayout level="L2" title="我的文件">
      <View className="personal-files-page">
        {loading && files.length === 0 ? (
          <View className="loading-wrapper">
            <Text className="loading-text">加载中...</Text>
          </View>
        ) : files.length > 0 ? (
          <ScrollView scrollY className="files-scroll" enhanced showScrollbar={false}>
            {files.map((file) => (
              <View key={file.id} className="file-card" onClick={() => handleClick(file)}>
                <View className="file-icon">
                  <Text>{getIcon(file.type)}</Text>
                </View>
                <View className="file-info">
                  <Text className="file-name">{file.name}</Text>
                  <Text className="file-meta">
                    {formatFileSize(file.size)} · {formatTime(file.createTime)}
                  </Text>
                </View>
                <View className="file-arrow">
                  <Text>›</Text>
                </View>
              </View>
            ))}
            {!hasMore && files.length > 0 && (
              <View className="no-more">
                <Text>没有更多了</Text>
              </View>
            )}
            {hasMore && (
              <View className="load-more" onClick={() => loadData(pageNum + 1)}>
                <Text>加载更多</Text>
              </View>
            )}
          </ScrollView>
        ) : (
          <View className="empty-wrapper">
            <Text className="empty-icon">📄</Text>
            <Text className="empty-title">暂无文件</Text>
            <Text className="empty-desc">
              您上传和处理的图像文件将显示在这里
            </Text>
          </View>
        )}
      </View>
    </PageLayout>
  );
};

export default FilesPage;

// dehaze-uniapp/src/pages/personal/files/index.vue
<template>
  <PageLayout level="L2" title="我的文件" class="page">
    <view class="main-content">
      <!-- 加载状态 -->
      <view v-if="loading" class="loading-container">
        <view class="loading-spinner" />
        <text class="loading-text">加载中...</text>
      </view>

      <!-- 文件列表 -->
      <view v-else-if="files.length > 0" class="file-list">
        <view
          v-for="file in files"
          :key="file.id"
          class="file-card"
          @click="handleClick(file)"
        >
          <view class="file-icon">
            <SvgIcon :name="getIcon(file.type)" size="24" color="#10b981" />
          </view>
          <view class="file-info">
            <text class="file-name">{{ file.name }}</text>
            <text class="file-meta">
              {{ formatFileSize(file.size || "") }} ·
              {{ formatRelativeTime(file.createTime || "") }}
            </text>
          </view>
          <view class="file-arrow">
            <SvgIcon name="arrow-right" size="16" color="#d1d5db" />
          </view>
        </view>

        <view v-if="!hasMore" class="end-text">— 没有更多了 —</view>
        <view v-else class="load-more" @click="loadMore">
          <text class="load-more-text">加载更多</text>
        </view>
      </view>

      <!-- 空状态 -->
      <view v-else class="empty-state">
        <view class="empty-tip">暂无文件</view>
        <text class="empty-hint">上传图片后文件会显示在这里</text>
      </view>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import PageLayout from "@/layout/index.vue";
import { FileAPI } from "dehaze-sdk-js";
import type { FileInfo } from "dehaze-sdk-js";
import { formatFileSize, formatRelativeTime } from "@/utils/format";

const loading = ref(false);
const files = ref<FileInfo[]>([]);
const currentPage = ref(1);
const hasMore = ref(true);

async function loadData(page = 1) {
  if (loading.value) return;
  loading.value = true;
  try {
    const result = await FileAPI.getPage({ pageNum: page, pageSize: 20 });
    if (page === 1) {
      files.value = result.list;
    } else {
      files.value = [...files.value, ...result.list];
    }
    hasMore.value = files.value.length < result.total;
    currentPage.value = page;
  } catch {
    uni.showToast({ title: "加载失败", icon: "none" });
  } finally {
    loading.value = false;
  }
}

function loadMore() {
  if (hasMore.value) loadData(currentPage.value + 1);
}

function handleClick(file: FileInfo) {
  if (file.url) {
    uni.setClipboardData({
      data: file.url,
      success: () => uni.showToast({ title: "URL 已复制", icon: "success" }),
    });
  }
}

function getIcon(type?: string): string {
  if (!type) return "file";
  const t = type.toLowerCase();
  if (t.includes("image")) return "photo";
  if (t.includes("video")) return "play-circle";
  if (t.includes("audio")) return "mic";
  if (t.includes("pdf") || t.includes("doc")) return "file-text";
  return "file";
}

onMounted(() => loadData());
</script>

<style lang="scss" scoped>
@import "@/styles/mixins.scss";

.page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}
.main-content {
  padding: $spacing-md;
  @include safe-area-bottom(80rpx);
}

.file-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}
.file-card {
  display: flex;
  align-items: center;
  gap: 20rpx;
  background: $color-white;
  border-radius: 20rpx;
  padding: 24rpx;
  box-shadow: $shadow-sm;
  &:active {
    background: $color-bg-primary;
  }
}
.file-icon {
  width: 80rpx;
  height: 80rpx;
  background: #ecfdf5;
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.file-info {
  flex: 1;
  min-width: 0;
}
.file-name {
  display: block;
  font-size: $font-md;
  font-weight: 500;
  color: $color-text-primary;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-bottom: 6rpx;
}
.file-meta {
  font-size: $font-sm;
  color: $color-text-placeholder;
}
.file-arrow {
  flex-shrink: 0;
}

.end-text {
  text-align: center;
  font-size: $font-sm;
  color: $color-text-disabled;
  padding: 32rpx 0;
}
.load-more {
  text-align: center;
  padding: 24rpx 0;
}
.load-more-text {
  font-size: $font-sm;
  color: $color-success;
}

.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 120rpx 0;
}
.loading-text {
  margin-top: 24rpx;
  font-size: $font-md;
  color: $color-text-placeholder;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 80rpx 0;
}
.empty-tip {
  font-size: $font-md;
}
.empty-hint {
  font-size: $font-sm;
  color: $color-text-placeholder;
  margin-top: 16rpx;
}
</style>
