// dehaze-uniapp/src/layout/Navbar.vue
<template>
  <view class="app-navbar">
    <!-- 状态栏占位 -->
    <view class="status-bar" :style="{ height: statusBarHeight + 'px' }" />

    <!-- 导航栏内容 -->
    <view class="navbar-content">
      <!-- Logo + 标题 -->
      <view class="navbar-brand" @click="goHome">
        <view class="logo-wrapper">
          <u-icon name="cloud-fill" color="#fff" size="18" />
        </view>
        <text class="app-title">图像去雾系统</text>
      </view>

      <!-- 右侧操作区 -->
      <view class="navbar-actions">
        <view class="action-btn" @click="handleSearch">
          <u-icon name="search" size="22" color="#374151" />
        </view>
        <view class="action-btn menu-btn" @click="toggleMenu">
          <u-icon name="list" size="22" color="#374151" />
        </view>
      </view>
    </view>
  </view>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";

interface Emits {
  (e: "toggle-menu"): void;
  (e: "search"): void;
}

const emit = defineEmits<Emits>();

/** 状态栏高度 */
const statusBarHeight = ref(0);

onMounted(() => {
  // 获取状态栏高度
  try {
    const sysInfo = uni.getSystemInfoSync();
    statusBarHeight.value = sysInfo.statusBarHeight || 0;
  } catch (error) {
    console.warn("[AppNavbar] Failed to get statusBarHeight:", error);
  }
});

/** 跳转首页 */
const goHome = () => {
  uni.switchTab({ url: "/pages/home/index" });
};

/** 搜索按钮点击 */
const handleSearch = () => {
  emit("search");
  uni.showToast({ title: "搜索功能开发中", icon: "none" });
};

/** 切换菜单 */
const toggleMenu = () => {
  emit("toggle-menu");
};
</script>

<style lang="scss" scoped>
.app-navbar {
  position: sticky;
  top: 0;
  z-index: 100;
  background: #ffffff;
  box-shadow: 0 2rpx 16rpx rgba(0, 0, 0, 0.08);
}

.status-bar {
  width: 100%;
  background: #ffffff;
}

.navbar-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16rpx 32rpx;
  height: 88rpx;
}

.navbar-brand {
  display: flex;
  align-items: center;
  gap: 16rpx;
  cursor: pointer;

  &:active {
    opacity: 0.8;
  }
}

.logo-wrapper {
  width: 64rpx;
  height: 64rpx;
  background: linear-gradient(135deg, #3b82f6 0%, #6366f1 100%);
  border-radius: 16rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 4rpx 12rpx rgba(59, 130, 246, 0.3);
}

.app-title {
  font-size: 32rpx;
  font-weight: 700;
  color: #1f2937;
}

.navbar-actions {
  display: flex;
  align-items: center;
  gap: 8rpx;
}

.action-btn {
  width: 72rpx;
  height: 72rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 16rpx;
  transition: background 0.2s;

  &:active {
    background: #f3f4f6;
  }
}
</style>

// dehaze-taro/src/layout/navbar/index.tsx
/**
 * 顶部导航栏组件
 */
import React from 'react';
import { View, Text } from '@tarojs/components';
import Taro from '@tarojs/taro';
import { Search, Bars, EyeOutlined } from '@taroify/icons';
import { useStatusBarHeight } from '@/hooks/useLayout';
import './index.less';

interface AppNavbarProps {
  /** 切换菜单回调 */
  onToggleMenu?: () => void;
  /** 搜索回调 */
  onSearch?: () => void;
  /** 标题 */
  title?: string;
}

const AppNavbar: React.FC<AppNavbarProps> = ({
  onToggleMenu,
  onSearch,
  title = '图像去雾系统',
}) => {
  const statusBarHeight = useStatusBarHeight();

  /** 跳转首页 */
  const goHome = () => {
    Taro.switchTab({ url: '/pages/home/index' });
  };

  /** 搜索按钮点击 */
  const handleSearch = () => {
    if (onSearch) {
      onSearch();
    } else {
      Taro.showToast({ title: '搜索功能开发中', icon: 'none' });
    }
  };

  /** 切换菜单 */
  const handleToggleMenu = () => {
    onToggleMenu?.();
  };

  return (
    <View className='app-navbar'>
      {/* 状态栏占位 */}
      <View className='status-bar' style={{ height: `${statusBarHeight}px` }} />

      {/* 导航栏内容 */}
      <View className='navbar-content'>
        {/* Logo + 标题 */}
        <View className='navbar-brand' onClick={goHome}>
          <View className='logo-wrapper'>
            <EyeOutlined size='20' color='#ffffff' />
          </View>
          <Text className='app-title'>{title}</Text>
        </View>

        {/* 右侧操作区 */}
        <View className='navbar-actions'>
          <View className='action-btn' onClick={handleSearch}>
            <Search size='18' color='#374151' />
          </View>
          <View className='action-btn menu-btn' onClick={handleToggleMenu}>
            <Bars size='18' color='#374151' />
          </View>
        </View>
      </View>
    </View>
  );
};

export default AppNavbar;
