// dehaze-front-react/src/pages/member/growth-logs/index.tsx
import {
  MemberAPI,
  type GrowthChangeType,
  type GrowthLogVO,
  type GrowthLogQuery,
} from "dehaze-sdk-js";
import {
  Button,
  Card,
  DatePicker,
  Form,
  Select,
  Space,
  Table,
  type TableColumnsType,
} from "antd";
import {
  ArrowLeftOutlined,
  ReloadOutlined,
  SearchOutlined,
} from "@ant-design/icons";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./index.scss";

const { RangePicker } = DatePicker;

const CHANGE_TYPE_OPTIONS: { value: GrowthChangeType; label: string }[] = [
  { value: "process", label: "图像处理" },
  { value: "evaluate", label: "指标评估" },
  { value: "rating", label: "评价奖励" },
  { value: "sign_in", label: "每日签到" },
  { value: "sign_in_bonus", label: "签到奖励" },
  { value: "consume", label: "消费获得" },
  { value: "refund_deduct", label: "退款扣除" },
  { value: "admin_adjust", label: "后台调整" },
];

const CHANGE_TYPE_LABEL: Record<string, string> = Object.fromEntries(
  CHANGE_TYPE_OPTIONS.map((o) => [o.value, o.label])
);

const GrowthLogs: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [pageData, setPageData] = useState<GrowthLogVO[]>([]);
  const [total, setTotal] = useState(0);
  const [searchForm] = Form.useForm();
  const [queryParams, setQueryParams] = useState<GrowthLogQuery>({
    pageNum: 1,
    pageSize: 20,
  });
  const [refreshFlag, setRefreshFlag] = useState(0);

  const loadData = useCallback(async (params: GrowthLogQuery) => {
    setLoading(true);
    try {
      const result = await MemberAPI.getGrowthLogs(params);
      setPageData(result.list || []);
      setTotal(result.total || 0);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData(queryParams);
  }, [queryParams, refreshFlag]);

  const handleSearch = useCallback(
    (values: {
      changeType?: GrowthChangeType;
      timeRange?: [string, string];
    }) => {
      setQueryParams((prev) => ({
        ...prev,
        pageNum: 1,
        changeType: values.changeType,
        startTime: values.timeRange?.[0]
          ? `${values.timeRange[0]} 00:00:00`
          : undefined,
        endTime: values.timeRange?.[1]
          ? `${values.timeRange[1]} 23:59:59`
          : undefined,
      }));
    },
    []
  );

  const handleReset = useCallback(() => {
    searchForm.resetFields();
    setQueryParams({ pageNum: 1, pageSize: 20 });
  }, [searchForm]);

  const handlePageChange = useCallback((page: number, pageSize: number) => {
    setQueryParams((prev) => ({ ...prev, pageNum: page, pageSize }));
  }, []);

  const columns: TableColumnsType<GrowthLogVO> = useMemo(
    () => [
      {
        title: "#",
        key: "index",
        width: 50,
        align: "center",
        render: (_: unknown, __: GrowthLogVO, index: number) => index + 1,
      },
      {
        title: "变动类型",
        dataIndex: "changeType",
        key: "changeType",
        width: 130,
        align: "center",
        render: (type: GrowthChangeType) => (
          <span className={`type-tag tag-${type}`}>
            {CHANGE_TYPE_LABEL[type] || type}
          </span>
        ),
      },
      {
        title: "变动值",
        dataIndex: "changeValue",
        key: "changeValue",
        width: 100,
        align: "center",
        render: (value: number) => (
          <span className={value >= 0 ? "value-up" : "value-down"}>
            {value >= 0 ? "+" : ""}
            {value}
          </span>
        ),
      },
      {
        title: "变动后余额",
        dataIndex: "balance",
        key: "balance",
        width: 120,
        align: "center",
      },
      {
        title: "原因",
        dataIndex: "reason",
        key: "reason",
        ellipsis: true,
        render: (reason?: string) => reason || "-",
      },
      {
        title: "关联ID",
        dataIndex: "relatedId",
        key: "relatedId",
        width: 120,
        align: "center",
        render: (relatedId?: string) => relatedId || "-",
      },
      {
        title: "操作人",
        dataIndex: "operatorId",
        key: "operatorId",
        width: 100,
        align: "center",
        render: (operatorId?: number) =>
          operatorId ? `用户${operatorId}` : "系统",
      },
      {
        title: "时间",
        dataIndex: "createTime",
        key: "createTime",
        width: 180,
        align: "center",
      },
    ],
    []
  );

  return (
    <div className="growth-logs">
      <div className="page-header">
        <div className="header-title">
          <Button
            type="link"
            icon={<ArrowLeftOutlined />}
            onClick={() => navigate("/member/center")}
          />
          <span className="title-text">成长值明细</span>
        </div>
      </div>

      <Card className="search-card" size="small">
        <Form form={searchForm} layout="inline" onFinish={handleSearch}>
          <Form.Item name="changeType" label="变动类型">
            <Select
              placeholder="全部"
              allowClear
              style={{ width: 150 }}
              options={CHANGE_TYPE_OPTIONS}
            />
          </Form.Item>
          <Form.Item name="timeRange" label="时间范围">
            <RangePicker style={{ width: 240 }} />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                htmlType="submit"
                icon={<SearchOutlined />}
              >
                搜索
              </Button>
              <Button
                htmlType="reset"
                icon={<ReloadOutlined />}
                onClick={handleReset}
              >
                重置
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card className="table-card" size="small">
        <Table
          columns={columns}
          dataSource={pageData}
          rowKey="id"
          loading={loading}
          scroll={{ x: 1000 }}
          pagination={{
            current: queryParams.pageNum,
            pageSize: queryParams.pageSize,
            total,
            showSizeChanger: true,
            pageSizeOptions: ["10", "20", "50", "100"],
            showTotal: (t) => `共 ${t} 条`,
            onChange: handlePageChange,
          }}
        />
      </Card>
    </div>
  );
};

export default GrowthLogs;

// dehaze-front-vue/src/views/member/growth-logs/index.vue
<template>
  <div class="app-container growth-logs">
    <div class="page-header">
      <div class="header-title">
        <el-button link @click="router.push('/member/center')">
          <el-icon><ArrowLeft /></el-icon>
        </el-button>
        <span class="title-text">成长值明细</span>
      </div>
    </div>

    <div class="search-container">
      <el-form ref="queryFormRef" :inline="true" :model="queryParams">
        <el-form-item label="变动类型" prop="changeType">
          <el-select
            v-model="queryParams.changeType"
            clearable
            placeholder="全部"
            style="width: 150px"
          >
            <el-option
              v-for="item in changeTypeOptions"
              :key="item.value"
              :label="item.label"
              :value="item.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="时间范围" prop="timeRange">
          <el-date-picker
            v-model="timeRange"
            type="daterange"
            range-separator="至"
            start-placeholder="开始"
            end-placeholder="结束"
            value-format="YYYY-MM-DD"
            @change="handleTimeChange"
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleQuery">
            <el-icon><Search /></el-icon>搜索
          </el-button>
          <el-button @click="resetQuery">
            <el-icon><Refresh /></el-icon>重置
          </el-button>
        </el-form-item>
      </el-form>
    </div>

    <el-card class="table-container" shadow="never">
      <el-table v-loading="loading" :data="pageData" border>
        <el-table-column type="index" label="#" width="50" align="center" />
        <el-table-column label="变动类型" width="130" align="center">
          <template #default="scope">
            <span :class="['type-tag', `tag-${scope.row.changeType}`]">
              {{ getChangeTypeLabel(scope.row.changeType) }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="变动值" width="100" align="center">
          <template #default="scope">
            <span
              :class="scope.row.changeValue >= 0 ? 'value-up' : 'value-down'"
            >
              {{ scope.row.changeValue >= 0 ? "+" : ""
              }}{{ scope.row.changeValue }}
            </span>
          </template>
        </el-table-column>
        <el-table-column
          label="变动后余额"
          prop="balance"
          width="120"
          align="center"
        />
        <el-table-column
          label="原因"
          prop="reason"
          min-width="200"
          show-overflow-tooltip
        />
        <el-table-column
          label="关联ID"
          prop="relatedId"
          width="120"
          align="center"
        >
          <template #default="scope">
            {{ scope.row.relatedId || "-" }}
          </template>
        </el-table-column>
        <el-table-column
          label="操作人"
          prop="operatorId"
          width="100"
          align="center"
        >
          <template #default="scope">
            {{ scope.row.operatorId ? `用户${scope.row.operatorId}` : "系统" }}
          </template>
        </el-table-column>
        <el-table-column
          label="时间"
          prop="createTime"
          width="180"
          align="center"
        />
      </el-table>

      <pagination
        v-if="total > 0"
        v-model:limit="queryParams.pageSize"
        v-model:page="queryParams.pageNum"
        v-model:total="total"
        @pagination="handleQuery"
      />
    </el-card>
  </div>
</template>

<script lang="ts" setup>
import {
  MemberAPI,
  GrowthLogQuery,
  GrowthLogVO,
  GrowthChangeType,
} from "dehaze-sdk-js";
import { ArrowLeft, Refresh, Search } from "@element-plus/icons-vue";

defineOptions({ name: "MemberGrowthLogs" });

const router = useRouter();
const queryFormRef = ref(ElForm);

const loading = ref(false);
const total = ref(0);
const pageData = ref<GrowthLogVO[]>([]);
const timeRange = ref<string[]>([]);
const queryParams = reactive<GrowthLogQuery>({
  pageNum: 1,
  pageSize: 20,
});

const changeTypeOptions: Array<{ value: GrowthChangeType; label: string }> = [
  { value: "process", label: "图像处理" },
  { value: "evaluate", label: "指标评估" },
  { value: "rating", label: "评价奖励" },
  { value: "sign_in", label: "每日签到" },
  { value: "sign_in_bonus", label: "签到奖励" },
  { value: "consume", label: "消费获得" },
  { value: "refund_deduct", label: "退款扣除" },
  { value: "admin_adjust", label: "后台调整" },
];

function getChangeTypeLabel(type: GrowthChangeType) {
  return changeTypeOptions.find((t) => t.value === type)?.label ?? type;
}

function handleTimeChange(val: string[] | null) {
  if (val && val.length === 2) {
    queryParams.startTime = val[0] + " 00:00:00";
    queryParams.endTime = val[1] + " 23:59:59";
  } else {
    queryParams.startTime = undefined;
    queryParams.endTime = undefined;
  }
}

function handleQuery() {
  loading.value = true;
  MemberAPI.getGrowthLogs(queryParams)
    .then((data) => {
      pageData.value = data.list;
      total.value = data.total;
    })
    .finally(() => {
      loading.value = false;
    });
}

function resetQuery() {
  queryFormRef.value?.resetFields();
  timeRange.value = [];
  queryParams.startTime = undefined;
  queryParams.endTime = undefined;
  queryParams.pageNum = 1;
  handleQuery();
}

onMounted(() => {
  handleQuery();
});
</script>

<style lang="scss" scoped>
.growth-logs {
  max-width: 1000px;
  padding: 24px 20px 40px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 16px;

  .header-title {
    display: flex;
    gap: 8px;
    align-items: center;

    .title-text {
      font-size: 22px;
      font-weight: 600;
      color: var(--el-text-color-primary);
    }
  }
}

.type-tag {
  display: inline-block;
  padding: 2px 8px;
  font-size: 12px;
  border-radius: 4px;

  &.tag-dehaze {
    color: #409eff;
    background: #ecf5ff;
  }

  &.tag-evaluate {
    color: #13c2c2;
    background: #e6fffb;
  }

  &.tag-rating {
    color: #fa8c16;
    background: #fff7e6;
  }

  &.tag-sign_in,
  &.tag-sign_in_bonus {
    color: #52c41a;
    background: #f6ffed;
  }

  &.tag-consume {
    color: #722ed1;
    background: #f9f0ff;
  }

  &.tag-refund_deduct {
    color: #f5222d;
    background: #fff1f0;
  }

  &.tag-admin_adjust {
    color: #8c8c8c;
    background: #fafafa;
  }
}

.value-up {
  font-weight: 600;
  color: #52c41a;
}

.value-down {
  font-weight: 600;
  color: #f5222d;
}
</style>
