// dehaze-front-vue/src/views/algorithm/index.vue
<script lang="ts" setup>
import EditDialog from "@/components/DataList/EditDialog/index.vue";
import type { FormInstance } from "element-plus";
import { Algorithm, AlgorithmAPI, AlgorithmQuery } from "dehaze-sdk-js";

defineOptions({
  name: "AlgorithmList",
  inheritAttrs: false,
});

const queryFormRef = ref<FormInstance>();
const loading = ref(false);
const queryParams = reactive<AlgorithmQuery>({
  keywords: "",
});
const list = ref<Algorithm[]>([]);

// 列选项
const selectedColumns = ref([
  "name",
  "type",
  "description",
  "size",
  "importPath",
  "path",
  "status",
]);
const columns = [
  { label: "名称", value: "name" },
  { label: "类型", value: "type" },
  { label: "描述", value: "description" },
  { label: "大小", value: "size" },
  { label: "代码导入路径", value: "importPath" },
  { label: "存储位置", value: "path" },
  { label: "状态", value: "status" },
];

// 查询算法列表
function handleQuery() {
  loading.value = true;
  AlgorithmAPI.getList(queryParams)
    .then((data) => {
      list.value = data;
    })
    .catch((e) => {
      ElMessage.error("查询失败：" + e.message);
    })
    .finally(() => {
      loading.value = false;
    });
}

// 搜索防抖（300ms）
const debouncedQuery = useDebounceFn(handleQuery, 300);

// 关键字变化时防抖搜索
watch(
  () => queryParams.keywords,
  () => {
    debouncedQuery();
  }
);

function resetQuery() {
  queryFormRef.value?.resetFields();
  handleQuery();
}

const dialogRef = ref();

function openDialog<T extends Algorithm>(type: string, row: T) {
  dialogRef.value.open(type, row);
}

// 删除算法（带算法名确认文案）
function handleDelete(row: Algorithm) {
  ElMessageBox.confirm(
    `确认删除算法「${row.name}」吗？删除后不可恢复。`,
    "警告",
    {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning",
    }
  )
    .then(async () => {
      await AlgorithmAPI.deleteByIds([row.id.toString()]);
      ElMessage.success("删除成功");
      handleQuery();
    })
    .catch((err) => {
      // 仅用户取消时静默，接口错误需提示
      if (err !== "cancel" && err !== "close") {
        ElMessage.error("删除失败：" + (err.message || "未知错误"));
      }
    });
}

// 切换算法状态
function handleStatusChange(row: Algorithm, val: string | number | boolean) {
  const status = Number(val);
  AlgorithmAPI.updateStatus(row.id, status)
    .then(() => {
      row.status = status;
      ElMessage.success(status === 1 ? "已启用" : "已禁用");
    })
    .catch((e) => {
      // 接口失败时回滚状态并提示
      row.status = status === 1 ? 0 : 1;
      ElMessage.error("状态切换失败：" + e.message);
    });
}

// 算法详情弹窗
const detailVisible = ref(false);
const detailData = ref<Algorithm>();

function handleShowDetail(row: Algorithm) {
  detailData.value = row;
  detailVisible.value = true;
}

onMounted(() => {
  handleQuery();
});
</script>

<template>
  <div class="app-container">
    <div class="search-container">
      <el-form ref="queryFormRef" :inline="true" :model="queryParams">
        <el-form-item label="关键字" prop="keywords">
          <el-input
            v-model="queryParams.keywords"
            placeholder="算法名称"
            clearable
            @keyup.enter="handleQuery"
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleQuery">
            <template #icon>
              <i-ep-search />
            </template>
            搜索
          </el-button>
          <el-button @click="resetQuery">
            <template #icon>
              <i-ep-refresh />
            </template>
            重置
          </el-button>
          <el-dropdown class="setting-button">
            <el-button>
              <template #icon>
                <i-ep-setting />
              </template>
              设置
            </el-button>
            <template #dropdown>
              <div class="setting-title">列选项</div>
              <el-divider class="p-0" />
              <el-checkbox-group
                v-model="selectedColumns"
                class="setting-checkbox"
              >
                <el-checkbox
                  v-for="column in columns"
                  :key="column.value"
                  :label="column.label"
                  :value="column.value"
                />
              </el-checkbox-group>
            </template>
          </el-dropdown>
        </el-form-item>
      </el-form>
    </div>

    <el-card class="table-container" shadow="never">
      <el-table
        v-loading="loading"
        :data="list"
        :tree-props="{
          children: 'children',
          hasChildren: 'hasChildren',
        }"
        :default-expand-all="true"
        highlight-current-row
        row-key="id"
      >
        <el-table-column
          v-if="selectedColumns.includes('name')"
          label="名称"
          prop="name"
          width="200"
        >
          <template #default="scope">
            <el-button
              link
              type="primary"
              @click.stop="handleShowDetail(scope.row)"
            >
              {{ scope.row.name }}
            </el-button>
          </template>
        </el-table-column>
        <el-table-column
          v-if="selectedColumns.includes('type')"
          label="类型"
          prop="type"
          width="100"
        />
        <el-table-column
          v-if="selectedColumns.includes('description')"
          label="描述"
          min-width="500"
          prop="description"
        />
        <el-table-column
          v-if="selectedColumns.includes('size')"
          label="大小"
          prop="size"
          width="120"
        />
        <el-table-column
          v-if="selectedColumns.includes('importPath')"
          label="代码导入路径"
          min-width="180"
          prop="importPath"
        />
        <el-table-column
          v-if="selectedColumns.includes('path')"
          label="存储位置"
          prop="path"
          width="300"
        />
        <el-table-column
          v-if="selectedColumns.includes('status')"
          align="center"
          label="状态"
          min-width="90"
        >
          <template #default="scope">
            <el-switch
              :model-value="scope.row.status"
              :active-value="1"
              :inactive-value="0"
              active-text="启用"
              inactive-text="禁用"
              inline-prompt
              @change="(val) => handleStatusChange(scope.row, val)"
              @click.stop
            />
          </template>
        </el-table-column>
        <el-table-column align="center" fixed="right" label="操作" width="220">
          <template #default="scope">
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="openDialog('新增', scope.row)"
            >
              <i-ep-plus />
              新增
            </el-button>
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="openDialog('编辑', scope.row)"
            >
              <i-ep-edit />
              编辑
            </el-button>
            <el-button
              link
              size="small"
              type="primary"
              @click.stop="handleDelete(scope.row)"
            >
              <i-ep-delete />
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <EditDialog
      ref="dialogRef"
      :isDatasetList="false"
      @on-update="handleQuery"
      @on-add="handleQuery"
    />

    <!-- 算法详情弹窗 -->
    <el-dialog
      v-model="detailVisible"
      title="算法详情"
      width="640px"
      append-to-body
      destroy-on-close
    >
      <el-descriptions
        v-if="detailData"
        :column="2"
        border
        label-class-name="detail-label"
      >
        <el-descriptions-item label="算法名称">
          {{ detailData.name }}
        </el-descriptions-item>
        <el-descriptions-item label="算法类型">
          {{ detailData.type }}
        </el-descriptions-item>
        <el-descriptions-item label="算法大小">
          {{ detailData.size }}
        </el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag v-if="detailData.status === 1" type="success">启用</el-tag>
          <el-tag v-else type="info">禁用</el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="导入路径" :span="2">
          {{ detailData.importPath }}
        </el-descriptions-item>
        <el-descriptions-item label="存储位置" :span="2">
          {{ detailData.path }}
        </el-descriptions-item>
        <el-descriptions-item label="创建时间" :span="2">
          {{ detailData.createTime }}
        </el-descriptions-item>
        <el-descriptions-item label="算法描述" :span="2">
          {{ detailData.description }}
        </el-descriptions-item>
      </el-descriptions>
      <template #footer>
        <el-button @click="detailVisible = false">关闭</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style lang="scss" scoped>
.setting-button {
  margin-left: 12px;
}

.setting-title {
  margin-top: 8px;
  margin-bottom: 8px;
  font-size: 16px;
  font-weight: bold;
  text-align: center;
}

.setting-checkbox {
  display: flex;
  flex-direction: column;
  margin: 0 15px;
}

:deep(.detail-label) {
  width: 110px;
  font-weight: bold;
}
</style>

<style lang="scss">
.el-divider--horizontal {
  margin: 5px 0;
}
</style>

// dehaze-front-react/src/pages/algorithm/index.tsx
import {
  AlgorithmAPI,
  type Algorithm,
  type AlgorithmQuery,
} from "dehaze-sdk-js";
import AlgorithmFormDialog, {
  type AlgorithmFormDialogRef,
} from "@/pages/algorithm/components/AlgorithmFormDialog";
import {
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Descriptions,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Space,
  Switch,
  Table,
  Tag,
  type TableColumnsType,
} from "antd";
import { useDebounceFn } from "ahooks";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

/** 清理空 children */
function cleanAlgorithms(algorithms: Algorithm[]): void {
  for (const a of algorithms) {
    if (a.children?.length) {
      cleanAlgorithms(a.children);
    } else if (a.children && Object.keys(a.children).length === 0) {
      delete a.children;
    }
  }
}

export default function AlgorithmList(): React.JSX.Element {
  const [algorithmList, setAlgorithmList] = useState<Algorithm[]>([]);
  const [loading, setLoading] = useState(false);
  const [queryParams, setQueryParams] = useState<AlgorithmQuery>({});
  const [searchForm] = Form.useForm();
  const dialogRef = useRef<AlgorithmFormDialogRef>(null);
  const [refreshFlag, setRefreshFlag] = useState(0);
  const [detailVisible, setDetailVisible] = useState(false);
  const [detailRecord, setDetailRecord] = useState<Algorithm | null>(null);

  // ==================== 数据加载 ====================

  const loadData = useCallback(async (params: AlgorithmQuery) => {
    setLoading(true);
    try {
      const data = await AlgorithmAPI.getList(params);
      if (Array.isArray(data)) {
        cleanAlgorithms(data);
        setAlgorithmList(data);
      } else {
        setAlgorithmList([]);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData(queryParams);
  }, [queryParams, refreshFlag]); // eslint-disable-line

  const refreshList = useCallback(() => setRefreshFlag((prev) => prev + 1), []);

  // ==================== 搜索防抖（300ms） ====================

  const { run: debouncedSearch } = useDebounceFn(
    (keywords: string) => {
      setQueryParams({ keywords: keywords || undefined });
    },
    { wait: 300 }
  );

  const handleSearchChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      debouncedSearch(e.target.value);
    },
    [debouncedSearch]
  );

  const handleReset = useCallback(() => {
    searchForm.resetFields();
    setQueryParams({});
  }, [searchForm]);

  /** 点击搜索按钮：读取表单当前值并触发查询 */
  const handleSearch = useCallback(() => {
    const keywords = searchForm.getFieldValue("keywords") as string | undefined;
    setQueryParams({ keywords: keywords || undefined });
  }, [searchForm]);

  // ==================== 事件处理 ====================

  const handleAdd = useCallback(() => dialogRef.current?.open("add"), []);
  const handleAddSub = useCallback(
    (record: Algorithm) => dialogRef.current?.open("addSub", record),
    []
  );
  const handleEdit = useCallback(
    (record: Algorithm) => dialogRef.current?.open("edit", record),
    []
  );

  /** 查看算法详情 */
  const handleViewDetail = useCallback((record: Algorithm) => {
    setDetailRecord(record);
    setDetailVisible(true);
  }, []);

  /** 切换算法启用状态 */
  const handleStatusChange = useCallback(
    async (checked: boolean, record: Algorithm) => {
      const status = checked ? 1 : 0;
      try {
        await AlgorithmAPI.updateStatus(record.id, status);
        message.success(`算法「${record.name}」已${checked ? "启用" : "禁用"}`);
        refreshList();
      } catch (error: any) {
        message.error(error?.message || "状态更新失败");
      }
    },
    [refreshList]
  );

  const handleDelete = useCallback(
    (record: Algorithm) => {
      AlgorithmAPI.deleteByIds([String(record.id)])
        .then(() => {
          message.success(`算法「${record.name}」删除成功`);
          refreshList();
        })
        .catch((error) => message.error(error?.message || "删除失败"));
    },
    [refreshList]
  );

  // ==================== 表格列 ====================

  const columns: TableColumnsType<Algorithm> = useMemo(
    () => [
      {
        title: "算法名称",
        dataIndex: "name",
        key: "name",
        width: 200,
        align: "left" as const,
        render: (text: string, record: Algorithm) => (
          <Button
            type="link"
            size="small"
            style={{ padding: 0 }}
            onClick={() => handleViewDetail(record)}
          >
            {text}
          </Button>
        ),
      },
      {
        title: "类型",
        dataIndex: "type",
        key: "type",
        width: 120,
        align: "center",
        render: (text: string) => <Tag>{text}</Tag>,
      },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
        width: 100,
        align: "center",
        render: (status: number, record: Algorithm) => (
          <Switch
            checked={status === 1}
            checkedChildren="启用"
            unCheckedChildren="禁用"
            onChange={(checked) => handleStatusChange(checked, record)}
          />
        ),
      },
      {
        title: "代码导入路径",
        dataIndex: "importPath",
        key: "importPath",
        width: 160,
        render: (text: string) => text || "-",
      },
      {
        title: "FLOPs",
        dataIndex: "flops",
        key: "flops",
        width: 100,
        align: "center",
        render: (text: string) => text || "-",
      },
      {
        title: "参数量",
        dataIndex: "params",
        key: "params",
        width: 100,
        align: "center",
        render: (text: string) => text || "-",
      },
      {
        title: "描述",
        dataIndex: "description",
        key: "description",
        render: (text: string) => text || "-",
      },
      {
        title: "操作",
        key: "action",
        width: 220,
        align: "center",
        fixed: "right",
        render: (_: unknown, record: Algorithm) => (
          <Space size="small">
            <Button
              type="link"
              size="small"
              icon={<PlusOutlined />}
              onClick={() => handleAddSub(record)}
            >
              新增下级
            </Button>
            <Button
              type="link"
              size="small"
              icon={<EditOutlined />}
              onClick={() => handleEdit(record)}
            >
              编辑
            </Button>
            <Popconfirm
              title={`确认删除算法「${record.name}」吗？删除后不可恢复。`}
              onConfirm={() => handleDelete(record)}
              okText="确定"
              cancelText="取消"
              okType="danger"
            >
              <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                删除
              </Button>
            </Popconfirm>
          </Space>
        ),
      },
    ],
    [
      handleAddSub,
      handleEdit,
      handleDelete,
      handleStatusChange,
      handleViewDetail,
    ]
  );

  // ==================== 渲染 ====================

  return (
    <div className="app-container">
      <Card className="search-card" size="small">
        <Form form={searchForm} layout="inline" onFinish={handleSearch}>
          <Form.Item name="keywords" label="关键字">
            <Input
              placeholder="算法名称"
              allowClear
              style={{ width: 200 }}
              onChange={handleSearchChange}
              onPressEnter={handleSearch}
            />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button
                type="primary"
                htmlType="submit"
                icon={<SearchOutlined />}
              >
                搜索
              </Button>
              <Button
                htmlType="reset"
                icon={<ReloadOutlined />}
                onClick={handleReset}
              >
                重置
              </Button>
              <Button
                type="primary"
                icon={<PlusOutlined />}
                onClick={handleAdd}
              >
                新增
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>

      <Card className="table-card" size="small">
        <Table
          columns={columns}
          dataSource={algorithmList}
          rowKey={(record) => record.id}
          loading={loading}
          expandable={{ defaultExpandAllRows: true, indentSize: 30 }}
          pagination={false}
          scroll={{ x: 1200 }}
        />
      </Card>

      <AlgorithmFormDialog ref={dialogRef} onSuccess={refreshList} />

      {/* 算法详情弹窗 */}
      <Modal
        title="算法详情"
        open={detailVisible}
        width={680}
        footer={null}
        onCancel={() => setDetailVisible(false)}
        destroyOnHidden
      >
        {detailRecord && (
          <Descriptions column={2} bordered size="small">
            <Descriptions.Item label="算法名称">
              {detailRecord.name}
            </Descriptions.Item>
            <Descriptions.Item label="算法类型">
              <Tag>{detailRecord.type}</Tag>
            </Descriptions.Item>
            <Descriptions.Item label="状态">
              <Tag color={detailRecord.status === 1 ? "green" : "default"}>
                {detailRecord.status === 1 ? "启用" : "禁用"}
              </Tag>
            </Descriptions.Item>
            <Descriptions.Item label="代码导入路径">
              {detailRecord.importPath || "-"}
            </Descriptions.Item>
            <Descriptions.Item label="FLOPs">
              {detailRecord.flops || "-"}
            </Descriptions.Item>
            <Descriptions.Item label="参数量">
              {detailRecord.params || "-"}
            </Descriptions.Item>
            <Descriptions.Item label="算法大小">
              {detailRecord.size || "-"}
            </Descriptions.Item>
            <Descriptions.Item label="创建时间">
              {detailRecord.createTime || "-"}
            </Descriptions.Item>
            <Descriptions.Item label="算法描述" span={2}>
              {detailRecord.description || "-"}
            </Descriptions.Item>
          </Descriptions>
        )}
      </Modal>
    </div>
  );
}
