// dehaze-uniapp/src/pages/home/components/AlgorithmSection.vue
<template>
  <view class="algorithm-section">
    <view class="algorithm-content">
      <view class="algorithm-text">
        <text class="section-title">多算法智能选择</text>
        <text class="section-subtitle">
          支持DCP、AOD-Net、DehazeNet等多种先进算法
        </text>
        <view class="algorithm-features">
          <view
            v-for="(feature, index) in algorithmFeatures"
            :key="index"
            class="feature-item"
          >
            <u-icon name="checkmark-circle" size="20" color="#34d399" />
            <text class="feature-text">{{ feature }}</text>
          </view>
        </view>
        <up-button
          type="primary"
          :plain="true"
          @click="handleLearnMore"
          :custom-style="learnMoreButtonStyle"
        >
          了解更多算法详情
          <u-icon
            name="arrow-right"
            size="16"
            color="#3b82f6"
            :margin-left="8"
          />
        </up-button>
      </view>
      <view class="algorithm-visual">
        <image
          src="https://zhiyan-ai-agent-with-1258344702.cos.ap-guangzhou.tencentcos.cn/with/f49e4b9e-6079-4a0b-8f91-bcab5deec2c7/image_1763727581_1_3.jpg"
          mode="widthFix"
          class="algorithm-image"
        />
      </view>
    </view>
  </view>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { homeData } from "../data/homeData";

interface Emits {
  (e: "learn-more"): void;
}

const emit = defineEmits<Emits>();
const algorithmFeatures = ref(homeData.algorithmFeatures);

const learnMoreButtonStyle = {
  background: "#ffffff",
  color: "#3b82f6",
  border: "2rpx solid #ffffff",
  borderRadius: "10rpx",
};

const handleLearnMore = () => {
  emit("learn-more");
};
</script>

<style lang="scss" scoped>
.algorithm-section {
  padding: 80rpx 40rpx;
  background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);
  color: white;
}

.algorithm-content {
  max-width: 100%;
  margin: 0 auto;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 60rpx;
  align-items: center;
}

.section-title {
  display: block;
  font-size: 48rpx;
  font-weight: 700;
  color: #ffffff;
  margin-bottom: 16rpx;
  letter-spacing: -0.02em;
}

.section-subtitle {
  display: block;
  font-size: 28rpx;
  color: rgba(255, 255, 255, 0.8);
  line-height: 1.6;
  margin-bottom: 32rpx;
}

.algorithm-features {
  list-style: none;
  padding: 0;
  margin: 0 0 32rpx 0;
}

.feature-item {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 16rpx;
}

.feature-text {
  font-size: 28rpx;
  color: rgba(255, 255, 255, 0.95);
  line-height: 1.6;
}

.algorithm-image {
  width: 100%;
  height: auto;
  border-radius: 20rpx;
  box-shadow: 0 20rpx 60rpx rgba(0, 0, 0, 0.3);
}

@media screen and (max-width: 768rpx) {
  .algorithm-content {
    grid-template-columns: 1fr;
    gap: 40rpx;
  }

  .section-title {
    font-size: 36rpx;
  }

  .section-subtitle {
    font-size: 24rpx;
  }

  .feature-text {
    font-size: 24rpx;
  }
}
</style>

// dehaze-taro/src/pages/home/components/AlgorithmSection.tsx
import React from "react";
import { View, Text, Button, Image } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Arrow, Success } from "@taroify/icons";

import "./AlgorithmSection.less";

const AlgorithmSection: React.FC = () => {
  const algorithmImageUrl =
    "https://zhiyan-ai-agent-with-1258344702.cos.ap-guangzhou.tencentcos.cn/with/f49e4b9e-6079-4a0b-8f91-bcab5deec2c7/image_1763727581_1_3.jpg";

  const handleLearnMoreClick = () => {
    try {
      Taro.navigateTo({ url: "/pages/algorithm/index" });
    } catch (error) {
      console.warn("导航到算法页面不存在，将在实现后可用");
      Taro.showToast({
        title: "功能开发中",
        icon: "none",
      });
    }
  };

  const algorithmFeatures = [
    {
      text: "智能推荐最适合的去雾算法",
    },
    {
      text: "实时对比不同算法的处理效果",
    },
    {
      text: "毫秒级处理速度，即时查看结果",
    },
    {
      text: "支持批量处理和参数自定义",
    },
  ];

  return (
    <View className="algorithm-section">
      <View className="algorithm-content">
        <View className="algorithm-text">
          <Text className="section-title">多算法智能选择</Text>
          <Text className="section-subtitle">
            支持DCP、AOD-Net、DehazeNet等多种先进算法
          </Text>
          <View className="algorithm-features">
            {algorithmFeatures.map((feature, index) => (
              <View key={index} className="feature-item">
                <Success size="18" color="#34d399" />
                <Text className="feature-text">{feature.text}</Text>
              </View>
            ))}
          </View>
          <Button className="learn-more-btn" onClick={handleLearnMoreClick}>
            了解更多算法详情
            <Arrow className="btn-icon" size="14" color="#3b82f6" />
          </Button>
        </View>
        <View className="algorithm-visual">
          <Image
            src={algorithmImageUrl}
            className="algorithm-image"
            mode="widthFix"
            lazyLoad
          />
        </View>
      </View>
    </View>
  );
};

export default AlgorithmSection;
