// dehaze-front-vue/src/views/register/index.vue
<template>
  <div class="login-container">
    <el-card class="!border-none !bg-transparent !rounded-4% w-100 <sm:w-85">
      <div class="text-center relative">
        <h2>{{ defaultSettings.title }}</h2>
        <el-tag class="ml-2 absolute-rt">{{ defaultSettings.version }}</el-tag>
      </div>

      <el-form
        ref="registerFormRef"
        :model="registerData"
        :rules="registerRules"
        class="login-form"
      >
        <el-form-item prop="username">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="user" />
            <el-input
              v-model="registerData.username"
              placeholder="用户名（3-32位字母、数字、下划线）"
              class="h-[48px]"
              name="username"
              size="large"
            />
          </div>
        </el-form-item>

        <el-form-item prop="nickname">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="user" />
            <el-input
              v-model="registerData.nickname"
              placeholder="昵称"
              class="h-[48px]"
              name="nickname"
              size="large"
            />
          </div>
        </el-form-item>

        <el-form-item prop="password">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="lock" />
            <el-input
              v-model="registerData.password"
              placeholder="密码（6-20位，含字母和数字）"
              class="h-[48px] pr-2"
              name="password"
              show-password
              size="large"
              type="password"
            />
          </div>
        </el-form-item>

        <el-form-item prop="confirmPassword">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="lock" />
            <el-input
              v-model="registerData.confirmPassword"
              placeholder="确认密码"
              class="h-[48px] pr-2"
              show-password
              size="large"
              type="password"
              @keyup.enter="handleRegister"
            />
          </div>
        </el-form-item>

        <el-form-item prop="captchaCode">
          <div class="flex-y-center w-full">
            <svg-icon class="mx-2" icon-class="captcha" />
            <el-input
              v-model="registerData.captchaCode"
              placeholder="验证码"
              auto-complete="off"
              class="flex-1"
              size="large"
              @keyup.enter="handleRegister"
            />
            <el-image
              :src="captchaBase64"
              class="rounded-tr-md rounded-br-md cursor-pointer h-[48px]"
              @click="getCaptcha"
            />
          </div>
        </el-form-item>

        <el-button
          :loading="loading"
          class="w-full"
          size="large"
          type="primary"
          @click.prevent="handleRegister"
        >
          注 册
        </el-button>
      </el-form>

      <div class="text-center mt-4">
        <router-link to="/login">已有账号？立即登录</router-link>
      </div>
    </el-card>
  </div>
</template>

<script lang="ts" setup>
import router from "@/router";
import defaultSettings from "@/settings";
import { AuthAPI, RegisterData } from "dehaze-sdk-js";

const loading = ref(false);
const captchaBase64 = ref("");
const registerFormRef = ref(ElForm);

const registerData = ref<RegisterData & { confirmPassword: string }>({
  username: "",
  password: "",
  nickname: "",
  confirmPassword: "",
  captchaCode: "",
});

const registerRules = {
  username: [{ required: true, trigger: "blur", message: "请输入用户名" }],
  nickname: [{ required: true, trigger: "blur", message: "请输入昵称" }],
  password: [{ required: true, trigger: "blur", message: "请输入密码" }],
  confirmPassword: [{ required: true, trigger: "blur", message: "请确认密码" }],
  captchaCode: [{ required: true, trigger: "blur", message: "请输入验证码" }],
};

function getCaptcha() {
  AuthAPI.getCaptcha().then((data) => {
    registerData.value.captchaKey = data.captchaKey;
    captchaBase64.value = data.captchaBase64;
  });
}

function handleRegister() {
  registerFormRef.value.validate((valid: boolean) => {
    if (!valid) return;
    if (registerData.value.password !== registerData.value.confirmPassword) {
      ElMessage.error("两次密码输入不一致");
      return;
    }
    loading.value = true;
    AuthAPI.register({
      username: registerData.value.username,
      password: registerData.value.password,
      nickname: registerData.value.nickname,
      captchaKey: registerData.value.captchaKey,
      captchaCode: registerData.value.captchaCode,
    })
      .then(() => {
        ElMessage.success("注册成功，请登录");
        router.push("/login");
      })
      .catch(() => {
        registerData.value.captchaCode = "";
        getCaptcha();
      })
      .finally(() => {
        loading.value = false;
      });
  });
}

onMounted(() => {
  getCaptcha();
});
</script>

<style lang="scss" scoped>
html.dark .login-container {
  background: url("@/assets/images/login-bg-dark.jpg") no-repeat center right;
}

.login-container {
  overflow-y: auto;
  padding-top: var(--titlebar-h, 0px);
  background: url("@/assets/images/login-bg.jpg") no-repeat center right;
  @apply wh-full flex-center;

  .login-form {
    padding: 30px 10px;
  }
}

.el-form-item {
  background: var(--el-input-bg-color);
  border: 1px solid var(--el-border-color);
  border-radius: 5px;
}
</style>

// dehaze-front-react/src/pages/register/index.tsx
import { AuthAPI, RegisterData } from "dehaze-sdk-js";
import defaultSettings from "@/settings";
import { LockOutlined, SafetyOutlined, UserOutlined } from "@ant-design/icons";
import { Button, Card, Form, Input, Tag } from "antd";
import React, { useCallback, useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import "./index.scss";

export default function Register() {
  const [form] = Form.useForm();
  const [captchaBase64, setCaptchaBase64] = useState("");
  const [captchaKey, setCaptchaKey] = useState("");
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const getCaptcha = useCallback(() => {
    AuthAPI.getCaptcha().then((data) => {
      setCaptchaBase64(data.captchaBase64);
      setCaptchaKey(data.captchaKey);
    });
  }, []);

  useEffect(() => {
    getCaptcha();
  }, []);

  const handleRegister = (values: {
    username: string;
    password: string;
    confirmPassword: string;
    nickname: string;
    captchaCode: string;
  }) => {
    if (values.password !== values.confirmPassword) {
      form.setFields([
        { name: "confirmPassword", errors: ["两次密码输入不一致"] },
      ]);
      return;
    }

    setLoading(true);
    const data: RegisterData = {
      username: values.username,
      password: values.password,
      nickname: values.nickname,
      captchaKey,
      captchaCode: values.captchaCode,
    };

    AuthAPI.register(data)
      .then(() => {
        navigate("/login", { replace: true });
      })
      .catch(() => {
        form.setFieldsValue({ captchaCode: "" });
        getCaptcha();
      })
      .finally(() => {
        setLoading(false);
      });
  };

  return (
    <div className="login-container">
      <Card className="!border-none !bg-transparent !rounded-4% w-100 <sm:w-85">
        <div className="text-center relative">
          <h2>{defaultSettings.title}</h2>
          <Tag className="ml-2 absolute-rt">{defaultSettings.version}</Tag>
        </div>

        <Form form={form} className="login-form" onFinish={handleRegister}>
          <Form.Item
            name="username"
            rules={[
              { required: true, message: "请输入用户名" },
              {
                pattern: /^[a-zA-Z0-9_]{3,32}$/,
                message: "3-32位字母、数字、下划线",
              },
            ]}
          >
            <Input
              prefix={<UserOutlined />}
              placeholder="用户名"
              size="large"
              autoFocus
            />
          </Form.Item>

          <Form.Item
            name="nickname"
            rules={[{ required: true, message: "请输入昵称" }]}
          >
            <Input prefix={<UserOutlined />} placeholder="昵称" size="large" />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[
              { required: true, message: "请输入密码" },
              {
                pattern: /^(?=.*[a-zA-Z])(?=.*\d).{6,20}$/,
                message: "6-20位，含字母和数字",
              },
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="密码（6-20位，含字母和数字）"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="confirmPassword"
            rules={[{ required: true, message: "请确认密码" }]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="确认密码"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="captchaCode"
            rules={[{ required: true, message: "请输入验证码" }]}
          >
            <Input
              prefix={<SafetyOutlined />}
              placeholder="验证码"
              size="large"
              suffix={
                captchaBase64 ? (
                  <img
                    src={captchaBase64}
                    onClick={() => getCaptcha()}
                    alt="加载失败"
                    style={{ height: 34, cursor: "pointer" }}
                  />
                ) : (
                  <Button
                    type="link"
                    size="small"
                    onClick={getCaptcha}
                    style={{ height: 34, padding: 0 }}
                  >
                    加载验证码
                  </Button>
                )
              }
            />
          </Form.Item>

          <Form.Item>
            <Button
              className="w-full"
              size="large"
              type="primary"
              htmlType="submit"
              loading={loading}
            >
              注册
            </Button>
          </Form.Item>
        </Form>

        <div className="text-center mt-4">
          <Link to="/login">已有账号？立即登录</Link>
        </div>
      </Card>
    </div>
  );
}
