// dehaze-front-react/src/components/ImportExportToolbar/index.tsx
import {
  DownloadOutlined,
  DownOutlined,
  ImportOutlined,
  UploadOutlined,
} from "@ant-design/icons";
import { Button, Dropdown, Space, type MenuProps } from "antd";
import React, { useState } from "react";
import type { ExportModule, ImportModule } from "dehaze-sdk-js";
import { useImportExport } from "@/hooks/useImportExport";
import ExportDialog from "./ExportDialog";
import ImportDialog from "./ImportDialog";
import TaskListDrawer from "./TaskListDrawer";
import type { ImportExportToolbarProps } from "./types";

const ImportExportToolbar: React.FC<ImportExportToolbarProps> = ({
  module,
  importable = true,
  queryParams,
  extraImportParams,
  onImportComplete,
}) => {
  const { templateLoading, downloadTemplate } = useImportExport({
    module,
    queryParams,
    extraImportParams,
  });

  const [importDialogVisible, setImportDialogVisible] = useState(false);
  const [exportDialogVisible, setExportDialogVisible] = useState(false);
  const [exportInitialFormat, setExportInitialFormat] = useState<
    "excel" | "csv"
  >("excel");
  const [taskDrawerVisible, setTaskDrawerVisible] = useState(false);

  const templateMenuItems: MenuProps["items"] = [
    { key: "excel", label: "下载 Excel 模板", icon: <DownloadOutlined /> },
    { key: "csv", label: "下载 CSV 模板", icon: <DownloadOutlined /> },
  ];

  const exportMenuItems: MenuProps["items"] = [
    { key: "excel", label: "导出为 Excel" },
    { key: "csv", label: "导出为 CSV" },
  ];

  const handleTemplateMenuClick: MenuProps["onClick"] = ({ key }) => {
    downloadTemplate(key as "excel" | "csv");
  };

  const handleExportMenuClick: MenuProps["onClick"] = ({ key }) => {
    setExportInitialFormat(key as "excel" | "csv");
    setExportDialogVisible(true);
  };

  return (
    <Space>
      {importable && (
        <Space.Compact>
          <Button
            icon={<ImportOutlined />}
            onClick={() => setImportDialogVisible(true)}
          >
            导入
          </Button>
          <Dropdown
            menu={{
              items: templateMenuItems,
              onClick: handleTemplateMenuClick,
            }}
          >
            <Button
              icon={<DownOutlined />}
              loading={templateLoading}
              style={{ paddingInline: 8 }}
            />
          </Dropdown>
        </Space.Compact>
      )}
      <Dropdown
        menu={{ items: exportMenuItems, onClick: handleExportMenuClick }}
      >
        <Button icon={<DownloadOutlined />}>
          导出 <DownOutlined />
        </Button>
      </Dropdown>
      <Button
        icon={<UploadOutlined />}
        onClick={() => setTaskDrawerVisible(true)}
      >
        任务列表
      </Button>

      {importable && (
        <ImportDialog
          open={importDialogVisible}
          module={module as ImportModule}
          extraImportParams={extraImportParams}
          onClose={() => setImportDialogVisible(false)}
          onImportComplete={() => {
            setImportDialogVisible(false);
            onImportComplete?.();
          }}
        />
      )}

      <ExportDialog
        open={exportDialogVisible}
        module={module as ExportModule}
        queryParams={queryParams}
        initialFormat={exportInitialFormat}
        onClose={() => setExportDialogVisible(false)}
      />

      <TaskListDrawer
        open={taskDrawerVisible}
        module={module}
        onClose={() => setTaskDrawerVisible(false)}
      />
    </Space>
  );
};

export default ImportExportToolbar;

// dehaze-front-vue/src/components/ImportExportToolbar/index.vue
<script lang="ts" setup>
import { ExportModule, ImportModule } from "dehaze-sdk-js";
import { ArrowDown, Download, Top, Upload } from "@element-plus/icons-vue";
import { useImportExport } from "@/composables/useImportExport";
import ImportDialog from "./ImportDialog.vue";
import ExportDialog from "./ExportDialog.vue";
import TaskListDrawer from "./TaskListDrawer.vue";

defineOptions({
  name: "ImportExportToolbar",
});

const props = withDefaults(
  defineProps<{
    module: ExportModule;
    importable?: boolean;
    queryParams: Record<string, any>;
    extraImportParams?: Record<string, unknown>;
    fields?: { label: string; value: string }[];
  }>(),
  {
    importable: true,
  }
);

const emit = defineEmits<{
  (e: "import-complete"): void;
}>();

const moduleRef = computed(() => props.module);
const queryParamsRef = computed(() => props.queryParams);
const extraImportParamsRef = computed(() => props.extraImportParams);

const { downloadTemplate, templateLoading } = useImportExport({
  module: moduleRef,
  queryParams: queryParamsRef,
  extraImportParams: extraImportParamsRef,
});

const importDialogVisible = ref(false);
const exportDialogVisible = ref(false);
const exportInitialFormat = ref<"excel" | "csv">("excel");
const taskDrawerVisible = ref(false);

function handleDownloadTemplate(format: "excel" | "csv") {
  downloadTemplate(format);
}

function openImportDialog() {
  importDialogVisible.value = true;
}

function handleExportCommand(command: string) {
  exportInitialFormat.value = command as "excel" | "csv";
  exportDialogVisible.value = true;
}

function openTaskDrawer() {
  taskDrawerVisible.value = true;
}

function handleImportComplete() {
  emit("import-complete");
}

const importModule = computed(() => props.module as ImportModule);

const exportFields = computed(() => props.fields);
</script>

<template>
  <div class="import-export-toolbar">
    <el-dropdown v-if="importable" split-button @click="openImportDialog">
      <el-icon><Top /></el-icon>导入
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item @click="handleDownloadTemplate('excel')">
            <el-icon><Download /></el-icon>
            下载 Excel 模板
          </el-dropdown-item>
          <el-dropdown-item @click="handleDownloadTemplate('csv')">
            <el-icon><Download /></el-icon>
            下载 CSV 模板
          </el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <el-dropdown class="ml-3" @command="handleExportCommand">
      <el-button :loading="templateLoading">
        <el-icon><Download /></el-icon>
        导出
        <el-icon class="el-icon--right"><ArrowDown /></el-icon>
      </el-button>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item command="excel">导出为 Excel</el-dropdown-item>
          <el-dropdown-item command="csv">导出为 CSV</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <el-button class="ml-3" @click="openTaskDrawer">
      <el-icon><Upload /></el-icon>
      任务列表
    </el-button>

    <ImportDialog
      v-if="importable"
      v-model="importDialogVisible"
      :module="importModule"
      :extra-import-params="extraImportParams"
      @import-complete="handleImportComplete"
    />

    <ExportDialog
      v-model="exportDialogVisible"
      :module="module"
      :query-params="queryParams"
      :fields="exportFields"
      :initial-format="exportInitialFormat"
    />

    <TaskListDrawer v-model="taskDrawerVisible" :module="module" />
  </div>
</template>

<style lang="scss" scoped>
.import-export-toolbar {
  display: inline-flex;
  align-items: center;
}
</style>
