// dehaze-front-vue/src/App.vue
<template>
  <el-config-provider :locale="locale" :size="size">
    <!-- 开启水印 -->
    <el-watermark
      v-if="watermarkEnabled"
      :content="defaultSettings.watermarkContent"
      :font="{ color: fontColor }"
      class="wh-full"
    >
      <router-view />
    </el-watermark>
    <!-- 关闭水印 -->
    <router-view v-else />
  </el-config-provider>
</template>

<script lang="ts" setup>
import { SizeEnum } from "@/enums/SizeEnum";
import { ThemeEnum } from "@/enums/ThemeEnum";
import defaultSettings from "@/settings";
import { useAppStore, useSettingsStore } from "@/store";

const appStore = useAppStore();
const settingsStore = useSettingsStore();

const locale = computed(() => appStore.locale);
const size = computed(() => appStore.size as SizeEnum);
const watermarkEnabled = computed(() => settingsStore.watermarkEnabled);

// 明亮/暗黑主题水印字体颜色适配
const fontColor = computed(() => {
  return settingsStore.theme === ThemeEnum.DARK
    ? "rgba(255, 255, 255, .15)"
    : "rgba(0, 0, 0, .15)";
});
</script>

// src/App.tsx
import { useSelector } from "react-redux";
import { useMemo } from "react";
import { RouterProvider } from "react-router-dom";

import { ConfigProvider, Watermark } from "antd";
import { SizeType } from "antd/es/config-provider/SizeContext";
import zhCN from "antd/locale/zh_CN";
import enUS from "antd/locale/en_US";

import defaultSettings from "@/settings";
import { RootState } from "@/store";
import router from "@/router";

function App() {
  const appStore = useSelector((state: RootState) => state.app);
  const settingsStore = useSelector((state: RootState) => state.settings);

  const locale = useMemo(() => {
    switch (appStore.language) {
      case "zh-CN":
        return zhCN;
      case "en-US":
        return enUS;
      default:
        return zhCN;
    }
  }, [appStore.language]);

  return (
    <ConfigProvider locale={locale} componentSize={appStore.size as SizeType}>
      <Watermark
        content={
          settingsStore.watermarkEnabled
            ? defaultSettings.watermarkContent
            : undefined
        }
      >
        <RouterProvider router={router} />
      </Watermark>
    </ConfigProvider>
  );
}

export default App;
