// dehaze-front-react/src/components/TitleBar/index.tsx
import defaultSettings from "@/settings";
import React, { useState } from "react";

import "./index.scss";

export default function TitleBar() {
  const [isMaximized, setIsMaximized] = useState(false);

  const handleMinimize = () => window.electronAPI?.minimize();
  const handleToggleMaximize = () => {
    window.electronAPI?.toggleMaximize();
    setIsMaximized((v) => !v);
  };
  const handleClose = () => window.electronAPI?.close();

  return (
    <div className="titlebar">
      <div className="titlebar__left">
        <img src="/favicon.ico" className="titlebar__logo" alt="logo" />
        <span className="titlebar__title">{defaultSettings.title}</span>
      </div>
      <div className="titlebar__controls">
        <button
          className="titlebar__btn"
          title="最小化"
          onClick={handleMinimize}
        >
          <svg width="10" height="10" viewBox="0 0 10 10">
            <path d="M0 5h10" stroke="currentColor" strokeWidth="1" />
          </svg>
        </button>
        <button
          className="titlebar__btn"
          title="最大化"
          onClick={handleToggleMaximize}
        >
          {isMaximized ? (
            <svg width="10" height="10" viewBox="0 0 10 10">
              <rect
                x="0.5"
                y="2.5"
                width="7"
                height="7"
                fill="none"
                stroke="currentColor"
                strokeWidth="1"
              />
              <rect
                x="2.5"
                y="0.5"
                width="7"
                height="7"
                fill="none"
                stroke="currentColor"
                strokeWidth="1"
              />
            </svg>
          ) : (
            <svg width="10" height="10" viewBox="0 0 10 10">
              <rect
                x="0.5"
                y="0.5"
                width="9"
                height="9"
                fill="none"
                stroke="currentColor"
                strokeWidth="1"
              />
            </svg>
          )}
        </button>
        <button
          className="titlebar__btn titlebar__btn--close"
          title="关闭"
          onClick={handleClose}
        >
          <svg width="10" height="10" viewBox="0 0 10 10">
            <path
              d="M0 0l10 10M10 0L0 10"
              stroke="currentColor"
              strokeWidth="1"
            />
          </svg>
        </button>
      </div>
    </div>
  );
}

// dehaze-front-vue/src/components/TitleBar/index.vue
<template>
  <div class="titlebar">
    <div class="titlebar__left">
      <img :src="logo" class="titlebar__logo" />
      <span class="titlebar__title">{{ defaultSettings.title }}</span>
    </div>
    <div class="titlebar__controls">
      <button class="titlebar__btn" title="最小化" @click="handleMinimize">
        <svg width="10" height="10" viewBox="0 0 10 10">
          <path d="M0 5h10" stroke="currentColor" stroke-width="1" />
        </svg>
      </button>
      <button
        class="titlebar__btn"
        title="最大化"
        @click="handleToggleMaximize"
      >
        <svg v-if="!isMaximized" width="10" height="10" viewBox="0 0 10 10">
          <rect
            x="0.5"
            y="0.5"
            width="9"
            height="9"
            fill="none"
            stroke="currentColor"
            stroke-width="1"
          />
        </svg>
        <svg v-else width="10" height="10" viewBox="0 0 10 10">
          <rect
            x="0.5"
            y="2.5"
            width="7"
            height="7"
            fill="none"
            stroke="currentColor"
            stroke-width="1"
          />
          <rect
            x="2.5"
            y="0.5"
            width="7"
            height="7"
            fill="none"
            stroke="currentColor"
            stroke-width="1"
          />
        </svg>
      </button>
      <button
        class="titlebar__btn titlebar__btn--close"
        title="关闭"
        @click="handleClose"
      >
        <svg width="10" height="10" viewBox="0 0 10 10">
          <path
            d="M0 0l10 10M10 0L0 10"
            stroke="currentColor"
            stroke-width="1"
          />
        </svg>
      </button>
    </div>
  </div>
</template>

<script lang="ts" setup>
import defaultSettings from "@/settings";

const logo = ref("/favicon.ico");
const isMaximized = ref(false);

function handleMinimize() {
  window.electronAPI?.minimize();
}

function handleToggleMaximize() {
  window.electronAPI?.toggleMaximize();
  isMaximized.value = !isMaximized.value;
}

function handleClose() {
  window.electronAPI?.close();
}
</script>

<style lang="scss" scoped>
.titlebar {
  position: fixed;
  top: 0;
  right: 0;
  left: 0;
  z-index: 2000;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: $titlebar-height;
  padding-left: 12px;
  user-select: none;
  background: var(--el-bg-color);
  border-bottom: 1px solid var(--el-border-color-light);
  -webkit-app-region: drag;
}

.titlebar__left {
  display: flex;
  gap: 8px;
  align-items: center;
}

.titlebar__logo {
  width: 18px;
  height: 18px;
}

.titlebar__title {
  font-size: 12px;
  font-weight: 500;
  color: var(--el-text-color-primary);
}

.titlebar__controls {
  display: flex;
  height: 100%;
  -webkit-app-region: no-drag;
}

.titlebar__btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 46px;
  height: 100%;
  padding: 0;
  color: var(--el-text-color-regular);
  cursor: pointer;
  background: transparent;
  border: none;
  transition: background 0.15s;

  &:hover {
    background: var(--el-fill-color-light);
  }

  &:active {
    background: var(--el-fill-color);
  }
}

.titlebar__btn--close:hover {
  color: #fff;
  background: #e81123;
}
</style>
