// dehaze-front-vue/src/views/algorithm-select/index.vue
<script lang="ts" setup>
import { Algorithm, AlgorithmAPI, RecommendationAPI } from "dehaze-sdk-js";
import type { RecommendedAlgorithm } from "dehaze-sdk-js";
import {
  CircleCheckFilled,
  Folder,
  Grid,
  Loading,
  MagicStick,
  Refresh,
  Search,
  Upload,
} from "@element-plus/icons-vue";

defineOptions({
  name: "AlgorithmSelect",
  inheritAttrs: false,
});

const emit = defineEmits<{
  (e: "select", algorithm: Algorithm): void;
}>();

const router = useRouter();
const loading = ref(false);
const keyword = ref("");
// 所有算法（扁平化后的叶子节点）
const allAlgorithms = ref<Algorithm[]>([]);
// 当前选中的分类
const activeCategory = ref<string>("全部");
// 当前选中的算法
const selectedAlgorithm = ref<Algorithm>();

// 算法分类体系：传统/深度学习/混合
const categories = [
  { label: "全部", value: "全部" },
  { label: "传统算法", value: "传统算法" },
  { label: "深度学习算法", value: "深度学习算法" },
  { label: "混合算法", value: "混合算法" },
];

// 根据算法类型归入分类
function classifyAlgorithm(type: string): string {
  if (type.includes("深度学习") || type.includes("deep")) {
    return "深度学习算法";
  }
  if (type.includes("混合")) {
    return "混合算法";
  }
  return "传统算法";
}

// 递归扁平化算法树，提取叶子算法
function flattenAlgorithms(nodes: Algorithm[]): Algorithm[] {
  const result: Algorithm[] = [];
  nodes.forEach((node) => {
    if (node.children && node.children.length > 0) {
      result.push(...flattenAlgorithms(node.children));
    } else {
      result.push(node);
    }
  });
  return result;
}

// 树形分类数据
const treeData = computed(() => {
  const tree: any[] = categories
    .filter((c) => c.value !== "全部")
    .map((c) => ({
      label: c.label,
      value: c.value,
      children: allAlgorithms.value
        .filter((a) => classifyAlgorithm(a.type) === c.value)
        .map((a) => ({ label: a.name, value: a.name, algorithm: a })),
    }));
  return tree;
});

// 各分类算法数量统计
const categoryCount = computed(() => {
  const counts: Record<string, number> = {
    全部: allAlgorithms.value.length,
    传统算法: 0,
    深度学习算法: 0,
    混合算法: 0,
  };
  allAlgorithms.value.forEach((a) => {
    const cat = classifyAlgorithm(a.type);
    counts[cat]++;
  });
  return counts;
});

// 过滤后的算法卡片列表
const filteredAlgorithms = computed(() => {
  let result = allAlgorithms.value;
  // 分类过滤
  if (activeCategory.value !== "全部") {
    result = result.filter(
      (a) => classifyAlgorithm(a.type) === activeCategory.value
    );
  }
  // 关键词过滤
  const kw = keyword.value.trim().toLowerCase();
  if (kw) {
    result = result.filter(
      (a) =>
        a.name.toLowerCase().includes(kw) ||
        a.type.toLowerCase().includes(kw) ||
        (a.description || "").toLowerCase().includes(kw)
    );
  }
  return result;
});

// 智能推荐：基于算法类型推荐 Top 3（每个分类取第一个启用的算法）
const recommendAlgorithms = computed(() => {
  const recommended: Algorithm[] = [];
  const categoryList = ["传统算法", "深度学习算法", "混合算法"];
  categoryList.forEach((cat) => {
    const found = allAlgorithms.value.find(
      (a) => classifyAlgorithm(a.type) === cat && a.status === 1
    );
    if (found) {
      recommended.push(found);
    }
  });
  return recommended.slice(0, 3);
});

// ===== 图像推荐引擎 =====
const recommendTab = ref<"quick" | "image">("quick");
const imageUrlInput = ref("");
const analyzing = ref(false);
const imageRecommendations = ref<RecommendedAlgorithm[]>([]);
const analysisResult = ref<{
  hazeLevel: string;
  sceneType: string;
  lighting: string;
  complexity: number;
} | null>(null);

async function handleImageRecommend() {
  const url = imageUrlInput.value.trim();
  if (!url) {
    ElMessage.warning("请输入图片URL");
    return;
  }
  analyzing.value = true;
  imageRecommendations.value = [];
  analysisResult.value = null;
  try {
    const analysis = await RecommendationAPI.analyze({ imageUrl: url });
    analysisResult.value = {
      hazeLevel: analysis.hazeLevel,
      sceneType: analysis.sceneType,
      lighting: analysis.lighting,
      complexity: analysis.complexity,
    };
    const recs = await RecommendationAPI.getAlgorithmRecommendations({
      imageMd5: analysis.imageMd5,
    });
    imageRecommendations.value = recs;
  } catch (e: any) {
    ElMessage.error("推荐分析失败：" + (e.message || "未知错误"));
  } finally {
    analyzing.value = false;
  }
}

function selectRecommended(algo: RecommendedAlgorithm) {
  const matched = allAlgorithms.value.find((a) => a.id === algo.algorithmId);
  if (matched) {
    selectedAlgorithm.value = matched;
    ElMessage.success(`已选择推荐算法：${algo.algorithmName}`);
  }
}

// 加载算法列表
function loadAlgorithms() {
  loading.value = true;
  AlgorithmAPI.getList()
    .then((data) => {
      allAlgorithms.value = flattenAlgorithms(data);
    })
    .catch((e: any) => {
      ElMessage.error("加载算法列表失败：" + (e.message || "未知错误"));
    })
    .finally(() => {
      loading.value = false;
    });
}

// 重置过滤
function resetFilter() {
  keyword.value = "";
  activeCategory.value = "全部";
}

// 点击树节点
function handleNodeClick(data: any) {
  if (data.algorithm) {
    // 点击叶子节点：选中算法
    selectedAlgorithm.value = data.algorithm;
  } else if (data.value) {
    // 点击分类节点：切换分类
    activeCategory.value = data.value;
  }
}

// 选择算法卡片
function handleSelectCard(algorithm: Algorithm) {
  selectedAlgorithm.value = algorithm;
}

// 确认选择
function handleConfirm() {
  if (!selectedAlgorithm.value) {
    ElMessage.warning("请先选择一个算法");
    return;
  }
  emit("select", selectedAlgorithm.value);
  ElMessage.success(`已选择算法：${selectedAlgorithm.value.name}`);
  // 返回上一页
  router.back();
}

onMounted(() => {
  loadAlgorithms();
});
</script>

<template>
  <div class="algorithm-select-container">
    <!-- 顶部搜索区 -->
    <el-card class="search-card" shadow="never">
      <div class="search-header">
        <el-input
          v-model="keyword"
          placeholder="搜索算法名称、类型或描述"
          clearable
          class="search-input"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>
        <el-button @click="resetFilter">
          <template #icon>
            <el-icon><Refresh /></el-icon>
          </template>
          重置
        </el-button>
      </div>
    </el-card>

    <!-- 智能推荐区域 -->
    <el-card class="recommend-card" shadow="never">
      <template #header>
        <div class="card-title">
          <el-icon><MagicStick /></el-icon>
          <span>智能推荐</span>
          <el-radio-group v-model="recommendTab" size="small">
            <el-radio-button label="quick">快速推荐</el-radio-button>
            <el-radio-button label="image">图像分析推荐</el-radio-button>
          </el-radio-group>
        </div>
      </template>

      <!-- 快速推荐（静态） -->
      <div
        v-if="recommendTab === 'quick'"
        v-loading="loading"
        class="recommend-list"
      >
        <div
          v-for="algo in recommendAlgorithms"
          :key="algo.id"
          class="recommend-item"
          :class="{ active: selectedAlgorithm?.id === algo.id }"
          @click="handleSelectCard(algo)"
        >
          <div class="recommend-info">
            <div class="recommend-name">{{ algo.name }}</div>
            <el-tag size="small" type="primary">
              {{ classifyAlgorithm(algo.type) }}
            </el-tag>
          </div>
          <div class="recommend-desc">{{ algo.description || "暂无描述" }}</div>
        </div>
        <el-empty
          v-if="!loading && recommendAlgorithms.length === 0"
          description="暂无推荐算法"
          :image-size="60"
        />
      </div>

      <!-- 图像分析推荐（真实推荐引擎） -->
      <div v-else class="image-recommend-section">
        <div class="image-url-input">
          <el-input
            v-model="imageUrlInput"
            placeholder="输入图片URL以获取智能推荐"
            clearable
            @keyup.enter="handleImageRecommend"
          >
            <template #append>
              <el-button :loading="analyzing" @click="handleImageRecommend">
                <el-icon><Search /></el-icon>分析
              </el-button>
            </template>
          </el-input>
        </div>
        <div v-if="analysisResult" class="analysis-result">
          <el-tag size="small">雾霾: {{ analysisResult.hazeLevel }}</el-tag>
          <el-tag size="small" type="success"
            >场景: {{ analysisResult.sceneType }}</el-tag
          >
          <el-tag size="small" type="warning"
            >光照: {{ analysisResult.lighting }}</el-tag
          >
          <span class="complexity-label">
            复杂度: {{ (analysisResult.complexity * 100).toFixed(0) }}%
          </span>
        </div>
        <div v-if="imageRecommendations.length > 0" class="image-rec-list">
          <div
            v-for="rec in imageRecommendations"
            :key="rec.algorithmId"
            class="image-rec-item"
            :class="{
              active: selectedAlgorithm?.id === rec.algorithmId,
            }"
            @click="selectRecommended(rec)"
          >
            <div class="rec-header">
              <span class="rec-name">{{ rec.algorithmName }}</span>
              <el-progress
                :percentage="rec.matchScore"
                :stroke-width="6"
                :show-text="false"
                style="width: 100px"
              />
              <span class="rec-score">{{ rec.matchScore }}%</span>
            </div>
            <div class="rec-reason">{{ rec.reason }}</div>
            <div v-if="rec.effectDescription" class="rec-effect">
              {{ rec.effectDescription }}
            </div>
          </div>
        </div>
        <el-empty
          v-if="
            !analyzing && imageRecommendations.length === 0 && !analysisResult
          "
          description="输入图片URL获取个性化算法推荐"
          :image-size="80"
        />
        <div v-if="analyzing" class="analyzing-hint">
          <el-icon class="is-loading"><Loading /></el-icon>
          正在分析图像特征并匹配算法...
        </div>
      </div>
    </el-card>

    <!-- 主体区域：左侧树 + 右侧卡片 -->
    <div class="main-content">
      <!-- 左侧树形分类 -->
      <el-card class="tree-card" shadow="never">
        <template #header>
          <div class="card-title">
            <el-icon><Folder /></el-icon>
            <span>算法分类</span>
          </div>
        </template>
        <div class="category-tabs">
          <div
            v-for="cat in categories"
            :key="cat.value"
            class="category-tab"
            :class="{ active: activeCategory === cat.value }"
            @click="activeCategory = cat.value"
          >
            {{ cat.label }}
            <span class="category-count">{{ categoryCount[cat.value] }}</span>
          </div>
        </div>
        <el-tree
          :data="treeData"
          :props="{ label: 'label', children: 'children' }"
          node-key="value"
          default-expand-all
          highlight-current
          @node-click="handleNodeClick"
        >
          <template #default="{ data }">
            <span class="tree-node">
              <span>{{ data.label }}</span>
              <span v-if="data.algorithm" class="tree-node-type">
                {{ data.algorithm.type }}
              </span>
            </span>
          </template>
        </el-tree>
      </el-card>

      <!-- 右侧算法卡片列表 -->
      <el-card class="cards-card" shadow="never">
        <template #header>
          <div class="card-title">
            <el-icon><Grid /></el-icon>
            <span>算法列表</span>
            <el-tag size="small">共 {{ filteredAlgorithms.length }} 个</el-tag>
          </div>
        </template>
        <div v-loading="loading" class="card-list">
          <div
            v-for="algo in filteredAlgorithms"
            :key="algo.id"
            class="algo-card"
            :class="{ selected: selectedAlgorithm?.id === algo.id }"
            @click="handleSelectCard(algo)"
          >
            <div class="algo-card-header">
              <span class="algo-name">{{ algo.name }}</span>
              <el-tag
                size="small"
                :type="algo.status === 1 ? 'success' : 'info'"
              >
                {{ algo.status === 1 ? "启用" : "禁用" }}
              </el-tag>
            </div>
            <div class="algo-card-type">
              <el-tag size="small" type="primary">
                {{ classifyAlgorithm(algo.type) }}
              </el-tag>
              <span class="algo-type-raw">{{ algo.type }}</span>
            </div>
            <div class="algo-card-desc">
              {{ algo.description || "暂无描述" }}
            </div>
            <div
              v-if="selectedAlgorithm?.id === algo.id"
              class="algo-card-check"
            >
              <el-icon><CircleCheckFilled /></el-icon>
            </div>
          </div>
          <el-empty
            v-if="!loading && filteredAlgorithms.length === 0"
            description="暂无匹配算法"
          />
        </div>
      </el-card>
    </div>

    <!-- 底部确认选择 -->
    <div class="footer-bar">
      <div class="selected-info">
        已选择：
        <span v-if="selectedAlgorithm" class="selected-name">
          {{ selectedAlgorithm.name }}
        </span>
        <span v-else class="selected-empty">未选择</span>
      </div>
      <el-button
        type="primary"
        size="large"
        :disabled="!selectedAlgorithm"
        @click="handleConfirm"
      >
        确认选择
      </el-button>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.algorithm-select-container {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 16px;
}

.search-header {
  display: flex;
  gap: 12px;
  align-items: center;

  .search-input {
    width: 360px;
  }
}

.card-title {
  display: flex;
  gap: 8px;
  align-items: center;
  font-size: 16px;
  font-weight: bold;
}

.recommend-list {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.recommend-item {
  position: relative;
  flex: 1;
  min-width: 220px;
  padding: 12px 16px;
  cursor: pointer;
  background: var(--el-fill-color-light);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  transition: all 0.2s;

  &:hover {
    border-color: var(--el-color-primary);
    box-shadow: 0 2px 12px rgb(0 0 0 / 10%);
  }

  &.active {
    background: var(--el-color-primary-light-9);
    border-color: var(--el-color-primary);
  }

  .recommend-info {
    display: flex;
    gap: 8px;
    align-items: center;
    margin-bottom: 6px;

    .recommend-name {
      font-size: 15px;
      font-weight: 600;
    }
  }

  .recommend-desc {
    display: -webkit-box;
    overflow: hidden;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
    font-size: 13px;
    line-height: 1.5;
    color: var(--el-text-color-secondary);
    -webkit-box-orient: vertical;
  }
}

.main-content {
  display: flex;
  gap: 16px;
  align-items: flex-start;
}

.tree-card {
  flex: 0 0 260px;

  .category-tabs {
    display: flex;
    flex-direction: column;
    gap: 4px;
    margin-bottom: 12px;
  }

  .category-tab {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 12px;
    cursor: pointer;
    border-radius: 6px;
    transition: all 0.2s;

    &:hover {
      background: var(--el-fill-color-light);
    }

    &.active {
      color: var(--el-color-primary);
      background: var(--el-color-primary-light-9);
    }

    .category-count {
      padding: 0 8px;
      font-size: 12px;
      color: var(--el-text-color-secondary);
      background: var(--el-fill-color);
      border-radius: 10px;
    }
  }
}

.tree-node {
  display: flex;
  gap: 8px;
  align-items: center;

  .tree-node-type {
    font-size: 12px;
    color: var(--el-text-color-secondary);
  }
}

.cards-card {
  flex: 1;
  min-width: 0;
}

.card-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 16px;
}

.algo-card {
  position: relative;
  padding: 16px;
  cursor: pointer;
  background: var(--el-bg-color);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  transition: all 0.2s;

  &:hover {
    border-color: var(--el-color-primary);
    box-shadow: 0 2px 12px rgb(0 0 0 / 10%);
  }

  &.selected {
    background: var(--el-color-primary-light-9);
    border-color: var(--el-color-primary);
  }

  .algo-card-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;

    .algo-name {
      font-size: 15px;
      font-weight: 600;
    }
  }

  .algo-card-type {
    display: flex;
    gap: 8px;
    align-items: center;
    margin-bottom: 8px;

    .algo-type-raw {
      font-size: 12px;
      color: var(--el-text-color-secondary);
    }
  }

  .algo-card-desc {
    display: -webkit-box;
    overflow: hidden;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
    font-size: 13px;
    line-height: 1.5;
    color: var(--el-text-color-secondary);
    -webkit-box-orient: vertical;
  }

  .algo-card-check {
    position: absolute;
    top: 12px;
    right: 12px;
    font-size: 20px;
    color: var(--el-color-primary);
  }
}

.footer-bar {
  position: sticky;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 24px;
  background: var(--el-bg-color);
  border-top: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  box-shadow: 0 -2px 12px rgb(0 0 0 / 5%);

  .selected-info {
    font-size: 14px;

    .selected-name {
      font-weight: 600;
      color: var(--el-color-primary);
    }

    .selected-empty {
      color: var(--el-text-color-secondary);
    }
  }
}

.image-recommend-section {
  .image-url-input {
    margin-bottom: 12px;
  }

  .analysis-result {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    align-items: center;
    padding: 8px 12px;
    margin-bottom: 12px;
    background: var(--el-fill-color-light);
    border-radius: 6px;

    .complexity-label {
      font-size: 12px;
      color: var(--el-text-color-secondary);
    }
  }

  .image-rec-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .image-rec-item {
    padding: 12px 16px;
    cursor: pointer;
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 8px;
    transition: all 0.2s;

    &:hover {
      border-color: var(--el-color-primary);
      box-shadow: 0 2px 12px rgb(0 0 0 / 10%);
    }

    &.active {
      background: var(--el-color-primary-light-9);
      border-color: var(--el-color-primary);
    }

    .rec-header {
      display: flex;
      gap: 12px;
      align-items: center;
      margin-bottom: 6px;

      .rec-name {
        min-width: 160px;
        font-size: 15px;
        font-weight: 600;
      }

      .rec-score {
        font-size: 14px;
        font-weight: 600;
        color: var(--el-color-primary);
      }
    }

    .rec-reason {
      font-size: 13px;
      color: var(--el-text-color-secondary);
    }

    .rec-effect {
      margin-top: 4px;
      font-size: 12px;
      color: var(--el-color-success);
    }
  }

  .analyzing-hint {
    display: flex;
    gap: 8px;
    align-items: center;
    justify-content: center;
    padding: 24px;
    font-size: 14px;
    color: var(--el-text-color-secondary);
  }
}
</style>

// dehaze-front-react/src/pages/algorithm-select/index.tsx
import { AlgorithmAPI, RecommendationAPI, type Algorithm } from "dehaze-sdk-js";
import { useDebounceFn } from "ahooks";
import {
  CheckCircleFilled,
  FireOutlined,
  ReloadOutlined,
  SearchOutlined,
  ThunderboltFilled,
  PictureOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Col,
  Divider,
  Empty,
  Form,
  Input,
  Progress,
  Rate,
  Row,
  Space,
  Spin,
  Statistic,
  Tabs,
  Tag,
  Tree,
  Typography,
  message,
} from "antd";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

const { Title, Paragraph, Text } = Typography;

/** 算法类型分类配置 */
const TYPE_CATEGORIES: { key: string; label: string }[] = [
  { key: "traditional", label: "传统算法" },
  { key: "deep_learning", label: "深度学习算法" },
  { key: "hybrid", label: "混合算法" },
];

/** 推荐优先级：深度学习 > 混合 > 传统 */
const RECOMMEND_ORDER = ["deep_learning", "hybrid", "traditional"];

/** 类型标签颜色映射 */
const TYPE_COLOR_MAP: Record<string, string> = {
  traditional: "blue",
  deep_learning: "volcano",
  hybrid: "cyan",
};

/** 递归提取叶子算法（无 children 的节点） */
function flattenAlgorithms(list: Algorithm[]): Algorithm[] {
  const result: Algorithm[] = [];
  const walk = (nodes: Algorithm[]) => {
    for (const node of nodes) {
      if (node.children?.length) {
        walk(node.children);
      } else {
        result.push(node);
      }
    }
  };
  walk(list);
  return result;
}

export default function AlgorithmSelect(): React.JSX.Element {
  const navigate = useNavigate();
  const [algorithmTree, setAlgorithmTree] = useState<Algorithm[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedType, setSelectedType] = useState<string>("all");
  const [keywords, setKeywords] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);

  // ==================== 智能推荐 - 图像分析 ====================

  /** 图像分析结果 */
  interface ImageAnalysisResult {
    hazeLevel: string;
    sceneType: string;
    lighting: string;
    complexity: string;
  }

  const [analysisResult, setAnalysisResult] =
    useState<ImageAnalysisResult | null>(null);
  const [imageUrlInput, setImageUrlInput] = useState("");
  const [imageMd5, setImageMd5] = useState<string>("");
  const [analyzing, setAnalyzing] = useState(false);
  const [recommendations, setRecommendations] = useState<
    Array<{
      algorithm: Algorithm;
      matchScore: number;
      reason: string;
      effectDescription: string;
    }>
  >([]);
  const [analyzingRecs, setAnalyzingRecs] = useState(false);

  /** 分析图像特征 */
  const handleAnalyzeImage = useCallback(async (imageUrl: string) => {
    if (!imageUrl.trim()) {
      message.warning("请输入图片地址");
      return;
    }
    setAnalyzing(true);
    try {
      const analysis = await RecommendationAPI.analyze({
        imageUrl: imageUrl.trim(),
      });
      setAnalysisResult({
        hazeLevel: String(analysis.hazeLevel) || "未知",
        sceneType: String(analysis.sceneType) || "未知",
        lighting: String(analysis.lighting) || "未知",
        complexity: String(analysis.complexity) || "未知",
      });
      setImageMd5(analysis.imageMd5 || "");
      // 获取推荐算法
      if (analysis.imageMd5) {
        setAnalyzingRecs(true);
        const recs = await RecommendationAPI.getAlgorithmRecommendations({
          imageMd5: analysis.imageMd5,
        });
        const mapped = (recs || []).slice(0, 3).map((r) => ({
          algorithm: {
            id: r.algorithmId,
            name: r.algorithmName,
            type: "deep_learning" as const,
            description: r.effectDescription || "",
            status: 1,
          } as Algorithm,
          matchScore: r.matchScore || 0,
          reason: r.reason || "",
          effectDescription: r.effectDescription || "",
        }));
        setRecommendations(mapped);
      }
    } catch (error: any) {
      message.error(error?.message || "图像分析失败");
    } finally {
      setAnalyzing(false);
      setAnalyzingRecs(false);
    }
  }, []);

  /** 选择推荐算法 */
  const handleSelectRecommendation = useCallback((algo: Algorithm) => {
    setSelectedId(algo.id);
    message.success(`已选择 ${algo.name}`);
  }, []);

  // ==================== 数据加载 ====================

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const data = await AlgorithmAPI.getList();
      setAlgorithmTree(Array.isArray(data) ? data : []);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // ==================== 派生数据 ====================

  /** 所有叶子算法 */
  const allAlgorithms = useMemo(
    () => flattenAlgorithms(algorithmTree),
    [algorithmTree]
  );

  /** 按类型统计数量 */
  const typeCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const a of allAlgorithms) {
      counts[a.type] = (counts[a.type] || 0) + 1;
    }
    return counts;
  }, [allAlgorithms]);

  /** 分类树数据 */
  const treeData = useMemo(() => {
    const nodes = TYPE_CATEGORIES.map((c) => ({
      key: c.key,
      title: `${c.label}（${typeCounts[c.key] || 0}）`,
    }));
    return [
      { key: "all", title: `全部算法（${allAlgorithms.length}）` },
      ...nodes,
    ];
  }, [allAlgorithms.length, typeCounts]);

  /** 智能推荐 Top 3（基于算法类型推荐，取已启用算法） */
  const recommendList = useMemo(() => {
    const enabled = allAlgorithms.filter((a) => a.status === 1);
    const ordered: Algorithm[] = [];
    for (const type of RECOMMEND_ORDER) {
      for (const a of enabled) {
        if (ordered.length >= 3) break;
        if (a.type === type) ordered.push(a);
      }
      if (ordered.length >= 3) break;
    }
    return ordered.slice(0, 3);
  }, [allAlgorithms]);

  /** 当前展示的算法列表（按分类 + 关键词过滤） */
  const displayList = useMemo(() => {
    let list = allAlgorithms;
    if (selectedType !== "all") {
      list = list.filter((a) => a.type === selectedType);
    }
    const kw = keywords.trim().toLowerCase();
    if (kw) {
      list = list.filter(
        (a) =>
          a.name.toLowerCase().includes(kw) ||
          (a.description || "").toLowerCase().includes(kw) ||
          (a.type || "").toLowerCase().includes(kw)
      );
    }
    return list;
  }, [allAlgorithms, selectedType, keywords]);

  // ==================== 搜索防抖（300ms） ====================

  const { run: debouncedSearch } = useDebounceFn(
    (value: string) => setKeywords(value),
    { wait: 300 }
  );

  // ==================== 事件处理 ====================

  const handleTreeSelect = useCallback((keys: React.Key[]) => {
    setSelectedType((keys[0] as string) || "all");
    setSelectedId(null);
  }, []);

  const handleReset = useCallback(() => {
    setKeywords("");
    setSelectedType("all");
    setSelectedId(null);
  }, []);

  /** 确认选择，跳转回图像去雾页并传递算法参数 */
  const handleConfirm = useCallback(() => {
    const selected = allAlgorithms.find((a) => a.id === selectedId);
    if (!selected) {
      message.warning("请先选择一个算法");
      return;
    }
    navigate("/presentation/dehaze", {
      state: {
        algorithmId: selected.id,
        algorithmName: selected.name,
        algorithmType: selected.type,
        importPath: selected.importPath,
      },
    });
  }, [allAlgorithms, selectedId, navigate]);

  // ==================== 渲染 ====================

  return (
    <div className="app-container">
      {/* 智能推荐区域 */}
      <Card size="small" style={{ marginBottom: 12 }} loading={loading}>
        <Title level={5} style={{ marginTop: 0, marginBottom: 12 }}>
          <ThunderboltFilled style={{ color: "#faad14", marginRight: 8 }} />
          智能推荐
        </Title>
        <Tabs
          defaultActiveKey="quick"
          items={[
            {
              key: "quick",
              label: (
                <Space>
                  <ThunderboltFilled style={{ color: "#faad14" }} />
                  快速推荐
                </Space>
              ),
              children:
                recommendList.length === 0 ? (
                  <Empty description="暂无推荐算法" style={{ padding: 24 }} />
                ) : (
                  <Row gutter={[12, 12]}>
                    {recommendList.map((algo) => (
                      <Col key={algo.id} span={8}>
                        <Card
                          size="small"
                          hoverable
                          style={{
                            borderColor:
                              selectedId === algo.id ? "#3B82F6" : undefined,
                            background:
                              selectedId === algo.id ? "#eff6ff" : undefined,
                          }}
                          onClick={() => setSelectedId(algo.id)}
                        >
                          <Space
                            direction="vertical"
                            size={4}
                            style={{ width: "100%" }}
                          >
                            <Space>
                              {selectedId === algo.id && (
                                <CheckCircleFilled
                                  style={{ color: "#3B82F6" }}
                                />
                              )}
                              <Text strong>{algo.name}</Text>
                              <Tag color="orange">推荐</Tag>
                            </Space>
                            <Space size={4}>
                              <Tag>{algo.type}</Tag>
                              <Tag
                                color={algo.status === 1 ? "green" : "default"}
                              >
                                {algo.status === 1 ? "启用" : "禁用"}
                              </Tag>
                            </Space>
                            <Paragraph
                              type="secondary"
                              ellipsis={{ rows: 2 }}
                              style={{ marginBottom: 0 }}
                            >
                              {algo.description || "暂无描述"}
                            </Paragraph>
                          </Space>
                        </Card>
                      </Col>
                    ))}
                  </Row>
                ),
            },
            {
              key: "image",
              label: (
                <Space>
                  <PictureOutlined />
                  图像分析推荐
                </Space>
              ),
              children: (
                <Card size="small">
                  {/* 图像分析输入区 */}
                  <Form layout="inline" style={{ marginBottom: 16 }}>
                    <Form.Item label="图片地址">
                      <Input
                        placeholder="请输入图片 URL"
                        prefix={<FireOutlined />}
                        value={imageUrlInput}
                        disabled={!!analysisResult}
                        onChange={(e) => setImageUrlInput(e.target.value)}
                        onPressEnter={() => handleAnalyzeImage(imageUrlInput)}
                        style={{ width: 320 }}
                      />
                    </Form.Item>
                    <Form.Item>
                      <Button
                        type="primary"
                        icon={<SearchOutlined />}
                        onClick={() => handleAnalyzeImage(imageUrlInput)}
                        loading={analyzing}
                      >
                        分析
                      </Button>
                    </Form.Item>
                  </Form>

                  {/* 分析结果 */}
                  {analyzing && (
                    <Spin
                      tip="正在分析图像特征..."
                      style={{ display: "block", marginBottom: 16 }}
                    />
                  )}

                  {analysisResult && !analyzing && (
                    <>
                      <Card size="small" style={{ marginBottom: 16 }}>
                        <Title
                          level={5}
                          style={{ marginTop: 0, marginBottom: 8 }}
                        >
                          图像特征分析
                        </Title>
                        <Row gutter={[16, 8]}>
                          <Col span={6}>
                            <Statistic
                              title="雾霾程度"
                              value={analysisResult.hazeLevel}
                              suffix=""
                            />
                          </Col>
                          <Col span={6}>
                            <Statistic
                              title="场景类型"
                              value={analysisResult.sceneType}
                              suffix=""
                            />
                          </Col>
                          <Col span={6}>
                            <Statistic
                              title="光照条件"
                              value={analysisResult.lighting}
                              suffix=""
                            />
                          </Col>
                          <Col span={6}>
                            <Statistic
                              title="复杂度"
                              value={analysisResult.complexity}
                              suffix=""
                            />
                          </Col>
                        </Row>
                      </Card>

                      {/* 推荐算法列表 */}
                      <Title level={5} style={{ marginBottom: 8 }}>
                        推荐算法
                      </Title>
                      {analyzingRecs ? (
                        <Spin
                          tip="正在获取推荐..."
                          style={{ display: "block", padding: 16 }}
                        />
                      ) : recommendations.length === 0 ? (
                        <Empty
                          description="暂无推荐结果"
                          image={Empty.PRESENTED_IMAGE_SIMPLE}
                        />
                      ) : (
                        <Row gutter={[12, 12]}>
                          {recommendations.map((rec, idx) => (
                            <Col key={idx} span={24}>
                              <Card
                                size="small"
                                style={{
                                  borderLeft: `3px solid ${rec.matchScore >= 80 ? "#52c41a" : rec.matchScore >= 60 ? "#faad14" : "#f5222d"}`,
                                }}
                              >
                                <Row gutter={12} align="middle">
                                  <Col span={16}>
                                    <Space direction="vertical" size={4}>
                                      <Space>
                                        <Text strong>{rec.algorithm.name}</Text>
                                        <Tag
                                          color={
                                            TYPE_COLOR_MAP[
                                              rec.algorithm.type
                                            ] || "blue"
                                          }
                                        >
                                          {rec.algorithm.type}
                                        </Tag>
                                      </Space>
                                      <Progress
                                        percent={rec.matchScore}
                                        strokeColor={{
                                          "60%": "#52c41a",
                                          "40%": "#faad14",
                                          "0%": "#f5222d",
                                        }}
                                        format={() => `${rec.matchScore}% 匹配`}
                                      />
                                      <Paragraph
                                        type="secondary"
                                        style={{ marginBottom: 0 }}
                                      >
                                        {rec.effectDescription ||
                                          rec.reason ||
                                          "暂无描述"}
                                      </Paragraph>
                                    </Space>
                                  </Col>
                                  <Col span={8} style={{ textAlign: "right" }}>
                                    <Button
                                      type="primary"
                                      size="small"
                                      onClick={() =>
                                        handleSelectRecommendation(
                                          rec.algorithm
                                        )
                                      }
                                    >
                                      选择
                                    </Button>
                                  </Col>
                                </Row>
                              </Card>
                            </Col>
                          ))}
                        </Row>
                      )}
                    </>
                  )}
                </Card>
              ),
            },
          ]}
        />
      </Card>

      {/* 主体：左侧分类树 + 右侧算法卡片 */}
      <Row gutter={12}>
        <Col span={5}>
          <Card size="small" title="算法分类" loading={loading}>
            <Tree
              treeData={treeData}
              defaultSelectedKeys={["all"]}
              onSelect={handleTreeSelect}
              blockNode
            />
          </Card>
        </Col>
        <Col span={19}>
          <Card
            size="small"
            title={
              <Space>
                <Input
                  placeholder="搜索算法名称、类型、描述"
                  allowClear
                  prefix={<SearchOutlined />}
                  style={{ width: 260 }}
                  value={keywords}
                  onChange={(e) => debouncedSearch(e.target.value)}
                />
                <Button icon={<ReloadOutlined />} onClick={handleReset}>
                  重置
                </Button>
              </Space>
            }
            extra={
              <Button
                type="primary"
                disabled={!selectedId}
                onClick={handleConfirm}
              >
                确认选择
              </Button>
            }
          >
            {displayList.length === 0 ? (
              <Empty description="暂无匹配算法" />
            ) : (
              <Row gutter={[12, 12]}>
                {displayList.map((algo) => (
                  <Col key={algo.id} span={8}>
                    <Card
                      size="small"
                      hoverable
                      style={{
                        borderColor:
                          selectedId === algo.id ? "#3B82F6" : undefined,
                        background:
                          selectedId === algo.id ? "#eff6ff" : undefined,
                      }}
                      onClick={() => setSelectedId(algo.id)}
                    >
                      <Space
                        direction="vertical"
                        size={6}
                        style={{ width: "100%" }}
                      >
                        <Space>
                          {selectedId === algo.id && (
                            <CheckCircleFilled style={{ color: "#3B82F6" }} />
                          )}
                          <Text strong>{algo.name}</Text>
                        </Space>
                        <Space size={4}>
                          <Tag>{algo.type}</Tag>
                          <Tag color={algo.status === 1 ? "green" : "default"}>
                            {algo.status === 1 ? "启用" : "禁用"}
                          </Tag>
                        </Space>
                        <Paragraph
                          type="secondary"
                          ellipsis={{ rows: 2 }}
                          style={{ marginBottom: 0 }}
                        >
                          {algo.description || "暂无描述"}
                        </Paragraph>
                      </Space>
                    </Card>
                  </Col>
                ))}
              </Row>
            )}
          </Card>
        </Col>
      </Row>
    </div>
  );
}
