// dehaze-front-react/src/pages/feedback/stats/index.tsx
import * as echarts from "echarts";
import {
  FeedbackAPI,
  type FeedbackStatsVO,
  type FeedbackStatus,
  type FeedbackType,
  type RatingStatsVO,
} from "dehaze-sdk-js";
import {
  Card,
  Col,
  DatePicker,
  Empty,
  Progress,
  Rate,
  Row,
  Spin,
  Table,
  Tabs,
  Tag,
  type TableColumnsType,
} from "antd";
import {
  BarChartOutlined,
  MessageOutlined,
  StarOutlined,
} from "@ant-design/icons";
import type { Dayjs } from "dayjs";
import dayjs from "dayjs";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { useSearchParams } from "react-router-dom";
import "./index.scss";

const { RangePicker } = DatePicker;

const RATING_COLOR_MAP: Record<number, string> = {
  1: "#f5222d",
  2: "#fa8c16",
  3: "#faad14",
  4: "#409eff",
  5: "#52c41a",
};

const TYPE_LABEL: Record<FeedbackType, string> = {
  suggestion: "功能建议",
  bug: "问题报告",
  experience: "体验反馈",
  complaint: "投诉",
};
const TYPE_COLOR: Record<FeedbackType, string> = {
  suggestion: "#409eff",
  experience: "#67c23a",
  complaint: "#e6a23c",
  bug: "#f56c6c",
};

const STATUS_LABEL: Record<FeedbackStatus, string> = {
  pending: "待处理",
  processing: "处理中",
  replied: "已回复",
  closed: "已关闭",
};
const STATUS_COLOR: Record<FeedbackStatus, string> = {
  pending: "#e6a23c",
  processing: "#409eff",
  replied: "#67c23a",
  closed: "#909399",
};

function pad(n: number) {
  return String(n).padStart(2, "0");
}
function formatDate(d: Dayjs) {
  return `${d.year()}-${pad(d.month() + 1)}-${pad(d.date())}`;
}
function defaultRange(): [Dayjs, Dayjs] {
  const end = dayjs();
  const start = end.subtract(30, "day");
  return [start, end];
}

const FeedbackStats: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const activeTab =
    searchParams.get("tab") === "feedback" ? "feedback" : "rating";

  const [timeRange, setTimeRange] = useState<[Dayjs, Dayjs]>(defaultRange());
  const [ratingLoading, setRatingLoading] = useState(false);
  const [feedbackLoading, setFeedbackLoading] = useState(false);
  const [ratingStats, setRatingStats] = useState<RatingStatsVO | null>(null);
  const [feedbackStats, setFeedbackStats] = useState<FeedbackStatsVO | null>(
    null
  );

  const ratingDistRef = useRef<HTMLDivElement>(null);
  const feedbackTypeRef = useRef<HTMLDivElement>(null);
  const feedbackStatusRef = useRef<HTMLDivElement>(null);

  const ratingDistChart = useRef<echarts.ECharts | null>(null);
  const feedbackTypeChart = useRef<echarts.ECharts | null>(null);
  const feedbackStatusChart = useRef<echarts.ECharts | null>(null);

  const startTime = timeRange[0]?.format("YYYY-MM-DD");
  const endTime = timeRange[1]?.format("YYYY-MM-DD");

  const loadRatingStats = useCallback(async () => {
    setRatingLoading(true);
    try {
      const data = await FeedbackAPI.getRatingStats(startTime, endTime);
      setRatingStats(data);
    } finally {
      setRatingLoading(false);
    }
  }, [startTime, endTime]);

  const loadFeedbackStats = useCallback(async () => {
    setFeedbackLoading(true);
    try {
      const data = await FeedbackAPI.getFeedbackStats(startTime, endTime);
      setFeedbackStats(data);
    } finally {
      setFeedbackLoading(false);
    }
  }, [startTime, endTime]);

  useEffect(() => {
    loadRatingStats();
    loadFeedbackStats();
  }, [loadRatingStats, loadFeedbackStats]);

  const renderRatingDistChart = useCallback((data: RatingStatsVO) => {
    if (!ratingDistRef.current) return;
    if (ratingDistChart.current) {
      ratingDistChart.current.dispose();
    }
    ratingDistChart.current = echarts.init(ratingDistRef.current);
    ratingDistChart.current.setOption({
      tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
      legend: { bottom: 0 },
      series: [
        {
          type: "pie",
          radius: ["40%", "70%"],
          label: { formatter: "{b}: {c}" },
          data: Object.entries(data.ratingDistribution || {}).map(([k, v]) => ({
            name: `${k}星`,
            value: v,
            itemStyle: { color: RATING_COLOR_MAP[Number(k)] },
          })),
        },
      ],
    });
  }, []);

  const renderFeedbackCharts = useCallback((data: FeedbackStatsVO) => {
    if (feedbackTypeRef.current) {
      if (feedbackTypeChart.current) {
        feedbackTypeChart.current.dispose();
      }
      feedbackTypeChart.current = echarts.init(feedbackTypeRef.current);
      feedbackTypeChart.current.setOption({
        tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
        legend: { bottom: 0 },
        series: [
          {
            type: "pie",
            radius: ["40%", "70%"],
            label: { formatter: "{b}: {c}" },
            data: (Object.keys(TYPE_LABEL) as FeedbackType[]).map((t) => ({
              name: TYPE_LABEL[t],
              value: data.typeDistribution?.[t] || 0,
              itemStyle: { color: TYPE_COLOR[t] },
            })),
          },
        ],
      });
    }

    if (feedbackStatusRef.current) {
      if (feedbackStatusChart.current) {
        feedbackStatusChart.current.dispose();
      }
      feedbackStatusChart.current = echarts.init(feedbackStatusRef.current);
      const statuses = Object.keys(STATUS_LABEL) as FeedbackStatus[];
      feedbackStatusChart.current.setOption({
        tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
        legend: { bottom: 0 },
        grid: { left: "3%", right: "3%", bottom: "15%", containLabel: true },
        xAxis: {
          type: "category",
          data: statuses.map((s) => STATUS_LABEL[s]),
        },
        yAxis: { type: "value" },
        series: [
          {
            type: "bar",
            barWidth: "40%",
            data: statuses.map((s) => ({
              value: data.statusDistribution?.[s] || 0,
              itemStyle: { color: STATUS_COLOR[s] },
            })),
          },
        ],
      });
    }
  }, []);

  useEffect(() => {
    if (activeTab === "rating" && ratingStats) {
      renderRatingDistChart(ratingStats);
    } else if (activeTab === "feedback" && feedbackStats) {
      renderFeedbackCharts(feedbackStats);
    }
    return () => {
      if (activeTab === "rating") {
        ratingDistChart.current?.dispose();
        ratingDistChart.current = null;
      } else {
        feedbackTypeChart.current?.dispose();
        feedbackTypeChart.current = null;
        feedbackStatusChart.current?.dispose();
        feedbackStatusChart.current = null;
      }
    };
  }, [
    activeTab,
    ratingStats,
    feedbackStats,
    renderRatingDistChart,
    renderFeedbackCharts,
  ]);

  useEffect(() => {
    const handleResize = () => {
      ratingDistChart.current?.resize();
      feedbackTypeChart.current?.resize();
      feedbackStatusChart.current?.resize();
    };
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
      ratingDistChart.current?.dispose();
      feedbackTypeChart.current?.dispose();
      feedbackStatusChart.current?.dispose();
    };
  }, []);

  const handleTabChange = (key: string) => {
    setSearchParams({ tab: key });
  };

  const handleTimeChange = (values: [Dayjs, Dayjs] | null) => {
    if (!values || values.length !== 2) return;
    setTimeRange(values);
  };

  const ratingMetrics = useMemo(() => {
    const dist = ratingStats?.ratingDistribution || {};
    const total = ratingStats?.totalRatings || 0;
    const good = (dist[4] || 0) + (dist[5] || 0);
    const bad = (dist[1] || 0) + (dist[2] || 0);
    return {
      total,
      average: ratingStats?.averageRating || 0,
      positiveRate: total ? Math.round((good * 10000) / total) / 100 : 0,
      negativeRate: total ? Math.round((bad * 10000) / total) / 100 : 0,
    };
  }, [ratingStats]);

  const feedbackMetrics = useMemo(() => {
    const total = feedbackStats?.totalFeedback || 0;
    const pending = feedbackStats?.statusDistribution?.pending || 0;
    return {
      total,
      avgResponse: feedbackStats?.averageResponseTime ?? 0,
      avgClose: feedbackStats?.averageCloseTime ?? 0,
      pending,
    };
  }, [feedbackStats]);

  const positiveMax = useMemo(
    () =>
      Math.max(
        1,
        ...(ratingStats?.positiveTagRanking || []).map((t) => t.count)
      ),
    [ratingStats]
  );
  const negativeMax = useMemo(
    () =>
      Math.max(
        1,
        ...(ratingStats?.negativeTagRanking || []).map((t) => t.count)
      ),
    [ratingStats]
  );
  const keywordMax = useMemo(
    () =>
      Math.max(1, ...(feedbackStats?.topKeywords || []).map((k) => k.count)),
    [feedbackStats]
  );
  const keywordFontSize = (count: number) =>
    Math.round(14 + (count / keywordMax) * 10);

  const algorithmColumns: TableColumnsType<
    RatingStatsVO["algorithmStats"][number]
  > = [
    {
      title: "算法",
      dataIndex: "algorithmName",
      key: "algorithmName",
      minWidth: 160,
    },
    {
      title: "平均评分",
      dataIndex: "averageRating",
      key: "averageRating",
      width: 180,
      align: "center",
      render: (val: number) => <Rate disabled allowHalf value={val} />,
    },
    {
      title: "评价数",
      dataIndex: "totalRatings",
      key: "totalRatings",
      width: 100,
      align: "center",
    },
    {
      title: "差评率",
      dataIndex: "lowRatingRate",
      key: "lowRatingRate",
      minWidth: 220,
      render: (val: number) => (
        <Progress
          percent={val}
          strokeColor={val > 20 ? "#f5222d" : "#409eff"}
        />
      ),
    },
  ];

  const tagColumn = (max: number, color: string) =>
    ({
      title: "相对占比",
      key: "percent",
      minWidth: 180,
      render: (_: unknown, record: { count: number }) => (
        <Progress
          percent={Math.round((record.count * 100) / max)}
          strokeColor={color}
        />
      ),
    }) as TableColumnsType<{ tag: string; count: number }>[number];

  const tagColumns = (max: number, color: string) =>
    [
      { title: "标签", dataIndex: "tag", key: "tag", minWidth: 120 },
      {
        title: "次数",
        dataIndex: "count",
        key: "count",
        width: 80,
        align: "center",
      },
      tagColumn(max, color),
    ] as TableColumnsType<{ tag: string; count: number }>;

  const moduleColumns: TableColumnsType<{
    module: string;
    count: number;
  }> = [
    { title: "模块", dataIndex: "module", key: "module", minWidth: 160 },
    {
      title: "反馈数",
      dataIndex: "count",
      key: "count",
      width: 100,
      align: "center",
    },
    {
      title: "占比",
      key: "percent",
      minWidth: 240,
      render: (_: unknown, record: { count: number }) => (
        <Progress
          percent={
            feedbackMetrics.total
              ? Math.round((record.count * 100) / feedbackMetrics.total)
              : 0
          }
        />
      ),
    },
  ];

  return (
    <div className="feedback-stats-container">
      <Card className="filter-card" size="small">
        <span className="filter-label">时间范围：</span>
        <RangePicker
          value={timeRange}
          onChange={(values) =>
            handleTimeChange(values as [Dayjs, Dayjs] | null)
          }
          allowClear={false}
          style={{ width: 260 }}
        />
      </Card>

      <Tabs
        activeKey={activeTab}
        onChange={handleTabChange}
        items={[
          {
            key: "rating",
            label: (
              <span>
                <StarOutlined /> 评价统计
              </span>
            ),
            children: (
              <Spin spinning={ratingLoading}>
                <Row gutter={16} className="stat-cards">
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">总评价数</div>
                        <div className="stat-value">{ratingMetrics.total}</div>
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">平均评分</div>
                        <div className="stat-value">
                          {ratingMetrics.average.toFixed(2)}
                        </div>
                        <Rate
                          disabled
                          allowHalf
                          value={ratingMetrics.average}
                        />
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">好评率</div>
                        <div
                          className="stat-value"
                          style={{ color: "#52c41a" }}
                        >
                          {ratingMetrics.positiveRate}%
                        </div>
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">差评率</div>
                        <div
                          className="stat-value"
                          style={{ color: "#f5222d" }}
                        >
                          {ratingMetrics.negativeRate}%
                        </div>
                      </div>
                    </Card>
                  </Col>
                </Row>

                <Card
                  size="small"
                  className="section-card"
                  title={
                    <span className="card-title">
                      <BarChartOutlined /> 评分分布
                    </span>
                  }
                >
                  <div
                    ref={ratingDistRef}
                    style={{ width: "100%", height: 300 }}
                  />
                </Card>

                <Card
                  size="small"
                  className="section-card"
                  title={
                    <span className="card-title">
                      <BarChartOutlined /> 算法维度统计
                    </span>
                  }
                >
                  <Table
                    size="small"
                    columns={algorithmColumns}
                    dataSource={ratingStats?.algorithmStats || []}
                    rowKey={(record) => record.algorithmId}
                    pagination={false}
                    bordered
                  />
                </Card>

                <Row gutter={16} className="section-card">
                  <Col span={12}>
                    <Card size="small" title="正面标签排行">
                      <Table
                        size="small"
                        columns={tagColumns(positiveMax, "#52c41a")}
                        dataSource={ratingStats?.positiveTagRanking || []}
                        rowKey="tag"
                        pagination={false}
                        bordered
                      />
                    </Card>
                  </Col>
                  <Col span={12}>
                    <Card size="small" title="负面标签排行">
                      <Table
                        size="small"
                        columns={tagColumns(negativeMax, "#f5222d")}
                        dataSource={ratingStats?.negativeTagRanking || []}
                        rowKey="tag"
                        pagination={false}
                        bordered
                      />
                    </Card>
                  </Col>
                </Row>
              </Spin>
            ),
          },
          {
            key: "feedback",
            label: (
              <span>
                <MessageOutlined /> 反馈统计
              </span>
            ),
            children: (
              <Spin spinning={feedbackLoading}>
                <Row gutter={16} className="stat-cards">
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">总反馈数</div>
                        <div className="stat-value">
                          {feedbackMetrics.total}
                        </div>
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">平均响应时间</div>
                        <div className="stat-value">
                          {feedbackMetrics.avgResponse}
                          <span className="unit">分钟</span>
                        </div>
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">平均关闭时间</div>
                        <div className="stat-value">
                          {feedbackMetrics.avgClose}
                          <span className="unit">小时</span>
                        </div>
                      </div>
                    </Card>
                  </Col>
                  <Col span={6}>
                    <Card hoverable>
                      <div className="stat-card">
                        <div className="stat-label">待处理数</div>
                        <div
                          className="stat-value"
                          style={{ color: "#e6a23c" }}
                        >
                          {feedbackMetrics.pending}
                        </div>
                      </div>
                    </Card>
                  </Col>
                </Row>

                <Row gutter={16} className="section-card">
                  <Col span={12}>
                    <Card
                      size="small"
                      title={
                        <span className="card-title">
                          <BarChartOutlined /> 类型分布
                        </span>
                      }
                    >
                      <div
                        ref={feedbackTypeRef}
                        style={{ width: "100%", height: 300 }}
                      />
                    </Card>
                  </Col>
                  <Col span={12}>
                    <Card
                      size="small"
                      title={
                        <span className="card-title">
                          <BarChartOutlined /> 状态分布
                        </span>
                      }
                    >
                      <div
                        ref={feedbackStatusRef}
                        style={{ width: "100%", height: 300 }}
                      />
                    </Card>
                  </Col>
                </Row>

                <Card
                  size="small"
                  className="section-card"
                  title={
                    <span className="card-title">
                      <BarChartOutlined /> 模块分布
                    </span>
                  }
                >
                  <Table
                    size="small"
                    columns={moduleColumns}
                    dataSource={feedbackStats?.moduleDistribution || []}
                    rowKey="module"
                    pagination={false}
                    bordered
                  />
                </Card>

                <Card
                  size="small"
                  className="section-card"
                  title={
                    <span className="card-title">
                      <BarChartOutlined /> 高频关键词
                    </span>
                  }
                >
                  <div className="keyword-cloud">
                    {feedbackStats?.topKeywords?.length ? (
                      feedbackStats.topKeywords.map((kw) => (
                        <Tag
                          key={kw.keyword}
                          style={{
                            fontSize: keywordFontSize(kw.count),
                            margin: 6,
                          }}
                        >
                          {kw.keyword} ({kw.count})
                        </Tag>
                      ))
                    ) : (
                      <Empty description="暂无数据" />
                    )}
                  </div>
                </Card>
              </Spin>
            ),
          },
        ]}
      />
    </div>
  );
};

export default FeedbackStats;

// dehaze-front-vue/src/views/feedback/stats/index.vue
<template>
  <div class="app-container">
    <div class="search-container">
      <el-form :inline="true">
        <el-form-item label="时间范围">
          <el-date-picker
            v-model="timeRange"
            type="daterange"
            range-separator="至"
            start-placeholder="开始日期"
            end-placeholder="结束日期"
            value-format="YYYY-MM-DD"
            :shortcuts="shortcuts"
            style="width: 260px"
            @change="handleTimeChange"
          />
        </el-form-item>
        <el-form-item>
          <el-radio-group v-model="activeTab" @change="handleTabChange">
            <el-radio-button value="rating">
              <el-icon><Star /></el-icon><span class="tab-text">评价统计</span>
            </el-radio-button>
            <el-radio-button value="feedback">
              <el-icon><ChatLineRound /></el-icon
              ><span class="tab-text">反馈统计</span>
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-form>
    </div>

    <div v-if="activeTab === 'rating'" v-loading="ratingLoading">
      <el-row :gutter="16">
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">总评价数</div>
              <div class="stat-value">{{ totalRatings }}</div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">平均评分</div>
              <div class="stat-value">{{ averageRating.toFixed(2) }}</div>
              <el-rate :model-value="averageRating" disabled allow-half />
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">好评率</div>
              <div class="stat-value" style="color: #52c41a">
                {{ positiveRate }}%
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">差评率</div>
              <div class="stat-value" style="color: #f5222d">
                {{ negativeRate }}%
              </div>
            </div>
          </el-card>
        </el-col>
      </el-row>

      <el-card shadow="never" class="section-card">
        <template #header>
          <div class="card-title">
            <el-icon><DataAnalysis /></el-icon>评分分布
          </div>
        </template>
        <div id="ratingDistChart" style="width: 100%; height: 300px"></div>
      </el-card>

      <el-card shadow="never" class="section-card">
        <template #header>
          <div class="card-title">
            <el-icon><DataAnalysis /></el-icon>算法维度统计
          </div>
        </template>
        <el-table :data="ratingStats?.algorithmStats || []" border>
          <el-table-column label="算法" prop="algorithmName" min-width="160" />
          <el-table-column label="平均评分" width="180" align="center">
            <template #default="scope">
              <el-rate
                :model-value="scope.row.averageRating"
                disabled
                allow-half
              />
            </template>
          </el-table-column>
          <el-table-column
            label="评价数"
            prop="totalRatings"
            width="100"
            align="center"
          />
          <el-table-column label="差评率" min-width="220">
            <template #default="scope">
              <el-progress
                :percentage="scope.row.lowRatingRate"
                :color="scope.row.lowRatingRate > 20 ? '#f5222d' : '#409eff'"
              />
            </template>
          </el-table-column>
        </el-table>
      </el-card>

      <el-row :gutter="16" class="section-card">
        <el-col :span="12">
          <el-card shadow="never">
            <template #header>
              <div class="card-title">正面标签排行</div>
            </template>
            <el-table :data="ratingStats?.positiveTagRanking || []" border>
              <el-table-column label="标签" prop="tag" min-width="120" />
              <el-table-column
                label="次数"
                prop="count"
                width="80"
                align="center"
              />
              <el-table-column label="相对占比" min-width="180">
                <template #default="scope">
                  <el-progress
                    :percentage="
                      Math.round((scope.row.count * 100) / positiveMax)
                    "
                    color="#52c41a"
                  />
                </template>
              </el-table-column>
            </el-table>
          </el-card>
        </el-col>
        <el-col :span="12">
          <el-card shadow="never">
            <template #header>
              <div class="card-title">负面标签排行</div>
            </template>
            <el-table :data="ratingStats?.negativeTagRanking || []" border>
              <el-table-column label="标签" prop="tag" min-width="120" />
              <el-table-column
                label="次数"
                prop="count"
                width="80"
                align="center"
              />
              <el-table-column label="相对占比" min-width="180">
                <template #default="scope">
                  <el-progress
                    :percentage="
                      Math.round((scope.row.count * 100) / negativeMax)
                    "
                    color="#f5222d"
                  />
                </template>
              </el-table-column>
            </el-table>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <div v-if="activeTab === 'feedback'" v-loading="feedbackLoading">
      <el-row :gutter="16">
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">总反馈数</div>
              <div class="stat-value">{{ totalFeedback }}</div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">平均响应时间</div>
              <div class="stat-value">
                {{ feedbackStats?.averageResponseTime ?? 0
                }}<span class="unit">分钟</span>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">平均关闭时间</div>
              <div class="stat-value">
                {{ feedbackStats?.averageCloseTime ?? 0
                }}<span class="unit">小时</span>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <div class="stat-card">
              <div class="stat-label">待处理数</div>
              <div class="stat-value" style="color: #e6a23c">
                {{ pendingCount }}
              </div>
            </div>
          </el-card>
        </el-col>
      </el-row>

      <el-row :gutter="16" class="section-card">
        <el-col :span="12">
          <el-card shadow="never">
            <template #header>
              <div class="card-title">
                <el-icon><DataAnalysis /></el-icon>类型分布
              </div>
            </template>
            <div
              id="feedbackTypeChart"
              style="width: 100%; height: 300px"
            ></div>
          </el-card>
        </el-col>
        <el-col :span="12">
          <el-card shadow="never">
            <template #header>
              <div class="card-title">
                <el-icon><DataAnalysis /></el-icon>状态分布
              </div>
            </template>
            <div
              id="feedbackStatusChart"
              style="width: 100%; height: 300px"
            ></div>
          </el-card>
        </el-col>
      </el-row>

      <el-card shadow="never" class="section-card">
        <template #header>
          <div class="card-title">
            <el-icon><DataAnalysis /></el-icon>模块分布
          </div>
        </template>
        <el-table :data="feedbackStats?.moduleDistribution || []" border>
          <el-table-column label="模块" prop="module" min-width="160" />
          <el-table-column
            label="反馈数"
            prop="count"
            width="100"
            align="center"
          />
          <el-table-column label="占比" min-width="240">
            <template #default="scope">
              <el-progress
                :percentage="
                  totalFeedback
                    ? Math.round((scope.row.count * 100) / totalFeedback)
                    : 0
                "
              />
            </template>
          </el-table-column>
        </el-table>
      </el-card>

      <el-card shadow="never" class="section-card">
        <template #header>
          <div class="card-title">
            <el-icon><DataAnalysis /></el-icon>高频关键词
          </div>
        </template>
        <div class="keyword-cloud">
          <el-tag
            v-for="kw in feedbackStats?.topKeywords || []"
            :key="kw.keyword"
            :style="{
              fontSize: keywordFontSize(kw.count) + 'px',
              margin: '6px',
            }"
            effect="plain"
          >
            {{ kw.keyword }} ({{ kw.count }})
          </el-tag>
          <span
            v-if="
              !feedbackStats?.topKeywords ||
              feedbackStats.topKeywords.length === 0
            "
            style="color: #909399"
            >暂无数据</span
          >
        </div>
      </el-card>
    </div>
  </div>
</template>

<script lang="ts" setup>
import * as echarts from "echarts";
import { Star, ChatLineRound, DataAnalysis } from "@element-plus/icons-vue";
import {
  FeedbackAPI,
  RatingStatsVO,
  FeedbackStatsVO,
  FeedbackType,
  FeedbackStatus,
} from "dehaze-sdk-js";

defineOptions({ name: "FeedbackStats" });

const route = useRoute();

const activeTab = ref<"rating" | "feedback">(
  route.query.tab === "feedback" ? "feedback" : "rating"
);

const ratingLoading = ref(false);
const feedbackLoading = ref(false);
const ratingStats = ref<RatingStatsVO | null>(null);
const feedbackStats = ref<FeedbackStatsVO | null>(null);

const ratingDistChart = ref<echarts.ECharts | null>(null);
const feedbackTypeChart = ref<echarts.ECharts | null>(null);
const feedbackStatusChart = ref<echarts.ECharts | null>(null);

function pad(n: number) {
  return String(n).padStart(2, "0");
}
function formatDate(d: Date) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function defaultRange(): [string, string] {
  const end = new Date();
  const start = new Date();
  start.setTime(start.getTime() - 30 * 24 * 3600 * 1000);
  return [formatDate(start), formatDate(end)];
}
const timeRange = ref<[string, string]>(defaultRange());

const shortcuts = [
  {
    text: "近7天",
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 7 * 24 * 3600 * 1000);
      return [start, end];
    },
  },
  {
    text: "近30天",
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 30 * 24 * 3600 * 1000);
      return [start, end];
    },
  },
  {
    text: "近90天",
    value: () => {
      const end = new Date();
      const start = new Date();
      start.setTime(start.getTime() - 90 * 24 * 3600 * 1000);
      return [start, end];
    },
  },
];

const ratingDistribution = computed(
  () => ratingStats.value?.ratingDistribution || {}
);
const totalRatings = computed(() => ratingStats.value?.totalRatings || 0);
const averageRating = computed(() => ratingStats.value?.averageRating || 0);
const positiveRate = computed(() => {
  const d = ratingDistribution.value;
  const good = (d[4] || 0) + (d[5] || 0);
  return totalRatings.value
    ? Math.round((good * 10000) / totalRatings.value) / 100
    : 0;
});
const negativeRate = computed(() => {
  const d = ratingDistribution.value;
  const bad = (d[1] || 0) + (d[2] || 0);
  return totalRatings.value
    ? Math.round((bad * 10000) / totalRatings.value) / 100
    : 0;
});
const positiveMax = computed(() =>
  Math.max(
    1,
    ...(ratingStats.value?.positiveTagRanking || []).map((t) => t.count)
  )
);
const negativeMax = computed(() =>
  Math.max(
    1,
    ...(ratingStats.value?.negativeTagRanking || []).map((t) => t.count)
  )
);

const totalFeedback = computed(() => feedbackStats.value?.totalFeedback || 0);
const pendingCount = computed(
  () => feedbackStats.value?.statusDistribution?.pending || 0
);
const keywordMax = computed(() =>
  Math.max(1, ...(feedbackStats.value?.topKeywords || []).map((k) => k.count))
);
function keywordFontSize(count: number) {
  return Math.round(14 + (count / keywordMax.value) * 10);
}

const typeLabelMap: Record<FeedbackType, string> = {
  suggestion: "功能建议",
  bug: "问题报告",
  experience: "体验反馈",
  complaint: "投诉",
};
const typeColorMap: Record<FeedbackType, string> = {
  suggestion: "#409eff",
  experience: "#67c23a",
  complaint: "#e6a23c",
  bug: "#f56c6c",
};
const statusLabelMap: Record<FeedbackStatus, string> = {
  pending: "待处理",
  processing: "处理中",
  replied: "已回复",
  closed: "已关闭",
};
const statusColorMap: Record<FeedbackStatus, string> = {
  pending: "#e6a23c",
  processing: "#409eff",
  replied: "#67c23a",
  closed: "#909399",
};

function initRatingCharts(data: RatingStatsVO) {
  const distEl = document.getElementById("ratingDistChart");
  if (!distEl) return;
  if (ratingDistChart.value) {
    ratingDistChart.value.dispose();
    ratingDistChart.value = null;
  }
  ratingDistChart.value = markRaw(echarts.init(distEl));
  const colorMap: Record<number, string> = {
    1: "#f5222d",
    2: "#fa8c16",
    3: "#faad14",
    4: "#409eff",
    5: "#52c41a",
  };
  ratingDistChart.value.setOption({
    tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
    legend: { bottom: 0 },
    series: [
      {
        type: "pie",
        radius: ["40%", "70%"],
        label: { formatter: "{b}: {c}" },
        data: Object.entries(data.ratingDistribution).map(([k, v]) => ({
          name: k + "星",
          value: v,
          itemStyle: { color: colorMap[Number(k)] },
        })),
      },
    ],
  });
}

function initFeedbackCharts(data: FeedbackStatsVO) {
  const typeEl = document.getElementById("feedbackTypeChart");
  if (typeEl) {
    if (feedbackTypeChart.value) {
      feedbackTypeChart.value.dispose();
      feedbackTypeChart.value = null;
    }
    feedbackTypeChart.value = markRaw(echarts.init(typeEl));
    feedbackTypeChart.value.setOption({
      tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
      legend: { bottom: 0 },
      series: [
        {
          type: "pie",
          radius: ["40%", "70%"],
          label: { formatter: "{b}: {c}" },
          data: (Object.keys(typeLabelMap) as FeedbackType[]).map((t) => ({
            name: typeLabelMap[t],
            value: data.typeDistribution?.[t] || 0,
            itemStyle: { color: typeColorMap[t] },
          })),
        },
      ],
    });
  }

  const statusEl = document.getElementById("feedbackStatusChart");
  if (statusEl) {
    if (feedbackStatusChart.value) {
      feedbackStatusChart.value.dispose();
      feedbackStatusChart.value = null;
    }
    feedbackStatusChart.value = markRaw(echarts.init(statusEl));
    const statuses = Object.keys(statusLabelMap) as FeedbackStatus[];
    feedbackStatusChart.value.setOption({
      tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
      legend: { bottom: 0 },
      grid: { left: "3%", right: "3%", bottom: "15%", containLabel: true },
      xAxis: {
        type: "category",
        data: statuses.map((s) => statusLabelMap[s]),
      },
      yAxis: { type: "value" },
      series: [
        {
          type: "bar",
          barWidth: "40%",
          data: statuses.map((s) => ({
            value: data.statusDistribution?.[s] || 0,
            itemStyle: { color: statusColorMap[s] },
          })),
        },
      ],
    });
  }
}

function disposeCharts() {
  [ratingDistChart, feedbackTypeChart, feedbackStatusChart].forEach((c) => {
    if (c.value) {
      c.value.dispose();
      c.value = null;
    }
  });
}

function handleResize() {
  [ratingDistChart, feedbackTypeChart, feedbackStatusChart].forEach((c) =>
    c.value?.resize()
  );
}

function loadRatingStats() {
  ratingLoading.value = true;
  FeedbackAPI.getRatingStats(timeRange.value[0], timeRange.value[1])
    .then((data) => {
      ratingStats.value = data;
      if (activeTab.value === "rating") {
        nextTick(() => initRatingCharts(data));
      }
    })
    .finally(() => {
      ratingLoading.value = false;
    });
}

function loadFeedbackStats() {
  feedbackLoading.value = true;
  FeedbackAPI.getFeedbackStats(timeRange.value[0], timeRange.value[1])
    .then((data) => {
      feedbackStats.value = data;
      if (activeTab.value === "feedback") {
        nextTick(() => initFeedbackCharts(data));
      }
    })
    .finally(() => {
      feedbackLoading.value = false;
    });
}

function handleTabChange() {
  disposeCharts();
  nextTick(() => {
    if (activeTab.value === "rating" && ratingStats.value) {
      initRatingCharts(ratingStats.value);
    } else if (activeTab.value === "feedback" && feedbackStats.value) {
      initFeedbackCharts(feedbackStats.value);
    }
  });
}

function handleTimeChange() {
  if (!timeRange.value || timeRange.value.length !== 2) {
    ElMessage.warning("请选择时间范围");
    return;
  }
  if (activeTab.value === "rating") {
    loadRatingStats();
  } else {
    loadFeedbackStats();
  }
}

onMounted(() => {
  loadRatingStats();
  loadFeedbackStats();
  window.addEventListener("resize", handleResize);
});

onActivated(() => {
  handleResize();
});

onBeforeUnmount(() => {
  window.removeEventListener("resize", handleResize);
  disposeCharts();
});
</script>

<style lang="scss" scoped>
.search-container {
  margin-bottom: 16px;
}

.tab-text {
  margin-left: 4px;
}

.section-card {
  margin-top: 16px;
}

.stat-card {
  text-align: center;

  .stat-label {
    margin-bottom: 8px;
    font-size: 14px;
    color: #909399;
  }

  .stat-value {
    font-size: 28px;
    font-weight: 600;
    color: #303133;

    .unit {
      margin-left: 4px;
      font-size: 14px;
      font-weight: normal;
      color: #909399;
    }
  }
}

.card-title {
  display: flex;
  align-items: center;
  font-weight: 600;

  .el-icon {
    margin-right: 6px;
  }
}

.keyword-cloud {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  min-height: 60px;
}
</style>
