// dehaze-uniapp/src/pages/profile/index.vue
<template>
  <PageLayout level="L1" title="我的" class="page">
    <view class="main-content">
      <!-- 用户卡 -->
      <view class="user-card">
        <view class="user-info">
          <image
            v-if="auth.userInfo?.avatar"
            :src="auth.userInfo.avatar"
            class="avatar-img"
          />
          <view v-else class="avatar-placeholder">
            <text class="avatar-text">{{ initial }}</text>
          </view>
          <view class="user-text">
            <view class="user-name-row">
              <text class="nickname">{{ auth.nickname || auth.username }}</text>
              <view v-if="auth.roles.length > 0" class="role-tags">
                <text v-for="role in auth.roles" :key="role" class="role-tag">{{
                  formatRole(role)
                }}</text>
              </view>
            </view>
            <text class="username">@{{ auth.username }}</text>
          </view>
        </view>
      </view>

      <!-- VIP 横幅 -->
      <view class="vip-banner" @click="handleMember">
        <view class="vip-info">
          <text class="vip-title" v-if="isVip">
            {{ memberProfile.levelName }} · 成长值
            {{ memberProfile.growthValue }}
          </text>
          <text class="vip-title" v-else>开通 VIP 畅享更多次数</text>
          <text class="vip-subtitle" v-if="isVip">
            本月已用 {{ memberProfile.monthlyUsed }} 次
          </text>
          <text class="vip-subtitle" v-else>解锁全部高级功能</text>
        </view>
        <view class="vip-action">
          <text>{{ isVip ? "查看权益" : "去开通" }}</text>
          <SvgIcon name="arrow-right" size="14" color="#fff" />
        </view>
      </view>

      <!-- 数据统计 -->
      <view class="stats-row">
        <view class="stat-item" @click="handleQuota">
          <text class="stat-value">{{ quota.remaining }}</text>
          <text class="stat-label">剩余额度</text>
        </view>
        <view class="stat-item" @click="handleTaskHistory">
          <text class="stat-value">{{ quota.used }}</text>
          <text class="stat-label">本月处理</text>
        </view>
        <view class="stat-item" @click="handleFavorite">
          <text class="stat-value">{{ favCount }}</text>
          <text class="stat-label">我的收藏</text>
        </view>
      </view>

      <!-- 分组入口：个人数据 -->
      <view class="menu-group">
        <text class="group-title">个人数据</text>
        <view class="menu-card">
          <MenuItem
            icon="folder"
            icon-color="#10b981"
            label="我的文件"
            @click="goPersonal('files')"
          />
          <MenuItem
            icon="database"
            icon-color="#6366f1"
            label="我的数据集"
            @click="goPage('/pages/dataset/index')"
          />
          <MenuItem
            icon="clock"
            icon-color="#6366f1"
            label="处理历史"
            @click="goPage('/pages/task-history/index')"
          />
          <MenuItem
            icon="star"
            icon-color="#f59e0b"
            label="我的收藏"
            @click="goPersonal('favorites')"
          />
        </view>
      </view>

      <!-- 分组入口：商业服务 -->
      <view class="menu-group">
        <text class="group-title">商业服务</text>
        <view class="menu-card">
          <MenuItem
            icon="man-delete"
            icon-color="#3b82f6"
            label="我的会员"
            @click="goPersonal('member')"
          />
          <MenuItem
            icon="rmb-circle"
            icon-color="#f59e0b"
            label="我的套餐"
            @click="goPersonal('package')"
          />
          <MenuItem
            icon="order"
            icon-color="#10b981"
            label="我的订单"
            @click="goPersonal('orders')"
          />
          <MenuItem
            icon="calendar"
            icon-color="#8b5cf6"
            label="我的额度"
            @click="goPersonal('quota')"
          />
          <MenuItem
            icon="edit-pen"
            icon-color="#ec4899"
            label="反馈评价"
            @click="goPersonal('feedback')"
          />
        </view>
      </view>

      <!-- 分组入口：其他 -->
      <view class="menu-group">
        <text class="group-title">其他</text>
        <view class="menu-card">
          <MenuItem
            icon="setting"
            icon-color="#6b7280"
            label="系统设置"
            @click="goPersonal('settings')"
          />
          <MenuItem
            icon="question-circle"
            icon-color="#3b82f6"
            label="帮助中心"
            @click="goPersonal('help')"
          />
          <MenuItem
            icon="info-circle"
            icon-color="#9ca3af"
            label="关于我们"
            @click="goPersonal('about')"
          />
          <MenuItem
            icon="bell"
            icon-color="#f59e0b"
            label="消息设置"
            @click="goPage('/pages/notify/index')"
          />
        </view>
      </view>

      <!-- 管理入口（权限过滤） -->
      <view v-if="hasAnyAdminPerm" class="menu-group">
        <text class="group-title">管理入口</text>
        <view class="menu-card">
          <template v-if="hasPermGroup('algorithm') || hasPermGroup('dataset')">
            <text class="sub-group-title">算法与数据</text>
            <MenuItem
              v-if="auth.hasPerm('sys:algorithm:*')"
              icon="cpu"
              icon-color="#3b82f6"
              label="算法管理"
              @click="goPage('/pages/system/algorithm/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dataset:*')"
              icon="database"
              icon-color="#6366f1"
              label="数据集管理"
              @click="goPage('/pages/system/dataset/index')"
            />
          </template>

          <template v-if="hasPermGroup('sys')">
            <text class="sub-group-title">系统管理</text>
            <MenuItem
              v-if="auth.hasPerm('sys:user:*')"
              icon="account"
              icon-color="#10b981"
              label="用户管理"
              @click="goPage('/pages/system/user/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:role:*')"
              icon="grid"
              icon-color="#f59e0b"
              label="角色管理"
              @click="goPage('/pages/system/role/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:menu:*')"
              icon="list-dot"
              icon-color="#8b5cf6"
              label="菜单管理"
              @click="goPage('/pages/system/menu/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dept:*')"
              icon="home"
              icon-color="#ec4899"
              label="部门管理"
              @click="goPage('/pages/system/dept/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:dict:*')"
              icon="bookmark"
              icon-color="#14b8a6"
              label="字典管理"
              @click="goPage('/pages/system/dict/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:task:*')"
              icon="play-circle"
              icon-color="#f97316"
              label="任务管理"
              @click="goPage('/pages/system/task/index')"
            />
          </template>

          <template v-if="hasPermGroup('biz')">
            <text class="sub-group-title">运营管理</text>
            <MenuItem
              v-if="auth.hasPerm('sys:member:*')"
              icon="man-delete"
              icon-color="#3b82f6"
              label="会员管理"
              @click="goPage('/pages/system/member/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:package:*')"
              icon="rmb-circle"
              icon-color="#f59e0b"
              label="套餐管理"
              @click="goPage('/pages/system/package/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:order:*')"
              icon="order"
              icon-color="#10b981"
              label="订单管理"
              @click="goPage('/pages/system/order/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:feedback:*')"
              icon="edit-pen"
              icon-color="#ec4899"
              label="反馈评价管理"
              @click="goPage('/pages/system/feedback/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:recommendation:*')"
              icon="thumb-up"
              icon-color="#8b5cf6"
              label="推荐管理"
              @click="goPage('/pages/system/recommend/index')"
            />
            <MenuItem
              v-if="auth.hasPerm('sys:notify:*')"
              icon="bell"
              icon-color="#f97316"
              label="消息管理"
              @click="goPage('/pages/system/message/index')"
            />
          </template>
        </view>
      </view>

      <!-- 退出登录 -->
      <view class="logout-area">
        <view class="logout-btn" @click="handleLogout">
          <SvgIcon name="close-circle" size="22" color="#ef4444" />
          <text class="logout-text">退出登录</text>
        </view>
      </view>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import PageLayout from "@/layout/index.vue";
import MenuItem from "./components/MenuItem.vue";
import { useAuthStore } from "@/store/auth";
import { LOGIN_PATH } from "@/routers/guard";
import { MemberAPI, ModelAPI, FavoriteAPI } from "dehaze-sdk-js";

const auth = useAuthStore();

const initial = computed(() =>
  (auth.nickname || auth.username || "U").charAt(0).toUpperCase()
);

// VIP/会员信息
const memberProfile = ref({
  levelCode: "level_0",
  levelName: "",
  growthValue: 0,
  monthlyUsed: 0,
});

const isVip = computed(
  () =>
    memberProfile.value.levelCode !== "level_0" &&
    memberProfile.value.levelCode !== "level_1"
);

// 配额
const quota = ref({ remaining: 0, used: 0, total: 0 });

// 收藏数
const favCount = ref(0);

onMounted(async () => {
  try {
    const profile = await MemberAPI.getProfile();
    memberProfile.value = profile;
  } catch {
    // 非会员或无接口
  }

  try {
    const q = await ModelAPI.getQuota();
    quota.value = q;
  } catch {
    // 无数据
  }

  try {
    const c = await FavoriteAPI.getCount();
    const total = c.reduce((sum, item) => sum + item.count, 0);
    favCount.value = total;
  } catch {
    // 无数据
  }
});

function formatRole(role: string): string {
  return role.replace("ROLE_", "");
}

function goPage(url: string) {
  uni.navigateTo({ url });
}

function goPersonal(page: string) {
  uni.navigateTo({ url: `/pages/personal/${page}/index` });
}

function handleMember() {
  uni.navigateTo({ url: "/pages/personal/member/index" });
}

function handleQuota() {
  uni.navigateTo({ url: "/pages/personal/quota/index" });
}

function handleTaskHistory() {
  uni.navigateTo({ url: "/pages/task-history/index" });
}

function handleFavorite() {
  uni.navigateTo({ url: "/pages/personal/favorites/index" });
}

// 管理权限分组判断
const hasAnyAdminPerm = computed(() => {
  const adminPerms = [
    "sys:algorithm:*",
    "sys:dataset:*",
    "sys:user:*",
    "sys:role:*",
    "sys:menu:*",
    "sys:dept:*",
    "sys:dict:*",
    "sys:task:*",
    "sys:member:*",
    "sys:package:*",
    "sys:order:*",
    "sys:feedback:*",
    "sys:recommendation:*",
    "sys:notify:*",
  ];
  return adminPerms.some((p) => auth.hasPerm(p));
});

function hasPermGroup(group: string) {
  switch (group) {
    case "algorithm":
      return auth.hasPerm("sys:algorithm:*") || auth.hasPerm("sys:dataset:*");
    case "sys":
      return [
        "sys:user:*",
        "sys:role:*",
        "sys:menu:*",
        "sys:dept:*",
        "sys:dict:*",
        "sys:task:*",
      ].some((p) => auth.hasPerm(p));
    case "biz":
      return [
        "sys:member:*",
        "sys:package:*",
        "sys:order:*",
        "sys:feedback:*",
        "sys:recommendation:*",
        "sys:notify:*",
      ].some((p) => auth.hasPerm(p));
    default:
      return false;
  }
}

async function handleLogout() {
  uni.showModal({
    title: "确认退出",
    content: "退出登录后需要重新登录",
    confirmColor: "#ef4444",
    success: async (res) => {
      if (res.confirm) {
        try {
          await auth.logout();
          uni.showToast({ title: "已退出", icon: "success" });
          setTimeout(() => uni.reLaunch({ url: LOGIN_PATH }), 800);
        } catch {
          uni.reLaunch({ url: LOGIN_PATH });
        }
      }
    },
  });
}
</script>

<style lang="scss" scoped>
.page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}
.main-content {
  padding: $spacing-md;
  padding-bottom: calc(100rpx + constant(safe-area-inset-bottom));
  padding-bottom: calc(100rpx + env(safe-area-inset-bottom));
}

// 用户卡
.user-card {
  background: #fff;
  border-radius: $radius-xl;
  padding: $spacing-lg;
  margin-bottom: $spacing-md;
  box-shadow: $shadow-sm;
}
.user-info {
  display: flex;
  align-items: center;
  gap: 24rpx;
}
.avatar-img {
  width: 112rpx;
  height: 112rpx;
  border-radius: 50%;
  flex-shrink: 0;
}
.avatar-placeholder {
  width: 112rpx;
  height: 112rpx;
  border-radius: 50%;
  background: $color-bg-secondary;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.avatar-text {
  font-size: $font-xl;
  font-weight: 700;
  color: $color-text-secondary;
}
.user-text {
  flex: 1;
  min-width: 0;
}
.user-name-row {
  display: flex;
  align-items: center;
  gap: 12rpx;
  flex-wrap: wrap;
}
.nickname {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
}
.username {
  display: block;
  font-size: $font-sm;
  color: $color-text-placeholder;
  margin-top: 4rpx;
}
.role-tags {
  display: flex;
  gap: 8rpx;
  flex-wrap: wrap;
}
.role-tag {
  font-size: 20rpx;
  color: $color-secondary;
  background: #e0e7ff;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
  font-weight: 500;
}

// VIP 横幅
.vip-banner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: $gradient-primary;
  border-radius: $radius-lg;
  padding: 28rpx;
  margin-bottom: $spacing-md;
}
.vip-info {
  flex: 1;
}
.vip-title {
  font-size: $font-md;
  font-weight: 600;
  color: #fff;
  display: block;
}
.vip-subtitle {
  font-size: $font-xs;
  color: rgba(255, 255, 255, 0.8);
  margin-top: 4rpx;
  display: block;
}
.vip-action {
  display: flex;
  align-items: center;
  gap: 4rpx;
  background: rgba(255, 255, 255, 0.2);
  padding: 12rpx 24rpx;
  border-radius: 12rpx;
  font-size: $font-sm;
  color: #fff;
  flex-shrink: 0;
}

// 统计
.stats-row {
  display: flex;
  background: #fff;
  border-radius: $radius-xl;
  margin-bottom: $spacing-md;
  box-shadow: $shadow-sm;
}
.stat-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 28rpx 16rpx;
  &:active {
    background: #f9fafb;
  }
  & + & {
    border-left: 1rpx solid $color-border-light;
  }
}
.stat-value {
  font-size: $font-lg;
  font-weight: 700;
  color: $color-text-primary;
}
.stat-label {
  font-size: $font-xs;
  color: $color-text-placeholder;
  margin-top: 4rpx;
}

// 菜单分组
.menu-group {
  margin-bottom: $spacing-md;
}
.group-title {
  display: block;
  font-size: $font-xs;
  font-weight: 500;
  color: $color-text-placeholder;
  text-transform: uppercase;
  padding: 0 4rpx 12rpx;
}
.menu-card {
  background: #fff;
  border-radius: $radius-xl;
  overflow: hidden;
  box-shadow: $shadow-sm;
}
.sub-group-title {
  display: block;
  font-size: $font-xs;
  color: $color-text-placeholder;
  padding: 20rpx 28rpx 8rpx;
}

// 退出
.logout-area {
  margin-top: 48rpx;
  padding: $spacing-md 0;
  display: flex;
  justify-content: center;
}
.logout-btn {
  display: flex;
  align-items: center;
  gap: 12rpx;
  padding: 20rpx 48rpx;
  background: #fff;
  border-radius: 16rpx;
  box-shadow: $shadow-sm;
  &:active {
    background: #f9fafb;
  }
}
.logout-text {
  font-size: $font-md;
  color: $color-danger;
}
</style>

// dehaze-taro/src/pages/profile/index.tsx
import React, { useState, useEffect, useCallback, useMemo } from "react";
import { View, Text, ScrollView, Image } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { Tag } from "@taroify/core";
import { MemberAPI, ModelAPI, FavoriteAPI, TaskAPI } from "dehaze-sdk-js";
import type { MemberProfileVO } from "dehaze-sdk-js";
import { confirmDialog } from "@/utils/dialog";
import { useAuth } from "@/hooks/useAuth";
import { usePermission } from "@/hooks/usePermission";
import { tabBarItems } from "@/config/menu";
import PageLayout from "@/layout";
import { getErrorMessage } from "@/utils/error";
import "./index.less";

// ==================== 类型定义 ====================

interface StatItem {
  label: string;
  value: string | number;
  route?: string;
}

interface EntryItem {
  icon: string;
  title: string;
  route: string;
  permission?: string;
}

interface EntryGroup {
  title: string;
  entries: EntryItem[];
}

// ==================== 入口分组配置 ====================

const PERSONAL_DATA_ENTRIES: EntryItem[] = [
  { icon: "📄", title: "我的文件", route: "/pages/personal/files/index" },
  { icon: "📊", title: "我的数据集", route: "/pages/dataset/index" },
  { icon: "⏱️", title: "处理历史", route: "/pages/task/index" },
  { icon: "⭐", title: "我的收藏", route: "/pages/favorite/index" },
];

const BUSINESS_ENTRIES: EntryItem[] = [
  { icon: "👑", title: "我的会员", route: "/pages/personal/member/index" },
  { icon: "📦", title: "我的套餐", route: "/pages/personal/package/index" },
  { icon: "🛒", title: "我的订单", route: "/pages/personal/orders/index" },
  { icon: "💰", title: "我的额度", route: "/pages/personal/quota/index" },
  { icon: "💬", title: "反馈评价", route: "/pages/personal/feedback/index" },
];

const OTHER_ENTRIES: EntryItem[] = [
  { icon: "⚙️", title: "系统设置", route: "/pages/personal/settings/index" },
  { icon: "❓", title: "帮助中心", route: "/pages/personal/help/index" },
  { icon: "ℹ️", title: "关于我们", route: "/pages/personal/about/index" },
  { icon: "🔔", title: "消息设置", route: "/pages/notify/index" },
];

// 管理入口分组（仅管理员/有权限用户可见，按 dev-admin 规划）
const ADMIN_GROUPS: EntryGroup[] = [
  {
    title: "工作台",
    entries: [
      {
        icon: "📊",
        title: "工作台",
        route: "/pages/dashboard/index",
        permission: "sys:user:*",
      },
    ],
  },
  {
    title: "用户与权限",
    entries: [
      {
        icon: "👥",
        title: "用户管理",
        route: "/pages/system/user/index",
        permission: "sys:user:*",
      },
      {
        icon: "🛡️",
        title: "角色管理",
        route: "/pages/system/role/index",
        permission: "sys:role:*",
      },
      {
        icon: "📑",
        title: "菜单管理",
        route: "/pages/system/menu/index",
        permission: "sys:menu:*",
      },
      {
        icon: "🏢",
        title: "部门管理",
        route: "/pages/system/dept/index",
        permission: "sys:dept:*",
      },
      {
        icon: "📚",
        title: "字典管理",
        route: "/pages/system/dict/index",
        permission: "sys:dict:*",
      },
    ],
  },
  {
    title: "算法与数据",
    entries: [
      {
        icon: "🧠",
        title: "算法管理",
        route: "/pages/system/algorithm/index",
        permission: "sys:algorithm:*",
      },
      {
        icon: "📊",
        title: "数据集管理",
        route: "/pages/system/dataset/index",
        permission: "sys:dataset:*",
      },
      {
        icon: "🎯",
        title: "推荐管理",
        route: "/pages/system/recommend/index",
        permission: "sys:recommendation:*",
      },
    ],
  },
  {
    title: "业务管理",
    entries: [
      {
        icon: "👑",
        title: "会员管理",
        route: "/pages/system/member/index",
        permission: "sys:member:*",
      },
      {
        icon: "📦",
        title: "套餐管理",
        route: "/pages/system/package/index",
        permission: "sys:package:*",
      },
      {
        icon: "🛒",
        title: "订单管理",
        route: "/pages/system/order/index",
        permission: "sys:order:*",
      },
    ],
  },
  {
    title: "运营管理",
    entries: [
      {
        icon: "⏱️",
        title: "任务管理",
        route: "/pages/system/task/index",
        permission: "sys:task:*",
      },
      {
        icon: "💬",
        title: "反馈评价管理",
        route: "/pages/system/feedback/index",
        permission: "sys:feedback:*",
      },
      {
        icon: "🔔",
        title: "消息管理",
        route: "/pages/system/message/index",
        permission: "sys:message:*",
      },
    ],
  },
];

// ==================== 页面组件 ====================

const ProfilePage: React.FC = () => {
  const { user, roles, logout } = useAuth();
  const { hasPermission } = usePermission();

  // 会员信息
  const [member, setMember] = useState<MemberProfileVO | null>(null);
  // 数据统计
  const [quotaCount, setQuotaCount] = useState<number | null>(null);
  const [favoriteCount, setFavoriteCount] = useState<number | null>(null);
  const [taskTotal, setTaskTotal] = useState<number | null>(null);

  // 加载会员信息
  const loadMember = useCallback(async () => {
    try {
      const profile = await MemberAPI.getProfile();
      setMember(profile);
    } catch {
      // 非会员静默处理
    }
  }, []);

  // 加载数据统计
  const loadStats = useCallback(async () => {
    try {
      const quota = await ModelAPI.getQuota();
      setQuotaCount(quota.remaining ?? quota.total ?? null);
    } catch {
      setQuotaCount(null);
    }
    try {
      const fav = await FavoriteAPI.getCount();
      if (fav && fav.length > 0) {
        const total = fav.reduce((sum, item) => sum + (item.count || 0), 0);
        setFavoriteCount(total);
      }
    } catch {
      setFavoriteCount(null);
    }
    try {
      const tasks = await TaskAPI.getPage({ pageNum: 1, pageSize: 1 });
      setTaskTotal(tasks.total ?? null);
    } catch {
      setTaskTotal(null);
    }
  }, []);

  useEffect(() => {
    loadMember();
    loadStats();
  }, [loadMember, loadStats]);

  // 数据统计项
  const stats: StatItem[] = useMemo(() => {
    const items: StatItem[] = [
      {
        label: "剩余额度",
        value: quotaCount !== null ? `${quotaCount} 次` : "-",
        route: "/pages/personal/quota/index",
      },
      {
        label: "处理次数",
        value: taskTotal !== null ? `${taskTotal}` : "-",
        route: "/pages/task/index",
      },
      {
        label: "我的收藏",
        value: favoriteCount !== null ? `${favoriteCount}` : "-",
        route: "/pages/favorite/index",
      },
    ];
    return items;
  }, [quotaCount, taskTotal, favoriteCount]);

  // 权限过滤后的管理入口分组
  const visibleAdminGroups = useMemo(
    () =>
      ADMIN_GROUPS.map((group) => ({
        ...group,
        entries: group.entries.filter((entry) =>
          entry.permission ? hasPermission(entry.permission) : true
        ),
      })).filter((group) => group.entries.length > 0),
    [hasPermission]
  );

  // 跳转
  const handleNavigate = useCallback((route: string) => {
    if (tabBarItems.some((item) => item.route === route)) {
      Taro.switchTab({ url: route });
    } else {
      Taro.navigateTo({
        url: route,
        fail: () => {
          Taro.showToast({ title: "页面跳转失败", icon: "none" });
        },
      });
    }
  }, []);

  // 退出登录
  const handleLogout = useCallback(async () => {
    const confirmed = await confirmDialog({
      title: "退出登录",
      content: "确认退出当前账号吗？",
      confirmColor: "#ff4d4f",
    });
    if (!confirmed) return;
    try {
      await logout();
      Taro.showToast({ title: "已退出登录", icon: "success" });
      setTimeout(() => {
        Taro.reLaunch({ url: "/pages/login/index" });
      }, 800);
    } catch (err: unknown) {
      Taro.showToast({ title: getErrorMessage(err, "退出失败"), icon: "none" });
    }
  }, [logout]);

  // 头像首字母
  const avatarLetter = user?.nickname?.[0] || user?.username?.[0] || "U";
  const isFullAvatar = (avatar?: string) =>
    !!avatar && /^https?:\/\//.test(avatar);

  // VIP 状态
  const isVip =
    !!member &&
    member.levelCode !== "level_1" &&
    member.levelCode !== "level_0";

  // ==================== 渲染 ====================

  const renderEntry = (entry: EntryItem) => (
    <View
      key={entry.route}
      className="entry-item"
      onClick={() => handleNavigate(entry.route)}
    >
      <Text className="entry-icon">{entry.icon}</Text>
      <Text className="entry-title">{entry.title}</Text>
      <Text className="entry-arrow">›</Text>
    </View>
  );

  const renderEntryGroup = (group: EntryGroup) => (
    <View key={group.title} className="entry-group-section">
      <Text className="group-title">{group.title}</Text>
      <View className="entry-card">{group.entries.map(renderEntry)}</View>
    </View>
  );

  return (
    <PageLayout level="L1" title="我的">
      <View className="profile-page">
        <ScrollView scrollY className="profile-scroll">
          {/* 用户卡 */}
          <View className="user-card">
            <View className="user-card-bg" />
            <View className="user-card-content">
              <View className="avatar-wrapper">
                {isFullAvatar(user?.avatar) ? (
                  <Image
                    className="avatar-img"
                    src={user!.avatar!}
                    mode="aspectFill"
                  />
                ) : (
                  <Text className="avatar-text">{avatarLetter}</Text>
                )}
              </View>
              <View className="user-info">
                <Text className="user-nickname">
                  {user?.nickname || "未设置昵称"}
                </Text>
                <View className="user-roles">
                  {roles.length > 0 ? (
                    roles.slice(0, 2).map((role) => (
                      <Tag key={role} size="small" color="primary">
                        {role.replace("ROLE_", "")}
                      </Tag>
                    ))
                  ) : (
                    <Text className="no-role">普通用户</Text>
                  )}
                </View>
              </View>
            </View>
          </View>

          {/* VIP 横幅 */}
          <View
            className="vip-banner"
            onClick={() => handleNavigate("/pages/personal/member/index")}
          >
            <View className="vip-banner-left">
              <Text className="vip-banner-icon">👑</Text>
              <View className="vip-banner-text">
                <Text className="vip-banner-title">
                  {isVip
                    ? `${member?.levelName || "会员"}专属权益`
                    : "开通 VIP 畅享更多次数"}
                </Text>
                <Text className="vip-banner-desc">
                  {isVip
                    ? `成长值 ${member?.growthValue || 0}，点击查看详情`
                    : "解锁全部高级功能"}
                </Text>
              </View>
            </View>
            <View className="vip-banner-action">
              <Text className="vip-banner-btn">
                {isVip ? "详情" : "去开通"}
              </Text>
              <Text className="vip-banner-arrow">›</Text>
            </View>
          </View>

          {/* 数据统计 */}
          <View className="stats-card">
            {stats.map((stat, idx) => (
              <View
                key={stat.label}
                className={`stat-item ${idx < stats.length - 1 ? "stat-divider" : ""}`}
                onClick={() => stat.route && handleNavigate(stat.route)}
              >
                <Text className="stat-value">{stat.value}</Text>
                <Text className="stat-label">{stat.label}</Text>
              </View>
            ))}
          </View>

          {/* 个人数据分组 */}
          <View className="entry-group-section">
            <Text className="group-title">个人数据</Text>
            <View className="entry-card">
              {PERSONAL_DATA_ENTRIES.map(renderEntry)}
            </View>
          </View>

          {/* 商业服务分组 */}
          <View className="entry-group-section">
            <Text className="group-title">商业服务</Text>
            <View className="entry-card">
              {BUSINESS_ENTRIES.map(renderEntry)}
            </View>
          </View>

          {/* 其他分组 */}
          <View className="entry-group-section">
            <Text className="group-title">其他</Text>
            <View className="entry-card">{OTHER_ENTRIES.map(renderEntry)}</View>
          </View>

          {/* 管理入口分组（权限过滤） */}
          {visibleAdminGroups.map(renderEntryGroup)}

          {/* 退出登录 */}
          <View className="logout-section">
            <View className="logout-btn" onClick={handleLogout}>
              <Text>退出登录</Text>
            </View>
          </View>

          {/* 页脚 */}
          <View className="profile-footer">
            <Text>图像去雾系统 v1.0</Text>
          </View>
        </ScrollView>
      </View>
    </PageLayout>
  );
};

export default ProfilePage;
