// dehaze-front-vue/src/components/InfiniteFlowList/index.vue
<script lang="ts" setup>
defineOptions({
  name: "InfiniteFlowList",
});

const props = defineProps({
  urls: {
    type: Array<string>,
    required: true,
  },
  type: {
    type: String,
    default: "down",
  },
  scrollSpeed: {
    type: Number,
    default: 15,
  },
});

const { width, height } = useWindowSize();
const itemHeight = height.value * 0.4;
const doubleItems = ref([...props.urls, ...props.urls]);

const scrollIndex = ref(0);

let timer: number;
let startScroll: () => void;

if (props.type === "down") {
  let originStatus = -2 * props.urls.length * itemHeight + window.innerHeight;
  scrollIndex.value = originStatus;

  startScroll = () => {
    timer = window.setInterval(() => {
      scrollIndex.value += 1;
      if (
        scrollIndex.value >=
        -props.urls.length * itemHeight + window.innerHeight
      ) {
        scrollIndex.value = originStatus;
      }
    }, props.scrollSpeed);
  };
} else {
  startScroll = () => {
    timer = window.setInterval(() => {
      scrollIndex.value -= 1;
      if (scrollIndex.value <= -props.urls.length * itemHeight) {
        scrollIndex.value = 0;
      }
    }, props.scrollSpeed);
  };
}

const stopScroll = () => {
  window.clearInterval(timer);
};

onMounted(() => {
  startScroll();
});

onUnmounted(() => {
  stopScroll();
});
</script>

<template>
  <div class="scroll-container" @mouseout="startScroll" @mouseover="stopScroll">
    <div
      :style="{
        transform: `translateY(${scrollIndex}px)`,
        height: `${doubleItems.length * itemHeight}px`,
      }"
      class="scroll-content"
    >
      <div v-for="(url, index) in doubleItems" :key="index" class="scroll-item">
        <img :src="url.toString()" alt="数据集图片" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
$itemHeight: 40vh; // 与script中的itemHeight保持一致

.scroll-container {
  width: 20vw;
  height: 100vh;
  overflow: hidden;

  .scroll-content {
    display: flex;
    flex-direction: column;
  }

  .scroll-item {
    width: 20vw;
    height: $itemHeight;
    padding: 2.5px 5px;
    margin: 5px 10px;
    overflow: hidden;

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      transition: transform 0.2s linear;
    }

    img:hover {
      transform: scale(1.1);
    }
  }
}
</style>

// dehaze-front-react/src/components/InfiniteFlowList/index.tsx
import { useWindowSize } from "@/hooks/useWindowSize";
import { Timeout } from "ahooks/lib/useRequest/src/types";
import React, { useCallback, useEffect, useRef, useState } from "react";
import PropTypes from "prop-types";

interface InfiniteFlowListProps {
  urls: string[];
  type?: "down" | "up";
  scrollSpeed?: number;
}

// 计算初始滚动位置的辅助函数
const calculateOriginStatus = (
  scrollDirection: "down" | "up",
  itemLength: number,
  itemHeight: number
) => {
  return scrollDirection === "down"
    ? -2 * itemLength * itemHeight + window.innerHeight
    : 0;
};

// 获取滚动方向调整值的辅助函数
const getAdjustment = (scrollDirection: "down" | "up") =>
  scrollDirection === "down" ? 1 : -1;

// 判断是否需要重置滚动索引的辅助函数
const shouldResetIndex = (
  nextIndex: number,
  scrollDirection: "down" | "up",
  itemLength: number,
  itemHeight: number
) => {
  return (
    (scrollDirection === "down" &&
      nextIndex >= -itemLength * itemHeight + window.innerHeight) ||
    (scrollDirection !== "down" && nextIndex <= -itemLength * itemHeight)
  );
};

// 计算下一个滚动索引的辅助函数
const getNextIndex = (
  prevIndex: number,
  adjustment: number,
  scrollDirection: "down" | "up",
  itemLength: number,
  itemHeight: number
) => {
  const nextIndex = prevIndex + adjustment;
  return shouldResetIndex(nextIndex, scrollDirection, itemLength, itemHeight)
    ? calculateOriginStatus(scrollDirection, itemLength, itemHeight)
    : nextIndex;
};

const InfiniteFlowList: React.FC<InfiniteFlowListProps> = ({
  urls,
  type = "down",
  scrollSpeed = 15,
}) => {
  const { width, height } = useWindowSize();
  const [scrollIndex, setScrollIndex] = useState(0);
  const itemHeight = height * 0.4;
  const doubleItems = [...urls, ...urls];
  const timerRef = useRef<Timeout | null>(null);

  // 抽取滚动逻辑到单独的函数
  const startScrolling = useCallback(() => {
    const originStatus = calculateOriginStatus(
      type,
      itemHeight,
      window.innerHeight
    );
    setScrollIndex(originStatus);
    timerRef.current = setInterval(() => {
      const adjustment = getAdjustment(type);
      setScrollIndex((prev) =>
        getNextIndex(prev, adjustment, type, urls.length, itemHeight)
      );
    }, scrollSpeed);
  }, [type, itemHeight, scrollSpeed, urls.length]);

  useEffect(() => {
    startScrolling();
    return () => clearInterval(timerRef.current!);
  }, [urls, itemHeight, type, scrollSpeed, startScrolling]);

  function handleMouseOut() {
    if (!timerRef.current) {
      timerRef.current = setInterval(() => {
        const adjustment = type === "down" ? 1 : -1;
        setScrollIndex((prev) => {
          const nextIndex = prev + adjustment;
          if (
            (type === "down" &&
              nextIndex >= -urls.length * itemHeight + window.innerHeight) ||
            (type !== "down" && nextIndex <= -urls.length * itemHeight)
          ) {
            return -urls.length * itemHeight * (type === "down" ? 2 : 1);
          }
          return nextIndex;
        });
      }, scrollSpeed);
    }
  }

  function handleMouseOver() {
    clearInterval(timerRef.current!);
    timerRef.current = null;
  }

  return (
    <div
      className="scroll-container"
      onMouseOut={handleMouseOut}
      onMouseOver={handleMouseOver}
    >
      <div
        style={{
          transform: `translateY(${scrollIndex}px)`,
          height: `${doubleItems.length * itemHeight}px`,
        }}
        className="scroll-content"
      >
        {doubleItems.map((url, index) => (
          <div key={index} className="scroll-item">
            <img src={url} alt="数据集图片" />
          </div>
        ))}
      </div>
    </div>
  );
};

InfiniteFlowList.propTypes = {
  urls: PropTypes.arrayOf(PropTypes.string.isRequired).isRequired,
  type: PropTypes.oneOf(["down", "up"]),
  scrollSpeed: PropTypes.number,
};

export default InfiniteFlowList;
