// dehaze-uniapp/src/pages/processing/index.vue
<template>
  <PageLayout level="L2" title="去雾处理" class="processing-page">
    <view class="main-content">
      <!-- 页面标题 -->
      <PageHeaderCard
        icon="setting"
        icon-color="#f59e0b"
        icon-bg="linear-gradient(135deg, #fef3c7, #fde68a)"
        title="去雾处理"
        :subtitle="statusText"
      />

      <!-- 处理信息区 -->
      <view class="info-section">
        <view class="info-row">
          <text class="info-label">选择算法</text>
          <text class="info-value">{{
            store.selectedAlgorithm?.name || "-"
          }}</text>
        </view>
        <view class="info-row">
          <text class="info-label">图片文件</text>
          <text class="info-value ellipsis">{{
            store.currentImage?.name || "-"
          }}</text>
        </view>
      </view>

      <!-- 参数调节面板 -->
      <view class="params-card">
        <view class="params-header">
          <text class="params-title">处理参数</text>
          <text class="params-reset" @click="resetParams">重置</text>
        </view>

        <!-- 预设选择 -->
        <view v-if="presets.length > 0" class="preset-section">
          <text class="preset-label">参数预设</text>
          <scroll-view scroll-x class="preset-scroll" :show-scrollbar="false">
            <view
              v-for="preset in presets"
              :key="preset.id"
              class="preset-chip"
              @click="handleApplyPreset(preset)"
            >
              <text>{{ preset.name }}</text>
            </view>
          </scroll-view>
        </view>

        <view class="param-item">
          <view class="param-label">
            <text>去雾强度</text>
            <text class="param-value">{{ store.params.strength }}</text>
          </view>
          <slider
            :value="store.params.strength"
            :min="0"
            :max="100"
            :step="5"
            active-color="#f59e0b"
            block-size="20"
            @change="onStrengthChange"
          />
        </view>

        <view class="param-item">
          <view class="param-label">
            <text>色彩饱和度</text>
            <text class="param-value">{{ store.params.saturation }}</text>
          </view>
          <slider
            :value="store.params.saturation"
            :min="0"
            :max="200"
            :step="5"
            active-color="#f59e0b"
            block-size="20"
            @change="onSaturationChange"
          />
        </view>

        <view class="param-item">
          <view class="param-label">
            <text>对比度</text>
            <text class="param-value">{{ store.params.contrast }}</text>
          </view>
          <slider
            :value="store.params.contrast"
            :min="0"
            :max="200"
            :step="5"
            active-color="#f59e0b"
            block-size="20"
            @change="onContrastChange"
          />
        </view>

        <view class="param-item">
          <view class="param-label">
            <text>锐化程度</text>
            <text class="param-value">{{ store.params.sharpness }}</text>
          </view>
          <slider
            :value="store.params.sharpness"
            :min="0"
            :max="100"
            :step="5"
            active-color="#f59e0b"
            block-size="20"
            @change="onSharpnessChange"
          />
        </view>
      </view>

      <!-- 错误信息 -->
      <view v-if="store.errorMessage" class="error-card">
        <SvgIcon name="error-circle" size="20" color="#ef4444" />
        <text class="error-msg">{{ store.errorMessage }}</text>
      </view>

      <!-- 结果展示 -->
      <view v-if="store.isCompleted && store.result" class="result-section">
        <text class="section-label">处理结果</text>
        <view class="result-card">
          <image
            :src="store.result.resultUrl"
            class="result-image"
            mode="widthFix"
            @click="handlePreviewResult"
          />
          <view class="result-info">
            <text class="result-time">处理耗时: {{ store.result.time }}s</text>
            <text v-if="store.result.fromCache" class="cache-badge"
              >缓存命中</text
            >
          </view>
        </view>
      </view>
    </view>

    <!-- 底部操作栏 -->
    <view class="bottom-bar">
      <view class="bar-content">
        <!-- 处理前：开始按钮 -->
        <template
          v-if="store.status === 'algorithm' || store.status === 'failed'"
        >
          <button
            class="process-btn"
            :disabled="store.isProcessing"
            @click="handleProcess"
          >
            {{ store.isProcessing ? "处理中..." : "开始处理" }}
          </button>
        </template>

        <!-- 处理中 -->
        <template v-else-if="store.status === 'processing'">
          <view class="processing-indicator">
            <view class="loading-spinner" />
            <text class="processing-text">去雾处理中...</text>
            <text class="processing-elapsed"
              >已用 {{ formatDuration(store.elapsedTime) }}</text
            >
          </view>
          <button class="cancel-btn" @click="handleCancel">取消处理</button>
        </template>

        <!-- 完成后 -->
        <template v-else-if="store.isCompleted">
          <button class="compare-btn" @click="handleCompare">
            查看对比效果
          </button>
        </template>
      </view>
    </view>
  </PageLayout>
</template>

<script lang="ts" setup>
import { ref, computed, onMounted } from "vue";
import SvgIcon from "@/components/SvgIcon/index.vue";
import PageLayout from "@/layout/index.vue";
import PageHeaderCard from "@/components/common/PageHeaderCard.vue";
import { useProcessingStore, DEFAULT_DEHAZE_PARAMS } from "@/store/processing";
import { ModelAPI } from "dehaze-sdk-js";
import type { PresetVO } from "dehaze-sdk-js";
import type { SliderChangeEvent } from "@/types/uni-events";

// ==================== 状态 ====================

const store = useProcessingStore();
const presets = ref<PresetVO[]>([]);

// ==================== 计算属性 ====================

const statusText = computed(() => {
  const map: Record<string, string> = {
    idle: "等待开始",
    selected: "已选择图片",
    algorithm: "准备就绪",
    processing: "正在处理...",
    completed: "处理完成",
    failed: "处理失败",
  };
  return map[store.status] || store.status;
});

const formatDuration = (ms: number): string => {
  if (ms < 1000) return `${ms}ms`;
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}秒`;
  return `${Math.floor(s / 60)}分${s % 60}秒`;
};

// ==================== 方法 ====================

type ParamKey = "strength" | "saturation" | "contrast" | "sharpness";

/** 更新单个参数 */
function updateParam(key: ParamKey, value: number) {
  store.updateParams({ [key]: value });
}

const onStrengthChange = (e: SliderChangeEvent) =>
  updateParam("strength", e.detail.value);
const onSaturationChange = (e: SliderChangeEvent) =>
  updateParam("saturation", e.detail.value);
const onContrastChange = (e: SliderChangeEvent) =>
  updateParam("contrast", e.detail.value);
const onSharpnessChange = (e: SliderChangeEvent) =>
  updateParam("sharpness", e.detail.value);

/** 重置参数 */
function resetParams() {
  store.updateParams({ ...DEFAULT_DEHAZE_PARAMS });
}

/** 构建预测参数：仅提交与默认值不同的参数 */
function buildPredictParams(): string | undefined {
  const paramsObj: Record<string, number> = {};
  (Object.keys(DEFAULT_DEHAZE_PARAMS) as ParamKey[]).forEach((key) => {
    if (store.params[key] !== DEFAULT_DEHAZE_PARAMS[key]) {
      paramsObj[key] = store.params[key];
    }
  });
  return Object.keys(paramsObj).length > 0
    ? JSON.stringify(paramsObj)
    : undefined;
}

/** 开始处理 */
async function handleProcess() {
  if (store.isProcessing) return;
  if (!store.selectedAlgorithm || !store.currentImage) {
    uni.showToast({ title: "缺少图片或算法", icon: "none" });
    return;
  }

  // 确认对话框
  const confirmResult = await new Promise<boolean>((resolve) => {
    uni.showModal({
      title: "确认开始去雾处理",
      content: `图片：${store.currentImage!.name}\n算法：${store.selectedAlgorithm!.name}`,
      confirmText: "开始处理",
      cancelText: "取消",
      success: (res) => resolve(res.confirm),
      fail: () => resolve(false),
    });
  });
  if (!confirmResult) return;

  const res = await store.runPrediction({
    algorithmId: store.selectedAlgorithm.id,
    fileId: store.fileId ?? undefined,
    imageUrl: !store.fileId ? store.currentImage?.url : undefined,
    params: buildPredictParams(),
    onQuotaExhausted: ({ used, total }) => {
      uni.showModal({
        title: "预测次数不足",
        content: `当前剩余预测次数为 0（已使用 ${used}/${total}），请及时充值。`,
        confirmText: "去充值",
        cancelText: "取消",
        success: (r) => {
          if (r.confirm) {
            uni.navigateTo({ url: "/pages/personal/quota/index" });
          }
        },
      });
    },
  });

  if (res.ok && res.result) {
    uni.showToast({
      title: `处理完成，耗时${res.result.time ?? 0}s`,
      icon: "success",
      duration: 2000,
    });
  } else if (!res.ok && res.error) {
    uni.showToast({ title: res.error, icon: "none", duration: 2500 });
  }
}

/** 取消处理 */
function handleCancel() {
  store.cancelProcessing();
  uni.showToast({ title: "已取消处理", icon: "none" });
}

/** 查看对比效果 */
function handleCompare() {
  uni.navigateTo({
    url: "/pages/side-by-side/index",
    fail: () => {
      uni.showToast({ title: "对比页面开发中", icon: "none" });
    },
  });
}

/** 预览结果大图 */
function handlePreviewResult() {
  if (!store.result?.resultUrl) return;
  uni.previewImage({
    urls: [store.result.resultUrl],
    current: store.result.resultUrl,
  });
}

/** 应用预设 */
function handleApplyPreset(preset: PresetVO) {
  try {
    const p = JSON.parse(preset.params);
    store.updateParams({
      strength: p.strength ?? DEFAULT_DEHAZE_PARAMS.strength,
      saturation: p.saturation ?? DEFAULT_DEHAZE_PARAMS.saturation,
      contrast: p.contrast ?? DEFAULT_DEHAZE_PARAMS.contrast,
      sharpness: p.sharpen ?? DEFAULT_DEHAZE_PARAMS.sharpness,
    });
  } catch {
    uni.showToast({ title: "预设参数解析失败", icon: "none" });
  }
}

// ==================== 生命周期 ====================

onMounted(() => {
  if (!store.hasAlgorithm) {
    uni.showToast({ title: "请先选择算法", icon: "none", duration: 2000 });
    setTimeout(() => uni.navigateBack(), 2000);
  }
  ModelAPI.getPresets({ pageNum: 1, pageSize: 50 })
    .then((res) => {
      presets.value = res.list || [];
    })
    .catch(() => {
      /* 静默 */
    });
});
</script>

<style lang="scss" scoped>
@import "@/styles/mixins.scss";

.processing-page {
  width: 100%;
  min-height: 100vh;
  background: $color-bg-primary;
}

.main-content {
  padding: 24rpx;
  @include safe-area-bottom(180rpx);
}

/* 处理信息 */
.info-section {
  background: $color-white;
  border-radius: 20rpx;
  padding: 24rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
}

.info-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16rpx 0;

  & + & {
    border-top: 1rpx solid $color-border-light;
  }
}

.info-label {
  font-size: 26rpx;
  color: $color-text-secondary;
}
.info-value {
  font-size: 28rpx;
  font-weight: 500;
  color: $color-text-primary;
}

.ellipsis {
  max-width: 60%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* 参数面板 */
.params-card {
  background: $color-white;
  border-radius: 20rpx;
  padding: 28rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
}

.params-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24rpx;
}

.params-title {
  font-size: 30rpx;
  font-weight: 600;
  color: $color-text-primary;
}
.params-reset {
  font-size: 24rpx;
  color: $color-warning;
}

.preset-section {
  margin-bottom: 28rpx;

  .preset-label {
    font-size: 24rpx;
    color: $color-text-secondary;
    margin-bottom: 12rpx;
    display: block;
  }

  .preset-scroll {
    white-space: nowrap;
  }

  .preset-chip {
    display: inline-block;
    padding: 10rpx 24rpx;
    margin-right: 12rpx;
    font-size: 24rpx;
    color: $color-warning;
    background: $color-warning-bg;
    border-radius: 24rpx;

    &:active {
      background: #fef3c7;
    }
  }
}

.param-item {
  margin-bottom: 28rpx;
}

.param-label {
  display: flex;
  justify-content: space-between;
  margin-bottom: 12rpx;
  font-size: 26rpx;
  color: #374151;
}

.param-value {
  color: $color-warning;
  font-weight: 600;
}

/* 错误卡片 */
.error-card {
  display: flex;
  align-items: center;
  gap: 12rpx;
  background: $color-danger-bg;
  border: 2rpx solid #fecaca;
  border-radius: 16rpx;
  padding: 20rpx 24rpx;
  margin-bottom: 24rpx;
}

.error-msg {
  font-size: 26rpx;
  color: $color-danger;
  flex: 1;
}

/* 结果区域 */
.result-section {
  margin-bottom: 24rpx;
}
.section-label {
  font-size: 28rpx;
  font-weight: 600;
  color: #374151;
  margin-bottom: 16rpx;
  display: block;
}

.result-card {
  background: $color-white;
  border-radius: 20rpx;
  overflow: hidden;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.08);
  border: 2rpx solid $color-success;
}

.result-image {
  width: 100%;
  display: block;
}

.result-info {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20rpx 24rpx;
}

.result-time {
  font-size: 26rpx;
  color: $color-text-secondary;
}
.cache-badge {
  font-size: 22rpx;
  color: $color-success;
  background: $color-success-bg;
  padding: 4rpx 12rpx;
  border-radius: 8rpx;
}

/* 底部操作栏 */
.bottom-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: $color-white;
  border-top: 1rpx solid $color-border-light;
  padding: 20rpx 32rpx;
  @include safe-area-bottom(20rpx);
  box-shadow: 0 -4rpx 16rpx rgba(0, 0, 0, 0.04);
  z-index: 100;
}

.bar-content {
  display: flex;
  align-items: center;
  justify-content: center;
}

.process-btn {
  width: 100%;
  padding: 24rpx;
  background: linear-gradient(135deg, $color-warning, #d97706);
  color: $color-white;
  border: none;
  border-radius: 16rpx;
  font-size: 32rpx;
  font-weight: 700;

  &:disabled {
    background: $color-text-disabled;
    color: $color-text-placeholder;
  }

  &:active:not(:disabled) {
    opacity: 0.85;
  }
}

.loading-spinner {
  width: 32rpx;
  height: 32rpx;
  border: 3rpx solid rgba(255, 255, 255, 0.3);
  border-top-color: $color-white;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

.processing-indicator {
  display: flex;
  align-items: center;
  gap: 16rpx;
  padding: 24rpx 48rpx;
  background: linear-gradient(135deg, $color-warning, #d97706);
  border-radius: 16rpx;
}

.processing-text {
  font-size: 30rpx;
  font-weight: 600;
  color: $color-white;
}

.processing-elapsed {
  font-size: 24rpx;
  color: rgba(255, 255, 255, 0.8);
  margin-left: auto;
}

.cancel-btn {
  width: 100%;
  margin-top: 16rpx;
  padding: 20rpx;
  background: $color-bg-secondary;
  color: $color-text-secondary;
  border: none;
  border-radius: 16rpx;
  font-size: 28rpx;

  &:active {
    background: $color-border;
  }
}

.compare-btn {
  width: 100%;
  padding: 24rpx;
  background: linear-gradient(135deg, $color-success, #059669);
  color: $color-white;
  border: none;
  border-radius: 16rpx;
  font-size: 32rpx;
  font-weight: 700;

  &:active {
    opacity: 0.85;
  }
}
</style>

// dehaze-taro/src/pages/processing/index.tsx
import React, { useState, useEffect, useCallback, useRef } from "react";
import { View, Text, Image, Slider, ScrollView } from "@tarojs/components";
import Taro from "@tarojs/taro";
import CompareNavbar from "@/components/compare/CompareNavbar";
import { ModelAPI } from "dehaze-sdk-js";
import type { Algorithm, PredictionResultVO, PresetVO } from "dehaze-sdk-js";
import { formatFileSize, formatDuration } from "@/utils/format";
import { getErrorMessage } from "@/utils/error";
import { saveImageToAlbum } from "@/utils/saveImage";
import { uploadImage } from "@/config/upload";
import { useProcessStore } from "@/stores/process";
import "./index.less";

interface ImageData {
  url: string;
  name: string;
  width: number;
  height: number;
  size: number;
}

type ProcessStatus = "idle" | "processing" | "success" | "error";

// 通用处理参数
interface ProcessParams {
  strength: number; // 去雾强度 0-100
  saturation: number; // 饱和度 0-200
  contrast: number; // 对比度 0-200
  sharpen: number; // 锐化 0-100
}

const DEFAULT_PARAMS: ProcessParams = {
  strength: 50,
  saturation: 100,
  contrast: 100,
  sharpen: 30,
};

/** 重试间隔（毫秒）：2s → 5s → 10s */
const RETRY_DELAYS = [2000, 5000, 10000];
const MAX_RETRIES = 3;

// 根据算法类型预估处理时间（秒）
function estimateTime(algorithm: Algorithm | null): number {
  if (!algorithm) return 5;
  const type = (algorithm.type || "").toLowerCase();
  if (
    type.includes("cnn") ||
    type.includes("gan") ||
    type.includes("transformer") ||
    type.includes("深度")
  ) {
    return 6;
  }
  if (
    type.includes("传统") ||
    type.includes("dcp") ||
    type.includes("retinex")
  ) {
    return 2;
  }
  return 4;
}

const ProcessingPage: React.FC = () => {
  const [currentImage, setCurrentImage] = useState<ImageData | null>(null);
  const [selectedAlgorithm, setSelectedAlgorithm] = useState<Algorithm | null>(
    null
  );
  const [status, setStatus] = useState<ProcessStatus>("idle");
  const [result, setResult] = useState<PredictionResultVO | null>(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [params, setParams] = useState<ProcessParams>(DEFAULT_PARAMS);
  const [showParams, setShowParams] = useState(false);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [presets, setPresets] = useState<PresetVO[]>([]);
  const [presetsLoaded, setPresetsLoaded] = useState(false);

  const elapsedTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  // 缓存已上传的文件 ID，重试时复用，避免重复上传
  const uploadedFileIdRef = useRef<number | null>(null);
  // 重试计数
  const retryCountRef = useRef(0);
  // 取消标记
  const cancelledRef = useRef(false);

  // 清理定时器
  const clearAllTimers = useCallback(() => {
    if (elapsedTimerRef.current) {
      clearInterval(elapsedTimerRef.current);
      elapsedTimerRef.current = null;
    }
  }, []);

  useEffect(() => {
    return clearAllTimers;
  }, [clearAllTimers]);

  // 加载参数预设
  useEffect(() => {
    if (presetsLoaded) return;
    ModelAPI.getPresets({ pageNum: 1, pageSize: 50 })
      .then((res) => setPresets(res.list || []))
      .catch(() => {
        /* 静默 */
      })
      .finally(() => setPresetsLoaded(true));
  }, [presetsLoaded]);

  // 加载当前图片和算法
  useEffect(() => {
    const { image, algorithm } = useProcessStore.getState();
    if (!image) {
      Taro.showToast({ title: "请先选择图片", icon: "none" });
      setTimeout(() => Taro.navigateBack(), 1500);
    } else {
      setCurrentImage({
        url: image.url,
        name: image.name,
        width: image.width ?? 0,
        height: image.height ?? 0,
        size: image.size ?? 0,
      });
    }

    if (!algorithm) {
      Taro.showToast({ title: "请先选择算法", icon: "none" });
      setTimeout(() => Taro.navigateBack(), 1500);
    } else {
      setSelectedAlgorithm(algorithm);
    }
  }, []);

  // 启动已用时间计时（真实计时，非模拟进度）
  const startElapsedTimer = useCallback(() => {
    setElapsedTime(0);
    elapsedTimerRef.current = setInterval(() => {
      setElapsedTime((prev) => prev + 100);
    }, 100);
  }, []);

  // 实际执行处理（含递增重试）
  const handleProcess = useCallback(async () => {
    if (!currentImage || !selectedAlgorithm) return;

    setStatus("processing");
    setErrorMsg("");
    setResult(null);
    cancelledRef.current = false;
    startElapsedTimer();

    const attempt = async (attemptNumber: number): Promise<void> => {
      if (cancelledRef.current) return;

      try {
        // 本地临时路径（blob:/wxfile://）服务端不可访问，需先上传换取 fileId
        if (!uploadedFileIdRef.current) {
          const fileInfo = await uploadImage(
            currentImage.url,
            currentImage.name
          );
          uploadedFileIdRef.current = fileInfo.id;
        }

        const res = await ModelAPI.predictAndWait({
          algorithmId: selectedAlgorithm.id,
          fileId: uploadedFileIdRef.current,
          params: JSON.stringify(params),
        });

        if (cancelledRef.current) return;
        clearAllTimers();

        if (res.status === 3) {
          throw new Error(res.errorMessage || "处理失败");
        }

        setResult(res);
        setStatus("success");
        retryCountRef.current = 0;

        useProcessStore.getState().setResult(res);
        Taro.showToast({ title: "处理完成", icon: "success" });

        setTimeout(() => {
          Taro.navigateTo({ url: "/pages/side-by-side/index" });
        }, 1500);
      } catch (error: unknown) {
        if (cancelledRef.current) return;

        const errMsg = getErrorMessage(error, "处理失败");
        // 可重试的错误（网络/超时等）允许重试
        if (attemptNumber < MAX_RETRIES) {
          const delay = RETRY_DELAYS[attemptNumber];
          retryCountRef.current = attemptNumber + 1;
          setErrorMsg(
            `${errMsg}，${delay / 1000}秒后自动重试（${attemptNumber + 1}/${MAX_RETRIES}）`
          );
          await new Promise((resolve) => setTimeout(resolve, delay));
          if (!cancelledRef.current) {
            return attempt(attemptNumber + 1);
          }
        }

        clearAllTimers();
        setStatus("error");
        setErrorMsg(errMsg);
        Taro.showToast({
          title: getErrorMessage(error, "处理失败"),
          icon: "none",
        });
      }
    };

    await attempt(0);
  }, [
    currentImage,
    selectedAlgorithm,
    params,
    startElapsedTimer,
    clearAllTimers,
  ]);

  // 执行去雾处理（带确认对话框 + 配额检查）
  const handleStartProcess = useCallback(async () => {
    if (!currentImage || !selectedAlgorithm) return;

    try {
      const quota = await ModelAPI.getQuota();
      if (quota.remaining === 0) {
        Taro.showModal({
          title: "预测次数不足",
          content: `当前剩余预测次数为 0（已使用 ${quota.used}/${quota.total}），请及时充值。`,
          confirmText: "去充值",
          cancelText: "取消",
          success: (res) => {
            if (res.confirm) {
              Taro.navigateTo({ url: "/pages/user-center/index" });
            }
          },
        });
        return;
      }
    } catch {
      // 配额查询失败也允许继续处理
    }

    const estimatedSec = estimateTime(selectedAlgorithm);
    Taro.showModal({
      title: "确认开始去雾处理",
      content: `图片：${currentImage.name}\n尺寸：${currentImage.width}×${currentImage.height}\n算法：${selectedAlgorithm.name}\n预估耗时：约 ${estimatedSec} 秒`,
      confirmText: "开始处理",
      cancelText: "取消",
      success: (res) => {
        if (res.confirm) {
          retryCountRef.current = 0;
          handleProcess();
        }
      },
    });
  }, [currentImage, selectedAlgorithm, handleProcess]);

  // 取消处理
  const handleCancel = useCallback(() => {
    cancelledRef.current = true;
    clearAllTimers();
    setStatus("idle");
    setErrorMsg("");
    setElapsedTime(0);
    Taro.showToast({ title: "已取消处理", icon: "none" });
  }, [clearAllTimers]);

  // 重新处理
  const handleRetry = useCallback(() => {
    setStatus("idle");
    setResult(null);
    setErrorMsg("");
    setElapsedTime(0);
    retryCountRef.current = 0;
  }, []);

  // 返回算法选择
  const handleBackToAlgorithm = useCallback(() => {
    Taro.navigateBack();
  }, []);

  // 保存结果到相册
  const handleSaveToAlbum = useCallback(async () => {
    if (!result?.resultUrl) return;
    await saveImageToAlbum(result.resultUrl);
  }, [result]);

  // 重置参数
  const handleResetParams = useCallback(() => {
    setParams(DEFAULT_PARAMS);
  }, []);

  // 应用预设
  const handleApplyPreset = useCallback((preset: PresetVO) => {
    try {
      const presetParams = JSON.parse(preset.params);
      setParams({
        strength: presetParams.strength ?? DEFAULT_PARAMS.strength,
        saturation: presetParams.saturation ?? DEFAULT_PARAMS.saturation,
        contrast: presetParams.contrast ?? DEFAULT_PARAMS.contrast,
        sharpen: presetParams.sharpen ?? DEFAULT_PARAMS.sharpen,
      });
    } catch {
      Taro.showToast({ title: "预设参数解析失败", icon: "none" });
    }
  }, []);

  const estimatedTime = estimateTime(selectedAlgorithm);

  return (
    <View className="processing-page">
      {/* 顶部导航 */}
      <CompareNavbar title="去雾处理" />

      <View className="processing-content">
        {/* 图片信息 */}
        {currentImage && (
          <View className="info-section">
            <Text className="section-label">原始图片</Text>
            <View className="image-preview">
              <Image
                src={currentImage.url}
                className="preview-img"
                mode="aspectFit"
                lazyLoad
              />
            </View>
            <View className="image-meta">
              <Text className="meta-item">{currentImage.name}</Text>
              <Text className="meta-item">
                {currentImage.width}×{currentImage.height}
              </Text>
              <Text className="meta-item">
                {formatFileSize(currentImage.size)}
              </Text>
            </View>
          </View>
        )}

        {/* 算法信息 */}
        {selectedAlgorithm && (
          <View className="info-section">
            <Text className="section-label">使用算法</Text>
            <View className="algorithm-info">
              <View className="algo-name-row">
                <Text className="algo-name">{selectedAlgorithm.name}</Text>
                <View className="algo-type-tag">
                  <Text>{selectedAlgorithm.type || "算法"}</Text>
                </View>
              </View>
              {selectedAlgorithm.description && (
                <Text className="algo-desc">
                  {selectedAlgorithm.description}
                </Text>
              )}
              <View className="algo-meta-row">
                {selectedAlgorithm.version && (
                  <Text className="algo-version">
                    版本: {selectedAlgorithm.version}
                  </Text>
                )}
                <Text className="algo-estimate">
                  预估耗时: 约 {estimatedTime} 秒
                </Text>
              </View>
            </View>
          </View>
        )}

        {/* 参数调节面板（idle 状态可用）*/}
        {status === "idle" && (
          <View className="info-section params-section">
            <View
              className="params-header"
              onClick={() => setShowParams((prev) => !prev)}
            >
              <Text className="section-label" style={{ marginBottom: 0 }}>
                参数调节
              </Text>
              <Text className="toggle-text">
                {showParams ? "收起" : "展开"}
              </Text>
            </View>

            {showParams && (
              <View className="params-body">
                {/* 预设选择 */}
                {presets.length > 0 && (
                  <View className="preset-section">
                    <Text className="preset-label">参数预设</Text>
                    <ScrollView
                      scrollX
                      className="preset-scroll"
                      enhanced
                      showScrollbar={false}
                    >
                      {presets.map((preset) => (
                        <View
                          key={preset.id}
                          className="preset-chip"
                          onClick={() => handleApplyPreset(preset)}
                        >
                          <Text>{preset.name}</Text>
                        </View>
                      ))}
                    </ScrollView>
                  </View>
                )}

                <View className="param-item">
                  <View className="param-row">
                    <Text className="param-label">去雾强度</Text>
                    <Text className="param-value">{params.strength}</Text>
                  </View>
                  <Slider
                    min={0}
                    max={100}
                    value={params.strength}
                    onChanging={(e) =>
                      setParams((prev) => ({
                        ...prev,
                        strength: e.detail.value,
                      }))
                    }
                  />
                </View>

                <View className="param-item">
                  <View className="param-row">
                    <Text className="param-label">色彩饱和度</Text>
                    <Text className="param-value">{params.saturation}</Text>
                  </View>
                  <Slider
                    min={0}
                    max={200}
                    value={params.saturation}
                    onChanging={(e) =>
                      setParams((prev) => ({
                        ...prev,
                        saturation: e.detail.value,
                      }))
                    }
                  />
                </View>

                <View className="param-item">
                  <View className="param-row">
                    <Text className="param-label">对比度</Text>
                    <Text className="param-value">{params.contrast}</Text>
                  </View>
                  <Slider
                    min={0}
                    max={200}
                    value={params.contrast}
                    onChanging={(e) =>
                      setParams((prev) => ({
                        ...prev,
                        contrast: e.detail.value,
                      }))
                    }
                  />
                </View>

                <View className="param-item">
                  <View className="param-row">
                    <Text className="param-label">锐化程度</Text>
                    <Text className="param-value">{params.sharpen}</Text>
                  </View>
                  <Slider
                    min={0}
                    max={100}
                    value={params.sharpen}
                    onChanging={(e) =>
                      setParams((prev) => ({
                        ...prev,
                        sharpen: e.detail.value,
                      }))
                    }
                  />
                </View>

                <View className="params-actions">
                  <View className="reset-btn" onClick={handleResetParams}>
                    <Text>恢复默认</Text>
                  </View>
                </View>
              </View>
            )}
          </View>
        )}

        {/* 处理中：不定式加载（API 同步返回，不显示虚假百分比）*/}
        {status === "processing" && (
          <View className="status-section processing">
            <View className="processing-spinner" />
            <Text className="status-text">正在去雾处理中...</Text>
            <Text className="status-hint">
              已用 {formatDuration(elapsedTime)}
            </Text>
            <View className="action-buttons">
              <View className="btn btn-secondary" onClick={handleCancel}>
                <Text>取消处理</Text>
              </View>
            </View>
          </View>
        )}

        {/* 处理成功 */}
        {status === "success" && result && (
          <View className="status-section success">
            <View className="success-icon">
              <Text>✓</Text>
            </View>
            <Text className="status-text">处理完成</Text>
            <Text className="status-hint">
              耗时 {formatDuration(result.time ?? 0)}
              {result.fromCache ? " · 缓存命中" : ""}
            </Text>

            {/* 结果预览 */}
            {result.resultUrl && (
              <View className="result-preview">
                <Text className="section-label">处理结果</Text>
                <View className="result-image-wrapper">
                  <Image
                    src={result.resultUrl}
                    className="result-img"
                    mode="aspectFit"
                    lazyLoad
                  />
                </View>
              </View>
            )}

            <View className="action-buttons">
              <View
                className="btn btn-primary"
                onClick={() =>
                  Taro.navigateTo({ url: "/pages/side-by-side/index" })
                }
              >
                <Text>效果对比</Text>
              </View>
              <View className="btn btn-secondary" onClick={handleSaveToAlbum}>
                <Text>保存到相册</Text>
              </View>
            </View>
            <View className="action-buttons">
              <View className="btn btn-secondary" onClick={handleRetry}>
                <Text>重新处理</Text>
              </View>
            </View>
          </View>
        )}

        {/* 处理失败 */}
        {status === "error" && (
          <View className="status-section error">
            <View className="error-icon">
              <Text>!</Text>
            </View>
            <Text className="status-text">处理失败</Text>
            <Text className="status-hint">{errorMsg}</Text>
            <View className="action-buttons">
              <View className="btn btn-primary" onClick={handleProcess}>
                <Text>重试</Text>
              </View>
              <View
                className="btn btn-secondary"
                onClick={handleBackToAlgorithm}
              >
                <Text>更换算法</Text>
              </View>
            </View>
          </View>
        )}

        {/* 开始处理按钮 */}
        {status === "idle" && (
          <View className="action-section">
            <View
              className={`start-btn ${!currentImage || !selectedAlgorithm ? "disabled" : ""}`}
              onClick={handleStartProcess}
            >
              <Text>开始去雾</Text>
            </View>
            <View className="back-link" onClick={handleBackToAlgorithm}>
              <Text>← 重新选择算法</Text>
            </View>
          </View>
        )}
      </View>
    </View>
  );
};

export default ProcessingPage;
